### ISSUE TITLE
NPM doesn't display the README file

### ISSUE THREAD

**Issue by qbunt** [electron-userland/electron-builder#1001]
* **Version**: 10.7.0

* **Target**: All

Hey there, thanks for putting this out, it's been a tremendous help. 

[NPM](https://www.npmjs.com/package/electron-builder) doesn't display the README file listed in your repo. I've reached out to the folks at NPM about this, and why it was occurring. You clearly have the README file in the right location, and it **should** be displaying. This is what they responded back to me with:

>Generally, anytime there is a readme value in package.json it will create readme issues like this, but since their package.json shows "readme": "ERROR: No README data found!", our theory is the publisher likely published from node_modules instead of the current directory. npm saw there wasn't a readme in the node_modules dir and generated this error message.

>If they check their current directory, make sure there is no readme value in package.json, and push a patch update from there, it should resolve the issue.

I'd normally issue a PR for this, but because it's directly related to the build that was published to NPM, I thought I'd reach out and let you know that it's an easily solved problem.
Cheers!

**Comment by develar** [comment]
It is not so easy. NPM never displays actual readme because we publish package using `next` tag by default. So, NPM never updates readme correctly. And no way to request update properly.

To overcome this issue, sometimes we remove `publishConfig` from `package.json` to force `README` update. But month or so ago this trick instead of update — just deleted readme.

I have tried to push from NodeJS 6.5 instead of NodeJS 7 but still no luck.

For security reasons, we have never publish electron-builder from a development machine. Only from CI machine.

Thanks for info — I will try to investigate what's wrong and why README is not updated. Maybe `yarn` will detect README file more correctly than `npm`.

**Comment by qbunt** [comment]
Ah alright I see, that makes way more sense now. I'll send this along to
the NPM team, it could be something they're tweaking in the future. They
did also mention they're making some deeper changes around displaying
readme's, but with no timeline.

Thanks for the fast response, I'll see what can be done! Thanks again for
open sourcing this too, it's in heavy use on my team. 👍

**Comment by qbunt** [comment]
Sent a note with your response back to the NPM team referring directly to this ticket. If you see someone from NPM chime in, that's why.

**Comment by qbunt** [comment]
from Stephanie Snopek at NPM:
	
> I see, that is a more complicated situation and makes sense why this issue is happening. Thanks for sharing the results of that discussion with me. I've shared this with the team for further consideration as we improve README rendering.

No timeline still, but it sounds like they're talking about it internally.

**Comment by develar** [comment]
Bug in the `normalize-package-data` Solution — do not use it (https://github.com/develar/semantic-release/commit/44ca70bbe21c99fdde73a42bbaa3e7a295dae6ec#diff-bacafe7b95242be6e9884530e6cb0769R13)

**Comment by develar** [comment]
As soon as https://github.com/yarnpkg/yarn/issues/610#issuecomment-255230057 will be be fixed, `yarn` will be used instead of `npm` to publish.
