### ISSUE TITLE
Is code signing required for auto-update on Windows?

### ISSUE THREAD

**Issue by mobitar** [electron-userland/electron-builder#1189]
I know a lot has changed with auto-update functionality in the last few months, and I've had to learn the hard way that almost every online post about auto-update is outdated (like using Squirrel). In the old directions, code signing was required for auto-update to work properly on Windows. Is this still the case?

**Comment by develar** [comment]
Code signing was never required for Windows because on Windows code signing doesn't protect users and system doesn't provide protect users correctly. Code signing correctly works and correctly protect users only on macOS.

Code signing will be not required for auto-update in the future as well, but we are going to this check explicitly #1187
