### ISSUE TITLE
Adding examples to docs around publishing and auto-updates

### ISSUE THREAD

**Issue by 27percent** [electron-userland/electron-builder#1208]
Hey there!

I really appreciate what you're doing with electron-builder, it's super useful, however I'm having a little trouble publishing artefacts and getting auto updating working. It struck me that it'd be super useful to have some examples on both of those topics.

So for example, say I want to build a mac app and publish as a github release - what would that command look like, what's required from the package.json etc. similar to a reference design in an electronic component's datasheet.

I appreciate you're updating the codebase quite frequently, especially stuff surrounding auto updates, so I'd absolutely be happy to help write documentation if you find time to explain the process to me, I'd love to help you keep them up to date and take some of the load off you so you can spend more time on the actual code

Thanks again for all of your great work, like I said before it's really appreciated

**Comment by develar** [comment]
Please see this thread in the slack (and note about wiki in the end of thread) — https://electron-builder.slack.com/archives/general/p1485886051000072 (join: https://electron-builder.slack.com/shared_invite/MTMzMTc5NTcyNTAzLTE0ODUzNzE4MTctYzBhNGY1NjljYg)

Cool if you will update docs.

**Comment by develar** [comment]
>  I want to build a mac app and publish as a github release - what would that command look like

CI server: `build`

Local machine: `build --publish always`

`--publish` not required on CI server because https://github.com/electron-userland/electron-builder/wiki/Publishing-Artifacts#cli-flags "automatic rules instead of explicitly specifying publish"

> what's required from the package.json etc. 

You will get clear errors if something not specified.

> super useful to have some examples on both of those topics

Currently, we have docs, but we need also **tutorials** and if you can help us to write it — will be great.

**Comment by 27percent** [comment]
Thanks, I'll go over the resources you supplied but the slack invite link is no longer valid, could you post another? On your last point regarding tutorials, I'm in agreement - there are a few tutorials dotted around the web but they're mostly out of date with newer versions of electron-builder. I'd definitely be happy to help on that front as much as I can.

**Comment by develar** [comment]
slack join: http://electron-builder-slack.herokuapp.com

**Comment by akashnimare** [comment]
@27percent Btw I have written an [article](https://medium.com/@meakaakka/how-to-add-auto-updates-to-your-electron-application-an-up-to-date-guide-d62794a0467d#.4qzswsj02) on auto-updates although it uses nuts. I'm planning to write an updated version of this which will use NSIS (instead of Squirrel.windows) + electron-updater :)

**Comment by develar** [comment]
Moved to backlog to keep issue list clear.
