### ISSUE TITLE
Stub Executables not Signed for Squirrel.Windows

### ISSUE THREAD

**Issue by TimvdEijnden** [electron-userland/electron-builder#1249]
* **Version**: 13.6.0

* **Target**: Squirel.Windows

The update.exe file is correctly signed but the Stub Executable is not. This causes Virusscanner warnings on the computers of our users.

**Comment by develar** [comment]
Because to support code signing on Linux/macOS we sign on electron-builder side. Original Squirrel.Windows pack sign by mask. As result, we copy executable stub from Squirrel.Windows distribution to out, but forget to sign it.

Also, `elevate.exe` for NSIS target must be signed as well.

Will be fixed tomorrow CET.

**Comment by TimvdEijnden** [comment]
I wanted to create a PR to fix my Squirrel issue, currently trying to compile electron-builder.

**Comment by develar** [comment]
Here https://github.com/electron-userland/electron-builder/blob/master/packages/electron-builder-squirrel-windows/src/squirrelPack.ts#L238 must be added `await packager.sign()` 

> currently trying to compile electron-builder.

Feel free to join Slack (http://electron-builder-slack.herokuapp.com/).
