### ISSUE TITLE
Build application already packaged with electron-packager

### ISSUE THREAD

**Issue by debelop13** [electron-userland/electron-builder#1273]
Hello,

I will try to explain my problem,

My app (ember app) was built with ember electron (underhood it have electron-packager). I have created .app and .exe -with .dll and some stuff-, and is working correctly.

And I want to create .dmg/.exe adding Code Signing.

Exists any way to build .dmg and .exe with electron-builder once was compilated with electron-packager?

Thanks!!!

**Comment by develar** [comment]
Please see in the readme [Pack Only in a Distributable Format](https://github.com/electron-userland/electron-builder#pack-only-in-a-distributable-format)

Keep in mind that default quality of electron-packager result is worse than electron-builder pack. At least, please enable asar in the electron-packager to make your app faster on Windows (and reduce code sign time).

**Comment by develar** [comment]
Also, electron-builder will not sign your app exe — only installer. Hmm...

**Comment by debelop13** [comment]
But I have an importan option in electron-packager that I didn't found in electron-builder, that is   ignore a folder by platform.

electron:package --platform=darwin --arch=x64 --ignore=vendor/Windows

**Comment by develar** [comment]
@debelop13 electron-builder allows you do it in a more simple and easy way using glob pattern — please see [files](https://github.com/electron-userland/electron-builder/wiki/Options#Config-files) Please see also https://github.com/electron-userland/electron-builder/wiki/Options#file-patterns

**Comment by debelop13** [comment]
But I want to ignore by platform:

electron:package --platform=darwin --arch=x64 --ignore=vendor/Windows

electron:package --platform=win32 --arch=x64 --ignore=vendor/macOS

**Comment by develar** [comment]
You have three solutions:

1. Simply specify option per platform:
   ```json
   "build": {
     "win": {
       "files": ["!vendor/Windows${/*}"]
     },
     "mac": {
       "files": ["!vendor/macOS${/*}"]
     }
   }
   ```

2.  You can use `${os}` (expanded to mac, linux or win according to current platform) and `${arch}` in the pattern. So, rename your folder — macOS to mac, and Windows to win And use `["!vendor/${os}${/*}"]`

3. Pass extra configuration as CLI: `-c.files='!vendor/Windows${/*}]'` Not recommended because it is not readable and can leads to bash escaping issues.

I recommend solution 2, but if you don't wan't to renamed folders, you can use solution 1.

If you don't want to specify `build` config in the `package.json`, you can use electron-builder.yml or electron-builder.json or electron-builder.json5 in the root of your project or through the --config <path/to/yml-or-json5> option.

**Comment by debelop13** [comment]
My app does not work once is packaged with electron-builder, because when is running it has different bugs.

I try to Pack Only in a Distributable Format, but it neither does not work.

Using 

./node_modules/.bin/build --prepackaged <packed dir>

./node_modules/.bin/build --prepackaged electron-builds/example-8.0.21-darwin-x64
or 
./node_modules/.bin/build --prepackaged electron-builds/example-8.0.21-darwin-x64/example-8.0.21.app

Bash it shows nothing: neither errors nor where is the compiled

I am doing something badly

**Comment by develar** [comment]
Strange. What version of electron-builder do you use?

**Comment by debelop13** [comment]
./node_modules/.bin/build --version
13.11.1

**Comment by dperetti** [comment]
Same as @develar here.
