### ISSUE TITLE
Build for Linux: Icon set directory doesn't exist

### ISSUE THREAD

**Issue by cawa-93** [electron-userland/electron-builder#1276]
* **Version**: 13.9.0

* **Target**: -l --x64

It seems to me that a relative path is calculated as something strange.
Icons for my application, lie at `app/icons`
In `package.json` for Windows I can type
```
    "win": {
      "icon": "app/icons/icon.ico"
    }
```
and file will be found
In `package.json` for Linux I try set:
```
    "linux": {
      "icon": "app/icons/",
      "target": [
        "AppImage"
      ]
    }
```
But the builder is looking for them at `build/app/icons`

I have't `build` directory. 
```
Unhandled rejection Error: Icon set directory /home/alex/LinWin/Develop/command-editor/build/icons doesn't exist
```

**Comment by develar** [comment]
As stated in the docs: **The path to icon set directory, relative to build (build resources directory).**

But I totally understand you — it is not user-friendly. Because for windows icon also should be relative to build resources, but actually we allow it to be relative or to project dir, or to build.

Fix will be published in 10 minutes.

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder/wiki/Options#MetadataDirectories-buildResources

**Comment by develar** [comment]
Icon for DMG fixed as well.

**Comment by develar** [comment]
Please try 13.11.0
