### ISSUE TITLE
Builld windows build on osx using an EV code signing certificate

### ISSUE THREAD

**Issue by Sambego** [electron-userland/electron-builder#1299]
* **Version**:  11.4.4

* **Target**: mac, windows

I'm trying to build both a mac and windows version of an app on a computer running macOS and I want to sign them using an EV code signing certificate. These kind of certificates don't allow the export to `.p12` or `.pfx`.

When signing the mac build, the builder finds the installed certificate and uses this to sign the build.
For the windows build however you need to specify a `.p12` or `.pfx` file. It would be nice if electron-builder could also use the installed EV certificate to sign the windows build.

When using `signtool` on windows you can specify to automatically search for the correct  certificate using the `/a` param.

```
signtool sign /a /tr http://timestamp.globalsign.com/?signature=sha2 /td SHA256 "path\to\installer.exe"
```

I don't think that `mono signcode` supports this `/a` parameter, but I maybe there is another way to accomplish this automatic certificate detection?

**Comment by develar** [comment]
For now, you can sign using EV only on windows using https://github.com/electron-userland/electron-builder/wiki/Options#WinBuildOptions-certificateSubjectName

**Comment by Sambego** [comment]
It would be nice to be able to sign a windows version of the app from macOS, since electron-builder also supports the building of a windows app from macOS.

We have some scripts which build and upload both versions of the app from macOS. Without being able to sign windows apps, we have to manually sign them on windows, which interrupts our build and deployment flow.

Do you think it would be do-able to implement the windows ev certificate signing on macOS?

**Comment by develar** [comment]
Theoretically it is possible. Problem is that I don't have EV cert to test. I will investigate.

**Comment by develar** [comment]
https://github.com/SirAlex/RemoteSignTool will be used. Is it ok for you?

**Comment by arekkas** [comment]
@develar that looks pretty cool! Happy to test it with appveyor and some guidance!

**Comment by develar** [comment]
@arekkas so, for you it is possible to expose machine with token to internet (http port)?

**Comment by arekkas** [comment]
Yes. Gotta check of course that no one else is able to sign stuff with my cert :D

**Comment by brandonhilkert** [comment]
I'd be interested in having this as well, subscribing for updates.

**Comment by solshark** [comment]
Relevant for me as well

**Comment by balugege** [comment]
Relevant for me

**Comment by antelle** [comment]
Hi everyone!
As now Microsoft requires to store a key on smart card, this will affect more people soon.
I've managed to sign windows executables with `osslsigncode` on mac with key stored on a smart card. Here's how:
- install `openssl`, `opensc` and `engine_pkcs11` from brew
- build osslsigncode from master, here's the [patch](https://sourceforge.net/p/osslsigncode/osslsigncode/ci/50b66a1eb43a1eafe80e8d5d89e94c4aa9b905a4/) we need
- call it with args:
  - `pkcs11engine=/usr/local/lib/engines/engine_pkcs11.so`
  - `pkcs11module=/usr/local/lib/opensc-pkcs11.so`
  - `key=` your key slot, e.g. `01`
  - `-askpass` or `-pass=` your pin code
  - ...other args as in usual sign
- ❗️ run `osslsigncode verify` after sign: there's no validation by default: exe might be broken

This is working perfectly for me here: https://github.com/keeweb/keeweb/blob/develop/grunt/tasks/grunt-sign-exe.js
If anyone is interested in token model which is working on both Mac and Windows, it's PIVKey T800.

**Comment by develar** [comment]
Great.

> build osslsigncode from master, here's the patch we need, I don't know why the latest release is not updated (I've opened an issue but the author doesn't care)

@antelle because of this bug electron-builder provides version from master. But only for mac, not for Linux. I will fix it.

> As now Microsoft requires to store private keys on smart cards,

Even for non-EV certs?

**Comment by antelle** [comment]
Yes, for non-ev as well: https://casecurity.org/2016/12/08/leading-certificate-authorities-and-microsoft-introduce-new-standards-to-protect-consumers-online/
For example, Certum only allows PKs on tokens, I guess, others as well.

**Comment by heimpogo** [comment]
@antelle Thanks for the instructions. Thanks to this I was able to build und use a current version of osslsigncode. Some issues I had:

**Building osslsigncode**
After running `autogen.sh` I had to set the following variables in the `Makefile`:

    LDFLAGS = -L/usr/local/opt/openssl/lib
    CPPFLAGS = -I/usr/local/opt/openssl/include

**Using osslsigncode**

- The `pkcs11module` depends on the hardware token used. You can check if you are using the correct module using`pkcs11-tool -module <path> -I`. The token should be visible. `pkcs11-tool` is included in `opencs` and is installed at `/usr/local/Cellar/opensc/0.17.0/bin/pkcs11-tool`.
- The ID for the `-key` paramter can also be acquired using `pkcs11-tool -module <path> -O`. It is used to map private and public key, so it is the same for both and it doesn't matter which of both you are looking at.
- Yes, you have to provide the `-certs` parameter. This was a bit surprising since the `-key` parameter could be used to get the public key from the token (if it is stored there too).
- As it turns out, `osslsigncode` cannot sign appx packages.

**Comment by solshark** [comment]
Is it for AppX only? What about NSIS?

**Comment by develar** [comment]
@solshark For any windows code signing. Just set `certificateSubjectName`.

**Comment by solshark** [comment]
Thank you very much. Just tried and it works. Dealbreaker for me.

**Comment by exiadb** [comment]
I am coming from https://github.com/electron-userland/electron-builder/issues/1286, 

does it mean EV can be used for signing on a CI with smart card?

**Comment by Neo13Pr** [comment]
Guys, i want to sign my electron app with EV Code,  i have tried it with win.certificateSubjectName, but it stuck while creating publish, please help

Following is my package.json code

    "forceCodeSigning": false,
        "win": {
          "publisherName": "HM Developers",
          "certificateSubjectName": "HM INC"
        },

Thanks.

**Comment by Neo13Pr** [comment]
@solshark Hello Sir, if you have succeeded in code signing with EV Cert, then please help me in this.

Thanks.

**Comment by solshark** [comment]
@Neo13Pr I did with no special settings. I have `"certificateSubjectName": "XXXXXX"` in my package.json and thats it. 
I'm using Parallels on Mac if it matters.

**Comment by Neo13Pr** [comment]
@solshark if you don't mind can i see your packge.json sample.
i am using windows, it stuck here -
![image](https://user-images.githubusercontent.com/34686856/38029730-51c812f8-32b4-11e8-8ea0-344740235305.png)

Thanks.

**Comment by johnryan** [comment]
@Neo13Pr this is a ticket for building windows apps on OSX, if you're building on Windows i'd ask in Slack or open a new ticket

**Comment by jakubzitny** [comment]
Hi all, let me share my story of getting this to work. I mostly used tips from @heimpogo and @antelle. However, there are still some challenges on the way, so to sum up:

1. Get the EV signing certificate from your favourite provider. (We used DigiCert's with a discount code from [windows docs](https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/get-a-code-signing-certificate). Received a `SafeNet eToken 5100` device.)
2. Install `openssl`, `opensc` and `engine_pkcs11` from `brew`:
```
brew install openssl opensc engine_pkcs11
```
3. Build `osslsigncode` from master, with this [patch](https://sourceforge.net/p/osslsigncode/osslsigncode/ci/50b66a1eb43a1eafe80e8d5d89e94c4aa9b905a4/). (Clone git master, also download build from releases, copy `osslsigncode.c` from git repo to release directory, run `./configure && make && make install` there)
4. Extract the cert from your signing device and save it to `/secure/cert.crt`. (Our SafeNet device needs a "driver" for reading stuff, driver is bundled with app that can view/export certificates, available also for mac from [here](https://knowledge.digicert.com/solution/SO20503.html).)
5. Use `openssl` to convert the certificate to `/secure/cert.pem` if it's not already PEM.
6. Find out what module for `pkcs11-tools` is needed for your signing device (ours was in `/usr/local/lib/libeTPkcs11.dylib`) and always use it with `pkcs11-tools` with `--module <path-to-module.dylib>` parameter. (I found this by trying a lot of random stuff, finally found the driver name [here](https://kbpdfstudio.qoppa.com/how-to-setup-usb-smart-card-hardware-pkcs11-signing-on-mac/).)
7. Find out the private key id `pkcs11-tool --module <path-to-module.dylib> -O`.
8. run `osslsigncode`
```
osslsigncode sign \
  -pkcs11engine /usr/local/lib/engines/engine_pkcs11.so \
  -pkcs11module <path-to-module.dylib> \
  -spc /secure/cert.pem \
  -key <private-key-id> \
  -pass <pass> \
  -n app-name \
  -t http://timestamp.verisign.com/scripts/timstamp.dll \
  -in app.exe \
  -out app-signed.exe
```
9. Don't forget to sign everything (installer, solo executable, exe in zip, etc.)


**Our use case**:

We were building Electron app for win/lin/mac on our GitLab CI linux runners (in cloud). We used to have regular Windows signing certificate in the linux machine and electron-builder signed everything correctly during build. For signing mac builds, we are sending unsigned build from linux to a mac server in cloud and sign it there.

Since our new EV certificate has private key on a physical device, we're now using a local mac server for signing Windows builds where this device is plugged in. After all Windows builds (installer, zip package and squirrel bundles) are ready (unsigned) from our linux CI runner, they are sent to the local mac (via tunnel) and all parts that need signing are signed (as described above) one by one.

PS: Not sure how to scale this approach. Do all companies that use physical devices for signing stuff use only private infrastructure? Is there any best practice on connecting cloud and local servers (other than tunnelling or vpn)? But still, even for local/private infra, do the servers with plugged-in sign devices just lay around in racks or offices?

**Comment by damianobarbati** [comment]
@develar I'm prompted to enter the PIN/password for the "EV physical device USB token" about 10 times: is this normal? Anyway to prevent this or to ask it just on first usage of EV certificate?

**Comment by johnryan** [comment]
@damianobarbati there is a setting in the EV settings manager that lets you only be prompted once.

**Comment by develar** [comment]
@johnryan Will be great if you will provide screenshots and some steps. I will transform your comment as FAQ entry in the docs ;)

**Comment by damianobarbati** [comment]
@johnryan yes please! Because I'm using the SafeNet software and I can't find how to permanently unlock the token: or better, I see the option but it's greyed out (?!).

**Comment by amargautam** [comment]
@euangordon - any luck? My EV cert is from Digicert so I knew what you explained but it’s not part of the electron builder workflow. Problem is now I have to sign the windows build separately and then update latest.yml with correct checksum. And of course I can’t use the publish feature either. In the end it’s not 100% automated build and publish workflow. Let me know if you find something that can help code sign windows executeable directly from electron builder on OSX like it does with Mac builds.

**Comment by frederikbosch** [comment]
The example by @jakubzitny is working for us. The `osslsigncode` repo to clone is https://github.com/mtrojnar/osslsigncode, for more info see [this issue](https://github.com/OpenSC/libp11/issues/269).

**Comment by jakubzitny** [comment]
There is very nice summary [in Mattermost dev docs](https://developers.mattermost.com/contribute/desktop/code-signing/#code-signing-on-macos-and-linux) by @MusikPolice on signing win builds on macos/linux.

**Comment by Littlebigdondon** [comment]
Figured I'd share what worked for me after running into this problem trying to sign the Windows executables produced by Electron Builder on macOS...

I got an EV certificate from Digicert and installed the [v10.2 driver & client](https://www2.swift.com/3skey/help/mac_support.html) (**be aware this is not the hardware manufacturers link**--their download requires a login using a Customer ID that is only attainable when buying directly through them. _Lots of their partners have publicly accessible downloads for multiple versions of the driver, such as [DigiCert hosting v9.1](https://knowledge.digicert.com/solution/SO20503.html), or [Comodo hosting v10.1](https://support.comodo.com/index.php?/Knowledgebase/Article/View/1211/106/safenet-download-for-ev-codesigning-certificates)...I have emailed Gemalto (the USB key manufacturer) asking for more info as to why their links are locked down_). I first installed v9.1, but the certificates would rarely show up in Keychain Access, whereas v10.2 [includes Mojave support](https://data-protection-updates.gemalto.com/2018/12/10/safenet-authentication-client-sac-10-2-for-mac-release-announcement/) and works every time.

Anyway, after installing the driver and inserting the hardware key, a new keychain should appear in Keychain Access. Make sure the Keychain is unlocked (`Keychain Access -> File -> 'Unlock Keychain'`) before invoking Electron Builder.

Once I got to this point, I set up my Windows build parameters in package.json simply like this:
```json
...
    "win": {
      "target": "nsis",
      "sign": "./sign.js"
    },
...
```
And 'sign.js' is just: 
```javascript
exports.default = async function(configuration) {
  require("child_process").execSync(
    codesign -s "YOUR_CERTIFICATE_NAME" "${configuration.path}" --force,
    {
      stdio: "inherit"
    }
  );
};
```
_NOTE: If you have multiple certificates that even roughly match the same name and cause ambiguity, you can instead pass the certificate's SHA1 hash (found by running `security find-identity -v -p codesigning`, and used in the above function like: `codesign 01020303405060708090A0B0C0D0E0F1112131415 "${configuration.path}" --force`)._

The `--force` flag, for me, **was** necessary; without it, I found that signing with my EV cert failed because, at this step, the executables were already _'signed generic'_.

This solution signed the application, the installer, and the uninstaller.

Hope that helps someone, because it turned out to be a super simple way to delegate signing Windows applications with an EV certificate on macOS without going outside of the Electron Builder workflow...

**Comment by todanley** [comment]
@Littlebigdondon Hi, that's very helpful. Now I can get electron builder to build and sign the .exe installer automatically. But the problem remaining is that I'm using electron builder auto-updater to publish and update my app. Even if it works with "npm run dist", it does not work with "npm run publish". The updater tried to sign .exe installer even before the installer ever existed. Are you also using electron builder auto-updater for publishing?

**Comment by msannikov** [comment]
Hi @Littlebigdondon, thanks for your explanation! 
I actually did the same and codesign seems to be working properly for me, I checked generated installer with
`codesign --display --verbose=4` 
and it showed that there is the signature. But the problem is that when I am trying to run the installer in windows the smart screen pops up warning about the lack of the signature, and there is actually none shown in file properties as well. Do you have the same? Any thoughts on how to make windows see this signature? 

Also, there is a typo in your sign.js script, the command inside execSync should be inside back-ticks \`codesign ...\` to make the whole thingy work.

**Comment by Littlebigdondon** [comment]
@todanley I am using electron-builder (20.38.5) to publish, and using electron-updater (4.0.6) for installing new releases. 

> The updater tried to sign .exe installer

I'm not 100% sure I follow; the updater shouldn't be trying to sign anything...if electron-builder is successfully signing your executable, all you need to do is publish it to your repo/server with the `--publish` option.

If it helps, my `publish` script essentially boils down to `build -mwl --publish always`. This builds -> signs -> publishes, in that order.

**Comment by Littlebigdondon** [comment]
Hey @msannikov, I don't seem to have that problem. I'm really not sure why Windows would say it isn't signed if you are in fact able to sign it with your EV certificate.

Thanks for pointing out the typo, I think markdown ate the backticks when I copy/pasted. I'll edit my post.

**Comment by msannikov** [comment]
@Littlebigdondon this is super weird, could you please check whether you have signature in your installer properties like on the image below. I am asking because sometimes smart screen does not pop up if a file came from secure place, like copied from host to guest virtual OS, or downloaded from popular website.

![Screenshot 2019-03-15 at 19 24 10](https://user-images.githubusercontent.com/2928083/54446600-5a593280-4758-11e9-85c2-ce14cdf488b8.png)

**Comment by Littlebigdondon** [comment]
@msannikov I was just about to come back and say I just double checked -- you are right, the smart screen no longer pops up with a warning, yet there is no signature listed! Investigating this now...thanks for catching that.

**Comment by ITS-Safetrac** [comment]
@Littlebigdondon  Thank you. I was just confused by myself. Now the process seems to work except I'm having the same problem as @msannikov . I run `codesign --display --verbose=4` and it said the installer had been signed already. Even if I manually run `codesign -s [CERTFICATE_NAME] [INSTALLER_PATH]`, it still said the installer had been signed already and could not been signed again. However, Windows does not seem to recongize the signature. The smart screen pops up and complains that the signature is missing.

**Comment by todanley** [comment]
@Littlebigdondon Thank you. I was just confused by myself. Now the process seems to work except I'm having the same problem as @msannikov . I run codesign --display --verbose=4 and it said the installer had been signed already. Even if I manually run codesign -s [CERTFICATE_NAME] [INSTALLER_PATH], it still said the installer had been signed already and could not been signed again. However, Windows does not seem to recongize the signature. The smart screen pops up and complains that the signature is missing.

**Comment by msannikov** [comment]
@Littlebigdondon @todanley, I dropped the idea to do anything with codesign, and eventually the solution with [osslsigncode](https://github.com/electron-userland/electron-builder/issues/1299#issuecomment-393504798) works for me. 
My sign.js script looks as following, I need several attempts for every signature because my token Safenet 5110 sometimes fails to sign:

`
const util = require('util');

var execSync = require('child_process').execSync;
var exec = util.promisify(require('child_process').exec);
`

**Comment by Littlebigdondon** [comment]
@msannikov @todanley Yeah, I gave up on the codesign idea as well. Sorry to mislead anybody (I was mislead myself!).

Good to know the osslsigncode option works -- however, I do have one more solution that I've verified as working correctly. **This option assumes your Mac has Java installed**; so, if you don't want/need Java for any other reason, going the osslsigncode route would probably save some precious hard drive space... If anyone is unsure if they have Java installed, just run `java -v`.

### The new solution:

1. You will still need to install the [driver](https://www2.swift.com/3skey/help/mac_support.html) for your hardware token (I, too, am using a SafeNet 5110).
2. `cd` into your project's root directory and run:
     ```
     npm i -D readline-sync \
     && curl -OJL 'https://github.com/ebourg/jsign/releases/download/2.1/jsign-2.1.jar' \
     && curl -L 'https://gist.github.com/Littlebigdondon/08bab1f3936d185cdd068608689cc444/download' | tar -xvz --strip-components=1
     ```
     _This will install [readline-sync](https://www.npmjs.com/package/readline-sync) as a dev dependency (for prompting/obscuring your password input), download the [Jsign](https://ebourg.github.io/jsign/) tool, a [script for invoking the signing tool](https://gist.github.com/Littlebigdondon/08bab1f3936d185cdd068608689cc444#file-sign-js), and a [generic config file](https://gist.github.com/Littlebigdondon/08bab1f3936d185cdd068608689cc444#file-hardwaretoken-cfg) that points to the driver's eToken framework._
3. Replace `"YOUR_CERT_NAME_HERE"` on line 1 of `sign.js` to be the actual name of your certificate.
4. Setup the Windows build parameters in package.json:
     ```json
     ...
         "win": {
           "target": "nsis",
           "sign": "./sign.js"
         },
     ...
     ```
5. That's it! You can now run your package script.

**_NOTE:_** Right now, if you mistype your password, it doesn't have any retry-handling built in. I was looking for a way to differentiate the errors thrown by Jsign (e.g. incorrect password vs no hardware token found), but didn't see a solution right off the bat. If anyone wants to contribute to my gist (linked above), I'd be glad to update the script.

Whoever tries this, let me know if it works for you!

**Comment by todanley** [comment]
@Littlebigdondon @msannikov I just tried your Java solution and it works. I also tried osslsigncode but could not get it to work due to some problems with openssl on my Mac. Thank you all for the solutions. A side note for others: sometimes my Safenet client (10.2) fails to put certficate into my keychain even though the physical token is plugged in. To fix that, reboot Mac with the physical token plugged in. Then on the login screen, you Mac will ask you for certificate PIN/Password to log you in. After entering certificate PIN/Password, the certifcate is guaranteed to be in your Keychain Access (Not necessarily in "login" keychain though).

**Comment by Littlebigdondon** [comment]
@todanley Sweet! Glad it worked for you, too. Just curious, which SafeNet device are you using? For me, with a SafeNet 5110 and the v10.2 driver, it's been working flawlessly hot-plugging the device. I don't have to do anything for the certificate to appear in Keychain Access. Just wonder what the disparity is between our setups.

**Comment by ITS-Safetrac** [comment]
@Littlebigdondon My device is also 5110. But I downloaded v10.2 driver from [https://www2.swift.com/3skey/help/mac_support.html](This link) instead of [https://data-protection-updates.gemalto.com/2018/12/10/safenet-authentication-client-sac-10-2-for-mac-release-announcement/](The one locked up). I'm not sure if this matters. At this point, I can't see real difference between our setups.

**Comment by todanley** [comment]
@Littlebigdondon My device is also 5110. But I downloaded v10.2 driver from [This link](https://www2.swift.com/3skey/help/mac_support.html) instead of [The one locked up](https://data-protection-updates.gemalto.com/2018/12/10/safenet-authentication-client-sac-10-2-for-mac-release-announcement/). I'm not sure if this matters. At this point, I can't see real difference between our setups. [

**Comment by Littlebigdondon** [comment]
@todanley That is the link I provided. So we downloaded the same driver.

By the way, I did contact Gemalto about their driver being behind a verified customer lock (which you can't get to even if you go through a vendor of theirs, such as DigiCert). I voiced my opinion on either removing the customer ID requirement, pressuring their vendors to update their drivers, or providing a hash we could use to verify their software is genuine.

**Comment by frederikbosch** [comment]
Yesterday I worked on this for Mac. I got this working as follows. Also using a Safenet 5110 token.

1. create folder like `/usr/local/mac-dev`, give it rights of your current user, use the folder as a prefix during compilation (e.g. `./configure --prefix /usr/local/mac-dev/openssl-1.1.1b`)
2. configure, make, make install openssl 1.1
3. export openssl 1.1 variables for compiling the applications below
  - export LDFLAGS="-L/usr/local/mac-dev/openssl-1.1.1b/lib"
  - export CPPFLAGS="-L/usr/local/mac-dev/openssl-1.1.1b/include"
  - export PATH="/usr/local/mac-dev/openssl-1.1.1b/bin:$PATH"
4. install opensc
5. configure, make, make install libp11
6. install safenet driver 10.2, export the .cer and convert it to pem
7. configure, make, make install osslsigncode (afterwards symlink the binary to `/usr/local/bin`)
8. figure out the key ID by running `pkcs11-tool --module /usr/local/lib/libeTPkcs11.dylib -l -O`
9. run osslsigncode with the correct module, engine and key id

URLs:
- [OpenSSL 1.1 from their website](https://www.openssl.org/source/)
- [OpenSC from github](https://github.com/OpenSC/OpenSC/releases)
- [Libp11 from github](https://github.com/OpenSC/libp11/releases)
- [osslsigncode from github](https://github.com/mtrojnar/osslsigncode). 

The engine I am using is `/usr/local/mac-dev/openssl-1.1.1b/lib/engines-1.1/libpkcs11.dylib` and the module is `/usr/local/lib/libeTPkcs11.dylib`.

Full command for signing:
```sh
osslsigncode sign -verbose -pkcs11engine /usr/local/mac-dev/openssl-1.1.1b/lib/engines-1.1/libpkcs11.dylib -pkcs11module  /usr/local/lib/libeTPkcs11.dylib -h sha256 -n app-name -t https://timestamp.verisign.com/scripts/timestamp.dll -certs /link/to/cert.pem -key 'key-id-here' -pass 'password' -in /link/to/app.exe -in /link/to/app.signed.exe
```

**Comment by frederikbosch** [comment]
I think I will issue a PR somewhere to have this better documented. Maybe @Littlebigdondon can confirm that what I am writing is correct.

**Comment by Littlebigdondon** [comment]
@frederikbosch seems like it should work. When I have a chance I will test this unless someone else can first. One thing to note—you’re passing two `-in` flags to `osslsigncode`; that last one should be `-out`.

Did you try my solution using Java? I know macOS doesn’t ship with Java anymore, so maybe it would be good to document multiple solutions, but I think the Java-based route is quite simple and doesn’t require exporting certificates (and hasn’t failed to sign any of my executables yet). 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by frederikbosch** [comment]
Thanks, I changed that. Actually, I wanted to ask @todanley to try it. I haven't tried your Java solution. But that also seems a good solution. When I do the PR, I will also try to document your solution.

**Comment by frederikbosch** [comment]
Where I can find the documentation anyway? I would like to create a link inside the Windows signing page here: https://www.electron.build/code-signing to a new document (e.g. code-siging-windows-on-unix).

**Comment by Littlebigdondon** [comment]
@frederikbosch thanks man, sounds great. The docs are on a [separate branch](https://github.com/electron-userland/electron-builder/tree/docs). They do have a [note about deploying the docs](https://github.com/electron-userland/electron-builder/blob/master/CONTRIBUTING.md#documentation) in the contributing guide.

**Comment by frederikbosch** [comment]
PR is there.

**Comment by develar** [comment]
@frederikbosch Thanks a lot! Published: https://www.electron.build/tutorials/code-signing-windows-apps-on-unix

**Comment by HeberLemus** [comment]
> * If you get `no slot with a token was found` or some errors like `sc connect card error` and `Card is invalid or cannot be handled` you are not using the correct module, make sure you use correct one (for me it was located at `/usr/local/lib/libeTPkcs11.dylib`).

can you explain how you identified it? which module to use? im not finding any information on how to know what module i need or if its supposed to come automatically with safenet 10.0

**Comment by johnryan** [comment]
Thanks for the updated docs!

Can anyone elaborate on steps 4 &5:

```
4) Check the library link to make sure you have the correct PKCS module. This link might be different per token. On Linux you will find it in /lib, while on Mac you can find it in /Library/Frameworks or /usr/local/lib.
5) Install token driver for Mac, export the certificate (convert it to pem when it is .cer)
```

Namely: 
1) How do I get the correct PKCS module if i don't have it installed
2) What is "token driver for Mac" I assume this is a SafeNet client for mac but is there a recommended version?

Thanks!
John

**Comment by DanielJackson-Oslo** [comment]
Trying to get the latest version of SafeNet for Mac, linked here but behind a login wall that requires you to be a Thales customer (something I still haven't figured out how to do): 

The version is called **SafeNet Authentication Client (SAC) 10.2 for Mac (Post GA)** and supposedly supports Catalina

It's found here:
https://data-protection-updates.gemalto.com/2019/10/29/safenet-authentication-client-sac-10-2-for-mac-post-ga-release-announcement/

Anyone have any luck finding this version online?

**Comment by DanielJackson-Oslo** [comment]
Anyone been able to make this work on Catalina?

**Comment by Littlebigdondon** [comment]
> Anyone been able to make this work on Catalina?

@DanielJackson-Oslo The v10.2 client I linked above, which does not require you to be a customer, does not work on Catalina. I have not yet found an open client that does :/

**Comment by menelike** [comment]
I am finally able to sign my Windows binaries. As already mentioned the latest authentication client for mac Catalina is not available to the public. I asked my vendor (GlobalSign) if they could me provide that email and luckily they could! I am afraid that I can not upload the SafeNet client anywhere due to licencing issues, but you should ask your vendor as well.

This is our working setup (we don't use the CLI):

- macOS `10.15.1 (19B88)`
- SafeNet Client `10.2.97.0`
- SafeNet eToken `5110 FIPS`

build configuration:
```JS
  const buildConfig = {
    win: {
      target: [
        {
          target: 'nsis',
          arch: ['ia32', 'x64'],
        },
      ],
      sign: (configuration: CustomWindowsSignTaskConfiguration): void =>
        signWin(configuration, tokenAlias, tokenPassword),
    }
  };
```

hardwareToken.cfg:
```
name = HardwareToken
library = /Library/Frameworks/eToken.framework/Versions/A/libeToken.dylib
slotListIndex = 0
```

signing:
```JS
/*
use the following command to determine the alias:
keytool -list -keystore NONE -storetype PKCS11 -providerclass sun.security.pkcs11.SunPKCS11 -providerArg hardwareToken.cfg
source: https://support.globalsign.com/customer/en/portal/articles/2722672-code-signing-in-java-token-based- for more information
*/
import { execSync } from 'child_process';
import * as path from 'path';

import { CustomWindowsSignTaskConfiguration } from 'app-builder-lib/out/codeSign/windowsCodeSign';

const jsign = path.join(__dirname, 'jsign-2.1.jar');
const keystore = path.join(__dirname, 'hardwareToken.cfg');

export default (
  configuration: CustomWindowsSignTaskConfiguration,
  alias: string,
  storepass: string
): void => {
  const { hash } = configuration;

  if (!alias) throw Error('missing argument alias');
  if (!storepass) throw Error('missing argument storepass');

  console.log(`signing (${hash}): ${configuration.path}`);

  const cmd = [
    'java',
    `-jar ${jsign}`,
    `--keystore ${keystore}`,
    '--storetype PKCS11',
    '--tsaurl http://timestamp.digicert.com',
    `--alias "${alias}"`,
    `--storepass "${storepass}"`,
    `"${configuration.path}"`,
  ];

  execSync(cmd.join(' '), {
    stdio: 'inherit',
  });
};
```

Hopefully, this will help others.

**Comment by likema** [comment]
@frederikbosch 

I practiced  https://github.com/electron-userland/electron-builder/issues/1299#issuecomment-393504798 with **SafeNet eToken 5110** in **Ubuntu 16.04**, but it **failed**.

First of all, I found the [patch](https://sourceforge.net/p/osslsigncode/osslsigncode/ci/50b66a1eb43a1eafe80e8d5d89e94c4aa9b905a4/) is merged into osslsigncode upstream.

Then I cloned it  and built it. In addition, I installed `opensc` and `SafenetAuthenticationClient`: 

```bash
sudo apt-get install -y opensc
sudo dpkg -i SafenetAuthenticationClient-9.0.43-0_amd64.deb
```

Finally, 

```bash
pkcs11-tool --module /usr/lib/libeTPkcs11.so -r --id 'key id' --type cert > pubkey.der
openssl x509 -inform DER -in pubkey.der -pubkey > pubkey.pem
```
```bash
./osslsigncode sign \
    -pkcs11engine /usr/lib/engines/engine_pkcs11.so \
    -pkcs11module /usr/lib/libeTPkcs11.so \
    -spc pubkey.pem \
    -key 'key id' \
    -pass 'pin' \
    -in <input exe> -out <output exe>
```
It printed **error**:

```bash
Unable to enumerate certificates
PKCS11_get_private_key returned NULL
Failed to load private key <key id>:error:26096080:engine routines:ENGINE_load_private_key:failed loading private key:eng_pkey.c:124:

Failed
```

All the above `key id` are the same.

BTW, 

```bash
pkcs11-tool --module /usr/lib/libeTPkcs11.so -O -l
```

printed (The sensitive data is replace by ...):

```
Using slot 0 with a present token (0x0)
Logging in to "...".
Please enter User PIN: 
Private Key Object; RSA 
  label:      SafeNet eToken 5110:....
  ID:         6d...ec
  Usage:      decrypt, sign, unwrap
Public Key Object; RSA 2048 bits
  label:      
  ID:        6d...ec
  Usage:      encrypt, verify, wrap
Certificate Object, type = X.509 cert
  label:      SafeNet eToken 5110:...
  ID:         6d...ec
Certificate Object, type = X.509 cert
  label:      
Certificate Object, type = X.509 cert
  label:      
Certificate Object, type = X.509 cert
  label:      
Private Key Object; RSA 
  label:      
  ID:         82...16
  Usage:      sign
Certificate Object, type = X.509 cert
  label:      0F...23
  ID:         82...16
```

**Comment by iwiedenm** [comment]
This thread was very helpful but I am still getting some errors. I am using the solution by @Littlebigdondon, trying to sign with my EV certificate on Mac and running the build command inside Docker.

I am getting this error
```
stderr: pesign: Failed to create a SunPKCS11 provider from the configuration file hardwareToken.cfg
Error executing command: pesign: Failed to create a SunPKCS11 provider from the configuration file hardwareToken.cfg
stderr: 
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at net.jsign.PESignerHelper.createSunPKCS11Provider(PESignerHelper.java:367)
	at net.jsign.PESignerHelper.build(PESignerHelper.java:258)
	at net.jsign.PESignerHelper.sign(PESignerHelper.java:377)
	at net.jsign.PESignerCLI.execute(PESignerCLI.java:109)
	at net.jsign.PESignerCLI.main(PESignerCLI.java:40)
Caused by: java.security.ProviderException: Library /Library/Frameworks/eToken.framework/Versions/A/libeToken.dylib does not exist
	at sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:304)
	at sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:103)
	... 9 more
Try `pesign --help' for more information.
```

**Comment by iwiedenm** [comment]
OK I think Im making progress. I tried the osslsigncode method and I was able to run and successfully code sign for Windows on my mac OUTSIDE of Docker. Since we am using the Docker method to build for Win on Mac, how do we run `osslsigncode` inside docker? We get this error: 

`bash: osslsigncode: command not found`

Any help would be greatly appreciated!
