### ISSUE TITLE
Multi language support for LICENCES

### ISSUE THREAD

**Issue by maczikasz** [electron-userland/electron-builder#1365]
* **Version**: 13.6.0

* **Target**: NSIS

Is it possible to somehow create an installer that will be able to handle multiple license files in different languages?

**Comment by develar** [comment]
Yes. But it will be not implemented by me any time soon due to other more priority issues. PR or donation welcome.

**Comment by maczikasz** [comment]
Thanks for the feedback I will see what we can do.

**Comment by develar** [comment]
Ouch, I did not notice who you are. Reopened.

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder/wiki/Options#NsisOptions-license

**Comment by fttx** [comment]
The documentation doesn't say what to put in the _license_ field in order to match the translated files.
I tried `"license":"license.rtf"` and `"license":"*.rtf"` but both don't work, while if i put the exact name of the file (like license_de.rtf) it works

electron-builder@17.5.0

`Error: Cannot find specified resource "build/*.rtf", nor relative to ...`

**Comment by develar** [comment]
@fttx Just do not specify it, just put in the `build` (build  resources dir).

**Comment by zanzara** [comment]
though more than 5 yrs.....  but this doesn't work.
License files in the build dir as i.e.  (`license_de.html` and  `license_en.html`) or (`license_de.txt` and  `license_en.txt`)   will not be shown while `setup` 

Plz update docs
