### ISSUE TITLE
one file in asar archive got corrupted

### ISSUE THREAD

**Issue by kutu** [electron-userland/electron-builder#1400]
* **Version**: 
16.0.0+

* **Target**: 
squirrel-windows

one of my html file got corrupted after updating to latest 16.2.0 version
downgrading versions one by one, i found that 15.6.3 works as expected

everytime i pack or build, corrupted file was always the same

then i tried to make a copy of this file in the same directory, and then this new file got corrupted everytime

so i guess, that one file is always last in app.asar file, and electron-builder do something with that file after pack it with asar util

corrupted file, got always the same size as original file, but data inside was rather 00 00 or some random bytes

**Comment by develar** [comment]
Is it possible to provide sample project to reproduce (and filename?)

**Comment by HitomiTenshi** [comment]
Same here! Ever since `16.0.0` my `logo.svg` file inside my assets folder gets corrupted (or lost? electron displays it as missing, although in the dev tool source list the file can be seen)

I tested every version since `16.0.0`, happens with all of them. `15.6.3` works as expected.

Only happens when `asar` is being used. If I set `asar` to `false`, the svg image displays correctly.

I sadly can't offer a sample project at the moment.

**Comment by develar** [comment]
Hmm.... We do check for corrupted files in our test suite, but only for main and package files. It seems I should improve out tests to check ALL files.

**Comment by kutu** [comment]
[test_corruption.zip](https://github.com/electron-userland/electron-builder/files/865436/test_corruption.zip)
```
npm run pack
cd dist/win-unpacked/resources
asar e app.asar app
```
check sidebar1.html

**Comment by develar** [comment]
@kutu Thanks a lot. Fixed.
