### ISSUE TITLE
electron-compile support bug

### ISSUE THREAD

**Issue by willyb321** [electron-userland/electron-builder#1465]
* **Version**:  16.8.3

* **Target**: All

So, I'm using electron-compile for development, and would like to use babel for distribution - however, I need to change the entry point for babel - is there any way to do this within electron-builder?

Thanks

**Comment by develar** [comment]
`--em.main=foo.js`

**Comment by willyb321** [comment]
Ah, that should work! Is there any way to do it with the json config?

**Comment by develar** [comment]
> I'm using electron-compile for development, and would like to use babel for distribution

electron-compile is supported. Don't recommended to use babel officially — please see https://github.com/electron/electron-compile/issues/207#issuecomment-288787604

**Comment by willyb321** [comment]
Ok, when I tried that it gave me an error saying that `es6-init.js` had not been precompiled? Not sure if thats on my side or not however

**Comment by develar** [comment]
If you insist — "WHAT? I just want bablel", electron-builder can do something smart for you. But please think twice.

**Comment by develar** [comment]
Please provide project or sample to reproduce and I will check.

**Comment by willyb321** [comment]
[Here](https://github.com/willyb321/media_mate) is the project I am using. I run `npm run dist` to build NSIS installer.

**Comment by develar** [comment]
I will check after my working day (10 hours).

**Comment by willyb321** [comment]
Ok thanks

**Comment by willyb321** [comment]
Actually, I think I've found the reason electron-compile isn't working in built application on my windows box - the cache isn't being populated with built files, rather just `compiler-info.json.gz`. I tested on my mac box and it worked absolutely fine and actually populated the cache. I also tested making the cache on windows myself, and that actually had the built files in there - however when I ran electron-builder it removed the contents and just left `compiler-info.json.gz` @develar 
![image](https://cloud.githubusercontent.com/assets/9222609/25551250/9cb4808a-2cc5-11e7-9e05-98387218829e.png)

**Comment by willyb321** [comment]
Any update on this @develar ?

**Comment by develar** [comment]
Sorry for delay, I will take a look soon.

**Comment by willyb321** [comment]
Ok thankyou

**Comment by whphhg** [comment]
I ran into the (same?) issue. I'm trying to pack https://github.com/whphhg/vcash-electron/blob/master/package.json (on Linux - tar.gz) and keep getting the following error when I try to run the binary in dist/linux-unpacked: `Error: Asked for /home/.../app.asar/initialize.js but it was not precompiled!`.

The `package.json` on the `master` above is not yet updated to include electron-builder, so these are the changes I've made to it so far:

- I've moved electron-compile to dependencies (was in dev)
- Added pack and dist to scripts
- Added build: ``
"build": {
 "appId": "vcash.electron.gui",
 "linux": {
   "category": "Network",
   "target": [
     "tar.gz"
   ]
 }
}
``

Which is strange because when I execute `npm run pack` it looks like it's precompiling the source,

``
npm run pack
vcash-electron@0.30.0 pack /home/whphhg/Vcash/electron
build --dir
No native production dependencies
Packaging for linux x64 using electron 1.6.7 to dist/linux-unpacked
Compiling using electron-compile
``

**Comment by willyb321** [comment]
Sorry to be a bother, but have you found any fix for this? @develar
