### ISSUE TITLE
Modules not loading after asar packing after build

### ISSUE THREAD

**Issue by arkakkar** [electron-userland/electron-builder#1517]
* **Version**: 7.26.0

* **Target**: Windows exe, nupkg, delta nupkg

Packaging using electron builder packages successfully but on opening the app results in issues like module not found. Used to work fine earlier but not sure whats happening now.
Also tried using the latest version 17.1.1 , still the same issue.
App works fine when non packaged.
![capture](https://cloud.githubusercontent.com/assets/13099382/25547247/e52d8592-2c83-11e7-81fd-886182d55d0e.PNG)

Docs mention it automatically detects modules that needs to be unpacked.
<img width="302" alt="screen shot 2017-04-29 at 2 33 06 am" src="https://cloud.githubusercontent.com/assets/13099382/25547358/609bf8d0-2c84-11e7-94dd-824accdb9e38.png">

**Comment by paulprins** [comment]
The issue is that your script is likely running from inside the ASAR package (which is fine) so you simply need to do some path magic. I did this in my app and it solved the problem.

	if( __dirname.includes(".asar") ){
		console.log("running in ASAR");
		var awsomeModule = require( path.join( __dirname.replace('.asar', '.asar.unpacked'), 'node_modules', 'awsomeModule' ) );
	}else{
		var awsomeModule = require('awsomeModule');
	}

The documentation is not saying that your JS will automatically find the unpacked files, but that those resources which need to not be packed will be detected and not included in the ASAR package. So the language in the documentation is correct, but not what you were expecting it to do. If those resources were packed it would not run correctly.
