### ISSUE TITLE
Allow to start app after silent install

### ISSUE THREAD

**Issue by maczikasz** [electron-userland/electron-builder#1545]
* **Version**:  latest

 latest

* **Target**:  nsis

Hi, we would like to do silent updates on our app, but using our one click installer that's at the moment not possible. We are calling quitAndInstall on the update-downloaded trigger, which does not start in silent mode.

The other thing is that we would like to do it seemlessly so the app should start after a silent install.

There are two things there then, to allow to specify on quit and install to do a silent one , or an other method, and the other thing is to be able to specify for the installer a flag at runtime or compile time that overrides the if in : https://github.com/electron-userland/electron-builder/blob/002a7149ca71d931e061b42f5520458ac60262f0/packages/electron-builder/templates/nsis/installSection.nsh#L192

**Comment by develar** [comment]
If you call `quitAndInstall` explicitly (not auto install after user update), why installation should be silent?

**Comment by maczikasz** [comment]
what we want to achieve is to install as soon as the update is downloaded then start the app again, and this to be completely silent

Our app normally runs in the background (on the tray, this way we can achieve silent updates without the user being notified) if there is a better way to achieve this then pls tell me

**Comment by maczikasz** [comment]
My understanding how this works at the moment:

Install on app quit -> silent mode -> app wont start automatically
Install by shutting down the app -> non silent (now silent possible) -> app starts automatical

**Comment by develar** [comment]
App will be not started automatically on silent install. As you pointed (https://github.com/electron-userland/electron-builder/blob/002a7149ca71d931e061b42f5520458ac60262f0/packages/electron-builder/templates/nsis/installSection.nsh#L192). So, I think, this issue should be opened until it is not fixed.

**Comment by maczikasz** [comment]
I closed by accident, probably clicked on the wrong button, sry

**Comment by tiangolo** [comment]
I just had an issue using TypeScript, it seems like I have to call `autoUpdater.quitAndInstall(isSilent: boolean)` with an explicit `false` for the `isSilent` parameter, as in `autoUpdater.quitAndInstall(false)`. 

Otherwise I see a `Supplied parameters do not match any signature of call target.`.

---

But as I understand, that flag should have a default to `false` and be needed only for Windows / NSIS, right? That's what I infer from this comment: https://github.com/electron-userland/electron-builder/blob/master/packages/electron-updater/src/AppUpdater.ts#L265

It seems to have the default `false` in the specific code for NSIS in https://github.com/electron-userland/electron-builder/blob/master/packages/electron-updater/src/NsisUpdater.ts#L85

But not in the general `AutoUpdater`: https://github.com/electron-userland/electron-builder/blob/master/packages/electron-updater/src/AppUpdater.ts#L267

Am I misunderstanding something or maybe does the `AutoUpdater` need to have that default parameter too?
