### ISSUE TITLE
set asar false is not work

### ISSUE THREAD

**Issue by divefox** [electron-userland/electron-builder#1549]
* **Version**: 
version 13.11.1 up to latest 17.8.0

* **Target**: 
all platforms

when I up to the latest version 17.8.0, the config setting asar = false is not work. Older version 13.11.1 is work fine.
Is that a bug?
Could someone tell me how to fix it?
Thank you very much!

**Comment by black-snow** [comment]
Please provide your build config if possible.

**Comment by belloyang** [comment]
I have encountered the same issue. when asar is set to false, the resource is not asar packed, but it is also not transpiled, since my project is written in Typescript, I can't start the app.
when I set asar to true, I have to manually unpack the archive. and it works fine after that.
By comparison, the unpacked resource( when asar=false ) misses `__shim.js` and `.cache` folder which can be found in the manually unpacked archive.
Can anyone please share some idea or hint about how can I fix this problem? I really appreciate it.
by build config is as follows:
```
"build": {
    "asar": false,
    "win": {
      "target": [
        "nsis"
      ]
    },
    "nsis": {
      "oneClick": false,
      "perMachine": true,
      "allowElevation": true,
      "allowToChangeInstallationDirectory": true
    }
  }
```

**Comment by black-snow** [comment]
Sadly, I don't currently have time to help. Try following the pipeline to see where it starts to fail for you.
