### ISSUE TITLE
lowering minVersion 10.0.14316 for Windows Store .appx

### ISSUE THREAD

**Issue by giorgio-zamparelli** [electron-userland/electron-builder#1594]
* **Version**: 1.4.15
* **Target**: appx
.appx Windows Store apps are restricted by default to have min version 10.0.14316.0
This number is hard coded in the file [electron-builder/packages/electron-builder/templates/appx/appxmanifest.xml](https://github.com/electron-userland/electron-builder/blob/43add64ebf0943287858301b334dac8b28aee770/packages/electron-builder/templates/appx/appxmanifest.xml

Would it be possible to change the minVersion to an earlier OS Build of Windows 10 or that would be cause some incompatibility with some tools used by electron-builder?

**Comment by black-snow** [comment]
Thanks for your feedback.

I think I read something about redstone update being required in order to run desktop-bridge converted stuff. Don't know about the version though and if this (still) applies.

Anyhow, if you really need this you could always unpack the appx, change the manifest, pack it up again (and sign it again).

**Comment by black-snow** [comment]
There's also this: https://stackoverflow.com/questions/43925140/minimum-version-of-windows-for-centennial-apps/43926616#43926616

**Comment by develar** [comment]
As in the https://github.com/felixrieseberg/electron-windows-store/blob/master/template/appxmanifest.xml
