### ISSUE TITLE
Update from mirror

### ISSUE THREAD

**Issue by KochiyaOcean** [electron-userland/electron-builder#1600]
* **Version**: 
electron-builder@17.3.0
electron-updater@1.16.0
* **Target**: 
windows, mac

My users are mostly in China, where can't establish a stable connection to GitHub releases.
I have a mirror server of GitHub releases, and wants to give a option to select mirror or GitHub as update server for users.
But I have noticed that `setFeedURL` method is deprecated. Is there any other ways to set a mirror server besides GitHub release?

**Comment by develar** [comment]
Deprecated as string url, but uou can use `setFeedURL` (https://github.com/electron-userland/electron-builder/wiki/Auto-Update#module_electron-updater.AppUpdater+setFeedURL) to set configuration in runtime. And if url is string, it will be automatically converted into `generic` provider.

**Comment by develar** [comment]
Or do you mean that you have mirror of Github (i.e. you want to use Github provider, but with different url)?

**Comment by KochiyaOcean** [comment]
@develar Yes, my mirror is a completely dump of GitHub release
![image](https://cloud.githubusercontent.com/assets/8194131/26620178/4fc03928-4614-11e7-836e-e75ab0f18ac1.png)

**Comment by KochiyaOcean** [comment]
@develar If it's hard to set mirror as update server directly I will use a reverse proxy server as generic server.

**Comment by develar** [comment]
There are two stopper issues:

1. Your mirror doesn't have releases atom feed. So, GithubProvider cannot be used.
2. No simple way to set generic URL because in case of GitHub url contains version number.

So, I recommend you to not use GitHub releases at all for updates.

Configure 2 publish providers: first generic and second github. First will be used as update server, and publish will be performed for all. Of course, electron-builder cannot publish to generic server, so, you need to do it.

Simple way to avoid any issues and maintaining own servers — just use `s3` provider.

**Comment by KochiyaOcean** [comment]
@develar Thanks for your advice. In fact almost all of the cloud server provider (including s3) is blocked in China so I will build a generic server instead.

**Comment by develar** [comment]
Yeah... shiny open world.
