### ISSUE TITLE
Support override Application Manifest options.

### ISSUE THREAD

**Issue by cumajkeee** [electron-userland/electron-builder#1649]
Windows default Toast notification are using by default background color from Application manifest. Will be nice to have possibility to override some manifest options by setting some properties in package.json.

See more details according notification [here](https://social.msdn.microsoft.com/Forums/en-US/47963e9b-3020-4311-b336-71d47f04153f/how-to-change-toast-notifications-size-and-background-color?forum=winappsuidesign)

**Comment by dbolton** [comment]
The underlying electron-packager added support for "application-manifest" (and "requested-execution-level") in May 2017 (at least that's when it got added to the API doc)
https://github.com/electron-userland/electron-packager/blob/master/docs/api.md

Is there a way to call this API from electron builder?

**Comment by develar** [comment]
@dbolton I prefer to not force users to use low-level way. Could you please describe what do you want to change in the manifest, and maybe some easy declarative way will be added for you.

**Comment by dbolton** [comment]
In my case I needed to request elevated privileges which I discovered I could do by using the requestElevatedPrivileges package setting. I came across it by just adding similar wording to my package.json (and then being guided by the error messages). I documented the method here: https://stackoverflow.com/questions/37322862/check-if-electron-app-is-launched-with-admin-privileges-on-windows/46779649#46779649

Should this be added to the official documentation for electron builder?

**Comment by develar** [comment]
@dbolton It is documented — https://www.electron.build/configuration/win#WindowsConfiguration-requestedExecutionLevel

Issue will be closed as backlog. If you need some settings, just ask us :)

**Comment by raphaelmenges** [comment]
> If you need some settings, just ask us :)

Hello @develar! I would gladly take your offer and would like to ask you for adding support to set the `uiAccess` flag in the manifest, which is another property of the `requestedExecutionLevel` next to the `level` in a manifest: <https://docs.microsoft.com/en-us/windows/win32/winauto/uiauto-securityoverview#setting-uiaccess-in-the-application-manifest-file>

**Comment by HadiModarres** [comment]
@raphaelmenges Did you find a way to do this? Electron builder seems to not support it yet, and different versions of "mt.exe" that I used to modify the manifest they all fail with a general error message

**Comment by raphaelmenges** [comment]
I was able to modify the manifest using `mt.exe`from the `afterPack` hook of Electron builder. First, i use `mt.exe` to extract the current manifest. Then i set `uiAccess` to `true`. Last, i use `mt.exe` again to embed the updated manifest to the `.exe`.

Which error does `mt.exe` show to you? Perhaps make sure to place `midlrtmd.dll` next to `mt.exe` as it requires the dll to work!

**Comment by HadiModarres** [comment]
@raphaelmenges 
afterPack worked like a charm, thanks mate. I can generate the executable but it throws an error still, but I think it's related to the other requirement of using uiAccess which is signing with a trusted root CA. I'm applying for one at the moment.

**Comment by raphaelmenges** [comment]
You should be able to test it on your machine with a self signed certificate!

**Comment by raphaelmenges** [comment]
Your setup sounds good to me and and for me it works. However, the only feature I use of `uiAccess` is to render contents over all Windows UI, i.e., the start menu. I did not test any other features.

I remember reading about a Windows bug that it sometimes caches manifest files per .exe by its name and one cannot delete this cache. At least on my development machine `uiAccess` sometimes works and sometimes it does not. But on production systems it works always. Maybe the same happens to you?

**Comment by HadiModarres** [comment]
@raphaelmenges 
I resolved my issue, and it turned out I didn't need uiAccess at all for my use case. What I was trying to do was to continue to control Windows by calling SendInput, but this stopped working when Windows was locked or UAC prompt showed. 
It stops working because those special cases run on a different desktop called Winlogon and regular programs cannot send input to that desktop. In order to achieve this we need to have a process with the same access token of `winlogon.exe` process, and the only way to access that token is to run a service as SYSTEM user. So the flow goes like:
1- App runs and elevates 
2- App starts a service as SYSTEM user 
3- The service finds winlogon.exe and copies its access token
4- The service creates a new process (CreateProcessAsUser) with that token 
5- The new process needs to listen to events of desktop changes and call `setThreadDesktop` to switch between Default and Winlogon desktops

Interesting thing for me was I was able to achieve all this with JNA in Java. 
As for uiAccess I'm pretty confused what it's actually used for, I'm guessing by the scenario you mentioned it's just used for drawing on protected UI but not sending keyboard or mouse input to it.

**Comment by hpateljc** [comment]
@raphaelmenges I am trying your idea to update uiAccess flag on afterPack event, but having a hard time to make it work. Can you please share some code snippet if you have ? Thanks a lot for idea.

**Comment by shulzPro** [comment]
@HadiModarres 
@raphaelmenges 

I've been struggling with the problem for several days. Could you give any tips? Changing uiAccess to true breaks my electron app even if I sign it with a certificate.

I would appreciate any help.

**Comment by HadiModarres** [comment]
@shulzPro 

Have you put your script in afterPack hook? That's critical because that's the stage where your application is packed and there's an executable with a manifest, but right before signing it. If you do it after signing the signature will not match your binary and OS will sound the alarm when trying to run it. 

For my own use case, since I was creating a new process from another elevated process, I realized I could set the uiAccess property on the access token before creating the process, so didn't really need ``mt.exe`` , but I did manage to make it work with ``mt.exe`` before that.
