### ISSUE TITLE
Multiple icons for Windows?

### ISSUE THREAD

**Issue by JohnWeisz** [electron-userland/electron-builder#1663]
**Version**: `18.6.2`
**Target**:  `--win --x64`

_Thanks for maintaining electron-builder, it's a very valuable asset._

-----

I have linked the required 256x256 .ico file for `win` and electron-builder runs flawlessly and packs my app with the correct icons.

However, 256x256 is way too much for some display locations, such as the app window frame header, where it looks very noisy and low quality (as you would expect from jamming a 256x256 icon into a 16x16 display box).

To avoid this, I would like to include multiple icon sizes, such as 16x16, 32x32, and so on. How can I do this? I tried the following file-names, but it has no effect on Windows builds:

```
icon.ico (256x256)
16x16.ico
32x32.ico
...
```

**Comment by SimulatedGREG** [comment]
@JohnWeisz 

The `*.ico` filetype can be used for a variety of sizes all in one file. It can almost be thought of like a small archive of icons. So instead of trying to use multiple `*.ico` files (which won't work), just use something like GIMP or ConvertICO to create a set of icons in 1 `*.ico` file.

Related: https://graphicdesign.stackexchange.com/questions/17257/creating-an-ico-file-with-multiple-sizes-web-application

**Comment by JohnWeisz** [comment]
@SimulatedGREG 

So it's like mip-maps in `.dds` files. Thank you for your help.

**Comment by sdegutis** [comment]
Can a build phase be added into Electron Builder that converts multiple icons (e.g. when given via `icons` key as array of filenames) into an .ico file, instead of having this be a separate manual step?
