### ISSUE TITLE
How to use the integration with electron-forge?

### ISSUE THREAD

**Issue by alexstrat** [electron-userland/electron-builder#1675]
Reading thru #1193, it looks like I can build en `electron-forge` project with builder. Is that correct?
I can't find any documentation on how to do it. Happy to add doc if someone explains give me some hints.

**Comment by develar** [comment]
Electron-builder 19.x support forge — use 19.3.0

Just build forge as any other project. All forge commands except start not needed. Please note — forge uses by default `out`, but builder `dist`. So, if you by error uses forge make, you need or remove out dir manually, or add out dir to excluded using `files` option, or set directories.output to out (so, builder will use also out dir.

Before using forge — consider to use [boilerplates ](https://github.com/electron-userland/electron-builder#boilerplates), because quality of boilerplates are better than forge templates. As example, electron compile projects have performance problems in production. https://github.com/electron/electron-compile/issues/221

**Comment by alexstrat** [comment]
Thank you @develar! I was able to build for mac, but on windows it looks like the es6 support is not kicking in given the error message when running the application.

![screenshot 2017-06-17 00 10 50](https://user-images.githubusercontent.com/687961/27246446-ee116202-52f1-11e7-8e16-58266761f480.png)

Do you have any clue? Note I'm rebuilding a native module (sqlite3).

**Comment by alexstrat** [comment]
FUP in #1686
