### ISSUE TITLE
GUI to build and lint

### ISSUE THREAD

**Issue by azurinko** [electron-userland/electron-builder#1706]
Can we have a electron GUI for this? If somebody solve the programatic Issue I can do the UI.

**Comment by develar** [comment]
Planned. App will be called `Electrify`. When? Well... Are you really can help? Plan — use react + https://ant.design to create step-by-step wizard to configure and build Electron app.

**Comment by azurinko** [comment]
In a month or so, I need to find some time for that...

**Comment by develar** [comment]
> Is there a repo for that

https://github.com/electron-userland/electrify But not yet pushed. Feel free to create your repo and I will merge it and add you as a collaborator with push rights.

> Also I would go for Vue instead of react.

I am not frontend developer and know nothing, but I prefer react because of there is excellent UI lib https://ant.design/

What I want to do:

Step-by-step wizard to guide user from app creation to app code signing/publishing/auto-update. UI like https://ant.design/components/layout/#components-layout-demo-fixed-sider where in the nav all steps as vertical bar. Each step will verify user app and suggest fixes.

As part of this app, GUI to build can be added.

I don't insist to use react. If you will demonstrate app on Vue that will have such UI (or propose something more better) to implement wizard and GUI to build — it will be cool.

**Comment by develar** [comment]
>  If somebody solve the programatic Issue I can do the UI

Feel free to contact me directly using slack direct messages (to join https://slackin.electron.build)

**Comment by azurinko** [comment]
That layout is just composed of four or so components... We should add something like CTRL+Shift+P bar that is in atom, I don't know how it is called to navigate hyperquickly trought the app, and app should have api on this bars that are system wide...

**Comment by develar** [comment]
> We should add something like CTRL+Shift+P bar that is in atom, I don't know how it is called to navigate hyperquickly trought the app

macOS: Spotlight
JetBrains IDE: Search EveryWhere
Atom: https://github.com/atom/command-palette

I prefer to use react. I don't see any descent UI framework like we have for react. Ant.Design is amazing (and we have number other macos/win specific ui frameworks for react, but not for vuejs) and no such framework for vuejs. Also, react is much more popular and it will be easy for other contributors to help. But I said,  "if you will demonstrate app on Vue that will have such UI (or propose something more better) to implement wizard and GUI to build — it will be cool".

**Comment by azurinko** [comment]
We wont build something like ant for vue if we continue using react... All we need is just repository system for components. It's simple, I think in august Vue will became more interesting than react.

**Comment by develar** [comment]
@azurinko As stated, I am not frontend/web developer. Not easy and not interesting for me to adjust some existing UI framework for vuejs to be so cool/good looking as ant.design provides without any effort. If you or somebody else will demonstrate prototype app on vuejs, that will look good on macOS, — we will use vuejs. Until that, I will create such app using react.

**Comment by develar** [comment]
To be clear — it will be easy to create GUI to build. But to create wizard — we need rich and consistent UI framework (we cannot reuse different libraries, because I cannot rely that someone will help me — and as I am not web developer, it is not interesting for me to "and now we will try to use it all together").

**Comment by azurinko** [comment]
Can you mockup the screens you need in something like sketchup, or ... You know, the layout... I will provide you vue component with hooks as functions already on action triggered where you'll just hook up functionality.

**Comment by azurinko** [comment]
But I guess we will argue about rounded borders... :D

**Comment by azurinko** [comment]
And also, I just found out there is 3 implementations of ant desing for vue, just one for react.

**Comment by develar** [comment]
I found also ant for vue, but is not adapter, it is reimplementation like ant.

> Can you mockup the screens you need in something like sketchup

 I need something like https://ant.design/components/layout/#components-layout-demo-fixed-sider

Yes, you can create such components from scratch since it is just CSS/HTML, but what to do in the future? Maintain own style? Using some ui framework will allow me to just write logic and do not think about UI.

**Comment by develar** [comment]
In general, it will cool to use OS like UI, like react desktop/photon, but as far I understand in this case we need to think about each platform/ use of-specific components. So for now I decided to just some people universal UI.

**Comment by azurinko** [comment]
So left sidebar, that box on top is search? Does widow have to be resizable? I think we can keep original window frame, I am working on concept on clossplatform windowframe(mac style for macOS, win style for winOS, on linux you can choose) as component for electroned vue... But it's long way, electron now lacks api that have callback on maximize and similar events.

You can't give apple haters mac like UI... You can't use windows style either, it's hard those days.

**Comment by develar** [comment]
Ok, ok, vuejs. But I cannot agree that we can do app without using some UI framework — e.g. On some screen we need steps component. In case of ant I can simply use tested and ready component. Otherwise I will need to wait solution from you and then hope that it will look in the same professional and polished way as other parts of app :(

**Comment by azurinko** [comment]
Sketch up what you need... ;) Exactly the screen after screen, I will slice it up into reusable components and publish up for review.

**Comment by develar** [comment]
That is exactly the problem. Sketch means that I need to paint it somehow instead of just prototyping using ready components as Lego blocks :)

**Comment by azurinko** [comment]
Ach... I need computer to start working, I will buy something provisory instead of waiting for new CPUs releases and I will get something done... We'll see what will be used.

**Comment by develar** [comment]
Btw, why don't you like react?

**Comment by azurinko** [comment]
I've seen some facebook products before...

**Comment by azurinko** [comment]
Mostly that interface is slow if you don't have newer than 2013 processor

**Comment by develar** [comment]
I propose to use https://github.com/ElemeFE/element as UI framework. Vuejs looks promising. 

Material UI is no-no because from Google. And as no UI framework that will allow us to avoid platform specific code easily (obvious reasons — no direct mapping as apple differs from win not only in colors), for now we use universal style. And I don't see any descent alternative to And design (yes, Element does not follow spec precisely, but doesn't matter since consistent style is used).

**Comment by develar** [comment]
@azurinko https://github.com/electron-userland/electrify

**Comment by KamesCG** [comment]
Interesting. An Electron Application the builds Electron applications?

What kind of features are you imagining at first?

**Comment by develar** [comment]
App contains 3 blocks:

1. Wizard&linter Named as Project in the UI. To help you do several steps to prepare app for distribution. Without googling, RTFM.

2. Target configuration GUI. Nice UI to configure desired installer for Windows and so on.

3. Build UI. Will be removed if no help.

Block 1 will be ready to "use" next week.
