### ISSUE TITLE
For some reason when I make a new app it takes the package and main from the old project.

### ISSUE THREAD

**Issue by DeanPackard** [electron-userland/electron-builder#1745]
I'm using the most recent version
* **Version**: 

not applicable

* **Target**: 

I created an onsip desktop thing before for my first app and used electron builder to make an installer for it. Now I am making a new application with my own html, css, and js. the problem is that when i build the installer and run it, it pulls up the same stuff that was in my old app. It takes stuff from the other folders up in the file tree. I don't know why its doing this.

**Comment by develar** [comment]
Windows? Is it possible to provide old and new installer? Is error still reproducible if you remove app using uninstaller before installing new one?

**Comment by DeanPackard** [comment]
Yes this is on windows. I can't provide the installer through email because
the file is way too big. And yeah I can reproduce it over and over.

**Comment by develar** [comment]
You can share old and new installer on google drive (for develar).

**Comment by DeanPackard** [comment]
what email account would you like me to share these with?

**Comment by develar** [comment]
develar@gmail.com

**Comment by DeanPackard** [comment]
I shared both of them

**Comment by brandonmp** [comment]
not sure if this is related but i thought i was having the same problem--every time i built a new version and published to s3, I would download it in my windows VM and it'd be the old version. 

It turns out that because I didn't have the version # in the artifact name (because I wanted a stable download link), Cloudfront wasn't updating the distribution with the new file. Once I renamed the artifact, it updated the cache and the new artifact downloaded fine.

**Comment by DeanPackard** [comment]
I'll try that, thank you

**Comment by DeanPackard** [comment]
[image: Inline image 1]
I'm getting this error now. The helloworld folder is part of the filepath
for my old project. I don't know why it is even trying to look there.

**Comment by brandonmp** [comment]
img not showing up for me fyi

**Comment by DeanPackard** [comment]
Here it is as an attachment
