### ISSUE TITLE
GithubOptions - Private Repository

### ISSUE THREAD

**Issue by akendy** [electron-userland/electron-builder#1748]
electron-builder: 18.8.1
target: Mac Sierra 10.12.5

The repository of my releases is private, so I set the GH_TOKEN environment variable, but it is returning an error:
```
Error in auto-updater. ---> HttpError: 404 Not Found "method: undefined url: <URL>\n\n Please double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.
(...)
```
(It works if it's a public repository)

What file do I set the GithubOptions `"private": true`? I've tried adding it into the package.json file, like:
```
"build": {
    (...)
    "publish": [
        {
            "provider": "github",
            "private": true
        }
    ],
    (...)
}
```
But it didn't work

Thanks.. Appreciate any help

**Comment by develar** [comment]
Do you understand that user of app must add GH token? Not on build time?

**Comment by akendy** [comment]
So, I added the token, it is supposed to work here, isn't it?

**Comment by develar** [comment]
On runtime? Yes, but as env only on Windows. https://github.com/electron-userland/electron-builder/blob/master/packages/electron-updater/src/AppUpdater.ts#L325

Why not on Mac? Because you bash env is not available for app. https://stackoverflow.com/questions/135688/setting-environment-variables-in-os-x
