### ISSUE TITLE
Update Squirrel.Windows to 1.7.8

### ISSUE THREAD

**Issue by TimvdEijnden** [electron-userland/electron-builder#1762]
There's a new version out for Squirrel.Windows which fixes several bugs in the installer/updater.

https://github.com/Squirrel/Squirrel.Windows/releases/tag/1.7.6

**Comment by develar** [comment]
Not easy to update because LZMA is introduced and we need to verify some things.

**Comment by TimvdEijnden** [comment]
I understand, just let me know if I can do anything.

**Comment by develar** [comment]
For now I decided to wait when it will be finalised and proven to work (was 4 releases with bug fixes after initial release).

**Comment by TimvdEijnden** [comment]
There's a new release with bugfixes: https://github.com/Squirrel/Squirrel.Windows/releases/tag/1.7.7

**Comment by ascot21** [comment]
@develar what donation would be needed to get this done? willing to contribute if we could get this done soon

**Comment by develar** [comment]
Ha-ha-ha.... electron-builder PR was rejected and it was a reason of our fork... but now Squirrel.Window also uses some solution to speedup releasify — 7z. It means that difference between our fork and original will be reduced. Of course, quality of original Squirrel.Windows is not good (7z is used instead of 7za and no 32bit version of 7z), so, in any case for now we cannot use original.

I started work on updating Squirrel.

**Comment by develar** [comment]
Info for developers: SW doesn't support 0-level nupkg compressed files. It means that we are forced to use level `1` if `store` level requested.

**Comment by develar** [comment]
Unfortunately, SW still uses nuget under the hood.

**Comment by develar** [comment]
Squirrel.Windows updated to 1.7.8 in the 19.43.0.

> what donation would be needed to get this done

Problem is that this update is a result of our fork. So, it is our issue that we use it. But we have no choice because electron-builder quality level doesn't allow us to use original Squirrel.Windows (it is a reason why NSIS is recommended and default target for Windows). So, updated, sorry for delay :)

**Comment by develar** [comment]
Note for Docker users — maybe you will be forced to set additional env `TZ: Europe/Berlin` (any your favourite timezone). It is some not yet investigated mono issue. Since SW is not our main target, this issue will be investigated only by first user request (maybe our docker image should be modified somehow to mitigate this mono issue).

**Comment by ascot21** [comment]
thanks @develar
