### ISSUE TITLE
Auto-updater only running uninstaller as administrator

### ISSUE THREAD

**Issue by HRMsimon** [electron-userland/electron-builder#1857]
* **Version**: 19.16.2

* **Updater**: 2.7.1

* **Target**: nsis

When auto-updating a `perMachine: false`, `allowToChnageInstallationDirectory: true` application that has been installed machine-wide, only the uninstaller is running as an administrator. This has lead to the application itself being deleted, as the installer is running as a normal user and cannot write to `Program Files`

target sections of `package.json`:
```json
    "win": {
      "icon": "images/icon.ico",
      "certificateFile": "build/code-sign.pfx"
    },
    "nsis": {
      "oneClick": false,
      "allowToChangeInstallationDirectory": true,
      "createDesktopShortcut": false,
      "installerIcon": "images/icon.ico"
    },
```

`quitAndInstall` has `true` passed as the first argument to run the installer silently.

Custom installer.nsh (though removing it appears to have no effect):
```nsis
!ifndef BUILD_UNINSTALLER
  Function AddToStartup
    CreateShortCut "$SMSTARTUP\${APP_FILENAME}.lnk" "$INSTDIR\${APP_FILENAME}.exe" ""
  FunctionEnd

  ; Using the read me setting as an easy way to add an add to startup option
  !define MUI_FINISHPAGE_SHOWREADME
  !define MUI_FINISHPAGE_SHOWREADME_TEXT "Run at startup"
  !define MUI_FINISHPAGE_SHOWREADME_FUNCTION AddToStartup
!endif

!macro customInstall
  ${if} ${Silent}
    Var /GLOBAL startAppArgs
    ${if} ${Updated}
      StrCpy $startAppArgs "--updated"
    ${else}
      StrCpy $startAppArgs ""
    ${endif}

    ${StdUtils.ExecShellAsUser} $0 $startMenuLink "open" "$startAppArgs"
  ${elseIfNot} ${Updated}
    # create shortcuts in the start menu and on the desktop
    CreateShortCut "$startMenuLink" "$appExe" "" "$appExe" 0 "" "" "${APP_DESCRIPTION}"
    WinShell::SetLnkAUMI "$startMenuLink" "${APP_ID}"

    ClearErrors
    ${GetParameters} $R0
    ${GetOptions} $R0 "--no-desktop-shortcut" $R1
    ${If} ${Errors}
      CreateShortCut "$desktopLink" "$appExe" "" "$appExe" 0 "" "" "${APP_DESCRIPTION}"
      WinShell::SetLnkAUMI "$desktopLink" "${APP_ID}"
    ${endIf}
  ${endIf}
!macroend

!macro customUnInstall
  ${ifNot} ${Updated}
    Delete "$SMSTARTUP\${APP_FILENAME}.lnk"
  ${endIf}
!macroend
```

**Comment by develar** [comment]
allowToChnageInstallationDirectory was not intended for per user :) We need to forbid install to non user directories.

**Comment by jeremyspiegel** [comment]
This happens for me even if `allowToChangeInstallationDirectory` isn't set.

**Comment by burnhamup** [comment]
I'm also having this problem and digging into some possible solutions. 

The problem maybe stems from how `isAdminRightsRequired` is determined. Right now it is only set when you package an installer: 
https://github.com/electron-userland/electron-builder/blob/fca50aea42fc054b87bbe943bbe5c1c235a186e1/packages/app-builder-lib/src/targets/nsis/NsisTarget.ts#L295

However, when oneClick is false, and the user chooses a per machine install you still need admin rights to perform the update. You could have `isAdminRightsRequired` in those cases, but then users who choose a per user install will be prompted for admin rights when updating. 

I think a lasting solution involves the call to doInstall
 https://github.com/electron-userland/electron-builder/blob/f938de5aae09cb832a6f7f742e64a0d6c025fb9f/packages/electron-updater/src/BaseUpdater.ts#L63

Instead of determining whether admin rights are required when building the installer, I think the updater needs to check how the application is currently installed.

**Comment by hvuntokrul** [comment]
Here's a proposed fix to the situation on Windows where an Electron is installed for all users of the machine e.g. into Program Files, but fails to update (installed app version is deleted but the update is never installed) due to failure to request admin rights. Based on findings by @burnhamup 
https://github.com/electron-userland/electron-builder/pull/6073#issue-694335232
