### ISSUE TITLE
Error checking for updates: 404 

### ISSUE THREAD

**Issue by AhadCove** [electron-userland/electron-builder#1928]
Electron Updater: v2.8.5
Electron Builder: v19.20.0

Anytime I try to update it goes to a folder that I do not want and ends up being a 404 error because it does not exist.

Right now in my package.json I have publish that looks like this:
```
"publish": [
        {
          "provider": "github",
          "owner": "ahadcove",
          "repo": "lumia-twitch",
          "private": true
        }
      ]
```

and since this wasn't working, I set the feed url in autoUpdater:

```
  autoUpdater.setFeedUrl = "https://github.com/AhadCove/lumia-twitch";
```

This is private, so I also have my GH_TOKEN inside my ENV and made sure the GH_TOKEN has full access to repo.

Here is the error I am getting:

```
Cannot check for updates: HttpError: 404 Not Found
"method: undefined url: https://github.com/ahadcove/lumia-twitch/releases.atom\n\n    Please double check that your authentication token is correct. Due to security reasons actual status maybe not reported, 
but 404.\n    "
Headers: {
  "cache-control": [
    "no-cache"
  ],
  "content-encoding": [
    "gzip"
  ],
  "content-security-policy": [
    "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src data:; script-src 'self'; style-src 'unsafe-inline'"
  ],
  "content-type": [
    "text/plain; charset=utf-8"
  ],
  "date": [
    "Thu, 10 Aug 2017 19:21:15 GMT"
  ],
  "public-key-pins": [
    "max-age=5184000; pin-sha256=\"WoiWRyIOVNa9ihaBciRSC7XHjliYS9VwUGOIud4PB18=\"; pin-sha256=\"RRM1dGqnDFsCJXBTHky16vi1obOlCgFFn/yOhI/y+ho=\"; pin-sha256=\"k2v657xBsOVe1PQRwOsHsw3bsGT2VzIqz5K+59sNQws=\"; pin-sha256=\"K87oWBWM9UZfyddvDfoxL+8lpNyoUB2ptGtn0fv6G2Q=\"; pin-sha256=\"IQBnNBEiFuhj+8x6X8XLgh01V9Ic5/V3IRQLNFFc7v4=\"; pin-sha256=\"iie1VXtL7HzAMF+/PVPR9xzT80kQxdZeJ+zduCB3uj0=\"; pin-sha256=\"LvRiGEjRqfzurezaWuj8Wie2gyHMrW5Q06LspMnox7A=\"; includeSubDomains"
  ],
  "server": [
    "GitHub.com"
  ],
  "status": [
    "404 Not Found"
  ],
  "strict-transport-security": [
    "max-age=31536000; includeSubdomains; preload"
  ],
  "transfer-encoding": [
    "chunked"
  ],
  "vary": [
    "X-PJAX"
  ],

```

**Comment by develar** [comment]
Do you understand that your users will need to have token? Are  you on macOS?

**Comment by marcionicolau** [comment]
I have the same issue here. Any updates?

**Comment by develar** [comment]
@marcionicolau Answer to my question ;)

**Comment by AhadCove** [comment]
Sorry @develar
Yes I'm using mac. So injecting my ghtoken in at build time won't be enough?

**Comment by develar** [comment]
You should not use private github repo. Only if you understand what are you doing (e.g. you have GitHub org and create special read-only user to access releases).

1. You must not inject token during build using configuration. It is only for runtime.
2. terminal env on mac not available for mac app (https://github.com/sindresorhus/shell-env).

So, if you are not sure — do not use private repo. If you don't have public repo — just use s3.

**Comment by AhadCove** [comment]
I see. Will try it again and update. Thank you

**Comment by damianobarbati** [comment]
@AhadCove did you manage to have it working with GitHub?
Because I cannot understand what is the proper url for setFeedURL, I'm always getting `[error] autoUpdater: Error: Update check failed. The server sent an invalid response. Try again later.`

**Comment by drewberk** [comment]
I am having this issue with S3. 

The build works for "win" and the deploy to S3 works for both Mac and Windows (NSIS). However, auto update is throwing the following exception on the Mac. Windows auto update works just fine.

Here is a portion of my JS file used to build the DMG file.
`  
    var publishSetting = "always";
.
.
.
case 'mac':
        // build a MAC installer
        builder.build({
          targets: Platform.MAC.createTarget(),
          publish: publishSetting,
          config: {
            "extraFiles": [
              "documentation/**/*",
              "scripts/**/*"
            ],
            "directories": {
              "app": "dist",
              "output": "build"
            },
            "appId": "com.blah",
            "artifactName": "Blah Setup ${version}."+rev+".${ext}",
            "productName": "Blah",
            "copyright": "Copyright © 2020 Blah. All rights reserved.",
            "publish": [{
              "provider": "s3",
              "bucket": "bg-blah"
            }],
            "mac": {
              "target": "dmg",
              "files": ["**/*", "node_modules/**/*"],
              "extraResources": [
                {
                  "from": "src/assets/fonts",
                  "to": "fonts"
                }],
              "icon": "src/assets/icons/mac/blah.png",
              "type": "development",
              "provisioningProfile": "myApp.provisionprofile",
              "identity": "",
              "category": "public.app-category.business"
            }
          }
        })`

Below is the error I receive.

`
13:19:20.574 › [ ’Error: HttpError: 404 Not Found\n”method: GET url: https://github.com/BlahOrg/Blah/releases.atom\\n\\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\\n”\nHeaders: {\n “age”: [\n  “0"\n ],\n “cache-control”: [\n  “no-cache”\n ],\n “content-encoding”: [\n  “gzip”\n ],\n “content-length”: [\n  “40"\n ],\n “content-security-policy”: [\n  “default-src \‘none\’; base-uri \‘self\’; connect-src \‘self\’; form-action \‘self\’; img-src \‘self\’ data:; script-src \‘self\’; style-src \‘unsafe-inline\‘“\n ],\n “content-type”: [\n  “text/plain; charset=utf-8"\n ],\n “date”: [\n  “Fri, 27 Mar 2020 02:19:20 GMT”\n ],\n “expect-ct”: [\n  “max-age=2592000, report-uri=\\“https://api.github.com/_private/browser/errors\\“”\n ],\n “referrer-policy”: [\n  “origin-when-cross-origin, strict-origin-when-cross-origin”\n ],\n “server”: [\n  “GitHub.com”\n ],\n “set-cookie”: [\n  “_gh_sess=TDG6BGpZUGAhjGHxWmNpd487biAejr1%2BheM5ob0M6XBIMCNVircR8dBsEQCLEQCXKlEWCXy84y749M8xV6tScwA7L1rzVQAjlo4JayshG%2B46iia1onFzulLOXBHYUqQ06Zs29Fj5CMahF9U4P4k26FG1SjP0xdgrha72qSWTgyVOFAF76xKSPnurFSOTNuGHThk3jcAXhmoNqRa1PbuOnFjlQv%2Bgm7ahPczrwH%2Bqh9b3JbJFPyeh0zsGJclgdTxJmmgZkMESFbnC4hsSwIPNjQ%3D%3D--mEmnl%2FOGisrUtIdx--506LNIVZ1YOie6I%2F1z2ihw%3D%3D; Path=/; HttpOnly; Secure”,\n  “_octo=GH1.1.1224314304.1585275560; Path=/; Domain=github.com; Expires=Sat, 27 Mar 2021 02:19:20 GMT; Secure”,\n  “logged_in=no; Path=/; Domain=github.com; Expires=Sat, 27 Mar 2021 02:19:20 GMT; HttpOnly; Secure”\n ],\n “status”: [\n  “404 Not Found”\n ],\n “strict-transport-security”: [\n  “max-age=31536000; includeSubdomains; preload”\n ],\n “vary”: [\n  “X-PJAX, Accept-Encoding, Accept, X-Requested-With, X-GitHub-OpenAPI”\n ],\n “x-content-type-options”: [\n  “nosniff”\n ],\n “x-frame-options”: [\n  “deny”\n ],\n “x-github-request-id”: [\n  “EFED:36C1:71DB78:A7C642:5E7D62A8”\n ],\n “x-xss-protection”: [\n  “1; mode=block”\n ]\n}\n  at createHttpError (/Applications/Blah.app/Contents/Resources/app.asar/node_modules/builder-util-runtime/out/httpExecutor.js:84:10)\n  at ElectronHttpExecutor.handleResponse (/Applications/Blah.app/Contents/Resources/app.asar/node_modules/builder-util-runtime/out/httpExecutor.js:168:14)\n  at ClientRequest.request.createRequest.response (/Applications/Blah.app/Contents/Resources/app.asar/node_modules/builder-util-runtime/out/httpExecutor.js:134:16)\n  at ClientRequest.emit (events.js:182:13)\n  at URLRequest.ClientRequest.urlRequest.on (/Applications/Blah.app/Contents/Resources/electron.asar/browser/api/net.js:207:12)\n  at URLRequest.emit (events.js:182:13)’ ]
13:19:20.576 › [ ’Error in auto-updater. HttpError: 404 Not Found\n”method: GET url: https://github.com/BlahOrg/Blah/releases.atom\\n\\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\\n”\nHeaders: {\n “age”: [\n  “0"\n ],\n “cache-control”: [\n  “no-cache”\n ],\n “content-encoding”: [\n  “gzip”\n ],\n “content-length”: [\n  “40"\n ],\n “content-security-policy”: [\n  “default-src \‘none\’; base-uri \‘self\’; connect-src \‘self\’; form-action \‘self\’; img-src \‘self\’ data:; script-src \‘self\’; style-src \‘unsafe-inline\‘“\n ],\n “content-type”: [\n  “text/plain; charset=utf-8"\n ],\n “date”: [\n  “Fri, 27 Mar 2020 02:19:20 GMT”\n ],\n “expect-ct”: [\n  “max-age=2592000, report-uri=\\“https://api.github.com/_private/browser/errors\\“”\n ],\n “referrer-policy”: [\n  “origin-when-cross-origin, strict-origin-when-cross-origin”\n ],\n “server”: [\n  “GitHub.com”\n ],\n “set-cookie”: [\n  “_gh_sess=TDG6BGpZUGAhjGHxWmNpd487biAejr1%2BheM5ob0M6XBIMCNVircR8dBsEQCLEQCXKlEWCXy84y749M8xV6tScwA7L1rzVQAjlo4JayshG%2B46iia1onFzulLOXBHYUqQ06Zs29Fj5CMahF9U4P4k26FG1SjP0xdgrha72qSWTgyVOFAF76xKSPnurFSOTNuGHThk3jcAXhmoNqRa1PbuOnFjlQv%2Bgm7ahPczrwH%2Bqh9b3JbJFPyeh0zsGJclgdTxJmmgZkMESFbnC4hsSwIPNjQ%3D%3D--mEmnl%2FOGisrUtIdx--506LNIVZ1YOie6I%2F1z2ihw%3D%3D; Path=/; HttpOnly; Secure”,\n  “_octo=GH1.1.1224314304.1585275560; Path=/; Domain=github.com; Expires=Sat, 27 Mar 2021 02:19:20 GMT; Secure”,\n  “logged_in=no; Path=/; Domain=github.com; Expires=Sat, 27 Mar 2021 02:19:20 GMT; HttpOnly; Secure”\n ],\n “status”: [\n  “404 Not Found”\n ],\n “strict-transport-security”: [\n  “max-age=31536000; includeSubdomains; preload”\n ],\n “vary”: [\n  “X-PJAX, Accept-Encoding, Accept, X-Requested-With, X-GitHub-OpenAPI”\n ],\n “x-content-type-options”: [\n  “nosniff”\n ],\n “x-frame-options”: [\n  “deny”\n ],\n “x-github-request-id”: [\n  “EFED:36C1:71DB78:A7C642:5E7D62A8”\n ],\n “x-xss-protection”: [\n  “1; mode=block”\n ]\n}’ ]
(node:4542) UnhandledPromiseRejectionWarning: HttpError: 404 Not Found
“method: GET url: https://github.com/BlahOrg/Blah/releases.atom\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n”
Headers: {
 “age”: [
  “0"
 ],
 “cache-control”: [
  “no-cache”
 ],
 “content-encoding”: [
  “gzip”
 ],
 “content-length”: [
  “40"
 ],
 “content-security-policy”: [
  “default-src ‘none’; base-uri ‘self’; connect-src ‘self’; form-action ‘self’; img-src ‘self’ data:; script-src ‘self’; style-src ‘unsafe-inline’”
 ],
 “content-type”: [
  “text/plain; charset=utf-8"
 ],
 “date”: [
  “Fri, 27 Mar 2020 02:19:20 GMT”
 ],
 “expect-ct”: [
  “max-age=2592000, report-uri=\“https://api.github.com/_private/browser/errors\“”
 ],
 “referrer-policy”: [
  “origin-when-cross-origin, strict-origin-when-cross-origin”
 ],
 “server”: [
  “GitHub.com”
 ],
 “set-cookie”: [
  “_gh_sess=TDG6BGpZUGAhjGHxWmNpd487biAejr1%2BheM5ob0M6XBIMCNVircR8dBsEQCLEQCXKlEWCXy84y749M8xV6tScwA7L1rzVQAjlo4JayshG%2B46iia1onFzulLOXBHYUqQ06Zs29Fj5CMahF9U4P4k26FG1SjP0xdgrha72qSWTgyVOFAF76xKSPnurFSOTNuGHThk3jcAXhmoNqRa1PbuOnFjlQv%2Bgm7ahPczrwH%2Bqh9b3JbJFPyeh0zsGJclgdTxJmmgZkMESFbnC4hsSwIPNjQ%3D%3D--mEmnl%2FOGisrUtIdx--506LNIVZ1YOie6I%2F1z2ihw%3D%3D; Path=/; HttpOnly; Secure”,
  “_octo=GH1.1.1224314304.1585275560; Path=/; Domain=github.com; Expires=Sat, 27 Mar 2021 02:19:20 GMT; Secure”,
  “logged_in=no; Path=/; Domain=github.com; Expires=Sat, 27 Mar 2021 02:19:20 GMT; HttpOnly; Secure”
 ],
 “status”: [
  “404 Not Found”
 ],
 “strict-transport-security”: [
  “max-age=31536000; includeSubdomains; preload”
 ],
 “vary”: [
  “X-PJAX, Accept-Encoding, Accept, X-Requested-With, X-GitHub-OpenAPI”
 ],
 “x-content-type-options”: [
  “nosniff”
 ],
 “x-frame-options”: [
  “deny”
 ],
 “x-github-request-id”: [
  “EFED:36C1:71DB78:A7C642:5E7D62A8”
 ],
 “x-xss-protection”: [
  “1; mode=block”
 ]
}
  at createHttpError (/Applications/Blah.app/Contents/Resources/app.asar/node_modules/builder-util-runtime/out/httpExecutor.js:84:10)
  at ElectronHttpExecutor.handleResponse (/Applications/Blah.app/Contents/Resources/app.asar/node_modules/builder-util-runtime/out/httpExecutor.js:168:14)
  at ClientRequest.request.createRequest.response (/Applications/Blah.app/Contents/Resources/app.asar/node_modules/builder-util-runtime/out/httpExecutor.js:134:16)
  at ClientRequest.emit (events.js:182:13)
  at URLRequest.ClientRequest.urlRequest.on (/Applications/Blah.app/Contents/Resources/electron.asar/browser/api/net.js:207:12)
  at URLRequest.emit (events.js:182:13)
(node:4542) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4542) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by jcmlumacad** [comment]
Does anyone have the solution for this? I am also try to use this in a private Github repo but the error says 404

**Comment by eshajoshi** [comment]
Checking back in - was anyone able to figure this out for private repos? Running into the same issue. Thanks!
