### ISSUE TITLE
Specify my own location for the OSX icon file: doesn't work

### ISSUE THREAD

**Issue by develar** [electron-userland/electron-builder#197]
@jayalfredprufrock reported: I've been trying to specify my own location for the OSX icon file as detailed in the docs and it doesn't seem to be working. I know it's finding the icon because if I alter the path to something bogus it throws an error. Specifying the background image DOES work though. Oddly enough, when I place the icon.icns file and background.png file in the "build" directory and rely on the defaults, the icon loads properly but not the background. I've had to use a combination of both methods to get everything to work.

**Comment by michaelbazos** [comment]
I encountered the same problem and thought also, at first, that there was an issue with the customization of the background and the icon. 

But after investigation it appears that the issue is not related to electron-builder. 

It occurs **if you don't unmount a DMG with the same name** that was mounted before the customization.

Steps to reproduce:

 - Build a dmg with a background located at `build/background.png`
 - Open the dmg, then close the dialog
 - Build a new dmg with a customized background located at, say, `build/osx/background.png`
 - Open the dmg and notice how the background is the first one. Unless you unmount the first dmg.

**Comment by develar** [comment]
Obsolete, please try 3.6.0.

@michaelbazos Please see https://github.com/LinusU/node-appdmg/issues/84#issuecomment-197426861
