### ISSUE TITLE
Migrate to Zulip

### ISSUE THREAD

**Issue by develar** [electron-userland/electron-builder#1974]
[Zulip](https://zulipchat.com) is free for open source projects and offers service (i.e. not self-hosted).

Why:

1. No 10K limit.
2. officially supported public archive in the future (@meakaakka, right?).

Cons:

1. Slack is more popular and chance, that Slack app is already installed, much higher. It is the main reason why this issue is created. For example, in my company Slack is used.
2. Slack has more slick and sexy UI.

Yes, 10K message Slack limit is not a major issue because Slackarchive is configured — http://electron-builder.slackarchive.io/ (the only issue — Slackarchive doesn't support threads).

What do you think? Is Slack app already installed for another org? Is it problem for you to install Zulip app?

**Comment by pronebird** [comment]
Zulip looks like that clone of Slack that Facebook switched to because of 10k limit.

**Comment by surajreddy** [comment]
It's easier for me to stay connected on Slack because I already have it open for other organizations. I probably won't keep Zulip open unless I have an important organization switch to it.

However, I'm not active on the slack, so I will likely just use Zulip when I need to communicate about an electron-builder specific issue.

Summary: Highly Prefer Slack, but okay with Zulip

**Comment by timabbott** [comment]
Check out https://zulipchat.com/for/open-source/ for notes on a number of advantages Zulip has over Slack for fellow open source projects.

**Comment by develar** [comment]
Actually, currently no alternatives to Slack. All existing "alternatives" are not because service is not provided. And self-hosted is not an option. It is not clear from https://zulipchat.com/for/open-source/ and https://zulipchat.com/beta/ (and other zulip pages) that now, Zulip offers not only self-hosted, but service too.

So, maybe in the future, situation will be change, but for now, Slack is de-facto standard. Plus, Slack is really awesome. 

Thanks to all for answering, issue will be closed, but you can still discuss. For now just clear that migration not possible and suitable for most users.

**Comment by rishig** [comment]
In case anyone comes by this in the future: Zulip does provide a hosting service at zulipchat.com, and has done so for about a year. It is the first bold heading at https://zulipchat.com/for/open-source/. 

This is good feedback that that should perhaps be more visible :).

**Comment by develar** [comment]
@rishig Indeed. Forget about it probably because no link — no information.

In the mentioned paragraph:
* no link to register opensource project
* zulipchat.com is not a link and "commercial offerings" is not a link.
* on zulipchat.com I don't see "Pricing" page. 
* Not clear what "Sign up for the beta" means. Is it access to some new Zulip version? Or what? On the slack.com there is "Create team" and it is clear.

**Comment by rishig** [comment]
All good points, thanks for the feedback! You're right that the current website doesn't particularly advertise the hosting service. A pricing page should be up in another week or two, which will hopefully make things clearer. 

I don't want to take over this issue discussion (and so will bow out soon), but the fact that this discussion is happening in github issues rather than in slack is symptomatic of a number of failings of slack, in my mind:
* It's hard to have a coherent record of a conversation and decision. Both for pointing people at later, and for linking folks like timabbott above into the discussion while it is happening.
* It's hard for discussions to last very long. This discussion has already lasted 15 hours; in a busy slack channel, the conversation would have been interrupted by something else by now.
* Slack is not very fun to check if you only check once every several hundred messages. At work, this is not a problem, since everyone checks every day. But in a large open source project it can drive all but a core set of contributors away from reading or contributing to the chat.

I would be interested to hear more about what you're looking for in chat (either here or off-issue), if chat is something on your mind.

**Comment by develar** [comment]
electron-builder will be migrated from Slack to Zullip. I hope that Zullip will approve free hosting for our community. If not, I will check mattermost/zullip as a self-hosted solution.

Reason — Slack 10 000 messages applied to private messages also. And it leads to situation "who are you?".

Migration will be done as soon as free offer will be confirmed by Zullip sales.

**Comment by develar** [comment]
Migrated.

**Comment by develar** [comment]
GitHub is the main place where issues are discussed.

Chat platform is required mostly for private communications (companies, "VIP" users who donated, ping if no response). And... nowadays, it is quite convenient to use it as a forum. Zulip, as Slack, also supports threads (and even in a more advanced manner), so, it is not like ungrouped bunch of messages.

**Comment by quanglam2807** [comment]
@develar I'm not sure if this happens because of the migration but my account is banned from the zulip instance. I don't think I did anything wrong to be banned for real. Any idea?

<img width="508" alt="Screen Shot 2019-07-22 at 4 09 42 PM" src="https://user-images.githubusercontent.com/1548835/61616513-32945100-ac9b-11e9-8672-41c6f5b80eda.png">

**Comment by develar** [comment]
@quanglam2807 Strange. Reactivated.
