### ISSUE TITLE
How to add custom file to the app folder after build before package.

### ISSUE THREAD

**Issue by chairuosen** [electron-userland/electron-builder#1985]
* **Version**:  electron-builder 19.19.1

I'm using electron-builder to package my app into deb file.
Now I need to add some native lib to app installation root folder manually (such as xxxx.so) on linux platform.
because app got error `GLIBCXX_3.4.21 not found` in some pc with ubuntu14.04 sometimes. 
and putting higher version `libstdc++.so` to app's root folder can solve the problem.

I checked the docs and didn't find the solution.
So if anyone can give me some advice? Thank you.

**Comment by develar** [comment]
Please use `extraResources` or `extraFiles`  https://github.com/electron-userland/electron-builder/wiki/Options

Please note — you can use https://github.com/electron-userland/electron-builder/wiki/Options#file-macros in the patterns.

**Comment by bonavida** [comment]
@chairuosen Where can I get that `libstdc++.so` file? I need it to include it as extra resource and can't find it.

**Comment by chairuosen** [comment]
@bonavida 
[libstdc++.so.zip](https://github.com/electron-userland/electron-builder/files/1423936/libstdc.so.zip)

**Comment by probonopd** [comment]
__BEWARE:__ As a general rule of thumb, build software on a system with a libstdc++.so.6 no newer than the one that comes with the oldest distribution that you still want to support, i.e., the oldest still-supported LTS version__ (at the time of this writing, Ubuntu 14.04).

Some projects require newer C++ standards to build them. To keep the glibc dependency low you can build a newer GCC version on an older distro and use it to compile the project. If you do this, however, then your compiled application will require a newer version of the `libstdc++.so.6` library than available on that distro. 

__Bundling `libstdc++.so.6` however will in most cases break compatibility with distros that have a newer library version installed into their system than the bundled one. So blindly bundling the library is not reliable.__ While this is primarily an issue with `libstdc++.so.6` in some rare cases this might also occur with `libgcc_s.so.1`. That's because both libraries are part of GCC. You would have to know the library version of the host system and decide whether to use a bundled library or not before the application is started. This is exactly what the patched AppRun binary from https://github.com/darealshinji/AppImageKit-checkrt/ does. It will search for `usr/optional/libstdc++/libstdc++.so.6` and `usr/optional/libgcc_s/libgcc_s.so.1` inside the AppImage or AppDir. If found it will compare their internal versions with the ones found on the system and prepend their paths to `LD_LIBRARY_PATH` if necessary.

https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#libstdcso6

**Comment by abhijithcs** [comment]
Could anyone suggest a solution for this:

I have to include a whole directory which contains JSON files which contains data relevant to the App. App uses the data from this directory. While building this directory (which is in the root project directory) is not being included.

**Comment by abhijithcs** [comment]
@andreglegg I wanted the JSON to be editable. For example, concat new data to the JSON or remove a few from the JSON dynamically.

**Comment by ecrofpu** [comment]
![image](https://user-images.githubusercontent.com/72737199/100995476-d4a99600-357d-11eb-8d35-a372d228bb12.png)

I am also facing a similar issue. I have a .bat file that I have to execute when some setting in the Electron app is turned on. I am targeting Windows 10. But every time a build is created, it gives me error regarding the bat file not found.

You can see a part of the package.json in the above image. I have used the **extraFiles** attribute to inform the builder to include the **vendor** folder. This **vendor** folder is stored in the root directory i.e., same as package.json directory.

I have also tried setting **asar** false, but this also did not work.

Any suggestion or advice is appreciated.
