### ISSUE TITLE
Error: schema with key or id "http://json-schema.org/draft-04/schema" already exists

### ISSUE THREAD

**Issue by daveywc** [electron-userland/electron-builder#2012]
19.26.3

2.8.7

Windows

I upgraded to the latest versions of electron-builder and electron-updater in an attempt to fix the following error that started appearing when my application was attempting to check for updates:  "Cannot find module 'fs-extra'"

After updating I can no longer build my installer.  I now encounter the following error:

Error: schema with key or id "http://json-schema.org/draft-04/schema" already exists
    at checkUnique (C:\Data\Development\Projects\docsontapv2\node_modules\ajv\lib\ajv.js:410:13)
    at addSchema (C:\Data\Development\Projects\docsontapv2\node_modules\ajv\lib\ajv.js:132:5)
    at Ajv.addMetaSchema (C:\Data\Development\Projects\docsontapv2\node_modules\ajv\lib\ajv.js:145:5)
    at C:\Data\Development\Projects\docsontapv2\node_modules\read-config-file\src\main.ts:122:7
    at Generator.next (<anonymous>)

Can you provide any advice as to how to fix these errors?

Thanks,

David

**Comment by develar** [comment]
Please try to remove node_modules and install using `yarn` (not npm).

**Comment by daveywc** [comment]
Thanks @develar - removing node_modules and reinstalling (using npm) fixed both problems.

**Comment by develar** [comment]
Do not use broken and unreliable npm.

**Comment by dawnmist** [comment]
Removing node_modules and reinstalling with npm fixed it for me too.

I am unable to use yarn at the moment for a react typescript project due to https://github.com/yarnpkg/yarn/issues/4226 - the conflicting type definition versions (15.6.x, 16.0.x) that both get installed by yarn for @types/react (based on various other modules that use react - react-redux, react-dnd, react-bootstrap, etc) mean that compilation of the project breaks *entirely*.
