### ISSUE TITLE
Split windows x32 and x64 builds

### ISSUE THREAD

**Issue by nijikokun** [electron-userland/electron-builder#2048]
I'd rather not have users download a 60+ MB file for their architecture when you could just have a 30MB file per arch.  Here are the commands I am using (that works for split):

```
    "win64": "electron-builder --publish=never --win --x64",
    "win32": "electron-builder --publish=never --win --ia32",
```

However this causes the `latest.yml` to only show a single build, whatever was the last command ran. This is problematic because the `latest.yml` does not properly reflect for all possible arch / os.

Also using `${arch}` doesn't work for windows in the `artifactName` & using `--win32` does not work (is described in `electron-builder --help` as an option).

**Comment by develar** [comment]
Consider to use `nsis-web` target in this case. This target will even more reliable and better in the next release (several days).

**Comment by develar** [comment]
Not yet published docs: 


## Web Installer

To build web installer, set [target](/configuration/win.md#WindowsConfiguration-target) to `nsis-web`. Web Installer automatically detects OS architecture and downloads corresponding package file. So, user don't need to guess what installer to download and in the same time you don't bundle package files for all architectures in the one installer (as in case of default `nsis` target). It doesn't matter for common Electron application (due to superb LZMA compression, size difference is acceptable), but if your application is huge, Web Installer is a solution.

If for some reasons web installer cannot download (antivirus, offline):
* Download package file into the same directory where installer located. It will be detected automatically and used instead of downloading from the Internet. Please note — only original package file is allowed (checksum is checked).
* Specify any local package file using `--package-file=path_to_file`.

**Comment by nijikokun** [comment]
Wondering about auto-updates for the nsis-web, still supported?

**Comment by nijikokun** [comment]
Looks like it could become an issue with the electron-releases-server which I am using since I have not yet found a better alternative -- or built one.

Reason being, it supports upload for the architecture (64, 32) which means I can't upload the nsis-web & the architectures, I know that this isn't your problem and is more of a _my problem_ just wish there was some group thought around releases and management.

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder/releases/tag/v19.28.4

Web Installer even support delta updates.

>  electron-releases-server

I will check it after my vacation.

**Comment by bompi88** [comment]
@develar is it possible to split the build manually? creating a lastest-ia32.yml and referencing this in `electron-updater`?

**Comment by develar** [comment]
We want to avoid it. So, we suggest web installer. All users, that asked it, decided to use web installer. Please explain why do you want to distribute ia32, why current multi Arch installer not suitable, why web installer not suitable.

**Comment by bompi88** [comment]
@develar I bundle for instance mongodb and some other binaries together with the app, and I want the correct binary for each arch. But if there's another way of handling this use case I rather go down that path.

**Comment by develar** [comment]
@bompi88 please try nsis-web Any your issue with this target will be handled. We can even add ability to bundle x64 package as part of installer to avoid downloading, and download only ia32. But I think existing nsis-web will be suitable for you.

**Comment by fttx** [comment]
Hi, i've a similar problem: i'm currently using nsis with the [installer.nsh ](https://github.com/fttx/barcode-to-pc-server/blob/61bd2bec0c960dbba7cb57b16ea3e234a99ea068/electron-resources/installer.nsh) file to chain a different msi installer based on the "arch" value, will it work with nsisWeb as well?

Besides that, i'm still not convinced to switch to nsisWeb because i like the idea of having a single file that bundles everything and doesn't require either an internet connection and any other uncompression programs

**Comment by dangeredwolf** [comment]
The issue I have is that Auto Updating is annoying with nsisWeb because it only downloads the 1 MB installer and not the release itself
