### ISSUE TITLE
Filename issue when publishing to S3

### ISSUE THREAD

**Issue by pgostovic** [electron-userland/electron-builder#2224]
* **Version**: 
19.40.0

* **Target**: 
Mac, Windows

Hi.

I'm trying to publish my app/updates (Mac and Win) to S3 with the following config:

    "publish": {
      "provider": "s3",
      "bucket": "my-bucket",
      "acl": "public-read"
    },

It seems to work fine and I end up with the following files in my bucket:

- myApp Setup 0.0.7.exe
- myApp.dmg
- myApp.zip
- latest-mac.json
- latest-mac.yml
- latest.yml

Notice that the `myApp.zip` file has no version or platform in the name. This is problematic because the latest-mac.json looks like this:

    {
        "version": "0.0.7",
        "releaseDate": "2017-10-24T18:38:49.589Z",
        "url": "https://my-bucket.s3.amazonaws.com/myApp-0.0.7-mac.zip"
    }

So, the url is pointing to a nonexistent file.

FYI, this does not happen when I publish to GitHub. In that case myApp-0.0.7-mac.zip does get published.

Thanks

Patrick

**Comment by paramadeep** [comment]
i too had this issue. Only mac builds get published. My linux builds are not getting uploaded. It seems there is a issue with "createDifferentialPackage". in file "https://github.com/electron-userland/electron-builder/blob/master/packages/app-package-builder/src/blockMap.ts" . Line number 70. await write(fd, blockMapFileData). The method implementation treats 6 parameter as callback function while, since we pass only 3 params (including callback as third parameter) it takes null as the callback and the execution stops here.

**Comment by develar** [comment]
@paramadeep Works for me. Please specify nodes version.

**Comment by pgostovic** [comment]
FWIW, what @paramadeep is seeing is obviously **not** the same issue I was having.

**Comment by develar** [comment]
@pgostovic Please set env `DEBUG=electron-builder` and attach log of the terminal output. I cannot reproduce and it seems it is your configuration issue.
