### ISSUE TITLE
Ability to configure S3 base url 

### ISSUE THREAD

**Issue by nkt** [electron-userland/electron-builder#2233]
In case you want to upload artifacts to S3-compatible (not S3) service (minio for example), you have to configure base url, but it is impossible for now.

**Comment by graywolf336** [comment]
My vote is for this issue, would love to have this as we are looking into using Minio.

**Comment by develar** [comment]
Could you please provide information why S3 or DO Spaces is not suitable for you?

**Comment by develar** [comment]
Fixed in 19.45.0

**Don't forget to add `Read-only` policy for Minio bucket** otherwise public URLs will not work (critical for auto-updater).

<img width="1180" alt="screen shot 2017-11-04 at 10 15 12" src="https://user-images.githubusercontent.com/350686/32404065-1add5c9e-c149-11e7-8f2d-e3faea68a5c5.png">

**Comment by graywolf336** [comment]
@develar The reason S3 or DO Spaces is not suitable is because we are trying to keep our costs down, yes the cost of each of them is extremely low but when you don't have a budget (like on a side project) then just throwing up a docker image on an existing system is simple enough.

Thanks for adding this though, I appreciate it!

**Comment by develar** [comment]
... and in this case you don't need to reinvent the wheel implementing own uploading service and HTTP public API. Thanks for explanation. I will add note about Minio to docs.

**Comment by JPorter44** [comment]
@develar I am just trying to set up the localhost server to test auto updating with Electron and was curious where you navigate to in order to change the read only policy. I am new to Minio and don't really know much about it.

**Comment by rajivshah3** [comment]
@JPorter44 if you hover over the bucket name in the left sidebar, three dots will appear. You can click those and then click "Edit policy"
