### ISSUE TITLE
Moving to the electron-userland

### ISSUE THREAD

**Issue by havenchyk** [electron-userland/electron-builder#225]
Hi @stefanjudis.

It looks like electron-builder became a "must have" package for electron applications. 
What do you think about moving this package to the community repository: [electron-userland](https://github.com/electron-userland)?

**Comment by stefanjudis** [comment]
Actually I was thinking about that yesterday too. :) sure thing! :+1:
Am 09.03.2016 9:02 vorm. schrieb "Uladzimir Havenchyk" <
notifications@github.com>:

**Comment by stefanjudis** [comment]
How is the process for that? .cc @maxogden

**Comment by malept** [comment]
I'm :+1: for that idea.

**Comment by havenchyk** [comment]
@malept nice, could you please share some details, how to make this transfer?

**Comment by malept** [comment]
I need to make an admin of this repository an admin of electron-userland, and then they can transfer the repository to the org.

**Comment by havenchyk** [comment]
@stefanjudis @develar ping

**Comment by null9beta** [comment]
@malept you can make either @stefanjudis or me an admin of electron-userland and either one of us can start the transfer

there is just one pre-condition i have before starting the transfer
1. the electron-builder shall stay under MIT Licence and the Copyright notice shall still contain
`Copyright (c) 2015 Loopline Systems , <add_yourselfs_here>`

If you wonder who´s that guy from the offside here, i am the loopline-systems organization owner, nice to meet you, and great work around the electron community btw from all of you. Just keep in mind that the project started as an internal project here at our company and we open sourced then.

**Comment by malept** [comment]
There's no requirement for the license (or copyright holders) to change. It would be nice if electron-builder agreed to become an [open open source project](http://openopensource.org/), but that's not a requirement either.

**Comment by malept** [comment]
I have invited @stefanjudis to the org.

**Comment by maxogden** [comment]
Actually I'd say it is a requirement for all projects under electron-userland to be http://openopensource.org/ projects. Also it should only get transferred to electron-userland if the existing author(s) feel like they are not currently able to maintain the project effectively. If they have no issues with maintaining it now or in the forseeable future then I don't see any benefit to moving ownership to the electron-userland org, as none of the people on there have that many direct contributions to the code.

I don't think moving a repository from a personal account to an organization is necessarily a good thing, the reason I did it with my electron modules was because I wanted to make sure they continue to be maintained whether or not I am able to be involved.

**Comment by malept** [comment]
@maxogden sounds good. We should formalize that somewhere. (electron-userland.github.io or a electron-userland/meta repository, to give some examples.)

**Comment by maxogden** [comment]
@malept Good idea. The reason I think open open source should be a requirement is that is the way I can think of to prevent the electron-userland from becoming a dumping ground for modules that will end up unmaintained.

**Comment by malept** [comment]
> The reason I think open open source should be a requirement is that is the way I can think of to prevent the electron-userland from becoming a dumping ground for modules that will end up unmaintained.

:+1: :heavy_multiplication_x: :100:

**Comment by malept** [comment]
Given what Max wrote here and in https://github.com/electron-userland/about#readme, do you guys still want to move the repository?

**Comment by develar** [comment]
> It would be nice if electron-builder agreed to become an open open source project, but that's not a requirement either.

I don't see problem here. http://openopensource.org/ is not a license, but development model. Right?

@null9beta In the version 3.0 there will be no old code from the electron-build <2.7 :) But of course I think no one want to remove "Loopline Systems" copyright or something like that. 

And our current model exactly the same — e. g. when @stefanjudis decided that [electron-complete-builder API](https://github.com/loopline-systems/electron-builder/issues/138) is in better shape and has more benefit currently — I was added as a collaborator (because [no one want yet another tool](https://github.com/electron-userland/electron-packager/issues/33#issuecomment-182324033)).

Should we move or not? Well... If we want to get rid of `loopline-systems` in the URL and not to be associated with this company. But I think it is not a problem for anyone.

 In case of @maxogden — project was belonged to personal account, but in our case project is already part of organisation. We don't related to Loopline Systems anymore, but should be a reason to move to a neutral organisation. But I don't see any reason.  Current situation doesn't bother me. I am not going to contribute forever — only as I need.

**Comment by develar** [comment]
> Want to use http://openopensource.org/ governance

@stefanjudis is a great admin, his governance like http://openopensource.org (all rules are the same).

> Would benefit from having neutral ownership (e.g. anyone can become a maintainer)

@stefanjudis has a acceptable reaction to requests (that requires admin rights — e.g. add new CI server) and adds collaborators if need.
To summarise:

> Provide a generally useful function to the electron community

Well, I hope we do :)

> Would otherwise not be maintained effectively

Although @stefanjudis doesn't have a time to write code, but he always has a time to respond to collaborators requests :)

**Comment by stefanjudis** [comment]
Sorry for lack of response.

> The reason I think open open source should be a requirement is that is the way I can think of to prevent the electron-userland from becoming a dumping ground for modules that will end up unmaintained.

This is exactly what we're doing so far. :) As I have no real time currently and @develar is doing a fantastic job over with more people contributing and giving feedback. :)

> the reason I did it with my electron modules was because I wanted to make sure they continue to be maintained whether or not I am able to be involved.

That's exactly my feeling with the module right now - opening up is the only real solution. :+1: 

> For modules that have grown beyond the scope their original creators intended this organization provides a governance structure and neutral ownership model to help modules get new contributors and maintainers.

I have to say that I too think that a neutral ownership can help getting new contributors. 

Also there is the thing of bundling high quality modules in the same org - which feels nice. Even better in combination with open open source. :)

So in general I've got a positiv feeling of moving it and with keeping the copyright ( .cc @null9beta ) I'd go for it - if still everybody agrees or at least has no strong feelings against it. :)

**Comment by stefanjudis** [comment]
@malept 

Last question - npm handles this move easily by updating the `package.json`?

**Comment by malept** [comment]
@stefanjudis probably? I am not an expert on NPM publishing by any stretch of the imagination. :grin:

**Comment by develar** [comment]
@stefanjudis I don't see any problem. We don't change package name, npm allows to add/remove owner.

**Comment by stefanjudis** [comment]
Okay folks. I just pressed the button. :)

**Comment by develar** [comment]
@stefanjudis Do you have plans to update links in the readme? Or I can do it (I has some not yet ready changes).

**Comment by stefanjudis** [comment]
:+1:

**Comment by develar** [comment]
@stefanjudis Could you please add project to AppVeyor again (I cannot since I don't belong to org)? I don't see AppVeyor check in the #262 for example.

**Comment by stefanjudis** [comment]
![bildschirmfoto 2016-03-23 um 11 39 54](https://cloud.githubusercontent.com/assets/962099/13982740/007c01e0-f0ec-11e5-905c-73ac706b8d34.png)

Updated the settings... 
Don't the the `userland` project at appveyor so I'm not sure if this will work. 

Please let me know, when there are more troubles. :)
