### ISSUE TITLE
nsis-web: Connection not permitted or dropped out Inetc Plug-in

### ISSUE THREAD

**Issue by marceloavf** [electron-userland/electron-builder#2424]
* **Electron-builder Version**:  19.49.0
* **Electron-updater Version**:  2.16.3
* **Target**: Windows

When try to install via nsis-web .exe it says:

![screenshot_2](https://user-images.githubusercontent.com/5435657/34454652-d9a422b4-ed56-11e7-91d1-4e676f3b5f94.png)

![screenshot_1](https://user-images.githubusercontent.com/5435657/34454661-01d8f7f0-ed57-11e7-9ce3-d1ecd73b6a6a.png)

It work when I access the link in the browser and download nicely the nsis.7z but don't work via .exe
Tried to disable the firewall and anti-virus

The file is signed too

![screenshot_3](https://user-images.githubusercontent.com/5435657/34454667-1d4b9db2-ed57-11e7-9481-17b4f912c7a1.png)

[info.zip](https://github.com/electron-userland/electron-builder/files/1594458/info.zip)

**Comment by develar** [comment]
Interesting... it works for me. Is it working now?

**Comment by marceloavf** [comment]
Still happens @develar, we tried to disable firewall and anti-virus, but still get the same error.

**Comment by kushale** [comment]
Get the same error with nsis-web. Version of electron-builder is 19.56.2

**Comment by mastergberry** [comment]
Bringing up that this is still an issue (and one I believe I reported a while ago?)

https://prnt.sc/jrbrwu

This user reported that he has a download speed of 50kbps and a pretty bad connection...so I guess the plugin needs some upgrades to handle bad connections a bit better?

**Comment by mastergberry** [comment]
Still having users report this as a problem. Maybe there is a fix in a newer version @develar ?

**Comment by AlaShiban** [comment]
Running into the exact same problem. The installer says it's trying to reach localhost:8080/latest.7z, which I can if I place it in the browser - but not through the installer.
Thanks @develar - your work is appreciated!

**Comment by AlaShiban** [comment]
I ran into this issue and it turned out to be a http/https issue. Here's how I resolved it (for future finders):
In my package.json:
![image](https://user-images.githubusercontent.com/1911202/50118870-e913ed00-0205-11e9-82e6-ee9b02ed6cdc.png)
Notice the **http** part - for https I expect valid certificates to play a role in success/failure. 

The web server had these files:
![image](https://user-images.githubusercontent.com/1911202/50118934-1d87a900-0206-11e9-8c32-78c6a2fe02f3.png)
latest.7z is a copy of my latest build produced from npm run dist

Hope this helps!
Thanks @develar !

**Comment by fttx** [comment]
Any update on this?

**Comment by liaohui2030** [comment]
how can i solve this issue? thanks

**Comment by lifesboy** [comment]
Same error. My case is because of wrong time. Update windows time fix it!

**Comment by mastergberry** [comment]
I identified one possible cause my users were having...they didn't have TLS 1.2 enabled and we force 1.2 for our HTTPS connections.

Just noting it here in case it helps someone else.

**Comment by ArmelChesnais** [comment]
We've also opted to go with nsis instead of nsis-web. However, for differential updates, this does imply that the amount to download is doubled, whereas this wasn't an issue for nsis-web.

We're currently programmatically separating 32 and 64bit packaging right now to generate two separate installers of nsis as a result, as by default they're combined for a single 32/64 installer otherwise. 

A solution to this nsis-web issue would be preferable.
