### ISSUE TITLE
Error: Unable auto update on windows 10

### ISSUE THREAD

**Issue by focalhot** [electron-userland/electron-builder#2524]
* **Version**: "electron-updater": "^2.19.1",

* **Target**: Windows 10

```
A Javascript error occurred in the main process

Uncaught Exception:
Error: spawn C:\Users\ADMINI~1\AppData\Local\Temp\up-3sYQfM\MyApp Setup 1.0.3.exe ENOENT
  at exports._errnoException (util.js:1050:11)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
  Blah blah blah...
```

**Comment by purplekrayons** [comment]
ENOENT indicates that a file cannot be found.

Please post the contents of your package.json file. I feel like the issue is with your naming convention --
 probably using an invalid character. I've seen a similar issue in the past where someone tried to use Chinese characters in their app name.

My recommendations:

(1) use english characters
(2) dont use special characters
(3) dont use spaces

**Comment by focalhot** [comment]
@paulcbetts 
Thanks.
I found my app can auto update on most computers(windows 10), except that one.
