### ISSUE TITLE
[NSIS] Long time between 100% download progress and update-downloaded event

### ISSUE THREAD

**Issue by remicoges** [electron-userland/electron-builder#2535]
* **Version**:  19.55.2 

* **Electron Updater Version**:  2.20.1

* **Target**: NSIS

Hello,

I notified a time of about a minute between the 100% update download progress and the emitting of the `update-downloaded` event. On mac, the time is less than 2 seconds. Is there any way to reduce that time on NSIS ? What step is processed during this time ? Is there anyway to have a progress of this step ? 

Thanks

**Comment by develar** [comment]
> What step is processed during this time 

Nothing. Maybe antivirus checking file. Is it reproduced on another machine?

**Comment by Dorkside** [comment]
Ok, I've got the same problem and it seems to be related to nsis-web. Are you deploying to nsis, or nsis-web updater ?
After several tests, I think the problem is that electron-updater is emitting the update-downloaded event for the setup.exe, which in the case of nsis-web is very small, and then waits silently for the package.7z to download without emitting additional updates until completed.
On the other hand, normal nsis target emits the right updates, so I can track the download much easier.
Would be great to fix this bug in nsis-web, but otherwise I'll just wait til differential packaging comes to nsis target(I read that shouldn't be too long).
