### ISSUE TITLE
nsis-web installer always grab latest?

### ISSUE THREAD

**Issue by TanninOne** [electron-userland/electron-builder#2611]
This is a question or feature request:

As far as I understand it, if I build an installer with nsis-web, that installer will always grab a specific version, so with every update of my application I also have to update the installer.

So I was wondering: Would it be possible to  create a web installer that instead always installs the newest version available on github, so I only have to update the data package but not the installer?

**Comment by TanninOne** [comment]
ping

**Comment by develar** [comment]
No. This change will dramatically increase complexity of updater and a lot of manual testing will be required.

Why? Simply because our updater is designed to be a black box. To avoid vendor lock, for example. Don't like electron-updater? Feel free to switch to another solution — it will be possible without any dirty hacks.
Do you want to switch to INNO setup? No problem. Whatever PE executable can be provided, it will be executed and you can do whatever you want.

Keep in mind, that no one except you is aware what are you doing. Maybe you changed desktop shortcut name, or whatever beyond app data. Yes, electron-builder can detect it somehow, but again, increased complexity and maintenance cost doesn't worth it.
