### ISSUE TITLE
Error Updating From Private GitHub Repo

### ISSUE THREAD

**Issue by jaret32** [electron-userland/electron-builder#2641]
electron-builder **Version**: 20.0.7

electron-updater **Version**:2.20.1

* **Target**: 
Mac

From  what I can tell, I'm getting a 404 error in the auto updater when trying to find the release in my Private Github Repository.  I've created an access token and set the GH_TOKEN environment variable on my laptop, but for some reason, the auto updater is using the wrong URL.  I've included the full error below.

Error in auto-updater. HttpError: 404 Not Found
"method: undefined url: https://github.com/jaret32/JustBotIt/releases.atom\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"
Headers: {
  "cache-control": [
    "no-cache"
  ],
  "content-encoding": [
    "gzip"
  ],
  "content-security-policy": [
    "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src data:; script-src 'self'; style-src 'unsafe-inline'"
  ],
  "content-type": [
    "text/plain; charset=utf-8"
  ],
  "date": [
    "Mon, 26 Feb 2018 06:53:49 GMT"
  ],
  "expect-ct": [
    "max-age=2592000, report-uri=\"https://api.github.com/_private/browser/errors\""
  ],
  "server": [
    "GitHub.com"
  ],
  "status": [
    "404 Not Found"
  ],
  "strict-transport-security": [
    "max-age=31536000; includeSubdomains; preload"
  ],
  "transfer-encoding": [
    "chunked"
  ],
  "vary": [
    "X-PJAX"

**Comment by develar-vacation** [comment]
Related  #2559

**Comment by DigitalData** [comment]
I am getting the same error, but from a public repository.

electron-builder **Version:** ^20.24.4
electron-updater **Version:** ^3.0.3

**OS:** Windows 10 64x

I create a window that shows when the app is checking for an update/updating. The actual updater code is not in the rendered window, but in the `main.js`. 
The release is out, `latest.yml` is uploaded (I published using electron-builder, like the guide says to), but I think I get blocked before I can even access it.

#### However I get the following error:

`{description: "method: undefined url: https://github.com/CodeDigi…asons actual status maybe not reported, but 404.↵", name: "HttpError", statusCode: 404}
description
:
"method: undefined url: https://github.com/CodeDigital/botmyguy/releases/download/v0.0.3-pre-alpha/latest.yml↵↵Please double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.↵"
name
:
"HttpError"
statusCode
:
404`

I will probably create a separate issue as my github repository is public...

**Comment by samuelmaddock** [comment]
@jaret32 I received this error when I didn't set the `token` property passed into `setFeedURL`.

```js
autoUpdater.setFeedURL({
    provider: 'github',
    repo: 'repo',
    owner: 'owner',
    private: true,
    token: '<personal-access-token>'
})
```

**Comment by Nisthar** [comment]
@samuelmaddock does the users get the access-token if its included in the code?

**Comment by alipakbaz** [comment]
> @samuelmaddock does the users get the access-token if its included in the code?

### Set the Token in your environment:

**On Windows:**
Search for "Environment Variables" in the Start menu and open "Edit the system environment variables."
Click on "Environment Variables."
Under "System variables," click "New" and add a new variable with the name GH_TOKEN and the value as the token you just copied.

```
import { autoUpdater } from "electron-updater";

autoUpdater.setFeedURL({
  provider: "github",
  repo: "REPO-NAME",
  owner: "USERNAME",
  private: true,
  token: process.env.GH_TOKEN
});
```

**Comment by codeofandrin** [comment]
Can I somehow use a `.env` file? When I built it `process.env.GH_TOKEN` is `undefined` but not in dev. I use `dotenv`. Any suggestions?
