### ISSUE TITLE
Certificate publisherName changed, cannot update from previous versions

### ISSUE THREAD

**Issue by matheussige** [electron-userland/electron-builder#2790]
* electron-builder version 20.4.1

* Windows

Hello, I'm using NSIS installer for Windows, auto-update was working fine. However, our certificate (.pfx, issued by Comodo) expired, and we provided a new one now.

However, the publisher name on the certificate changed (because the company name changed), and the app in our customers' machines cannot update because the name doesn't match.

Is there any way I can update the existing versions on my customers' machines? I tried specifying the "publisherName" option on the new version, but I guess it only makes a difference on the installed one.

Here's my publish config (previous version):

```
"win": {
      "target": "nsis",
      "icon": "./icon.ico",
      "certificateFile": "./certificado-windows.pfx",
      "certificatePassword": "******",
    }
```

and on the newest version:

```
"win": {
      "target": "nsis",
      "icon": "./icon.ico",
      "certificateFile": "./certificado-windows.pfx",
      "certificatePassword": "******",
      "publisherName": [
        "OLD_COMPANY_NAME",
        "NEW_COMPANY_NAME"
      ],
    }
```

**Comment by mobitar** [comment]
Same issue here. I previously had a standard signing cert, and upgraded to EV. For the previous version of the app, I never specified `publisherName`, so it defaulted to "StartCom Class 1 Client CA" for whatever reason. However, the new version uses my company name, and since that doesn't match, autoupdate is rejected.

Looks like the only solution is to set `verifyUpdateCodeSignature` to false in config, at least for the first update with the new cert.

**Comment by matheussige** [comment]
@mobitar My app communicates with an external API, so I ended up using that API to tell the user that he needed to manually update the app.

Hope you can work it out

**Comment by mobitar** [comment]
Yeah, luckily had a similar architecture in place as a failsafe in case electron-builder autoupdate didn't work.
