### ISSUE TITLE
What is the purpose of blockmap file?

### ISSUE THREAD

**Issue by gmantri** [electron-userland/electron-builder#2851]
* **Version**: 20.10.0

* **Target**: NSIS

I recently switched to NSIS based installer for my electron application. It works great! When I build the installer, one of the artifacts created is a `blockmap` file (`MyApplicationName.exe.blockmap`). I am curious to know the purpose served by this file. I would appreciate if someone can explain this. I searched for `nsis blockmap` but couldn't find anything that would explain this.

**Comment by gknapp** [comment]
A quick web search:

>The package block map file is an XML document that contains a list of the app’s files along with indexes and cryptographic hashes for each block of data that is stored in the package.  

Taken from [App Package Blockmap for Universal Windows Platform (UWP) Apps](https://docs.microsoft.com/en-us/uwp/schemas/blockmapschema/app-package-block-map)

If you use automatic updates, I believe the blockmap file is used for partial / differential updates to your application, to shrink the update payload size.

**Comment by gmantri** [comment]
Thanks @gknapp. I don't think it's an XML document. In my case it is a binary file.

**Comment by develar** [comment]
This file is used for delta updates (#2217).

> In my case it is a binary file.

it is gzipped json.

**Comment by iffy** [comment]
@develar Are blockmap updates currently being used for macOS and Windows?  Do I have to do anything special to enable it?

**Comment by matthiasg** [comment]
How are these blockmaps integrated with signing though. Since signing creates a new .exe. Will the blockmap become invalid ?

**Comment by brianddk** [comment]
@delvar, the JSON contans an array of `base64` encoded strings and an array of `int`s.  I assume the `int`s are the size of the block being referenced and that the `base64` is some type of block hash.  But the base64 is 24 base64 chars long which would decode to 18 bytes.  An `md5` hash is 16 bytes, and a `sha1` hash is 20 bytes.

So if it is a hash, what hash algorithm does it use?

**Comment by Francrodi** [comment]
> 
> 
> How are these blockmaps integrated with signing though. Since signing creates a new .exe. Will the blockmap become invalid ?

I have the same problem. Is there a way to generate a new blockmap file?

**Comment by heliam1** [comment]
@Francrodi @matthiasg
I've tried signing .exe.blockmap using Windows signtool i.e.
`C:/\"Program Files (x86)\"/\"Windows Kits\"/10/\"App Certification Kit\"/signtool sign /fd SHA256 /a /f scripts/${aPfxFile} /p ${password} release/\"${aDotExeDotBlockMapFile}\"`
But it comes up with error, that this kind of file .exe.blockmap cannot be signed.
In contrast this tool is perfectly able to sign the .exe file.

So it looks like there's no need to sign the .exe.blockmap file.

Which makes sense since from the block map file size, we can tell it is definitely not being used as the data which is updating the app. Rather it is only being used as a set of keys/hashes to which blocks of the app need to be updated.
Therefore only the digital signatures of the .exe need to be compared and matched since this is the actual app content. The keys won't make any sense if the .exe is compromised.
The only signature of .exe.blockmap you would want to manually compare is of the file contents of .exe.blockmap itself to prevent any MITM, much like you would for most downloads i.e. checksum. I currently also perform this additional checksum on the .exe, but I'm not actually certain it's necessary, since if the .exe is modified the digital signature appears to be lost. To be safe though I still perform this check.

**Comment by HePingLaoSan** [comment]
> Thanks @gknapp. I don't think it's an XML document. In my case it is a binary file.

Add .zip extension, after unzip file , you will find the json content

**Comment by wuuli** [comment]
> > Thanks @gknapp. I don't think it's an XML document. In my case it is a binary file.
> 
> Add .zip extension, after unzip file , you will find the json content

it is not work for me

**Comment by AnneAlbert** [comment]
> > How are these blockmaps integrated with signing though. Since signing creates a new .exe. Will the blockmap become invalid ?
> 
> I have the same problem. Is there a way to generate a new blockmap file?

Is there already an answer to this? To me it seems that after signing, downloading the update with autoupdater takes much longer. Which suggests that the hashes in the blockmap file do not match the hashes of the actual installer, which results in autoupdater downloading the entire installer.

**Comment by leohxj** [comment]
does MacOS autoUpdate use it ?

**Comment by zerefdev** [comment]
> > > How are these blockmaps integrated with signing though. Since signing creates a new .exe. Will the blockmap become invalid ?
> > 
> > 
> > I have the same problem. Is there a way to generate a new blockmap file?
> 
> Is there already an answer to this? To me it seems that after signing, downloading the update with autoupdater takes much longer. Which suggests that the hashes in the blockmap file do not match the hashes of the actual installer, which results in autoupdater downloading the entire installer.

Have you found a solution to this? 
Also, the auto updater works fine without uploading a .blockmap file but the download process is a bit slow.

**Comment by AnneAlbert** [comment]
> Have you found a solution to this? Also, the auto updater works fine without uploading a .blockmap file but the download process is a bit slow.

I actually forgot about it, because auto updater indeed works fine. Just asked GPT, and it comes up with either

`yarn electron-builder build --prepackaged /path/to/your/signed/app`

or 

`yarn electron-builder build --windows --x64 --publish never --config.directories.output=dist/electron/Packaged --config.electronDist=yourSignedExeFolder`

A quick test threw some errors for me, and I don't have time to look into it at the moment. But if you figure something out let me know!
