### ISSUE TITLE
builder doesn't respect the snap config template

### ISSUE THREAD

**Issue by akashnimare** [electron-userland/electron-builder#2866]
electron-builder: `v20.11.1`

So I have a snap configuration is the `snap/snapcraft.yaml` and I thought builder respects that, found out it doesn't (maybe I'm wrong here). Here is my [`snapcraft.yaml`](https://github.com/zulip/zulip-electron/blob/master/snap/snapcraft.yaml) and [package.json](https://github.com/zulip/zulip-electron/blob/master/package.json).  With this setup I don't get the application launcher icon and the desktop icon (adding icon parameter to linux target works).

![screen shot 2018-05-03 at 7 09 14 pm 2](https://user-images.githubusercontent.com/2263909/39580375-aab6448e-4f06-11e8-836a-21e85530e34c.png)

![image](https://user-images.githubusercontent.com/2263909/39580879-d1d44bc8-4f07-11e8-9e8d-b262086bff97.png)

b) Also, for some reason the snap can't be auto-build, I get this [errors](https://build.snapcraft.io/user/zulip/zulip-electron/207565). So I have to manually build from the local 64-bit Ubuntu and push to the snapcraft.

**Comment by NeoTheThird** [comment]
This is BAD, and it worked before. This also means that it is not possible to specify more complex requirements that [you can not specify](https://www.electron.build/configuration/snap) in the electron-builder config any more. For example, it is now no longer possible to specify [parts](https://github.com/ubports/ubports-installer/blob/master/snap/snapcraft.yaml#L23) or [wrappers](https://github.com/ubports/ubports-installer/blob/master/snap/snapcraft.yaml#L13). Is it really not possible any more to make electron-builder use a custom snapcraft.yaml? That would be unfortunate, since as far as I can see, it kills snap for my usecase.

**Comment by develar** [comment]
Please see https://www.electron.build/configuration/snap
