### ISSUE TITLE
Symlinks not preserved in tar.gz (MAC packaging)

### ISSUE THREAD

**Issue by brianignacio5** [electron-userland/electron-builder#2868]
* **Version**: 20.11.1

* **Target**:  tar.gz using `yarn && yarn dist --mac`
Building on Ubuntu 16.04 LTS

When you build a tar.gz, tar.xz or tar.lz with electron-builder for mac release, the symlinks are not preserved. When you build a .7z or zip, it works correctly.

Steps to reproduce:

1.  Follow [Quick Setup guide](https://github.com/electron-userland/electron-builder#quick-setup-guide)
2. Add `"mac": {
      "category": "public.app-category.developer-tools",
      "target": [
        "tar.gz",
        "tar.xz",
        "zip",
        "7z"
      ]},` in package.json's build field. 
2. Run `yarn && yarn dist --mac`
3. Extract tar and zip. Compare files (such as those inside electron-webpack-quick-start.app/Contents/Frameworks/Electron Framework.framework) using `ls -l`

From what it seems there is an issue with electron builder tar. If i use my ubuntu `tar -zcvf to compress dist/mac/electron-webpack-quick-start.app` the symlink are preserved.

**Comment by adabru** [comment]
Same issue with me with version `20.38.5`. Following brianignacio5's example, I did:

Build `tar.gz`, `tar.xz`, `zip`, `7z`, both on Linux (Arcolinux) and Mac (10.13.3). Extract and try to run on the Mac. The result was that `zip` and `7z`were working while `tar.gz`and `tar.xz`weren't because of the symlinks. Compressing on the Mac with `tar -czf diet/*/*.app` and running the app from the extracted `.tar.gz` worked fine, the symlinks were preserved.

**Comment by BotellaA** [comment]
I have the same issue on macOS and Linux (both ubuntu and centos). Issue occurs with hardlinks and symlinks.

Anyone has an idea of this issue? This is a blocking issue for me...

**Comment by sepatel** [comment]
Blocking me as well. Really annoying bug indeed.
