### ISSUE TITLE
Issue when using ts-node/register in the main entry point of Electron

### ISSUE THREAD

**Issue by ghost** [electron-userland/electron-builder#2966]
* **Version**: 20.15.1

* **Target**: macOS as of right now

My current main entry point for the electron-main process is just the following two lines
```javascript
require("ts-node").register();
require("./ElectronMain");
```
while the `ElectronMain.ts` is generically creating and displaying the main window. When running `electron .` locally it works fine but after running `electron-builder` the app does not work. On macOS the icon bounces in the dock and nothing happens until I Force Quit the app. I tracked the issue down to the inclusion of `ts-node`. Basically the package electron app that the builder produces never passes the `require("ts-node").register()` statement. The `ts-node` package seems to be included correctly into the app archive and I can just assume that either it is not loaded at all but does not error or hangs during the execution of the `register` function.

My current workaround is to add a second build step and transpile the `ElectronMain.ts` into corresponding Javascript and it works. So it is literally just `ts-node` that doesn't get loaded/executed properly in the packaged electron application while it works when just running `electron .`.

**Comment by s73obrien** [comment]
Same issue here, but on Win10

[repro here](https://github.com/s73obrien/ts-node-electron-builder)

**Comment by s73obrien** [comment]
@NearAutomata do you have ts-node and typescript in the dependencies section in your package.json?  I just found that, in my simple example, if I move those over from devDependencies, the app builds and executes just fine.

**Comment by NearAutomata** [comment]
First of all I am not going to use `ts-node` anyways since adding `typescript` as a dependency to the project only for the Electron entry point is unreasonable anyways.

On the other hand I tried it again and got this exception which shows that `ts-node` is still buggy to some extent in my case:

![](https://i.imgur.com/7OkXMtq.png)

**Comment by nickdima** [comment]
I have the same problem with `ts-node` on mac. Did you find a solution?

**Comment by nickdima** [comment]
I manage to find a solution for MacOS. It seems that changing the working dir for the node process to the app's dir before registering `ts-node` fixes this, but I'm not sure why.
So what you need to do is this:
```
process.chdir(__dirname.replace("/app.asar", ""));
require("ts-node").register();
```
If you don't use asar you can remove the `replace` function call, but leaving it shouldn't hurt anyway.
The problem with asar is that when inside an asar package `__dirname`'s value will not be an actual dir so `chdir` will break. That's why we remove `app.asar` from the path. In your case the package name could be something else so try to log `__dirname` and see exactly who the asar package is called.
