### ISSUE TITLE
nsis installer: Error opening file for writing

### ISSUE THREAD

**Issue by TanninOne** [electron-userland/electron-builder#2992]
* **Version**: 20.11.1
* **Target**:  Windows (x64)

First of all, sorry for using an old version but reproducing this issue is hard as it appears only for a few users. I did look through the changelog and didn't see a fix that sounds like it is related.

So for a few of my users the nsis installer doesn't work when replacing an existing version, apparently it doesn't matter whether they go through an automatic update or manually install.

We use a one-click nsis installer. What happens is that the installer displays an error message "Error opening file for writing, ... Uninstall Vortex.exe".
This appears to be the first file it tries to write as the output directory is empty if the user cancels at this point.
Retrying the install then works however.
And from looking at process monitor (a tool to monitor api calls in windows) we can see that a "old-uninstaller.exe" is run and then the setup.exe tries to call "CreateFile" a few times and gets "DELETE PENDING" errors.

That seems to indicate that either the installer tries to install the new files at a time where the uninstaller isn't even finished yet or the uninstaller doesn't close at all and keeps file handles open so that windows can only clean up the files when the entire process tree has ended.

**Comment by nickdevereaux** [comment]
Getting this issue on a very slow VM I have. Based on your logging I've done some research
Some relevant lines of code: 

https://github.com/electron-userland/electron-builder/blob/c01b7c0b55d3466b826ea9cc9a11ad34118801c1/packages/app-builder-lib/templates/nsis/include/installUtil.nsh#L145

and line 173

Which led me to these NSIS doc pages:

https://nsis.sourceforge.io/When_I_use_ExecWait,_it_doesn't_wait

https://nsis.sourceforge.io/When_I_use_ExecWait_uninstaller.exe_it_doesn%27t_wait_for_the_uninstaller

So I wonder if the issue is related to line 145? Where it copies the uninstaller file. 

I know you can detect the one-click installer by checking: 

`${if} ${Silent}`

If I get the time I'll see if checking for one-click and not renaming the file works
