### ISSUE TITLE
How to use electron-forge-maker-nsis

### ISSUE THREAD

**Issue by benjtinsley** [electron-userland/electron-builder#3009]
This isn't a bug as much as a request for documentation. I am currently using Electron Forge on a project and wanted to use your [electron-forge-maker-nsis](https://github.com/electron-userland/electron-builder/tree/master/packages/electron-forge-maker-nsis) package to help create a NSIS installer.

The documentation is very scant on how to do this within the Electron Forge framework.

I think it would be most helpful to know:
- **how to configure this within Electron Forge.** Should there be a "nsis" key at the top level of my package.json?
- **how to run this task.** I have tried just running the task straight (`yarn electron-forge-maker-nsis`) but that is not a valid command. How can I hook this into a scripts object so I can create a shortcut to run it?

Thanks for all your hard work in improving the Electron development landscape!

**Comment by factorone** [comment]
I'm also interested in doing this, as while Electron Builder does a great job of building everything for distribution, we're using an instance of Atlassian's Nucleus for distributing our application. Electron Forge has a much better integration with that platform for distribution, but the installers it generates for windows are, frankly, hot garbage from a visual standpoint.

**Comment by develar** [comment]
> has a much better integration with that platform for distribution

What do you mean? Do you mean publisher?

**Comment by develar** [comment]
BTW, for electron-builder no need to use Atlassian's Nucleus or another smart servers — stage updates, channels and so on supported for any http server (s3 and so on). e.g. channels — https://www.electron.build/tutorials/release-using-channels

**Comment by factorone** [comment]
The reason we're sticking with Nucleus is its UI features, and its management of channels and releases from a visual standpoint (we're actually planning to extend it and add some features for our own installation). 

On a more specific note, I noticed that the Publisher and HttpPublisher classes are invoked for each task. Is it possible to write a custom Publisher that groups the publish tasks into a single upload, instead of doing a separate upload request for each task (e.g. one for the .exe, one for the .zip, one for the .dmg)?

**Comment by linonetwo** [comment]
Do you have example of using this package?

I'm currently using 

```json
      "makers": [
        {
          "name": "@electron-forge/maker-squirrel",
          "config": {
            "setupIcon": "build-resources/icon.ico"
          }
        },
```

In electron forge.

If I switch to `electron-forge-maker-nsis`, how the config file will be? Where to put icon path?

**Comment by sajtdavid** [comment]
I'm not sure why this was closed, as it is still not documented how to use it.

My findings:
I tried to get it working, but I think this version is broken (`npm i electron-forge-maker-nsis`):
* First issue was `TypeError [ERR_INVALID_ARG_TYPE]: The "paths[0]" argument must be of type string. Received undefined`
* I solved this by adding 'dir' parameter in the config, pointing to the current directory.
* Then got `Error: Unsupported arch undefined`
* I solved this by specifying `targetArch` in the config to ia32
* Then got `TypeError: Cannot read properties of undefined (reading 'includes')`
* I think this is an actual issue with the Maker. Tried to get through this, but got further errors (`TypeError: makers is not iterable`). Also, I think the build was already started in the `Resolving make targets` phase and not in `Making distributables`

I installed another library that worked a bit better, but still not the best:
https://github.com/imxeno/electron-forge-maker-nsis
* This worked quite well out of the box, the first .exe file was created
* The packager didn't used the configuration provided in the `forge.config.ts`
* I was able to configure it in the package.json in the following structure:
`{
  ..
  "build": {
    "productName": "...",
    "appId": "...",
    "nsis": {
      "oneClick": false,
      "installerIcon": "...",
      "runAfterFinish": true,
      "allowToChangeInstallationDirectory": true
    }
  },
..
}`
* I could not find any way to apply variables in the configuration. Does anyone have ideas how it is possible? Switching to js configuration would also work for me, but didn't found the way to use config.js instead of package.json.

**Comment by royorange** [comment]
> I'm not sure why this was closed, as it is still not documented how to use it.
> 
> My findings: I tried to get it working, but I think this version is broken (`npm i electron-forge-maker-nsis`):
> 
> * First issue was `TypeError [ERR_INVALID_ARG_TYPE]: The "paths[0]" argument must be of type string. Received undefined`
> * I solved this by adding 'dir' parameter in the config, pointing to the current directory.
> * Then got `Error: Unsupported arch undefined`
> * I solved this by specifying `targetArch` in the config to ia32
> * Then got `TypeError: Cannot read properties of undefined (reading 'includes')`
> * I think this is an actual issue with the Maker. Tried to get through this, but got further errors (`TypeError: makers is not iterable`). Also, I think the build was already started in the `Resolving make targets` phase and not in `Making distributables`
> 
> I installed another library that worked a bit better, but still not the best: https://github.com/imxeno/electron-forge-maker-nsis
> 
> * This worked quite well out of the box, the first .exe file was created
> * The packager didn't used the configuration provided in the `forge.config.ts`
> * I was able to configure it in the package.json in the following structure:
>   `{ .. "build": { "productName": "...", "appId": "...", "nsis": { "oneClick": false, "installerIcon": "...", "runAfterFinish": true, "allowToChangeInstallationDirectory": true } }, .. }`
> * I could not find any way to apply variables in the configuration. Does anyone have ideas how it is possible? Switching to js configuration would also work for me, but didn't found the way to use config.js instead of package.json.
> 
> Update: After checking the sources, I was able to apply dynamic variables to the build. I had to create a file electron-builder.js, include the dynamic config, and also remove the "build" config from packages.json (js file is ignored when it is there..).

hi, would pls tell me how to resolve this issue?
1. do i need to add a maker like "electron-forge-maker-nsis" inside the forge.config.js?
2. whats the command for package?i'v tried `electron-forge make --config electron-builder.json5` like i used to do inside electron-builder, but its not work. 
the pnpm has a lot of issues, so i changed to yarn

**Comment by sajtdavid** [comment]
> * do i need to add a maker like "electron-forge-maker-nsis" inside the forge.config.js?

I have this maker in the forge.config.js:
`    {
      name: '@imxeno/electron-forge-maker-nsis',
      config: {
        productName: environmentConfiguration.name,
      }
    },`



> 2\. whats the command for package?i'v tried `electron-forge make --config electron-builder.json5` like i used to do inside electron-builder, but its not work.

I use the default `npm run publish`, which leads to `electron-forge publish`, without any specific params

**Comment by ggchar** [comment]
For people who still manage to use electron-builder with electron-forge, here are my configurations that work for my project:

- Electron Forge: v7.4.0

```
// Step 1: Install this dependency for NSIS support. For me, the version is v7.0.2.
npm i @electron-addons/electron-forge-maker-nsis
```

```
// Step 2: Add this configuration to 'forge.config.js'.
makers: [
    {
      name: "@electron-addons/electron-forge-maker-nsis",
      config: {},
    }
  ]
```

```
// Step 3: Append this configuration to the end of the package.json file..
  "build": {
    "appId": "com.example.YourProjectName",
    "asar": true,
    "nsis": {
      "oneClick": false,
      "createDesktopShortcut": true,
      "runAfterFinish": true,
    },
    "win": {
      "target": [
        "nsis"
      ]
    }
  }
```
```
// Step 4: Run this command in the terminal
npm run make
```

**Comment by theIYD** [comment]
Anyone who was able to crack auto-update with this? I need a setup for auto-update with NSIS installer only for Windows.

**Comment by prayash** [comment]
nice mna
