### ISSUE TITLE
Not packaging all files in app/ directory

### ISSUE THREAD

**Issue by ryanmcclure4** [electron-userland/electron-builder#3016]
* **Version**: 20.15.1
* **Target**: OSX

I have a React app that I build with Webpack, which outputs **main.js**, **vendor.js**,  **xxx.woff**, **xxx.ttf**, and **xxx.svg** files. I have these output to a folder `app/` in my project's base directory, however when I run electron-builder, main.js and vendor.js are the only files packaged in the app folder.

From what I understand, _build_ in package.json has _files_ set to `**/*` by default and so everything should be included. I've tried modifying this to include `app/**/*` and also tried listing each file individually, but it still only includes the main and vendor files. Am I missing something here?

**Comment by popod** [comment]
Hi,

1. Can you provide the `build` section of your `package.json` ?
2. Can you provide the path of `package.json`, `main.js` and `xxx.ttf` ?
3. Has this configuration worked before or is it your first setup of electron-builder for this project ?

Thanks

**Comment by ryanmcclure4** [comment]
`build` section:

```
"build": {
    "appId": "io.reachify",
    "files": [
      "index.html",
      "main.js",
      "app/**/*",
      "package.json"
    ]
  }
```

Paths:
```
├── electron
│   ├── app
│   │   ├── 674f50d287a8c48dc19ba404d20fe713.eot
│   │   ├── 912ec66d7572ff821749319396470bde.svg
│   │   ├── af7ae505a9eed503f8b8e6982036873e.woff2
│   │   ├── b06871f281fee6b241d60582ae9369b9.ttf
│   │   ├── fee66e712a8a08eef5805a46892932ad.woff
│   │   ├── main.1ee7c28e5485d7179e70.js
│   │   ├── main.1ee7c28e5485d7179e70.js-e
│   │   └── vendor.c0abcf6c41d3a1662e53.js
│   ├── index.html
│   ├── main.js
│   └── package.json
```
`electron` is the base directory.

This is the first time I've tried using electron-builder. I have used electron-packager previously and did not run into these issues.

Thanks!

**Comment by popod** [comment]
Okey, thanks.

I think the only thing you should do is rename your `app` folder by `packaged` (or something else) and set your `build` config as this:

```
"main": "./packaged/main.js",
...
"build": {
    "appId": "io.reachify",
    "files": [
      "packaged/",
      "index.html"
  }
```

It is because the `app` directory is a "reserved" folder for electron-builder and interpreted as the root folder of your app if it exists.

Then, if you build your app with `"asar": false` in your `build` config, and open the packaged macOS application with something like right-click "Open application content", then, under `resource/app`, your should see all your files.

If your application launch, but do not display any content, add `mainWindow.webContents.openDevTools()` in your `main.js` and resolve the error displayed.

**Comment by ryanmcclure4** [comment]
That solved it for me - Thanks!
