### ISSUE TITLE
Not generating latest-linux.yml file

### ISSUE THREAD

**Issue by GammaGames** [electron-userland/electron-builder#3085]
* **Version**: 
electron-builder-lib@20.19.2
electron-updater@2.23.3

* **Target**: 
Win/Linux

At one point during my building I had a 'latest-linux.yml' file in my dist folder. I don't know what has happened to that file, but after running `electron-builder --x64 -l` the file is no longer generated, and the server (I use python3's simple server for local testing) has the error:
![image](https://user-images.githubusercontent.com/7832163/42388494-ea5548aa-8102-11e8-9ba5-1f26c6788373.png)

This happens both when building on linux and building on windows with the remote builder.

**Comment by GammaGames** [comment]
@develar is linux-latest only available for appImage targets? I've seen so many electron apps that use the deb target it seems like it would be handy to allow auto updating with that target. And if it's not planned, what is the reason?

**Comment by mkermani144** [comment]
@GammaGames 
I had the same issue. As you said, I found that linux-latest is only available for AppImage. It seems that, for example, deb packages should be updated using native package managers.

**Comment by develar** [comment]
1. Do no use deb
2. Use default AppImage as a solution that works everywhere
3. Use Snap instead of deb if you want to provide system package. And better for your users maybe will be if you will also publish snap to Ubuntu Store.

> And if it's not planned, what is the reason?

Reason is simple — electron-builder follows system convention and makes everything to not be alien on user system. That's why for example, default artifacts file patterns differs depends on target. Deb it is system package format and if you provide deb — it is expecting that you will use something like https://packagecloud.io to distribute updates.

But again — deb is not default target and we recommend AppImage and Snap (both are default if will not specify target explicitly).

@GammaGames So, you issue is that you set target to deb?

**Comment by GammaGames** [comment]
That makes sense, I guessed it might be because of the normal conventions of .deb files. Thank you!
