### ISSUE TITLE
Windows code signing from OS X

### ISSUE THREAD

**Issue by feross** [electron-userland/electron-builder#314]
What's left to do to make [this](https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Build_Instructions/Signing_an_executable_with_Authenticode) work?

**Comment by develar** [comment]
Time. Only time. And issue from user. Now we have the issue ;)

**Comment by feross** [comment]
Nice, glad I could help out :+1: 

But seriously, let me know if there's any way to help out.

According to @kevinsawicki's [comment](https://github.com/electron/windows-installer/issues/27#issuecomment-210169110), `signcode` only supports MD5 and SHA1 signing, which are both deprecated. We might want to look at using `SignTool` if that's possible to use from `wine`. Or maybe [`osslsigncode`](https://sourceforge.net/projects/osslsigncode/), as suggested.

**Comment by kevinsawicki** [comment]
I published a new [signcode](https://github.com/kevinsawicki/signcode) module last week that wraps `osslsigncode`.

It has both a simple CLI and API, https://github.com/kevinsawicki/signcode#cli

**Comment by kevinsawicki** [comment]
By default it signs with both `sha1` and `sha256 signatures.

**Comment by feross** [comment]
@kevinsawicki Nice!

**Comment by develar** [comment]
@kevinsawicki Thanks a lot. Works like a charm. We should add linux version of osslsigncode and specify [os](https://docs.npmjs.com/files/package.json#os) to not install this module on Windows, but it can be addressed later.

* electron-builder uses signcode to sign app exe regardless of Squirrel.Windows (because electron-builder is a smart facade of electron-packager/will pack into sfx/7z/zip/etc soon)
* installer is signed by windows-installer (my fork) — PR will be this/next week.

**Comment by develar** [comment]
Please note — all releases are now as `next`, i.e. `npm update` will not update to it. Use `next`. Once someone confirm that it works, it will be marked as `latest`.
