### ISSUE TITLE
Support publishing to Snapcraft

### ISSUE THREAD

**Issue by sindresorhus** [electron-userland/electron-builder#3187]
* **Version**: 20.26.0

* **Target**: Snap

`electron-builder` has a `snap` target, but it seems we still need to manually upload the binary using `snapcraft push dist/appname_2.16.0_amd64.snap` and then `snapcraft release appname 1 stable`. Would be nice if `electron-builder` could handle the publish-step too.

More info: https://docs.snapcraft.io/build-snaps/publish

**Comment by develar** [comment]
What is your development OS?

**Comment by develar** [comment]
`rpm` is not default target for Linux. And not popular (and you can set `_REMOTE_BUILD=true` to avoid installing).

**Comment by evandandrea** [comment]
@develar do you have suggestions on how we could distribute snapcraft for Mac such that electron-builder could handle publishing?

/cc @sergiusens @kyrofa

I love this idea. We're seeing quite a few instances of people publishing .snap files to GitHub releases. That doesn't give you the showcasing to the millions of Snap Store users, doesn't give you auto-updates, and requires trust (`snap install --dangerous`). This would solve all of that.

**Comment by evandandrea** [comment]
Alternatively, we could write a handler in JavaScript, as was done in Ruby for Travis:
* https://github.com/travis-ci/dpl/blob/master/lib/dpl/provider/snap.rb
* https://docs.travis-ci.com/user/deployment/snaps/

**Comment by develar** [comment]
Python is not a good language for CLI tools (the same as NodeJS ;)), but at least now snapcraft is available for macOS. I cannot find easily instructions how to install it on Windows without Linux subsystem.

electron-builder 21 forces you to publish to store. A new publish provider `snapStore` is the default value for snap and your regular publish configuration is ignored unless explicitly specified for `snap` (under key `snap`). 

electron build service cannot be used to publish snap for poor Windows users, who cannot migrate to a normal OS, because I don't want to take responsibility for credentials. Maybe later electron-builder will produce a special plugin for snapcraft, so, you will be able to use official build service from Canonical to build and publish your snap. I cannot predict when it will be implemented and will be implemented or not.

I like how snapcrat is developer friendly (shame on you, bloody Apple and not so bloody but still, MS).

`snapcrat push` produces correct and clear error messages, so, electron-builder is not forced to add another layer of error handling.

It will be released in 2 days.

**Comment by develar** [comment]
> electron-builder 21 forces you to publish to store

To make clear why — because snap is awesome. electron-builder goal is simple — you want just release your snap and that's all. Focus on your app development. Not to mix your sexual life and programming. So, even if big commercial companies allocate time to verify that app works in varios Linux distros (and should do it for obvious reasons), it is not an option for a lot of developers. And contradicts to what electron-builder promises.

So, snap and publishing to snap store is strongly recommended. It is the only format that will just works in 99% (no even glibc dependency).

**Comment by sindresorhus** [comment]
@develar Awesome. And I totally agree with that thinking.

**Comment by jtc42** [comment]
So am I right in thinking that we can set publish to first - a generic server, providing auto-updates for Windows installs, and second - SnapCraft, which will allow auto-updates on Linux via SnapCraft, rather than integrated auto-updates? Or will this cause problems?

**Comment by patarapolw** [comment]
So, how do I DISABLE publishing to SnapCraft. My build kept crashing...

**Comment by sergiusens** [comment]
@patarapolw a new issue might be better here, but I suspect your login credentials expired.

**Comment by rasgo-cc** [comment]
Quoting @adam-lynch , on issue #4982, you can disable it by providing a generic provider:

> You can also set snap.publish to:
> {
>   provider: "generic",
>   url: "https://anydummyurl.com"
> }
