### ISSUE TITLE
can not find module app.asar/*

### ISSUE THREAD

**Issue by fanyuzzz** [electron-userland/electron-builder#3240]
I have to use the spawn, It's works in the html file with the script 'electron .' before building.
`const node = spawn('node', [path.join(__dirname, 'app.js')], {
    cwd: process.cwd()
});`

but after building, the electron warning:
`Error: Cannot find module 'E:\npm2\electron-quick-start-master\dist\win-unpacked\resources\app.asar\app.js' `

how to make spawn work with the path?

**Comment by davidv1992** [comment]
The problem is that by using spawn this way you use the system-installed node, not electron's builtin node. Since the system node is not patched to see inside asar archives, it will complain about not being able to find the files you are referencing.

The best solution is probably to avoid depending on a system node altogether, since if you are distributing there isnt any guarantee that it will be available anyway.
