### ISSUE TITLE
Windows - Cannot Find Multiple modules after install

### ISSUE THREAD

**Issue by smithalan92** [electron-userland/electron-builder#3249]
Initally with 
electron-builder: 20.26.0
electron-builder-squirrel-windows: 20.26.0

updated then to 
electron-builder: 20.28.1
electron-builder-squirrel-windows: 20.28.0

Windows x86 Squirrel

It looks some some dependencies are failing to install on Windows. Initially it happened on 20.26.0 , I found an issue saying it was fixed in 20.27.x , so I updated to the latest 20.28.1/0 but the issues still there.

First error 

`Error: Cannot find module 'builder-util'`

I installed builder-util and tried to build again , this time I got 

`Error: cannot find module 'read-config-file'`

After installing that, I ran the build again this time I get 

```
Module electron-builder-squirrel-windows must be installed in addition to build Squirrel.Windows: Error: Cannot find module 'app-builder-lib'
```

**Comment by smithalan92** [comment]
Seems to be fine in 20.28.2

**Comment by Flygenring** [comment]
If anyone comes here, I had the exact same problem because I had a `.yarnclean` that was mindlessly setup to remove `package.json` from dependencies after installation, which is needed for Electron to install app dependencies.

You could white list each failing dependency (or individual files from them) one by one in `.yarnclean` if removing them from all other dependencies is important to you, but leaving all `package.json`s in there should be fine 😋
