### ISSUE TITLE
Programatic way to figure the target we're using

### ISSUE THREAD

**Issue by gajop** [electron-userland/electron-builder#3282]
Is there a way to figure out what target was used to build the app?
I want to provide different behavior depending on how the app was built.

There might be a hacky way to achieve this, but I feel that there should be a clear API which allows the app to figure out how it was built. This meta information should be included in the app if it isn't already.

**Comment by develar** [comment]
Linux:

env APPIMAGE is set if AppImage
env SNAP is set if Snap.

Please clarify for what OS you need.

**Comment by gajop** [comment]
Thanks. Is there a more complete list of these env variables?
At the very least I would like to detect:
- Linux: AppImage, Snap
- Windows: portable, nsis
- Mac: default, dmg, mas, pkg (fairly unfamiliar with Mac, so I'm not yet sure which I want)
- General: zip (and other plain archives)

PS: Wouldn't mind helping update the docs if you gave me a hint where to look at. Docs could use this info (imo).

**Comment by develar** [comment]
> Windows: portable, nsis

If env `PORTABLE_EXECUTABLE_DIR` defined, it is portable.

**Comment by develar** [comment]
> Mac: default, dmg, mas, pkg (fairly unfamiliar with Mac, so I'm not yet sure which I want)

Doesn't make sense. In all cases user just unpack app and you cannot say what originally was used to deliver app. (except pkg where you can put some extra file during installation).

> General: zip (and other plain archives)

On Linux: if both APPIMAGE and SNAP not defined, it is deb/zip/etc 
On other OS: app is extracted, the same story as DMG.

I will not add unified programmatic API and runtime module because for me it looks like as overhead. For production I guess these tricks will be enough to implement wanted functionality without complicated solutions.

(technical reason: electron-builder build app once for OS and then pack it into distributable formats in parallel using the same base packed app).

> PS: Wouldn't mind helping update the docs if you gave me a hint where to look at. Docs could use this info (imo).

FAQ section can be added to https://www.electron.build/configuration/configuration like we do for https://www.electron.build/configuration/nsis#common-questions See docs branch to edit docs (https://github.com/electron-userland/electron-builder/tree/docs)

**Comment by gajop** [comment]
Thanks for the detailed information. I think this should let me work with most scenarios I'm interested in right now (Mac is not yet well supported for the environment I'm writing this app in anyway).

> I will not add unified programmatic API and runtime module because for me it looks like as overhead.

That's certainly your choice as the developer, although in my opinion it makes little sense to be concerned about providing build meta information (a json file with a couple of kBs at worst?) in a system which is already hundreds of MBs in size and basically includes a nearly complete browser. I won't be building electron apps for embedded devices ;)

**Comment by gajop** [comment]
That's understandable of course. Thanks for your contributions !

**Comment by ZudoMC** [comment]
@develar is there any way to detect if we're running in an AppX?
