### ISSUE TITLE
devDependencies

### ISSUE THREAD

**Issue by wells1013** [electron-userland/electron-builder#3335]
* **Version**: 20.28.4  

* **Target**:  Mac, Windows

```
const deps = ["electron", "electron-prebuilt", "electron-rebuild"]
  if (process.env.ALLOW_ELECTRON_BUILDER_AS_PRODUCTION_DEPENDENCY !== "true") {
    deps.push("electron-builder")
  }
  for (const name of deps) {
    if (name in dependencies) {
      errors.push(`Package "${name}" is only allowed in "devDependencies". `
        + `Please remove it from the "dependencies" section in your package.json.`)
    }
  }
```

check Dependencies at 'devDependencies', how about 'optionalDependencies'?

**Comment by develar** [comment]
Not clear what do you mean. Should we check also optionalDependencies for these deps?

**Comment by s524797336** [comment]
The optionalDependencies will overwrite dependencies, add it to optionalDependencies is equal as dependencies.
But i have an other suggest.
I have a multi platform project which runs on web and electron, i use docker to build web version, so i added it to optionalDependencies, in docker i use `npm install --no-optional` to avoid install electron stuff, but in electron version, i have to move optionalDependencies to devDependencies, can you gays only check if electron-builder only in devDependencies instead of check it in dependencies?
Because i need add electron-builder in devDependencies and optionalDependencies, then `npm install --no-optional` will not install electron-builder
