### ISSUE TITLE
Suggestion: document the "asar: false" option

### ISSUE THREAD

**Issue by JeremyMiller** [electron-userland/electron-builder#335]
I needed to use the node `spawn` function in my app, which is a function that doesn't work with asar archives. I had to read the code to figure out how to stop electron-builder from archiving my app.

All it takes is setting `"asar": false` in the `build` section of `package.json`. I feel like this option should be documented here: https://github.com/electron-userland/electron-builder/blob/master/docs/Options.md#build.

I would have added it myself and submitted a pull request, but it seems these docs are autogenerated and I'm not quite sure how. Additionally, when trying to clone the repo I get prompted for a username and password to download an image (`test/fixtures/test-app-one/build/background.png`) so I decided to just create this issue instead.

I feel like having this feature documented would be very helpful to people in my position. Thank you for your time.

**Comment by whyboris** [comment]
@ghost -- you are a hero like no other!
I spent hours trying to figure out how to get my `ffmpeg` into an _Electron_ APP build.
This is what I have in my `main.ts` that worked while developing:
```
const ffprobePath = require('@ffprobe-installer/ffprobe').path;
const ffmpegPath = require('@ffmpeg-installer/ffmpeg').path;
const ffmpeg = require('fluent-ffmpeg');
ffmpeg.setFfprobePath(ffprobePath);
ffmpeg.setFfmpegPath(ffmpegPath);
```
But when I would build my app, since I was using [angular-electron](https://github.com/maximegris/angular-electron)
my default build instructions were
`"electron:mac": "npm run build:prod && node package.js --asar --platform=darwin --arch=x64",`
And after the build whenever the app tried to use _ffmpeg_, it would throw `spawn ENOTDIR` -- since it was looking for the _dll_ in `.../app.asar/node_modules/...`
All I had to do was remove the `--asar` from my build script (the argument was modifying the build instructions in `package.js`) -- and now my app works!
Thank you so much ❤️
