### ISSUE TITLE
Silent auto-update and shutting down Windows during silent update

### ISSUE THREAD

**Issue by lduros** [electron-userland/electron-builder#3362]
* **Version**: 
Latest

* **Target**: 
Windows 10

I'm curious if anybody has encountered issues while having a silent auto-update running in the background (without any user notification) and shutting down Windows in the same time. It looks like it still shuts down, but when restarting Windows, the application will not be in its installed state obviously, the executable will be removed from the AppData folder etc... Is there any mechanism that recovers from this? Or do we have to tell users basically, install the app again?

Many thanks,

**Comment by paulwib** [comment]
Yes, just come across this recently. Our app calls `autoUpdater.checkForUpdatesAndNotify()` when the application starts, so any update will be downloaded in the background. If the app is left open and the machine is shutdown, when it restarts shortcut icons (including from the start menu) will give an error because the target executable is missing.

I'm guessing this is something to do with the machine shutdown forcing the app to quit, then the auto-updater kicks in trying to copy the new files in place, but it can't complete before the machine shuts down, leaving a broken install.
