### ISSUE TITLE
Build ASAR individually.

### ISSUE THREAD

**Issue by yansenlei** [electron-userland/electron-builder#3476]
* **Version**: 
electron-builder: v19.56.2

* **Target**: 
Build ASAR individually.

When building the packages, a app.asar is constructed separately. The build directory is as follows: 
```
build/
├── app.asar
├── pkg-0.0.3.dmg
```
Is it feasible?

**Comment by develar** [comment]
What's problem to get asar from .app dir?

**Comment by yansenlei** [comment]
Yes, Get ASAR from .app dir.

I want to [update the .asar](https://github.com/yansenlei/electron-asar-hot-updater) process more closely.

**Comment by develar** [comment]
@yansenlei It doesn't make sense because electron-updater supports differential updates for win/linux and soon for macOS.

**Comment by yansenlei** [comment]
@develar Thank you for your reply.
I think app.asar is smaller, so I want to do my best to support it.

**Comment by develar** [comment]
@yansenlei Have you seen electron-updater output? It can be only 4% to download. And no need to complicate and think about what's changed in your info.plist/nsis script and so on. You can spend a lot of time and greatly increase maintenance costs for... just 1%? 2%? Doesn't worth it.

**Comment by yansenlei** [comment]
@develar As you say, electron-updater is really convenient, but we need to download the entire installation package when updating (.dmg| .exe| ...).
The contents of the main process and rendering process are already included in app.asar. Do we just need to update app.asar?

**Comment by develar** [comment]
> but we need to download the entire installation package when updating (.dmg| .exe| ...).

No. Only changed blocks are downloaded. Differential downloader not yet enabled for macOS, because at first I want to be sure that it works in all possible conditions and for now it is enabled only for Linux/Windows.

Don't get me wrong — I just want to be sure that you are understanding what are you doing. And it seems, "we need to download the entire installation package", you don't realize that actually electron-updater uses content-defined chunking to compute blockmaps to be able to compute delta updates from ANY version to ANY version (and it is black box — no need to know packaging format).

**Comment by Manuel-777** [comment]
Has there been any news on this? Now squirrel is deprecated and updater is bundled here, cross platform updates are like in a gray area requiring different processes each.

I was investigating asar updates as well, but I can't find anything about what @develar said about differential updates

**Comment by yansenlei** [comment]
https://github.com/electron-userland/electron-builder/commit/b7f8e8c4c172500220aa254abda6774f352005da
It should be a bug before, so they will go back.
This seems to be a tricky issue, and I am also looking forward to the news of the differential updates.
