### ISSUE TITLE
AppImage .desktop file broken for apps with spaces in their name

### ISSUE THREAD

**Issue by burnpanck** [electron-userland/electron-builder#3547]
* **Version**: 20.38.3

* **electron-updater**: ^4.0.4

* **Target**: AppImage (+macOS, +Windows)

We recently migrated from electron 2 to electron 3, and at the same time moved from electron-builder 20.22.0 to the most recent, 20.38.3. Now, the `.desktop` file (linux desktop integration) seems to be broken, the running app cannot be pinned to the dock (the "add to favourites" context menu entry is missing), and the app doesn't appear in the dash search. This seems to be related to our app name containing spaces: The `Exec` key of the generated `.desktop` file contains a quoted absolute path including spaces, that seems to work fine. The `TryExec` key on the other hand contains an unquoted, esacped absolute path, with the spaces escaped using `\\s` (note the double backslash). Manually changing those to `\s` makes the app re-appear in the dash searches and the image of a pinned app re-appear in the dock. I compared electron 3 combined with version `20.22.0` of electron-builder, where the generated AppImage did not contain any spaces (instead replaced by dashes), so the problem does not appear. As a workaround, I can use the `artifactName` key of the `appImage` options in `package.json` to avoid spaces in the appimage name.

**Comment by schnipseljagd** [comment]
I can confirm the problem for Linux as target as well.

**Comment by koden-km** [comment]
I just hit this issue in my app's AppImage build. If I use dash instead of space in the AppImage filename, my app works and integrates correctly (dash search, dock and icon). But if I use a space then integration doesn't work. The app does launch from file explorer and run fine, but it does not show in dash search and the icon on the dock is a placeholder for no icon even though the app's `.desktop` file and icons all appear to have installed correctly. The `.desktop` file `Icon` property matches the installed icon names.

The same `artifactName` workaround works for me also. The app project name can still contain spaces, with just the AppImage artifact name overridden.

**Comment by jayarjo** [comment]
Actually until now I believed that integration with system is not possible in `electron-builder` for `AppImage`, because my app file had a space in it's name and it didn't work. I was surprised that it actually works!
