### ISSUE TITLE
Set application name for windows notifications

### ISSUE THREAD

**Issue by philipgiuliani** [electron-userland/electron-builder#362]
The Windows 10 Notification center shows me `com.squirrel.youtv.YouTV-Downloader` but i would like to just have the app's name there. Im not sure if i just missed an option of electron-builder, but i couldn't find one.

![bildschirmfoto 2016-04-26 um 17 28 40](https://cloud.githubusercontent.com/assets/5446019/14844773/1efb5326-0c5a-11e6-973a-a7904181b723.png)

```javascript
new Notification("Download abgeschlossen", {
    body: `${download.title} wurde erfolgreich heruntergeladen`
});
```

**Comment by develar** [comment]
https://github.com/electron/electron/releases/tag/v0.37.3 "Automatically set Application User Model ID when Squirrel.Windows is used."

Hmm... should be a way to set custom "Application User Model ID". I will check how it is possible.

**Comment by philipgiuliani** [comment]
I'm not sure how windows notifications work, but setting the application id seems strange to me. I will also look if i can find something out. Thank you very much @develar for all your help! :)

**Comment by voltagex** [comment]
https://blogs.msdn.microsoft.com/tiles_and_toasts/2015/10/16/quickstart-handling-toast-activations-from-win32-apps-in-windows-10/ is pretty much the only non-UWP info I can find.

**Comment by develar** [comment]
Squirrel.Windows code: `sl.SetAppUserModelId(String.Format("com.squirrel.{0}.{1}", zf.Id, exeName.Replace(".exe", "")))`

Bug: https://github.com/electron/electron/issues/4381

Our NSIS target will allow you to set custom app id. For Squirrel.Windows you can use https://github.com/KochiyaOcean/windows-shortcuts instead of `spawnUpdate(['--createShortcut', exeName]);`. 

Yes, we maintain our own Squirrel.Windows fork (https://github.com/develar/Squirrel.Windows/tree/build) and can fix it. Well, help wanted. Currently I am working on NSIS target.

**Comment by develar** [comment]
Moved to backlog. Because fixed for NSIS and Squirrel.Windows will be not default target in the next major release.
