### ISSUE TITLE
png files must be at least 512x512

### ISSUE THREAD

**Issue by chhaymenghong** [electron-userland/electron-builder#3633]
* **20.36.2**: 

* **Mac**: 

I am trying to build an electron app for Mac. The app use a ui library that has image files in them which got moved to the dist folder where all the icons are as well during the packaging. When I run electron-builder build --mac,  I see this error "must be at least 512x512" on all of the third party image files.How should I fix this?

**Comment by deoxyseia** [comment]
Do you fixed it?

**Comment by chhaymenghong** [comment]
nope.

**Comment by j0hnwhyte** [comment]
I'm having the same issue, the file is from an external library. What's the proper approach to avoid this error?

Thanks

**Comment by j0hnwhyte** [comment]
Also there are several other questions like [this](https://github.com/electron-userland/electron-builder/issues/3709), so this might be marked as a duplicate.

Apparently this happens because the tool (as specified in `electron-builder.json` looks in the `dist/` folder (or whatever folder the app is generated in) for the icons. Changing the configuration fixed it for me.

```
{
  "productName": "angular-electron",
  "directories": {
    "output": "release/"
  },
    ...
  "win": {
    "icon": "dist/assets/icon",
    "target": [
      "portable"
    ]
  }
}
```

**Comment by chhaymenghong** [comment]
@deoxyseia: @j0hnwhyte is right. For me, i just do this

 "mac": {
    "asar": false,
    "icon": "dist/512x512.png",
    "target": [
      "dmg"
    ]
  },
I just reference the exact image file I need.
