### ISSUE TITLE
Preserve arguments on auto-updater quitAndInstall

### ISSUE THREAD

**Issue by alekplay** [electron-userland/electron-builder#3744]
We have two versions of our app that can be launched by passing a command line argument. Currently the `quitAndInstall()` does not preserve these, restarting the app in the default mode. Would it be possible to have `quitAndInstall()` restart the app with the same parameters, alternatively another solution for passing these back to the updated version?

**Comment by meekaah** [comment]
+1 currently as a workaround we have to save the original arguments to disk in a json file and load them back up once it has updated.

**Comment by hgouveia** [comment]
I am highly interested in this feature,  something like `quitAndInstall(isSilent, isForceRestart, openArguments)`

where **openArguments** could be an array of arguments that will append when reopening the app, ex: `['--updatedTo=2.0.0']`

right now i dont have any way to pass any argument after is updated

**Comment by mscoobby** [comment]
Any progress on that one? I'm building an application which has a CLI version and I really need a way to pass the parameters back once the update is done.

**Comment by tomaspiaggio** [comment]
I've been looking at the code. It doesn't seem very hard to add to `quitAndInstall`. 

I need this too. I'd be willing to add it. The arguments need to reach the method `doInstall` on `BaseUpdater` subclasses. `NsisUpdater` even has an argument list that's already using. We just need to add it to the `options` object provided in the method as an argument.

**Comment by jordandearsley** [comment]
By the way, process.env is copied to the spawned instance following update, so you can do something like:
```
const { env } = require("process");

if (!env["CI"]) {
  env["CI"] = process.argv.includes("--ci");
}
```

**Comment by rubenLindstrom** [comment]
Also interested in this

**Comment by ibandominguez** [comment]
Any news on this?

**Comment by zlshames** [comment]
Just bumping this because this is useful for headless deployments of electron apps, and in the current state, it doesn't maintain CLI args. I've tried calling `app.relaunch` with the correct args first with no dice. It's causing a bit of a roadblock in one of my apps.

**Comment by DMiradakis** [comment]
Yep very similar need here. I've made an Electron app that runs as an unattended kiosk-type application. Users set it up and don't want to have to touch it.

As such, I've had to build in two different types of updates:
- Manual updates (where I want a dialog box to popup)
- Automatic updates (where I do not want a dialog box to popup and instead want the entire update process automatic)

I basically had to hack together a goofy solution where I have a local variable in my JS module with the autoUpdate code that is supposed to represent the most recent updateCheck type. If that variable shows a manual updateCheck, then I have to set some flags to make a dialog box appear for the user. Conversely, if the variable shows an automatic/non-manual updateCheck, then I do not want a dialog box to appear.

This is suprisingly difficult/frustrating to work with since I have to show or hide dialog boxes in the event handlers of the `autoUpdater` object. Instead, the calling methods themselves need an `isSilent` parameter or something along those lines that they don't have today.

It's proving more cumbersome than I anticipated.

**Comment by Floyddotnet** [comment]
+1 for this feature. My electron app acts as url protocol handler but after update all arguments are gone.

**Comment by mmaietta** [comment]
So I see two routes for this.
```
quitAndInstall(isSilent, isForceRestart, openArguments)
```
Either `openArguments` appends to the current argv. i.e. `app.relaunch({ args: process.argv.slice(1).concat(openArguments) })`
OR
`openArguments` completely replaces launch args (which doesn't seem right to me?). i.e. `app.relaunch({ args: openArguments })`

Which route makes more sense for your purposes? In the 2nd case, you have the option of reusing launch args by manually providing/filtering them yourselves, so I'm currently leaning towards that

Note: I can't seem to find a way for NSIS to preserve launch args, unless it's possible to provide that via the NSIS installer. NsisUpdater doesn't call `app.relaunch` anywhere.

For mac, we call `autoUpdater.quitAndInstall()` (https://www.electronjs.org/docs/latest/api/auto-updater#autoupdaterquitandinstall) directly, which doesn't accept launch args, so we'd need to replicate this function manually I think? It looks like it's simply calling `relaunch(args)` and then `quit()`

**Comment by ufukomer** [comment]
This is a must, if relaunch() has it, this function should also support args.

**Comment by mmaietta** [comment]
@ufukomer please note from my previous comment.

>Note: I can't seem to find a way for NSIS to preserve launch args, unless it's possible to provide that via the NSIS installer. NsisUpdater doesn't call app.relaunch anywhere.

NsisUpdater executes a `.exe` file with `--force-run` appended as a cmd line argument to open the app after it installs. AFAICT, there's no way for NSIS to install **and then** pass provided arguments to the launch of the app as its command line args. That's just how `.exe` installers work AFAIK. Please prove me wrong and I can work to implement this feature, but as it currently looks to be, it does not seem possible to do so.
https://github.com/electron-userland/electron-builder/blob/fc1381079499a091a1d4121a05ae0cf609690a32/packages/electron-updater/src/NsisUpdater.ts#L128-L141

As such, closing this as Not Planned unless someone can prove otherwise. Sorry to all that need this feature, as I do see it as something that would be useful
