### ISSUE TITLE
Error following documentation about Windows app signing under Mac

### ISSUE THREAD

**Issue by Aarbel** [electron-userland/electron-builder#3876]
Cf: https://www.electron.build/tutorials/code-signing-windows-apps-on-unix#signing-windows-app-on-mac-using-osslsigncode

On step 3. I've downloaded OpenSSL 1.1.1 tar.gz but got this error while running `./config --prefix=/usr/local/mac-dev && make && make install`

![image](https://user-images.githubusercontent.com/25119847/57228404-05c58b80-7014-11e9-9954-2b7a4e2330b4.png)
```
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Do you know how to fix it ? 

(i downloaded the last version of OpenSSL 1.1.1) 
![image](https://user-images.githubusercontent.com/25119847/57228484-30174900-7014-11e9-9cab-7a7165d2421c.png)

Thanks a lot for your help ! 👐

**Comment by Aarbel** [comment]
This documentation seems obsolete.

I code signed my app with electron-builder and this package.json (i also bought a sectigo cert which is the `build/myapp_sectigo_cert.p12` file

```JS
{
  "name": "myapp",
  "productName": "myapp",
  "version": "3.0.1",
  "description": "myapp",
  "author": "Team",
  "main": "main.js",
  "scripts": {
    "postinstall": "electron-builder install-app-deps",
    "start": "electron main.js",
    "pack": "build --dir",
    "dist": "build"
  },
  "build": {
    "appId": "desktop.myapp.app",
    "dmg": {
      "contents": [
        {
          "x": 110,
          "y": 270
        },
        {
          "x": 370,
          "y": 270,
          "type": "link",
          "path": "/Applications"
        }
      ]
    },
    "mac": {
      "category": "public.app-category.productivity",
      "extendInfo": {
        "CFBundleURLName": "myapp",
        "CFBundleURLSchemes": [
          "myapp"
        ],
        "NSUserNotificationAlertStyle": "alert"
      }
    },
    "linux": {
      "category": "productivity",
      "icon": "build/1024x1024.png",
      "target": [
        "AppImage"
      ]
    },
    "win": {
      "target": "nsis",
      "icon": "build/icons/win/icon.ico",
      "certificateFile": "build/myapp_sectigo_cert.p12",
      "verifyUpdateCodeSignature": true,
      "publisherName": "MYCOMPANY"
    }
  },
  "dependencies": {
    "electron-is-dev": "^1.1.0",
    "electron-updater": "^4.0.6",
    "electron-window-state": "^5.0.3",
    "howler": "^2.1.1",
    "node-notifier": "^5.4.0"
  },
  "devDependencies": {
    "asar": "^1.0.0",
    "electron": "^4.1.4",
    "electron-builder": "^20.39.0",
    "electron-packager": "^13.1.1",
    "electron-reloader": "^0.2.0"
  }
}

```

**Comment by danlester** [comment]
I also ran into problems signing Windows MSI files when building on Mac OS. I don't think the configuration suggested by @Aarbel changes things.

In any case, I also had problems building the latest osslsigncode binary so decided to use Docker and run osslsigncode within a Linux container. If you're going to start with this, it might make sense just to run the whole build in a container, but anyway, here is a solution for just plugging in a replacement for osslsigncode.

Place the following Python script as scripts/osslsigncode-docker.py:

```
#!/usr/bin/env python3

import sys
import re
import subprocess
from pathlib import Path

if __name__!= '__main__':
    print('Please run on the command line directly')
    exit()

p = Path(__file__)
subpath = p.resolve().parent.parent

print(subpath)

outsubpath = '/files'

regex = re.compile(r"^{0}".format(subpath))

outargs = list(map( lambda x: regex.sub(outsubpath, x) , sys.argv[1:]))

dockercmd = ['docker', 'run', '-v', f'{subpath}:{outsubpath}', 'sporsh/osslsigncode', 'sign'] + outargs

print(dockercmd)

subprocess.run(dockercmd)
```

And then make sure all relevant files are within your project folder so that Docker can map the volume needed just to be your project root (it won't be able to access a key file somewhere outside of this folder for example). Something like this as an npm/yarn run command:

`export SIGNTOOL_PATH=\"/Users/dan/Dev/project/scripts/osslsigncode-docker.py\"; export WIN_CSC_LINK=\"file:///Users/dan/Dev/project/electron-key.pfx\"; export WIN_CSC_KEY_PASSWORD=\"<password>\"; electron-builder -w`

Make sure docker daemon is running of course!

I hope this helps.

Dan
