### ISSUE TITLE
Packaged apps don't persist localStorage data anymore.

### ISSUE THREAD

**Issue by grantcv1** [electron-userland/electron-builder#3885]
* **Version**:  20.38.0

* **Electron-Updater**: 4.0.6

* **Target**:  Windows 10

window.localStorage in my views is not persisting between sessions in a packaged app. The localStorage works fine in the dev environmnent.

I upgraded to Electron 5.0.0 (from 4.1.5) and am able to confirm that localStorage was working fine in a packaged app after that upgrade. Next I upgraded electron-builder to 20.38.0 (from 19.55.3) and have had the problem ever since.

My understanding is that Chromium, since version 61, offloads the localStorage data to a persistent storage (See https://github.com/electron/electron/issues/12175) when the application closes. This has been problematic with Electron in the past -- but does seem to be working fine now in a dev environment. I'm guessing there is something different about how an application package with electron-builder closes and that it's not working correctly with Chromium in more recent versions of electron-builder.

**Comment by grantcv1** [comment]
Actually, it was working fine with electron-builder 20.15.0

**Comment by grantcv1** [comment]
The workaround is to set a persistent partition for the webview.

**Comment by grantcv1** [comment]
Problem seems to be caused by a lockfile left behind. Closing

**Comment by grantcv1** [comment]
It seems that there is a lock file in the leveldb folder of the AppData.

C:\Users\grantcv1\AppData\Roaming\LegisPro\Local Storage\leveldb

This lockfile gets created the first time an application is launched, but never goes away. When you reopen the application, the lockfile is not regenerated or updated in any apparent way, but everything works fine, except...

When you reinstall the application, then the presence of the lockfile seems to appear as a block preventing the reinstalled application from reading the local storage. Simply deleting the lockfile is all that is needed make the localStorage visible again. The application even gets visibility to the prior data stored in localStorage. As long as that old lockfile exists, the application will not read any persisted localStorage.

**Comment by Tonyce** [comment]
i am also confuse with the same problem;  "electron": "^4.1.4",    "electron-builder": "^20.40.2",

**Comment by vkolova** [comment]
The workaround did not work for me. Any news on this?

**Comment by lbudakov** [comment]
@vkolova 
Did you manage to resolve this?

**Comment by vkolova** [comment]
@lbudakov No. I tried everything I could think of, but still nothing.

**Comment by lbudakov** [comment]
@vkolova 
Ok, thank you, will write here if I find a workaround.

**Comment by lbudakov** [comment]
@vkolova
Are you sure the issue you have is with localStorage... I tough that i had issues with the storage after building the app, but it was an issue with redux and more specific with compose when I was configuring the store...
After removing compose for production builds, now all is ok.

**Comment by vkolova** [comment]
@lbudakov Yes. We are not using Redux. I'm simply reading a value from Local Storage. It works perfectly under development, but when build, after the application is restarted Local Storage is empty.

**Comment by reyraa** [comment]
I'm facing a similar issue. My observation is that after I upgraded the electron-builder, the app runs against a different instance of Chromium. I can confirm that since my devtools settings are different when I run the [old version](https://github.com/LiskHQ/lisk-desktop/releases/tag/v1.24.0) of my application compared to when I run the [new version](https://github.com/LiskHQ/lisk-desktop/tree/release-1.25.0).
Additionally, I see different sets of bookmarks (which uses localStorage) running the old or the new versions of the application.

**Comment by irissoftworks** [comment]
I am also facing this issue - storage works in development but not when packaged.

**Comment by kasugaicrow** [comment]
I see the issue's closed but with no response. I am facing this issue as well and I cannot figure out how to solve. Sometimes everything works fine but sometimes the application loses the localstorage data (that's because of what @reyraa said: `the app runs against a different instance of Chromium`).
Is there a way to avoid this behaviour? Can I make the app run always on the same instance of Chromium?

**Comment by Alecyrus** [comment]
Any updates?
