### ISSUE TITLE
Resources folder of app is owned by root, app can't access files because of permissions

### ISSUE THREAD

**Issue by chrisknepper** [electron-userland/electron-builder#3918]
* **Version**: 20.40.2

electron-updater: 4.0.6

* **Target**: .deb (Linux: Ubuntu 18.04)

Basically the exact same thing as #786, but it seems recent. On Ubuntu 18.04, installing my app from the .deb, the install directory `/opt/<app name>` is owned by root, as are all files within. This seems like a recent change. My app interacts with files under `/opt/<app name>/resources` such as CRUD operations. Again, seems the same behavior as in the issue from years ago.

Is it now intended behavior that files under the `resources` folder should be owned by root and have permissions such that the user the app runs as cannot perform CRUD operations on files within? If so, why does this only happen on Linux?

<img width="368" alt="permissions" src="https://user-images.githubusercontent.com/4976096/58220640-b18dfd00-7cdd-11e9-8b53-dd759a86f99d.png">

**Comment by alex-dow** [comment]
I have a similar issue. 

When running the built application, all is extracted into /tmp/.mount_[randomId] and everything in there is owned by root.

unfortunately, I have to start a service that is bundled by my application, but since the service is started by the user that started the application, it fails.

I'm not sure how to work around this without forcing a linux user to run the application as root.

**Comment by develar** [comment]
@alex-dow Please try 21.0.3

**Comment by alex-dow** [comment]
@develar unfortunately I can't do this quickly as I am using a plugin for the VueJS ecosystem that handles a lot of the boilerplate that comes with setting up a modern JS webapp these days.

Is there a workaround that does not involve upgrading?

**Comment by develar** [comment]
Duplicates #2682
