### ISSUE TITLE
Linux Snap Gets Wrong `app.getPath('userData')`

### ISSUE THREAD

**Issue by framerate** [electron-userland/electron-builder#3920]
* **Version**:  ^20.38.5

* **Target**: Linux Snap

```"linux": {
            "target": [
                "snap",
                "deb"
            ],
            "category": "Game"
        },
```

My snap (installed  via --dangerous) works fine except any reference to `app.getPath('userData')` is returning a value inside the snap, instead of the `~/.config/AppName/` like normal. Maybe this is expected behavior but my asset updater on every system downloads to `app.getPath('userData')`, I would expect snaps to be no exception?

**Comment by framerate** [comment]
I realize this could be an electron bug, I'm just trying to track it down. From Electron documentation:

```appData Per-user application data directory, which by default points to:

%APPDATA% on Windows
$XDG_CONFIG_HOME or ~/.config on Linux
~/Library/Application Support on macOS

userData The directory for storing your app's configuration files, which by default it is the appData directory appended with your app's name.```

So this implies that even on Linux I should be seeing `~/.config` and I'm not. Surely SOMEONE has experienced this before!

**Comment by AdrianoFerrari** [comment]
Apparently this is expected behavior for snaps:
https://forum.snapcraft.io/t/accessing-xdg-config-home-of-the-host/9780/7

(can't access hidden files/directories, can't access $XDG_CONFIG_HOME).

The response seems to be "just deal with it"... even though it seems counter-intuitive to me. Especially since reinstalling an app [doesn't automatically restore the settings](https://forum.snapcraft.io/t/removing-a-snap-also-removes-its-matching-users-configuration/17890)!

**Comment by framerate** [comment]
Thanks @AdrianoFerrari 

I'm glad I'm not the only one with this issue!
