### ISSUE TITLE
macOS 10.14.5 Security warning

### ISSUE THREAD

**Issue by JoshRiser** [electron-userland/electron-builder#3931]
* **Version**: 20.42.0

* **Target**: Tried default (.app), dmg, and pkg

I am having some issues getting our app to open on certain computers, and it seems to be linked to the latest macOS update (10.14.5). When someone on this version opens the app, whether it be a .app, .dmg, or .pkg file, they get this error. I'm fairly certain it's exclusive to this version, because any computer on 10.14.4 opens it fine.

![dmg-error](https://user-images.githubusercontent.com/1509348/58642510-856d1000-82cb-11e9-8340-f7e2f894f70e.png)

This image obviously refers only to the .dmg version, but we have had the same error on .app and .pkg versions.

The app is signed and our developer license is up to date. It was only purchased about a month ago, and the app has been working fine up until about last week.

I tried googling but couldn't find anything about this error. Also didn't see an open issue about it, so I'm not sure if it has anything to do with Electron Builder or not, but I can't seem to find a way to fix it.

**Comment by lane-c-wagner** [comment]
FYI this is being addressed in #3926 however there are still some bugs in the PR. If you want to take a look at what I'm doing as a hacky fix take a peek here: https://github.com/Q-Vault/qvault
Its working now except my app is crashing AFTER installation now at runtime due to some codesigning errors, so still trying to work that out.

**Comment by puresick** [comment]
@JoshRiser Starting with macos 10.14.5, Apple changed the requirements developers need to meet for an app to work: [https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution?language=objc](https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution?language=objc)

**Comment by linuxjuggler** [comment]
@lane-c-wagner I was able to build my app using your hacky way, and my application worked like a charm, the key for me was the `entitlements.mac.inherit.plist` without it, my app will crash but when I used it with only `com.apple.security.cs.allow-jit` and `com.apple.security.cs.allow-unsigned-executable-memory` it worked.

side note, it also worked using your `entitlements.mac.inherit.plist` file.

**Comment by puresick** [comment]
@linuxjuggler you may not need the `com.apple.security.cs.allow-jit` flag, because `com.apple.security.cs.allow-unsigned-executable-memory` does include the same functionality:

[https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_cs_allow-unsigned-executable-memory](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_cs_allow-unsigned-executable-memory)

**Comment by linuxjuggler** [comment]
nice, thanks @puresick for the note, I'll just test it right away 👍
