### ISSUE TITLE
Uncaught Error: spawn python3 ENOENT

### ISSUE THREAD

**Issue by blahafrank** [electron-userland/electron-builder#4008]
Hey,

I'm trying to use python shell with electron.

Everything works fine, when I'm running the app with `electron .`, but when I build it with `electron-builder` and run .app file, it doesn't work and console is giving me:

```
Uncaught Error: spawn python3 ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246)
    at onErrorNT (internal/child_process.js:429)
    at processTicksAndRejections (internal/process/task_queues.js:81)
```

Do anyone have this experience and know hove to solve it?

**Comment by develar** [comment]
Please [debug](https://electronjs.org/docs/tutorial/application-debugging). Looks like this error related to your app code. Maybe you need to disable asar.

**Comment by benjaminbaker-dev** [comment]
@blahafrank @develar 
Hey were you able to solve this ? I'm having the same issue with .app file on OSX.
I'm pretty sure it's related to PATH issues - because when I use python instead of python3 all is well. I tried to fix problem by editing /etc/paths and adding python3 but to no avail.
@develar - any ideas ? where does child_process.spawn() get PATH from ?
Thank you :)

**Comment by lavchandaria** [comment]
@benjaminbaker-dev Did you got the solution for this issue? I am facing the same problem.

**Comment by simondemeule** [comment]
@blahafrank @benjaminbaker-dev @lavchandaria 

I have faced the exact same issue today. After a good headache I figured it out, so I thought I'd share what I did:

- disabling ASAR — ASAR apparently doesn't play well with added resource files
- including the whole python virtual environment as a set of resource files, taking care to replace the default symlinked python binaries with a copy of them
- inspecting the built app's resources to verify all necessary files were present (on macOS, Show package contents > Contents > Resources > app; you can bring back the package.json from your original project and run `npm start` to confirm everything works as intended)
- applying `path.join(__dirname, filePath)` for all relative `filePath`; the file system of the built application does not work with plain relative paths. This applies to everything; the targeted python environment itself, the python file, and any files accessed from within the spawned process. In my case, since my python process reached for some included files and I didn't want to pass `__dirname` as an argument, I retrieved it from within python with `pathlib.Path(__file__).parent.absolute()` (this assumes the python file sits at the project root) 

I know this is probably an old problem no longer relevant to the authors, but hopefully this helps some future internet people.

**Comment by benjaminbaker-dev** [comment]
@simondemeule you rock dude!

**Comment by simondemeule** [comment]
@blahafrank @benjaminbaker-dev @lavchandaria

I figured the answer I gave actually contains some issues... Doing what I've highlighted will get you something that builds and runs fine on your own workstation, but that will fail to run in other environments. Simply packaging the Python environment into the app isn't sufficient. To get this working, I had to use pyinstaller to create an executable from my Python program, and then pack that executable into the app's resources.
