### ISSUE TITLE
Unable to find openssl?

### ISSUE THREAD

**Issue by brandoncc** [electron-userland/electron-builder#4088]
* **Version**: 21.0.11

* **Target**: nsis

  • cannot decode PKCS 12 data using Go pure implementation, openssl will be used  error=pkcs12: error reading P12 data: asn1: syntax error: indefinite length found (not DER)
  ⨯ Cannot extract publisher name from code signing certificate: exec: "C:\\Users\\brandoncc\\AppData\\Local\\electron-builder\\Cache\\winCodeSign\\winCodeSign-2.4.1\\openssl\\openssl.exe": file does not exist

---

For some reason, it has an issue with my p12 file. Building then fails due to a missing openssl binary that it seems is supposed to be downloaded by electron-builder in winCodeSign.

Is there a resolution for this?

**Comment by develar** [comment]
Fixed in 21.1.4

**Comment by brandoncc** [comment]
Thanks. I actually meant to update to the latest stable release before making this issue but somehow my update did not update that far. Sorry about that. Thanks again for the response and solution!

**Comment by brandoncc** [comment]
It worked perfectly, thanks again!

**Comment by ryanbadger** [comment]
For anybody else who ends up here with the **cannot decode PKCS 12 data using Go pure implementation, openssl will be used error=pkcs12: error reading P12 data: asn1: syntax error: indefinite length found (not DER)** issue: my scenario was my cert had expired and I bought a new one, for some reason this caused issues?

It seems to be fixed by setting publisherName in package.json under the win property:

"win": { "publisherName": "Click Here Digital Ltd", "target": [ { "target": "nsis", "arch": [ "x64", "ia32" ] } ] },

The publisherName MUST match the common name set in your code signing cert i believe. it seems this is required actually and should have been there before. @DalderupMaurice do you want to try adding this if you haven't already got it and see if it helps?

**Comment by laurent22** [comment]
I've just noticed I had this "cannot decode PKCS 12 data" error in my CI log for a while, but it seems it didn't prevent the app from being built or running properly. So I guess that's just a warning that can be ignored?
