### ISSUE TITLE
Windows zip auto update question

### ISSUE THREAD

**Issue by fxha** [electron-userland/electron-builder#4119]
* **Version**:  `21.1.1`

* **Target**: Windows `zip`

The documentation [says](https://www.electron.build/auto-update#auto-updatable-targets) that the only upgradable targets is NSIS on Windows but when building the `zip` archives for Windows both archives have the auto update resource file `app-update.yml` included. As of #919 it's not possible to specify files per target, so how can I distinguish between the NSIS and zip target at runtime? E.g. for the AppImage I can check whether the `app-update.yml` exist and don't show the update menu but on Windows the zip version downloads the NSIS setup and I cannot distinguish between the NSIS and zip target.

**Comment by AxelTerizaki** [comment]
I'd like this issue reopened, because I'm experiencing it as well.

I'm building both NSIS and zip and the zip version tries to auto-update itself with the setup exe for my app. It fails though, but it causes my app to crash with an unhandled rejection (I tried try/catching downloadUpdate() and other methods called, but to no avail)

Is there something we can do to disable auto-updates on zip versions?
