### ISSUE TITLE
[Feature Request] Linux build target

### ISSUE THREAD

**Issue by mbrainiac** [electron-userland/electron-builder#414]
Can you add options to select other build targets for linux? (tar, rpm, pacman...), default should be tar.gz not deb.

**Comment by develar** [comment]
Easy to do since we use fpm under the hood. Will be fixed soon

**Comment by develar** [comment]
`sh` (self-extracting installer), `rpm`, `freebsd`, `pacman`, `p5p`, `apk` (very, very slow), `7z`, `zip`, `tar.xz`, `tar.gz`, `tar.bz2`, `tar.7z` targets added.

We don't make `tar.xz` by default — because only package formats can setup icons, shortcuts. I don't test `rpm` and other.  Feel free to file issues for `rpm` and other package formats.

Maybe we should change default according to current linux distro.... well, feel free to file issues :) (i.e. distro name and desired behaviour).
