### ISSUE TITLE
The ELECTRON_BUILDER_BINARIES_MIRROR variable doesn't effect winCodeSign 

### ISSUE THREAD

**Issue by huxiaoxi1992** [electron-userland/electron-builder#4217]
* **Version**:  21.2.0

* **Target**: win x64 nsis

* **Environment**: gitlab-ce CI/CD -> image: electronuserland/builder:wine-mono

The electron-builder-binaries download slowly, I have hosted my own binaries mirror and added some environment variables due to [#3761](https://github.com/electron-userland/electron-builder/pull/3761).
![image](https://user-images.githubusercontent.com/17983389/64397615-76e58000-d094-11e9-95d2-e957c548ab70.png)

`winCodeSign` seems to be not effected by this variable.
![image](https://user-images.githubusercontent.com/17983389/64397655-91b7f480-d094-11e9-9bc0-5a6494ad0726.png)

Sometimes, it runs successful with the default url, is it possible to make `winCodeSign`  download from the mirror variable?
![image](https://user-images.githubusercontent.com/17983389/64397765-e22f5200-d094-11e9-9c25-e5ed73127455.png)

**Comment by OutgoingOpossum** [comment]
I can confirm this does not work with electron-builder@20.44.4 for target `platform=win32 arch=x64 electron=2.0.14`

I think this because the windows code sign routine uses `getBin()` directly

https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/src/codeSign/windowsCodeSign.ts#L14-L16

while other processes use `getBinFromUrl()`

https://github.com/electron-userland/electron-builder/blob/d738644d6e55b027c81e9b7cdd27dc5af9189b0a/packages/app-builder-lib/src/targets/MsiTarget.ts#L74

which seems to be a wrapper around `getBin()` adding support for the configuration variables in question.

**Comment by g4w** [comment]
FWIW this is also occuring for me using ``"electron-builder": "^21.2.0"``

I can work around the problem by by pointing ELECTRON_BUILDER_CACHE to a manually downloaded copy of winCodeSign, but having winCodeSign download sames as e.g. ``nsis`` would be better.

**Comment by hausenism** [comment]
^22.0.0 fix this.

**Comment by beckaberhanu** [comment]
From what I can tell, the reason nothing has been changed in this repo to fix this. As @OutgoingOpossum mentioned the windows code sign routine is still using `getBin()` directly:
https://github.com/electron-userland/electron-builder/blob/8bd1a10a2dcdee080e3b5a0359453d5d34b3ffbf/packages/app-builder-lib/src/codeSign/windowsSignToolManager.ts#L21-L23

I think the reason the `ELECTRON_BUILDER_BINARIES_MIRROR` has been working since ^22.0.0 is due to changes to another tool that electron-builder depends on that `get in ()` ultimately calls, namely  [app-builder](https://github.com/develar/app-builder). Here's the PR that enabled switching the base URL based on the  `ELECTRON_BUILDER_BINARIES_MIRROR` env variable: https://github.com/develar/app-builder/pull/19
