### ISSUE TITLE
icon setting is not working when windows portable target set 

### ISSUE THREAD

**Issue by perrywang** [electron-userland/electron-builder#4241]
* electron-builder version
21.2.0

* pack target
**Windows (portable)**: 

* problem
icon setting is not working the electron defaut icon is always used

**Comment by catdad** [comment]
I am seeing the same issue. I am building a prepackaged app (with `--prepackaged path/to/dir`), and `build.win.icon` in my package.json. I have both nsis and portable targets (and the prepackaged app already has an icon applied). The nsis installer does use the proper icon, but the portable executable has the old-school computer with CD icon. When I run the portable app, the correct icon is used in the taskbar (since that is the icon of the prepackaged app), but the portable exe seems to not have an option to set the icon.

**Comment by cbcruk** [comment]
Try using the icon property in package.json

```
"build": {
    "win": {
      "target": "portable",
      "icon": "build/icon.ico"
    },
  },
```

**Comment by Taconvino** [comment]
Can this be reopened?  I noticed that only the "small" icon is showing the old CD drive setup icon.  In larger views in Windows Explorer (extra large icons, large icons,medium icons) the correct image is being displayed.   Maybe it's just an issue with the icon file itself?

**Comment by jely2002** [comment]
I experienced the exact same issue, but managed to fix it by restarting explorer.exe. But I'm sure a pc restart works fine as well. This is not an issue with electron-builder, so no need to re-open this issue.
