### ISSUE TITLE
Build fails when multi-byte characters are used for productName

### ISSUE THREAD

**Issue by ponta555** [electron-userland/electron-builder#4306]
* **Version**: 21.2.0

* **Target**: mac/dmg

If multibyte characters are used for pacage.json.productName, a 7zip error will occur and the build will be interrupted.

```
  ⨯ Exit code: 1. Command failed: /Users/***/node_modules/7zip-bin/mac/7za a -bd -mx=7 -mtc=off -mm=Deflate -mcu /Users/***/dist/アプリ-0.0.1-mac.zip アプリ.app

WARNING: No more files
アプリ.app



7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,16 CPUs x64)

Scanning the drive:
0 files, 0 bytes

Creating archive: /Users/***/dist/アプリ-0.0.1-mac.zip

Items to compress: 0


Files read from disk: 0
Archive size: 22 bytes (1 KiB)

Scan WARNINGS for files and folders:

アプリ.app : No more files
----------------
Scan WARNINGS: 1
```

**Comment by KaminoRyo** [comment]
I have same problem. In addition, the signing of apps for macOS also fails.

If the cause is a multi-byte string filename, I may be able to solve it by applying "artifactName" property to the app filename.
 [productName].exe/.app cannot be changed.
This is because many people who use multibyte characters want to use English for file names. We know that multi-byte character string file names are often troublesome.😅

package.json
```
"name" : "application",
"version" : "1.0.0"
```

electron-builder.json
```
"productName" : "アプリケーション",
"artifactName": "${name}-${version}.${ext}"
```

I hope to build "application-ver1.0.0.exe(.app)".

**Comment by guycalledseven** [comment]
this should not be closed, this issue still exists in 2020.

**Comment by feugy** [comment]
I confirm this is an issue as long as your productionName contains non-ASCII character (my application is named `Mélodie`).
Changing artifact name doesn't fix it, because the culprit is the the app file:
```bash
```

**Comment by sr258** [comment]
Did anyone solve this? This issue seems to be unfixed in Sept 2021.

**Comment by sr258** [comment]
I was able to fix the build issue by replacing the 7za file with a much newer version of 7zip from here: https://www.7-zip.org/download.html?utm_source=pocket_mylist The icon is still broken though and the dmg file is misaligned visually.
