### ISSUE TITLE
Windows installer

### ISSUE THREAD

**Issue by simonlast** [electron-userland/electron-builder#437]
The windows output seems to export a folder with a bunch of files, including a .exe. What is the recommended way to distribute this? I tried zipping the whole folder and that seemed to work, but when I tried just the .exe it threw an error.

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder#in-short step 4 "And then you can run npm run pack or npm run dist (to package in a distributable format (e.g. dmg, windows installer, deb package)). Both scripts are the same because If script named dist or name has prefix dist:, flag --dist is implied."

Related: https://github.com/electron-userland/electron-builder/issues/413

**Comment by VerteDinde** [comment]
@develar So sorry to comment on an old issue, but I'm having a similar problem and it looks as though the docs and functionality has changed somewhat since this issue was opened. 

Context: My Mac build is working perfectly, but the Windows build is only producing the .exe file and a `win-unpacked` full of files - no .nupkg or others.
Version: `electron-builder: 19.12.0`

Thanks so much!

**Comment by develar** [comment]
Default target now is nsis, not Squirrel.windows

**Comment by VerteDinde** [comment]
@develar Gotcha! Sorry, just to clear, is the output of the NSIS target only an .exe file, or also an .msi and .nupkg? 

I'm trying to generate an .msi specifically, but am having trouble doing so through the NSIS target. I had read through the NSIS target docs here (https://www.electron.build/configuration/nsis), but couldn't find the value to pass in. I had tried both "noMsi: false" and "msi: true" and both threw errors. 

Thanks so much! I really like your tool and would be happy to make a docs PR. :)
