### ISSUE TITLE
file permission errors in updater with 22.1.0

### ISSUE THREAD

**Issue by Kilian** [electron-userland/electron-builder#4435]
* **Version**: 22.1.0
* **electron-updater**: 4.2

* **Target**: mac and windows

Both Mac and Windows seem to give issues updating because of file permissions (or timing?) using the above combination.

Mac:
```
Error: ENOENT: no such file or directory, rename '/Users/admin/Library/Application Support/Caches/polypane-updater/pending/temp-Polypane-2.0.1-mac.zip' -> '/Users/admin/Library/Application Support/Caches/polypane-updater/pending/Polypane-2.0.1-mac.zip'
```

Windows:
```
Error: EPERM: operation not permitted, open 'C:\Users\admin\AppData\Local\polypane-updater\pending\temp-Polypane-Setup-2.0.1.exe'
```
Followed by 
```
Error: ENOENT: no such file or directory, rename 'C:\Users\admin\AppData\Local\polypane-updater\pending\temp-Polypane-Setup-2.0.1.exe' -> 'C:\Users\admin\AppData\Local\polypane-updater\pending\Polypane-Setup-2.0.1.exe'
```

**Comment by Kilian** [comment]
it's still relevant.

**Comment by BradleyDeLar** [comment]
It appears that after years of this issue being reported there is still no solution. Is that correct?

**Comment by ert78gb** [comment]
Hi @develar,

First of all, I don't like to comment on the closed issue, but it is still a problem on Linux AppImage and maybe on windows. I still have to investigate the windows issue.

I reviewed the [AppImageUpdater.ts](https://github.com/electron-userland/electron-builder/blob/master/packages/electron-updater/src/AppImageUpdater.ts),[FileWithEmbeddedBlockMapDifferentialDownloader](https://github.com/electron-userland/electron-builder/blob/7b335dbd7e5ca754598ca93318be1404fc518485/packages/electron-updater/src/differentialDownloader/FileWithEmbeddedBlockMapDifferentialDownloader.ts#L6) and I recognised you use the `fs-extra.close` to close the file descriptor, but `fs-extra.close` is not gurantad the OS finished the I/O operations. See in [close(2)](https://man7.org/linux/man-pages/man2/close.2.html) documentation.

> A successful close does not guarantee that the data has been
  successfully saved to disk, as the kernel uses the buffer cache to
  defer writes.  Typically, filesystems do not flush buffers when a
  file is closed.  If you need to be sure that the data is physically
  stored on the underlying disk, use [fsync(2)](https://man7.org/linux/man-pages/man2/fsync.2.html).  (It will depend on the
  disk hardware at this point.)

`fs.fsync` available in the node.js

I would like to suggest to use `fs.fsync` instead of `fs.close`. If you agree with me then I am opening a PR about it in the updater package.

In this case, we can fix `chmod` tries to run on file that not closed by the OS issue.

**Comment by ert78gb** [comment]
`fsync` is not a solution. I found the problem in our code.
The `autoUpdater.autoDownload` true by default. That's mean the download process starts automatically. If you also start the download manually it starts a new update and the 2 thread collide.
If you would like to manage the start the update manually then set `autoUpdater.autoDownload = false`

**Comment by douglassllc** [comment]
We do set `autoUpdater.autoDownload = false` and use the `autoUpdater.downloadUpdate()` and still receive this error:

`EPERM: operation not permitted, open 'C:\Users\<user>\AppData\Local\trackops-updater\pending\0-temp-<app>-win.exe'`

**Comment by liuestc** [comment]
same question, I cancel  download third times ,the fouth time will be failed!

```
Error: EPERM: operation not permitted
```

**Comment by MahmoudMousaHamad** [comment]
@douglassllc Have you found a solution to this problem?

**Comment by douglassllc** [comment]
> @douglassllc Have you found a solution to this problem?

@MahmoudMousaHamad The only solution has been to notify the user that one of the following is most likely blocking the auto application updater:

1.  Anti-Virus/Malware software
2. Microsoft policy restriction

I have not found a software work around for this issue.  I would like to understand how some of the larger Electron applications have avoided this issue? (i.e. MS VScode, GitHub Desktop, Amazon Music Player, Postman, etc.)

**Comment by douglassllc** [comment]
@MahmoudMousaHamad I will give your recommendation a test.  Thank you for the recommendation.
