### ISSUE TITLE
No way to know if the app was signed in the afterSign hook

### ISSUE THREAD

**Issue by cslecours** [electron-userland/electron-builder#4452]
Which version of electron-builder are you using?

*  *electron-updater*: "4.2.0"
*   *electron*: "6.1.4"
*   *electron-builder*: "21.2.0"
*   *electron-notarize*: "0.2.0"

* **Target**: MacOS Catalina

In the afterSign hook, there is no way to know if the app signing was successful or not. If it's not successful, I don't want to run the notarize process.

The info is not available in the packContext.
https://github.com/electron-userland/electron-builder/blob/b83f5801771585c18524c3cee74e59de5fa9ab30/packages/app-builder-lib/src/platformPackager.ts#L243-L248

**Comment by kzimny** [comment]
When the notarization was not successful you should get an error in the console in catch block:
```
const fs = require('fs');
const path = require('path');
var electron_notarize = require('electron-notarize');

module.exports = async function (params) {
    // Only notarize the app on Mac OS only.
    if (process.platform !== 'darwin') {
        return;
    }
    console.log('afterSign hook triggered', params);

    // Same appId in electron-builder.
    let appId = 'org.mycompany.myapp'

    let appPath = path.join(params.appOutDir, `${params.packager.appInfo.productFilename}.app`);
    if (!fs.existsSync(appPath)) {
        throw new Error(`Cannot find application at: ${appPath}`);
    }

    console.log(`Notarizing ${appId} found at ${appPath}`);

    try {
        await electron_notarize.notarize({
            appBundleId: appId,
            appPath: appPath,
            appleId: 's',
            appleIdPassword: '',
        });
    } catch (error) {
        console.error(error);
    }

    console.log(`Done notarizing ${appId}`);
};
```

**Comment by rbenet-lbo** [comment]
I actually was trying also to achieve the same thing. Anybody has an answer by now ?

I don't always want to sign my app (eg. on some CI builds) and in those cases I cannot run 'notarize' flow, because it will fail. 
Ideally the notarise script would only be called when the file was actually signed (not just after the sign phase). But I haven't figured out how to do that.
Second best, is that notarise script autodetect there was no signature and does not attempt to notarise the app.
