### ISSUE TITLE
install-app-deps builds grpc from source

### ISSUE THREAD

**Issue by v-morlock** [electron-userland/electron-builder#4518]
* **Version**: 1.4.0

* **Target**: Windows

Hello! 

When trying to install "grpc", `electron-builder install-app-deps` always seems to build grpc from source. When doing `npm rebuild --target=7.0.0 --runtime=electron --dist-url=https://atom.io/download/electron`, npm is downloading the prebuilt binaries. 
I set `buildDependenciesFromSource` to false, so i expected electron-builder to show the same behaviour as npm. 

Do you have any hints on that?

<!-- Enter your issue details below this comment. -→
<!-- If you want, you can donate to increase issue priority (https://www.electron.build/donate) -→

**Comment by v-morlock** [comment]
Closing it myself as it was caused by using electron 7.1.2 where no prebuild-binary seems to exist.

**Comment by eschirtz** [comment]
@v-morlock How did you solve this problem?

I am running on electron 6.0.0, so I believe there are binaries for gRCP. 

I was getting super long `yarn` times, seemingly caused by the `electron-builder install-app-deps` post install script rebuilding gRCP.

As you know gRCP recommends you do not rebuild from source as it already has its own binaries. 

When I remove the postinstall script completely my `yarn` (~ `npm instal`l) step takes a normal amount of time. And my electron project works fine. However I am apprehensive to remove the post install script entirely, just incase some other packages may actually need to be rebuilt. 

Is there a way to blacklist `gRCP` to not be rebuilt with the `install-app-deps` command?

Thanks!
