### ISSUE TITLE
How to only publish?

### ISSUE THREAD

**Issue by cawa-93** [electron-userland/electron-builder#4535]
* **Target**: any

In my workflow, I have to build an application, then test it, and ONLY then publish it.
To build an application without publishing, I use the command
```
electron-builder -p never
```

But how can I **only publish**? I already have an builded application and want to publish it. How can I do this. Is there any custom parameter to skip compilation and just publish the assembly. Something like this:

```
electron-builder --prebuilded <build dir> -p always
```

**Comment by hgouveia** [comment]
i am also interested in this functionality , i already has the installer using `--publish never` but now in later stage i want to publish it to S3, but without rebuilding it, i would like something `--distrib ./build/myinstaller.exe --c.publish.channel=channel`

**Comment by cawa-93** [comment]
@develar Is there a chance that this issue will be considered?

**Comment by MutableLoss** [comment]
The project I manage would really benefit from such a feature, as I also use a local build routine (build -> test -> publish), uploading to GitHub.

I build to 4 different targets, so I lose a significant amount of time with each app release because of the extra time taken to build during publishing. While I am planning to switch to a TravisCI setup (for this exact reason), I can still see where this feature could save a lot of time in the build process for myself and many others.

In regards to such a feature, is there a particular concern with adding an option to the publish to use the existing dist build (when available), or maybe an issue or concern specific to electron-publish?.

**Comment by cinan** [comment]
this issue should be reopened

**Comment by MutableLoss** [comment]
Can any of the maintainers add their thoughts on this addition? At the very least, can someone explain why this hasn't received any attention in the past? 

**I'm willing to dig into this myself, but I'll be honest, I don't want to waste my time if there are legitimate concerns.**

**Comment by mspoerer** [comment]
+1

**Comment by RobertLowe** [comment]
This would be a good workflow add. I typically want to review my build after building, but might not be ready to publish it, if I decide I am, I don't want to necessarily wait for the build time again.

**Comment by fgu-neo-soft** [comment]
Really a must have for my project too !
Please reopen 👍

**Comment by mmaietta** [comment]
I thought that was what `--prepackaged` configuration was supposed to provide.
Or are you requesting a way to do it after all processes, just using electron-publish?

> Can any of the maintainers add their thoughts on this addition? At the very least, can someone explain why this hasn't received any attention in the past?
> 
> **I'm willing to dig into this myself, but I'll be honest, I don't want to waste my time if there are legitimate concerns.**

My best guess is that only develar was maintaining the project at the time and didn't have time to get to this feature request.

I have no concerns from my side.

**Comment by MutableLoss** [comment]
Thanks @mmaietta !

Exactly to the latter. At the moment there isn't an optimal way to test builds in a publish workflow without having to publish multiple times, or build multiple times. One idea was to reuse the build used for testing with the publish, and remove an additional build process.

**Comment by suan** [comment]
Same here! Need this functionality

**Comment by MutableLoss** [comment]
How was this resolved, if at all?

**Comment by MutableLoss** [comment]
So if this isn't resolved, why has it been closed? Is it a feature that's not feasible?

**Comment by mmaietta** [comment]
It's not feasible with the current logic flow.

Happy to accept a community contribution if someone else is willing to investigate. Looks like a good start would be extracting much of the Provider logic to the `electron-publish` repo to externalize an API for this "only publish" functionality.

**Comment by MutableLoss** [comment]
Ok great, and absolutely! Thanks for the clarification, I definitely wanted to make sure this was something feasibly inline with the project before doing anything else. I'll try to carve out some time for this soon. Cheers 🙌

**Comment by pelletier197** [comment]
I figure this wasn't added since 2022 ? I have the same requirement, because I have a previous step in my pipeline that signs the executables produced by electron. I absolutely have to upload those executables when publishing, I cannot build them again. 

I don't mind doing the manual publish to keygen, but why this is closed if this is such a common use-case?

**Comment by mmaietta** [comment]
I'll see if I can take a stab at this when I find some free time

**Comment by mmaietta** [comment]
Created a draft PR https://github.com/electron-userland/electron-builder/pull/8150 with the following functionality. Still testing locally and trying to get some automated tests set up

Proposed solution
- `electron-builder publish -f <filepath> -f <filepath2>`
   - It should allow you to configure `publish` directly via electron-builder.js config. Note, it only can access the global `publish` config, not any nested ones within a specific arch/target since the files provided don't have an associated arch/target.
- Two APIs are available for the JS-approach configuration file. The latter allows an explicit array of PublishConfiguration for a more fine-grain approach when using
```
const electronBuilder. = require('electron-builder')

electronBuilder.publish(args: { files: string[] }
// OR
electronBuilder.publishArtifactsWithOptions(uploadOptions: { file: string; arch: string | null }[], publishConfiguration?: PublishConfiguration[])
```

These internally create `UploadTask`s. 
https://github.com/electron-userland/electron-builder/blob/8160363ac2821242ab22e225a9038b56e4798cc6/packages/electron-publish/src/publisher.ts#L29-L36
`safeArtifactName` is calculated internally since it seems Github requires some funky logic.
https://github.com/electron-userland/electron-builder/blob/8160363ac2821242ab22e225a9038b56e4798cc6/packages/app-builder-lib/src/platformPackager.ts#L741-L756

Please provide your thoughts and I'll try to incorporate them. Will likely need volunteers to test this feature in their project configurations as well

**Comment by pelletier197** [comment]
Sounds awesome. Thanks a lot for this!

**Comment by mmaietta** [comment]
Released in [v25.0.0-alpha.6](https://github.com/electron-userland/electron-builder/releases/tag/v25.0.0-alpha.6)

Please give it a shot! It worked well with my mock S3 uploads (minio server) but would like to hear the results of it being used in the wild. Happy to make iterations on the implementation as needed

Looks like I forgot to update the CLI doc files, so I'll get to that next. 

CLI is as follows
```
electron-builder publish -f <filepath> -f <filepath2> -v <buildVersion (if needed) -c <config file>
```
Only `-f`/`--files` are required, but depending on your publish target or custom config filename, you may need to provide the other args.

API:
```
const electronBuilder = require('electron-builder')

electronBuilder.publish(args:  { files: string[]; version? string; config?: string })
// OR
electronBuilder.publishArtifactsWithOptions(uploadOptions: { file: string; arch: string | null }[], buildVersion: string?, configurationFilePath?: string, publishConfiguration?: Publish)
```

**Comment by seanssel** [comment]
@mmaietta I'm probably missing something, but when I try to use this with a js config that extends a base config I get an `unable to find any publish configuration` error.

E.g. I have an `electron-builder-common.js` config without a publish configuration. My `electron-builder-staging.js` config extends common and has a publish configuration at the top level.

**Comment by mmaietta** [comment]
Please open a new issue for your request since this issue is already resolved.

Without much info to go on, my best guess is that your CLI invocation of the publish command is not pointing to the config with the `-c path/to/electron-builder-staging.js`. Nonetheless, please open a new Github issue and follow the issue template to include the necessary relevant data.

**Comment by choegyumin** [comment]
This issue has been resolved, but I'm leaving this here for anyone searching for related keywords. (This page comes up first in Google search results)

- New issue reported by @seanssel 
  - https://github.com/electron-userland/electron-builder/issues/9005
- PR that resolved the above issue
  - https://github.com/electron-userland/electron-builder/pull/9227
- PR that added the `--policy` option to the 'publish' command to set the trigger (e.g., 'always', 'onTagOrDraft', …)
  - https://github.com/electron-userland/electron-builder/pull/9228
