### ISSUE TITLE
signWithParams on Windows

### ISSUE THREAD

**Issue by ccnokes** [electron-userland/electron-builder#454]
I recently upgraded from electron-builder 3.16 to 3.25.0 and just realized that my Windows code signing is no longer happening. This looks like an API change.

My `build.win` looks like:
```json
"win": {
      "certificateFile": "Certificates.p12",
      "signWithParams": "/a /t http://timestamp.digicert.com /sha1 xxxx",
}
```
It looks like these properties are no longer used and that global env vars like `CSC_LINK ` are used instead. 

So, my question is: how do I pass params to the Windows code sign now? I'm not seeing a way to sign it with parameters in the new version.

node -v5.1.1
npm -v 3.3.12
Windows 10

**Comment by bontibon** [comment]
Duplicate #449

**Comment by ccnokes** [comment]
Thanks @bontibon. I'll track your issue.

**Comment by develar** [comment]
`CSC_LINK`

**Comment by develar** [comment]
> signWithParams

Is not supported because on Linux we use another tool to sign. And please note — now we sign using timestamp and sha1/sha256 dual by default.

> certificateFile
Please use `CSC_LINK` (you can set it to base64 data of file). If it is not suitable for you, we can add support for file param (but! on OS X we use keychain and, maybe, on Windows also there is such system store?).

**Comment by develar** [comment]
Duplicates #449
