### ISSUE TITLE
App crashes after com.apple.security.app-sandbox true added

### ISSUE THREAD

**Issue by j1exus** [electron-userland/electron-builder#4567]
electron-builder:
* **21.1.0**: 

target:
* **mas**: 

I'm trying to build mas target and upload to mac store.

Without com.apple.security.app-sandbox true in entitlements.mas.plist and entitlements.mas.inherit.plist .app from /mas/ folder launches successful.

**Comment by danutzcodrescu** [comment]
same thing here. If I do not provide any entitlements it works fine locally (and ofc it is refused by Apple) because it uses the template residing in `/node_modules/app-builder-lib/templates/entitlements.mac.plist`. However, if I add `com.apple.security.app-sandbox` like it was suggested as a workaround in this [issue](https://github.com/electron/electron-osx-sign/issues/192), the app crashes on start.

**Comment by ronghester** [comment]
I am facing similar issue if "com.apple.security.app-sandbox" is added in entitlements (any parent or child) then the app just crashes. If i don't include this then app runs fine. Please note it is not at all related to signing, the app runs fine even signed or unsigned. Basically without app-sandbox the app can't be uploaded to mac store so basically its a blocker.

**Comment by ahmadwaliesipick** [comment]
I am facing same issue anyone has resolved this issue?

**Comment by serdarde** [comment]
Hey @ahmadwaliesipick, did you solve this issue?
