### ISSUE TITLE
Need to clear cache and restart system, after each build

### ISSUE THREAD

**Issue by anubhav04** [electron-userland/electron-builder#4633]
* **Version**: **20.28.4**

* **Target**:  **Macintosh**

Every time I am making update to my application(HTML application running on node-static server), after building, I have to clear the application cache and restart my system to see the applied changes on the build. Is there any option to clear the application cache before/after installation of the new build.

**Comment by checho221** [comment]
Same here, "electron-builder": "^20.43.0"

I can get a fresh version renaming the "name" in package.json, this is not the best option because could be installed twice, while if it is the same name it just refresh version in the system info but unfortunately it does not contain the most recent changes.

I found this 2 recomendations 

`loginWindow.webContents.session.clearStorageData()`
`loginWindow.webContents.session.clearCache(function(){
//some callback.
});`

But i not sure if it works for me, my issue is not with cookies or local storage, my issue is even with files, i am requiring a file and if i change it, it wouldn't be updated in build

I would appreciate any help

**Comment by dodistyo** [comment]
> * **Version**: **20.28.4**
> 
> * **Target**:  **Macintosh**
> 
> Every time I am making update to my application(HTML application running on node-static server), after building, I have to clear the application cache and restart my system to see the applied changes on the build. Is there any option to clear the application cache before/after installation of the new build.

did you solve the issue ?

**Comment by raghu20ram** [comment]
I had the same issue and was able to solve it by deleting the **.cache** folder inside node_modules. I guess the main.js is being cached here. This can be added to the build process by updating the package.json file.
