### ISSUE TITLE
Postinstall electron-builder not working

### ISSUE THREAD

**Issue by pazfelipe** [electron-userland/electron-builder#4660]
I have an application built with quasar(vuejs), electron and sqlite3. I cannot rebuild my electron application when I use postinstall.

```
{
  "name": "linux",
  "version": "0.0.1",
  "description": "A Quasar Framework app",
  "productName": "Quasar App",
  "cordovaId": "",
  "capacitorId": "",
  "author": "Felipe Paz <xxfelipepaz@gmail.com>",
  "private": true,
  "scripts": {
    "lint": "eslint --ext .js,.vue src",
    "test": "echo \"No test specified\" && exit 0",
    "postinstall": "electron-builder install-app-deps"
  },
  "dependencies": {
    "@quasar/extras": "^1.0.0",
    "axios": "^0.18.1",
    "quasar": "^1.0.0",
    "vue-i18n": "^8.0.0"
  },
  "devDependencies": {
    "@quasar/app": "^1.0.0",
    "@vue/eslint-config-standard": "^4.0.0",
    "babel-eslint": "^10.0.1",
    "devtron": "^1.4.0",
    "electron": "^7.0.0",
    "electron-builder": "^22.3.2",
    "electron-debug": "^3.0.0",
    "electron-devtools-installer": "^2.2.4",
    "eslint": "^5.10.0",
    "eslint-loader": "^2.1.1",
    "eslint-plugin-vue": "^5.0.0"
  },
  "engines": {
    "node": ">= 10.18.1",
    "npm": ">= 6.13.4",
    "yarn": ">= 1.21.1"
  },
  "browserslist": [
    "last 1 version, not dead, ie >= 11"
  ]
}
```

And this is the error message when I try to run postinstall
```%error
Cannot compute electron version from installed node modules - none of the possible electron modules are installed
```
And yes, I've already removed node_modules and reinstall the dependencies again and even so it does not work.

**Comment by kzimny** [comment]
can you build your app with temporary deleted postinstall line from package.json?

**Comment by felixplum** [comment]
Hi,

I'm currently facing the same issue. To mitigate above error, I added a preinstall-script that adds electron as a dev-dependency to `dist\electron\UnPackaged\package.json`. While that fixes the error and allows me to build the application, on application start I'm getting a new error message "Cannot find module webpack..". I'm not sure whether this is caused by my workaround.

The easiest way to figure this out would be to pass a version flag to `electron-builder install-app-deps`, which is currently not accepted.

Looking forward to ideas on how to resolve this issue,
Felix
