### ISSUE TITLE
Please bring back the appimage's systemIntegration feature

### ISSUE THREAD

**Issue by viankakrisna** [electron-userland/electron-builder#4670]
i have an app that's recently need to upgrade to electron 7 from electron 2, which also means that i need to use the newer electron-builder, and quite puzzled by the decision to remove this feature on 21.x.x

i think the removal of appimage's systemIntegration is premature. until we have AppImageLauncher, AppImageUpdate, or appimaged is included in major linux distribution, the ux of appimages has worsen. previously the user just need the .appimage to install the app, now they also need to install these other software to have a nice ux. Is there any way we could bring back the systemIntegration without downgrading to earlier version?

the only way i can think right now to do is patch-package the electron builder to bring this feature back, and i'm not too familiar with the code base, which means i need to spend more time to learn it... anyone could point me to the direction on how to bring it back? i have tried restoring the schema.json on app-builder-lib to include the systemIntegration back, but it seems the actual code is already gone from the master branch, anyone knows on which commit that it's actually removed?

**Comment by viankakrisna** [comment]
yes it is

**Comment by AdrianoFerrari** [comment]
I agree wholeheartedly with this. I don't really care what technical solution is used, as long as it means that AppImage can be integrated in user's system without them having to jump through any hoops or install anything extra.

I've even started **using my own app less often** because I moved to a new laptop (19.10) and haven't gotten around to creating a desktop file, or installing AppImageLauncher :slightly_frowning_face: .
