### ISSUE TITLE
Code signing for MacOS works in SSh session, but not in Jenkins CI

### ISSUE THREAD

**Issue by vitalykarasik** [electron-userland/electron-builder#4683]
* **Version**:  22.3.2

* **Target**:  MacOS

My build includes code signing and notarization. Works nice in SSH session, fails in Jenkins CI with:
Any ideas?

` > Identity: {
name: 'Developer ID Application: XXXXXX  Technologies Ltd (XXXXXY2C)',
hash: 'xxxxxxxxxxxx2B6E68'
}
electron-osx-sign Walking... /Users/jenkins/build/workspace/build/mac/xxxxe.app/Contents
electron-osx-sign Signing... /Users/jenkins/build/workspace/build/mac/xxxxxxe.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
electron-osx-sign Executing... codesign --sign xxxxxxxxx12B6E68 --force --keychain /tmp/465cb35e5118c40bc576ed5cfe2207aed7194256a8804498d9a09ba17894a6dd.keychain --options runtime --entitlements entitlements.mac.plist /Users/jenkins/build/workspace/mac/xxxxxx.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
electron-osx-sign Error executing file:
Stdout:
Stderr: error: The specified item could not be found in the keychain.`

UPDATE: with DEBUG=code-builder I see that builder *removes* keychain file before looking for the key:

`executing       file=security args=delete-keychain /tmp/465cb35e5118c40bc576ed5cfe2207aed7194256a8804498d9a09ba17894a6dd.keychain
executed        file=security
Command failed: codesign --sign B6AEB2764D5F34709D0B40E803124C36D12B6E68 --force --keychain /tmp/465cb35e5118c40bc576ed5cfe2207aed7194256a8804498d9a09ba17894a6dd.keychain --options runtime --entitlements entitlements.mac.plist /Users/jenkins/build/workspace/ci_build_fixes/build/mac/xxxxx.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
error: The specified item could not be found in the keychain.`

**Comment by vitalykarasik** [comment]
yes, it's relevent.

**Comment by pietersartain** [comment]
I ran into this problem recently and @vitalykarasik's issue and [associated StackOverflow question](https://stackoverflow.com/questions/60286559/code-signing-for-macos-works-in-ssh-session-but-not-in-jenkins-ci) was the only hit I got that matched my error message. I haven't solved this problem so much as worked around it (see at the bottom of this post for our workaround), but I wanted to make sure my findings were available for anyone else searching.

# Project setup

 - CRA (4) + Electron (12) + Electron builder (22.10.5) in a single-package structure.
 - Attempting to include a ~10mb compiled binary via extraResources or extraFiles as part of the packaging step.
 - Using a self-managed CI pipeline made of Gitea + Drone.io with the SSH Runner.

# Problem

 - Running electron-builder locally on Windows -- success
 - Using Docker Runner to build and package an installer -- success
 - Running electron-builder locally on MacOS -- success
 - Using SSH Runner to drive MacOS to run electron-builder *without the binary* -- success
 - Using SSH Runner to drive MacOS to run electron-builder -- **failure**

What's different about using Drone to building by hand?

Mostly the environment. DroneSSH uses a custom HOME directory and isolated PATHs, for good reasons.
https://discourse.drone.io/t/solved-local-environment-not-available-in-ssh-pipeline/8637

## Error message

```
  • signing         file=dist/mac/my.app identityName=Developer ID Application: xxx identityHash=xxx provisioningProfile=none
  • spawning        command=/private/tmp/drone-TuVx6f3Ouq2D5Xiw/drone/src/node_modules/app-builder-bin/mac/app-builder decode-plist -f ./assets/entitlements.mac.plist -f /private/tmp/drone-TuVx6f3Ouq2D5Xiw/drone/src/dist/mac/my.app/Contents/Info.plist
  • map async       taskCount=2
  • exited          command=app-builder code=0 pid=38333 out=[...]
  • executing       file=security args=delete-keychain /var/folders/85/lv8tk4916z57rvmqml1f60g00000gn/T/e4aaa1a5eb81130ee625cded684f7a4bc54f6c077869638622f01e8584179c1f.keychain
  • executed        file=security
  ⨯ Command failed: codesign --sign xxx --force --keychain /var/folders/85/lv8tk4916z57rvmqml1f60g00000gn/T/e4aaa1a5eb81130ee625cded684f7a4bc54f6c077869638622f01e8584179c1f.keychain --timestamp --options runtime --entitlements ./assets/entitlements.mac.plist /private/tmp/drone-TuVx6f3Ouq2D5Xiw/drone/src/dist/mac/my.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Helpers/chrome_crashpad_handler
error: The specified item could not be found in the keychain.
```

To save scrolling, that last line looks like this:
`  ⨯ Command failed: codesign --sign xxx --force --keychain /var/folders/85/lv8tk4916z57rvmqml1f60g00000gn/T/e4aaa1a5eb81130ee625cded684f7a4bc54f6c077869638622f01e8584179c1f.keychain --timestamp --options runtime --entitlements ./assets/entitlements.mac.plist /private/tmp/drone-TuVx6f3Ouq2D5Xiw/drone/src/dist/mac/my.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Helpers/chrome_crashpad_handler`

It was *always* chrome_crashpad_handler that would fail if I included the extra binary.

Tracing the path in the electron-builder code, it looks like the `delete-keychain` command is run in a finally block as a cleanup step. When I wrote a test script (create keychains, sign things, delete keychains, verify signatures, etc) I could only get this error to appear from `codesign` when the signing identity wasn't in the chain (eg after the keychain had just been created before the identity was added, or after the keychain had been removed).

## Things tried

Some of these now look much more like I was grasping at straws than I felt like I was at the time.

 * Symlinking the library directory (https://discourse.drone.io/t/exec-runner-support-for-xcode-projects/5895) -- no change
 * Unlocking the login keychain (I saw a few references to locked login keychains and default search order in MacOS causing this problem) -- no change
 * Big Sur 11.2 + Catalina 10.15.7 -- no difference
 * Removing `extends: react` for `extends:  null` and building into a separate folder (not build) -- no difference
 * Building a test app to create keychain and sign things -- synchronously worked fine, but did require symlinking the library directory as above.

## Things that could be tried in the future

 * Unsetting process.env.CI / futzing with other environment variables to get it to fail without Drone.
 * Running in Github actions (does it interact with MacOS differently?)
 * Trying older versions of electron-builder with different auto-binary detection code (I saw a few references to this, not sure if it'd actually make a difference without more research)

## Things I did not and can no longer investigate / check

 * Checking if I had Yubikey installed (https://stackoverflow.com/questions/54022972/codesign-keychain-issues-after-data-migration-the-specified-item-could-not-be) -- I do own a Yubikey, so this wasn't complete unreasonable.
 * I don't have my original Big Sur environment where things were failing to test on, but the error has been the same in Catalina. I reinstalled and rolled back to Catalina to double check there wasn't anything strange going on with my environment.

# Current state

I'm currently of the opinion that some combination of the CI build flag, the way Drone's SSH runner (and probably others, like Jenkins) interacts with the Mac and even the Mac keychain tools themselves is tripping up electron-builder under certain circumstances - for me that's including an extra binary in the package.

I can see this being a very niche edge case where many things are coming together to cause this problem (which is why I only had one hit for the error ... ).

# Workaround

Like Vitaly before me, I ended up side-stepping the problem by replacing the Drone SSH runner with a Docker containing that would run SSH for me and a script that could be run automatically after shelling into the Mac. This doesn't look like a CI environment, (process.env.CI isn't set) but everything signs (and notarizes) just fine.

# Next steps

It's not obvious if this is an electron-builder problem, per se, or more the responsibility of the CI environment and/or MacOS to be less odd environments to operate in, but given that it's EB that throws the error, maybe there's an environment check that could be made just to bounce out a "we can't work like this" message.

If there's any interest, I may be able to build a minimally failing example, but right now I just need to put the past week behind me!

Thanks for electron-builder!
