### ISSUE TITLE
Override `name` from package.json

### ISSUE THREAD

**Issue by betamos** [electron-userland/electron-builder#4727]
* **Version**: 22.3.3

* **Target**: Linux/deb

The app name and name of deb (and other Linux) artifacts use the `name` key from `package.json`. Is there a way to override the name? If not, consider adding an option for it. Suggesting adding a new field `build.name` which can default to `name`.

My use case is I work in a monorepo (using yarn workspaces). I currently use `pkg/app/package.json` and `name: app` for my Electron package. If I were to change to `name: <app name>` (1) it risks collisions with other packages (either third party or my other packages) and (2) it dictates my project directory structure (I need to change the name of the `pkg/app` directory).

I'm happy to contribute a PR if a maintainer pre-approves the change.

**Comment by idanwork** [comment]
Hi just a thought,
is "productName" good?

I use this so my app name will contain space and capital characters.
Works great on macOS.

**Comment by betamos** [comment]
Thanks. I should have mentioned that I already use a custom `build.productName` which works great on MacOS and Windows, but it has no effect on the deb.

> Package names (both source and binary, see Package) must consist only of lower case letters (a-z), digits (0-9), plus (+) and minus (-) signs, and periods (.). They must be at least two characters long and must start with an alphanumeric character.

https://www.debian.org/doc/debian-policy/ch-controlfields.html#source

**Comment by betamos** [comment]
Hello bot. It's still relevant and blocked by a maintainer approving the API proposal.

**Comment by jwonderly** [comment]
Can you use the `extraMetadata` property?

`extraMetadata any - Inject properties to package.json`

https://www.electron.build/configuration/configuration

**Comment by klren0312** [comment]
> Can you use the `extraMetadata` property?
> 
> `extraMetadata any - Inject properties to package.json`
> 
> https://www.electron.build/configuration/configuration

it works, thanks

**Comment by uxduck** [comment]
I have a monorepo, and the packages/apps have a naming convention.

The productName and extraMetadata properties don't really override the package.json's name. For example, my app package name: `"name": "@repo/example-name",` leads to a file generated called `@repoexample-name.app`

Does anyone have a clue why it's not working? I would've though monorepos are quite common

Edit: I see the `builder-effective.config.yaml` is too simple, so the problem is my config isn't being used at all. That was because I was using a js config file (to get type hints), so I needed to pass `--config` to electron-builder:

```yaml
directories:
  output: dist
  buildResources: build
files: []
electronVersion: 39.0.0

```
