### ISSUE TITLE
Support S3 provider with AWS request signing in auto-updater

### ISSUE THREAD

**Issue by christarnowski** [electron-userland/electron-builder#4738]
* **Version**: 22.3.2

* **electron-updater**: 4.2.0

* **Target**: macOS and Windows

First of all, thanks a ton for making `electron-builder`. Much appreciated!

The issue I came across is with using non-public AWS S3 bucket for releases. The scenario is as follows:
1. Create a non-public AWS S3 bucket for releases.
2. Create IAM credentials and policies around that bucket to only allow read access via signed requests to AWS S3.
3. Embed read-access credentials in the Electron app and use them to sign requests: [example](https://gist.github.com/christarnowski/a683bf5741a1cddc88b79280c6f0f036).
4. Upload a release via `electron-builder` using other credentials with write permissions to the bucket.
5. Upload newer release.
6. Run Electron app with auto-updater enabled. It correctly identifies there is a newer version, however it falls back to full release download, since it cannot access release blockmap (403: Forbidden). This happens because there is no way of properly signing fetch request for blockmap – the S3 provider reuses headers set it `checking-for-update`/`download-update` handler.

To resolve this issue, the S3 provider would have to optionally allow *signing each outgoing request to S3* (checking for update, downloading blockmap, downloading full release as fallback) or, least invasive, allow setting request headers per each request, including the one for blockmap.

I might be missing something, so feel free to correct me if there is already a solution to this issue. In any case, any hopes of having this implemented in the near future?

Alternatively, any tips on how to contribute this feature to the project? Where would I have to start?

**Comment by develar** [comment]
Honestly to say, it will be not done by me because, it is quite specific request and not easy for me to do it properly.

First of all, before I will advice how to implement this feature (quite easy), could you please explain, for  what do you want to complicate the things? What's wrong with read-only bucket?

**Comment by develar** [comment]
See `providerFactory.ts` — we don't even have a special provider for S3, because `GenericProvider` can be used. Maybe you need to implement own Provider for S3 to support signed requests.

**Comment by develar** [comment]
e.g. as we have `PrivateGitHubProvider`

**Comment by christarnowski** [comment]
@develar Thanks for quick reply. It's to have an additional layer/step against direct downloads by gating access to allow only clients (auto-updater etc.) with appropriate AWS credentials.

While a separate provider for S3 is indeed quite specific, maybe adding an additional hook to allow setting request headers for blockmaps would be beneficial for the project?

**Comment by develar** [comment]
> While a separate provider for S3 is indeed quite specific, maybe adding an additional hook to allow setting request headers for blockmaps would be beneficial for the project?

Yes. That's we don't have special provider for S3. Less code, less issues.

See `createRequestOptions` in `DifferentialDownloader.ts`.
And `downloadBlockMap` in  `NsisUpdater.ts`.

**Comment by christarnowski** [comment]
Thank you, I will check these out and see how to solve my use case in a more generic way. What kind of contribution you think will help?

**Comment by develar** [comment]
@christarnowski Just send changes as some pull request.

**Comment by christarnowski** [comment]
Quick update. I hacked together a S3Provider that supports private access S3 buckets and works well with NSIS and Mac updaters (tested in my project). It is still a bit too rough to submit as a PR. Stay tuned.

**Comment by Nightbr** [comment]
@christarnowski We have the same problem, any update on a possible PR for a S3Provider which handle private access to S3 buckets.

I would really love to help clean the code and test it in order to include this in electron-builder.

We also really want to be able to distribute updates from private S3 with secure access.

Cheers

**Comment by christarnowski** [comment]
@Nightbr I finally found some time to prepare a PR addressing this issue. It's still rough and will probably require more work to meet the standards for EB, but we're using the code in production with good results. Try it yourself: #5138.

**Comment by piotrtomiak** [comment]
Any updates on this?

**Comment by scraggo** [comment]
Bumping this thread - my company's team would love to be able to incorporate this. Maintainers and @christarnowski  Is there anything I can do to help get this PR merged in?

**Comment by christarnowski** [comment]
I can devote some time to polishing the PR and making sure it works properly with upstream EB. I'm just need feedback on the approach I've taken.

Up to maintainers having spare time, I guess. Or enough people wanting this 😉.

**Comment by mmaietta** [comment]
Hiya, new maintainer here. 🙂  
I'm happy to review. I like the idea, I just don't have a way to test it on my own...

I saw in your PR that you have MacUpdater and NsisUpdater duplicate logic, and AppImageUpdater isn't covered. It seems like we could condense the logic to within AppUpdater.

---

It looks like everything is piped through here:
https://github.com/electron-userland/electron-builder/blob/8df250b4645924942883ba6ad1418da994116521/packages/electron-updater/src/AppUpdater.ts#L429-L433

The headers passed into `doDownloadUpdate` are generated in https://github.com/electron-userland/electron-builder/blob/8df250b4645924942883ba6ad1418da994116521/packages/electron-updater/src/AppUpdater.ts#L470

A potential route to go is to extract `fileInfo` out of `doDownloadUpdate`, then you can generate the headers from within `AppUpdater` since the provider is present
Every `doDownloadUpdate` has this line anyhow with only the extension changing ('AppImage' in this case)
https://github.com/electron-userland/electron-builder/blob/8df250b4645924942883ba6ad1418da994116521/packages/electron-updater/src/AppImageUpdater.ts#L33
`updateInfoAndProvider` isn't used much either, just for the version and resolving the file. Thus we can extract those to the AppUpdater too so that the request headers become simple when integrating your `createRequestOptions` approach
```
private computeRequestHeaders(url: URL, provider: Provider<any>): OutgoingHttpHeaders {
    const fileExtraDownloadHeaders = provider.fileExtraDownloadHeaders
    const headers = fileExtraDownloadHeaders ? {
    	...fileExtraDownloadHeaders,
    	...this.requestHeaders
    } : this.computeFinalHeaders({ accept: "*/*" })
    return provider.createRequestOptions(url, headers)
}
```

And eventually, we could get to something like this:
```
const { provider, info } = updateInfoAndProvider
const fileInfo = findFile(provider.resolveFiles(info), this.anAbstractPropertyForExpectedArtifactExtension)!!
return this.doDownloadUpdate({
	fileInfo,
	version: info.version
	requestHeaders: this.computeRequestHeaders(fileInfo.url, provider),
	cancellationToken,
})
```

I don't have a way to test that though

**Comment by christarnowski** [comment]
Thank you @mmaietta for looking into this issue and reviewing the PR! I will try to carve some time to update the PR this or next week.
