### ISSUE TITLE
macOS Notarization issue with ZIP builds

### ISSUE THREAD

**Issue by MehediH** [electron-userland/electron-builder#4822]
* **Version**:  22.3.2

* **Target**: macOS .zip

**Problem Description:** When notarizing a build using `electron-notarize` via the `afterSign` hook, the notarization and build is successful. However, the .zip artifact that gets created seems to have a problem -- when manually extracting the .zip, you can't open the .app inside it ("This application cannot be opened" error). However, if you use something like `ditto` on macOS to extract the .zip, the app opens just fine as expected (https://github.com/Automattic/wp-desktop/issues/792#issuecomment-596594324).

This means when a user downloads the .zip release from GitHub releases, the app cannot be opened. 

**Expected Behaviour:** Extracting the .zip file should allow the app to be opened without any errors.

**Comment by onekiloparsec** [comment]
I have the same problem, but I think the solution might be too hard to find. 

If you open the Console.app and then try to open the unzipped app, it says this: `Non-fatal error enumerating at <private>, continuing: Error Domain=NSCocoaErrorDomain Code=260 "The file “PlugIns” couldn’t be opened because there is no such file." UserInfo={NSURL=PlugIns/ -- file:///Users/onekiloparsec/code/arcsecond-front/dist-electron/Arcsecond.app/Contents/, NSFilePath=/Users/onekiloparsec/code/arcsecond-front/dist-electron/Arcsecond.app/Contents/PlugIns, NSUnderlyingError=0x7fa2f0d89dd0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}`

And indeed, when looking inside the app, the PlugIns folder is missing. What is strange is that the .dmg works fine and has no PlugIns folder either.

**Comment by MehediH** [comment]
@onekiloparsec So the only solution right now is to use a .dmg?

**Comment by onekiloparsec** [comment]
I finallt ended up making a `postelectron:build` script that creates the missing PlugIns dir inside the .app, re-zip the whole damn thing, get the new right hashes and stuff, update the lates-mac.yml and upload it to s3... U want a gist?

**Comment by onekiloparsec** [comment]
Ugly code, but it works: https://gist.github.com/onekiloparsec/744addc20da3024a25a8e88b6423be62

**Comment by MehediH** [comment]
Hmm, doesn't seem to be working on my end. I am not uploading to AWS but instead just saving the zip locally. So when I manually open the .zip, the app shows the same notarization error. 

I have checked and the new .zip does have the PlugIns folder, so not sure what's happening

**Comment by MehediH** [comment]
This is a duplicate and is being tracked here #4299.
