### ISSUE TITLE
electron builder and virustotal

### ISSUE THREAD

**Issue by Amosss** [electron-userland/electron-builder#4925]
Hi
electron-builder 22.6.0
electron 8.2.5
Windows - portable

The issue
![image](https://user-images.githubusercontent.com/17168621/81042511-f4c68900-8eb8-11ea-9ff5-2eb3dcc55c70.png)

Virustotal shows only one engine detection as a packed exe, which is correct (not a virus). 

From past experience, **not with electron-builder** but with UPX for example, it starts with this (one) detection so I release the application and later on, suddenly out of nowhere, other antiviruses join the party and start to false positive your exe/application.

I didn't have this happening with electron-builder (I'm new to it) but the beginning is the same (that one detection). Anyone else here had any experience with the latest 22.6.0 or this one detection will remain that way?

Thanks

**Comment by kevinlinv** [comment]
Hey, from other similar threads this might be caused by the same issue:
- https://github.com/electron-userland/electron-builder/issues/4930
- https://github.com/electron-userland/electron-builder/issues/5004#issue-623553520

From what I gather, one of the dependency of `electron-builder` -> `app-builder-bin@3.5.8` contains some additional files that gets shipped as part of the installer on windows, and the anti virus picked it up as a potential threat. e.g the copy and .zip:
<p align="center">
<img src="https://user-images.githubusercontent.com/44967897/85814167-acd12d80-b7a8-11ea-85da-7026c921d4e9.png" />
</p>


From those other issues, it seems like the problem no longer exists in the latest version of `electron-builder` `v27.x.x`. Perhaps try that version?

**Comment by Amosss** [comment]
If you mean 22.7, which is the latest, I'm using that. I just tried now and virustotal again shows 1 detection by bkav.

**Comment by kevinlinv** [comment]
>If you mean 22.7, which is the latest, I'm using that. I just tried now and virustotal again shows 1 detection by bkav.

Yep, thats the version I meant to type.

Are there perhaps any more useful info from the report? Such as which file is the culprit?

**Comment by Amosss** [comment]
I'm uploading 1 exe file (portable) so it scans that file only.
