### ISSUE TITLE
Include External Folder Into Build

### ISSUE THREAD

**Issue by creyD** [electron-userland/electron-builder#4926]
* **Version**: latest
* **Electron Version**:latest
* **Electron Type (current, beta, nightly)**:current
* **Target**: windows

I am building multiple electron apps and have one directory for common pictures and files. I would like to include them when building each app with electron-builder. The [docs](https://www.electron.build/configuration/configuration) recommended -if I understood correctly- adding the path to the build > files key but it doesn't seem to work using this config file:

```json
"build":{
    "files": [
        "**/*",
        "../common/img/*"
    ]
}
```

My directory structure is as follows:
```
|git_folder
|-- electronapp1
|---- package.json
|-- electronapp2
|---- package.json
|-- common
|---- img
|---- js
|---- css
```

I am trying to access the common directories with i.e. this HTML code `<link rel="stylesheet" href="../common/css/master.css">`. It works when starting it with `electron .` for debugging and developing, but when building with electron-builder, it doesn't seem to pack the common directories and throws "File not found" in the console.

For reference [this is on SO](https://stackoverflow.com/questions/61599298/electron-builder-include-external-folder)

**Comment by kiruh** [comment]
Have you found a solution?

**Comment by xzifan** [comment]
I use lerna for my electron app and here is how my project looks like:
```js
|ROOT
|--build // including all files built with vite
|--packages // source code
|------main
|------renderer
|------preload
```
Since I was calling build inside the main package, using the glob pattern in the `files` configuration, like `../../build/`, does not reach to the files outside.

Then I read the docs again and found out that `files` accepts a `FileSet` instead of a glob pattern.

then I tried this 
```js
{
    ......
    files: {
      from: '../../build/',
      to: 'build'
    }
}
```
This works perfectly in my case. The `build` folder will be inside the `app` or `app.asar`.
