### ISSUE TITLE
Signing/notarization status

### ISSUE THREAD

**Issue by mihaiav** [electron-userland/electron-builder#4934]
* **Version**: 

22.6.0

* **Electron Version**:
8.2.5

* **Electron Type (current, beta, nightly)**:

* **Target**: 
Mac

Application is not notarized. Is this a known issue? If so could we update the [signing docs](https://www.electron.build/code-signing) to make it clear that the current signing is not working on the  macOS 10.14.5 or higher?

**Comment by b-zurg** [comment]
There's a few articles floating around about how to notarize the app and a pinned issue:

https://github.com/electron-userland/electron-builder/issues/3870

I think the dust is still settling on this.  I haven't gotten notarization totally working either but that's not because of electron-builder but a separate issue with a native dependency not supporting hardened runtime.

I would recommend following this article - https://kilianvalkhof.com/2019/electron/notarizing-your-electron-application/

It's mentioned in the docs briefly but I agree the documentation could use a revamp with all of the changes that have happened.

**Comment by jrowny** [comment]
I believe this  #4656 is the actual issue. This has been fixed in electron-osx-sign, but it seems like that code was forked into electron-builder so electron-builder didn't get the fix.

I think for now the only thing we can do is manually sign.
