### ISSUE TITLE
Extension Error, 7zip-lite ENOENT error on checking for updates

### ISSUE THREAD

**Issue by jsheffers** [electron-userland/electron-builder#4957]
* **Version**: 
Builder version: 22.3.2

* **Electron Version**:  7.1.9
* **Electron Type (current, beta, nightly)**: current
Updater version: 4.2.0

* **Target**: NSIS

We're receiving the following error on a lot of machines.  It happens specifically when checking for updates.  In ALL cases, it's triggered when an update is not found.  

Screenshot of what happens directly before the error:
<img width="1143" alt="Screen Shot 2020-05-12 at 9 59 54 AM" src="https://user-images.githubusercontent.com/656483/81701040-74170800-9437-11ea-85de-b52c1a33e139.png">

After the above reporting, I'm getting the following error:

```
Extension Error: Error: spawn C:\AppFolder\App Folder\resources\app.asar\node_modules\7zip\7zip-lite\7z.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn C:\\AppFolder\\App Folder\\resources\\app.asar\\node_modules\\7zip\\7zip-lite\\7z.exe',
  path: 'C:\\AppFolder\\App Folder\\resources\\app.asar\\node_modules\\7zip\\7zip-lite\\7z.exe',
  spawnargs: [
    'x',
    'C:\\Users\\user\\AppData\\Roaming\\app-folder\\extensions\\lmhkpmbekcpmknklioeibfkpmmfibljd.crx',
    '-y',
    '-oC:\\Users\\user\\AppData\\Roaming\\app-folder\\extensions\\lmhkpmbekcpmknklioeibfkpmmfibljd'
  ]
}
```

**Comment by asmeikal** [comment]
Same problem here.

For us, the problem appeared between April 30th and May 11th. On April 30th we had an NSIS build for windows that works, while the build on May 11th has this problem. We tried to rebuild the April 30th version, but it shows the same problem. We didn't change any dependency between April 30th and May 11th.

On both builds we were using these versions:
- electron builder 20.44.4
- electron 4.2.10
- electron updater 4.1.2
The project is based on an old version of [electron-react-boilerplate](https://github.com/electron-react-boilerplate/electron-react-boilerplate).

We've tried updating to these versions (following the latest version of [electron-react-boilerplate](https://github.com/electron-react-boilerplate/electron-react-boilerplate)):
- electron builder 22.6.1
- electron 7.1.13
- electron updater 4.3.1
But the problem is still there.

Before the update, the `app.asar` did not contain the `7zip` directory inside node_modules.
After the update, the `7zip` directory with the `7z.exe` file is there, but we still have the problem.

**Comment by asmeikal** [comment]
We found that the problem was caused by version 2 of electron-devtools-installer (see [this issue](https://github.com/MarshallOfSound/electron-devtools-installer/issues/72)). The build that was not working installed version 2 of electron-devtools, that had this problem on windows. Upgrading to version 3 solved the problem for us.

**Comment by jsheffers** [comment]
Thanks for the info.  Closing
