### ISSUE TITLE
How to remove devtools from package

### ISSUE THREAD

**Issue by darwinye** [electron-userland/electron-builder#5178]
* **Version**: 

* **Electron Version**:
* **Electron Type (current, beta, nightly)**:

* **Target**: 
As title, I submit this issue to ask how to remove devtools from package. thanks

**Comment by b-zurg** [comment]
I don't really think this issue is relevant to this repository.  Devtools are built into the electron executable.  If you want to change that you'll have to make a custom build of electron...  which you probably don't want to do.

Just don't expose an option for end-users to open dev tools.  You have control over the API.
