### ISSUE TITLE
App doesn't start after update

### ISSUE THREAD

**Issue by Sergey-Churilin** [electron-userland/electron-builder#5197]
* **Version**: 22.7.0
* **Electron Version**: 9.0.5
* **Electron Type (current, beta, nightly)**: current
* **Electron-updater**: 4.1.2
* **Target**: Nsis

Our clients after update to a new release of my application can't start the app. This issue occur not for all users, only for some of them.
Versions of electron from which issue occurs for sure are: 6.1.7(electron builder version was 22.2.0) , 7.1.11 (electron builder version was 22.3.2). Version of electron in updated application is 9.0.5. 
**The common problem - application can't be started.**

If users try to run the app in debug mode via console, they see such error: **[24244:0731/165249.357:ERROR:crashpad_client_win.cc(794)] not connected**
For that case I observed that after update all files were new(were updated) except one: **icudtl.dat**.

A strange thing is that when users do all the same steps the second time, everything is going smoothly (I mean install exactly the same previous version and make update to the latest)

**Comment by Ryner01** [comment]
Hello I too have similar issue. Did you manage to find a fix?

Version: **22.8.0**
Electron Version: **9.0.0**
Electron-updater: **4.3.1**
Target: **Nsis**

After first time launch of Windows app will download the update and start installation then quit and nothing happens. Second launch works fine.

Not sure if this is helpful but it seems that in the first update attempt installation is quicker (eg installation progress is visibly faster then when update is working properly the second time)

**Comment by Sergey-Churilin** [comment]
No I didn't find a solution, because I can't imagine how to reproduce it. I am thinking that maybe antivirus or some other process lock the file, that leads to only partial update

**Comment by s4m0r4m4** [comment]
I have run into issues in the past where the updater silently fails to update certain files, and I traced it back to an issue in my own app where a process was left running that had those files locked. I basically had to update my installer to try to kill that hanging process (if it was running) before installing the update.

Not sure if that's your issue but I thought it would be worth mentioning!

**Comment by Sergey-Churilin** [comment]
Hi @s4m0r4m4 , could you please provide some more info regarding how you updated your installer? As installer is created with electron builder, what can I do to enhance the process?

**Comment by s4m0r4m4** [comment]
Sure - I updated the code of my application where I call `autoUpdater.quitAndInstall()`. Before calling that function, I run a function that looks like this:
```
const sKillCMD: string = 'taskkill /IM ApplicationNameHere.exe /F /FI \"memusage gt 2\"';

const sReturn = execSync(
	sKillCMD,
	{
		timeout: 5000 // in milliseconds
	});
```
This effectively uses the NodeJS child process API to run a simple command synchronously (so it will block) to kill all tasks named `ApplicationNameHere.exe` (which is the process that was locking some files that needed to be updated) before continuing to install the update.

Note that I am calling `autoUpdater.quitAndInstall()` separately from `autoUpdater.downloadUpdate()`. If you are calling `CheckForUpdatesAndNotify()` instead, you just need to put this logic before that call.

Also - its important to note that this will NOT fix existing systems where they have already broken due to this issue. It will only prevent additional systems from experiencing the same bug. The only way I know of to resolve the issue above after it has occured is to issue a new update or have the user install the program from scratch.

**Comment by Sergey-Churilin** [comment]
@s4m0r4m4 , thank you very much for providing details

**Comment by Slapbox** [comment]
App doesn't start after installing a new version manually either. 

If I'm not mistaken, this began shortly after https://github.com/electron-userland/electron-builder/pull/5292 was merged, although that might be a coincidence or bad observation on my part.

@develar any thoughts on a possible cause for this? In the rare case that it does run after install, it invariably runs the old version. 

Perhaps related, it also no longer asks the user to close the existing version when installing and just installs itself anyway, which seems dangerous. Is that behavior intentional?

**Comment by sandeep1995** [comment]
We are constantly facing this with our users. Does anyone have a good solution?

**Comment by s4m0r4m4** [comment]
@Slapbox and @sandeep1995, please do some digging to try to figure out why it's not starting. A few good tips for getting started:
1) Look at the application files (in Program Files or wherever it may be installed) to ensure everything the app needs in order to run is present
2) Verify that the versions of the exe and dlls are all the latest version (sometimes the updater will only update some of the dlls because others are locked, resulting in a version mismatch)
3) Try running the application from the command line (open of a windows Command Prompt and run the exe), see if anything interesting shows up there
4) If none of this works, you need to add more logging to your app to provide visibility into what's happening

@Slapbox - it sounds like your app just doesn't start at all, regardless of whether it is from an update or not. I'd suggest opening a new ticket and providing as much detail as possible. This issue is about Apps not starting after updating.
