### ISSUE TITLE
Auto update rename AppImage

### ISSUE THREAD

**Issue by slmarcos** [electron-userland/electron-builder#5239]
* **Version**: 22.8.0

* **Electron Version**: 7.2.4
* **Electron Type (current, beta, nightly)**: current

* **Target**: LInux - Ubuntu 20.04 x64

Hello, I am configuring auto update in my app but when performing the update AppImage is renamed to update.AppImage, losing the original name. Does anyone know how to get around this?

Thank you

**Comment by StaZhu** [comment]
Here my solutions, pack AppImage into Deb😁, write custom postinst file put this XXX.AppImage into /opt/XXX/XXX.AppImage, and maintain the name of AppImage each build process, then no matter what the name you changed in deb, AppImage name never changed and is not exposed to users. otherwise it seems no better ways.

**Comment by J-Ibarra** [comment]
> Here my solutions, pack AppImage into Deb😁, write custom postinst file put this XXX.AppImage into /opt/XXX/XXX.AppImage, and maintain the name of AppImage each build process, then no matter what the name you changed in deb, AppImage name never changed and is not exposed to users. otherwise it seems no better ways.

Hello, can you share an example for this please?

**Comment by perry-mitchell** [comment]
That's an awful lot of work to go through just to have a stable AppImage filename :confused:
