### ISSUE TITLE
Setting --c.buildVersion only sets the file version of the application, not the installer.

### ISSUE THREAD

**Issue by Delpire** [electron-userland/electron-builder#5277]
* **Version**: 22.8.0

* **Electron Version**: 9.0.5
* **Electron Type (current, beta, nightly)**: current (I believe)

* **Target**: Windows

I am trying to get both my application and installer to be versioned the same. I would imagine buildVersion would do this.

So my command is the following:
```
npx electron-builder --config=./bin/electron-builder.json --win --x64 -c.electronVersion=9.0.5 --c.buildVersion=13.1.2.32
```

If I look at the electron executable, the file version is 13.1.2.32, but if I look at the name of the installer, it is `{Product Name} Setup 1.0.0.exe`, and the file version is 1.0.0. 

Is there a way to set this setup.exe version to be the same as my executable **via a command line argument**? Shouldn't the buildVersion being setting it for both?

**Comment by Delpire** [comment]
As far as I know, this issue has not yet bet resolved.

**Comment by mmaietta** [comment]
Hi @tub5 / @Delpire 
The installer name uses `${version}` as the name template (it's the same approach all the other Targets use for the artifact template.)
https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/src/targets/nsis/NsisTarget.ts#L119

Alternatively, you can override `artifactName` template to provide the exact format you're looking for, such as forcing `buildVersion` to be used.
https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/src/platformPackager.ts#L491-L494
```
✗ yarn electron-builder -w --c.buildVersion='1.2.3' --c.artifactName='${productName}-${buildVersion}-${arch}.${ext}'
```


I'm not able to repro this issue locally though, but I'm guessing that's because I don't have the full EB.json.
```
✗ yarn electron-builder -w --c.buildVersion="1.2.3"
yarn run v1.22.10
$ <...>/electron-quick-start/node_modules/.bin/electron-builder -w --c.buildVersion=1.2.3
  • electron-builder  version=22.10.5 os=19.6.0
  • loaded configuration  file=<...>/electron-quick-start/electron-builder.js
  • writing effective config  file=dist/builder-effective-config.yaml
  • packaging       platform=win32 arch=x64 electron=11.1.1 appOutDir=dist/win-unpacked
  • Unpacking electron zip  zipPath=undefined
  • default Electron icon is used  reason=application icon is not set
  • building        target=nsis file=dist/electron-quick-start-1.2.3.exe archs=x64 oneClick=true perMachine=false
  • building block map  blockMapFile=dist/electron-quick-start-1.2.3.exe.blockmap
✨  Done in 25.96s.
```
Can you please share your `--config=./bin/electron-builder.json`?
