### ISSUE TITLE
"The binary uses an SDK older than the 10.9 SDK."

### ISSUE THREAD

**Issue by abhimatta** [electron-userland/electron-builder#5376]
* **Version**: 

* **Electron Version**: 3.0.6
* **Electron builder**: 21.2.0

* **Target**: 

We are trying to notarise our app but getting this error.

{
  "logFormatVersion": 1,
  "jobId": "-----",
  "status": "Invalid",
  "statusSummary": "Archive contains critical validation errors",
  "statusCode": 4000,
  "archiveFilename": "App.zip",
  "uploadDate": "2020-10-29T12:06:33Z",
  "sha256": "00c02039fc59193d6ececf7f8c9a323c6566447b6e84fde4f8fad3a07512f0fb",
  "ticketContents": null,
  "issues": [
    {
      "severity": "error",
      "code": null,
      "path": "App.zip/App.app/Contents/Resources/app.asar.unpacked/node_modules/app-builder-bin/mac/app-builder",
      "message": "The binary uses an SDK older than the 10.9 SDK.",
      "docUrl": null,
      "architecture": "x86_64"
    }
  ]
}

**Comment by mmaietta** [comment]
https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution/resolving_common_notarization_issues
> Use the macOS 10.9 SDK or Later
Because of significant differences in the way code signing works prior to macOS 10.9 (see Code Signing Changes in OS X Mavericks 10.9), notarization only works for binaries linked against macOS 10.9 or later. If you use an older SDK, notarization fails and reports an issue with the following message: The binary uses an SDK older than the 10.9 SDK.
