### ISSUE TITLE
MSI / Wix installer: missing xml escaping

### ISSUE THREAD

**Issue by mikeruhl** [electron-userland/electron-builder#5387]
* **Version**: 22.9.1

* **Electron Version**: 10.1.5
* **Electron Type (current, beta, nightly)**: current

* **Target**: win-x64
* **NPM Version**: 6.14.5
* **Node Version**: 12.18.2

Let me know if you need a package.json, I left it out to avoid probable unnecessary verbosity.

## Description
I'm trying to build my project which has been building fine in the past, however, after adding a file with an ampersand (&) in the file name, the build now errors out on my windows build.

I'm getting some errors with Wix, which I think may be related to this section:
https://github.com/electron-userland/electron-builder/blob/ede6d50ddb6c23fe6bbb056bd80509c8f2ea0116/packages/app-builder-lib/src/targets/MsiTarget.ts#L210

Here is the last 2 lines of the build log:
```
⨯ Exit code: 104. Command failed: \electron-builder\Cache\wix\wix-4.0.0.5512.2\candle.exe -arch x64 -dappDir=\release\win-unpacked -pedantic -wx project.wxs
\release\__msi-x64\project.wxs(3714) : error CNDL0104 : Not a valid source file; detail: An error occurred while parsing EntityName. Line 3714, position 36.
```

From the generated project.wxs:
```
<Component Directory="d2nHZkw5KEGe.vaBZrPC_ng">
    <File Name="One & Two.bin" Source="$(var.appDir)\resources\app\static\SharedData\One & Two.bin" ReadOnly="yes" KeyPath="yes"/>
</Component>
```

It appears none of the strings being interpolated are first being escaped for proper xml unmarshalling, which is resulting in the above error.  If I rename my file to `One and Two.bin`, it works.

I have only been working with electron-builder for a few months.   If this is truly a bug, I will gladly fix it.  I searched the codebase for an encode helper, but didn't find one.  I will gladly add that function to MsiTarget.ts and run all concatenated/interpolated strings through the function to ensure valid xml if it's ok with the maintainers.

Thanks!  I appreciate you all.
-Mike

**Comment by genezys** [comment]
This issue is still present in 23.0.9. It impossible to build a package where productName contains an ampersand.

The ampersands appear as-is in the file `dist/__msi-x64/project.wxs` making it an invalid XML file.

It appears to be related to some part of the XML being built by hand in:
https://github.com/electron-userland/electron-builder/blob/a138a86fb7b59098f5dac0c0a6b59c034eb9b222/packages/app-builder-lib/src/targets/MsiTarget.ts#L181

This function builds some XML code to be injected in the final WXS without escaping ampersands.

Other XML special characters like chevrons are not an issue since they are already removed by the code that cleanup file names. So this code should only care about escaping ampersands.
