### ISSUE TITLE
Electron not launching with latest sharp libraries

### ISSUE THREAD

**Issue by janakg** [electron-userland/electron-builder#5438]
electron: "8.5.5",
electron-builder: "22.9.1"
Target: Ubuntu Linux
Sharp: 0.26.3

Suggestion from sharp author::

electron-builder needs to be modified, either to skip dependencies that uses N-API, or to invoke prebuild-install with runtime=napi first, then fallback to runtime=electron.

https://github.com/lovell/sharp/issues/2440

**Comment by janakg** [comment]
Hi, any updates on this issue would help us understand timelines.

**Comment by Julusian** [comment]
Still valid, PR with a fix to invoke prebuild-install correctly https://github.com/develar/app-builder/pull/47

**Comment by marciomarim** [comment]
Any updates on this?

**Comment by Julusian** [comment]
All merged, waiting for release.
Until that is done I am working around the issue by forcing a newer version of app-builder-bin via resolutions (yarn only)
```
"resolutions": {
	"electron-builder/**/app-builder-bin": "3.5.13",
}
```

**Comment by sujiewen** [comment]
INFO  Building app with electron-builder:
  • electron-builder  version=22.10.5 os=19.6.0
  • electron-rebuild not required if you use electron-builder, please consider to remove excess dependency from devDependencies

To ensure your native dependencies are always matched electron version, simply add script `"postinstall": "electron-builder install-app-deps" to your `package.json`
  • writing effective config  file=dist_electron/builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=sharp@0.28.1 platform=win32 arch=x64
  • install prebuilt binary  name=sharp version=0.28.1 platform=win32 arch=x64
  ⨯ cannot build native dependency  reason=prebuild-install failed with error and build from sources not possible because platform or arch not compatible
                                    cause=exit status 1
                                    errorOut=prebuild-install info begin Prebuild-install version 6.1.2
    prebuild-install WARN install prebuilt binaries enforced with --force!
    prebuild-install WARN install prebuilt binaries may be out of date!
    prebuild-install info looking for local prebuild @ prebuilds/sharp-v0.28.1-electron-v87-win32-x64.tar.gz
    prebuild-install info looking for cached prebuild @ /Users/lc/.npm/_prebuilds/e4bca0-sharp-v0.28.1-electron-v87-win32-x64.tar.gz
    prebuild-install http request GET https://github.com/lovell/sharp/releases/download/v0.28.1/sharp-v0.28.1-electron-v87-win32-x64.tar.gz
    prebuild-install WARN install connect ETIMEDOUT 192.30.255.112:443
    
                                    command=/usr/local/bin/node /Users/lc/st/wmswarehouse/node_modules/prebuild-install/bin.js --platform=win32 --arch=x64 --target=12.0.5 --runtime=electron --verbose --force
                                    workingDir=/Users/lc/st/wmswarehouse/node_modules/sharp
ExecError: /Users/lc/st/wmswarehouse/node_modules/app-builder-bin/mac/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
    at ChildProcess.<anonymous> (/Users/lc/st/wmswarehouse/node_modules/builder-util/src/util.ts:243:14)
    at Object.onceWrapper (events.js:422:26)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) {
  exitCode: 2,
  alreadyLogged: true,
  code: 'ERR_ELECTRON_BUILDER_CANNOT_EXECUTE'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by AlanSean** [comment]
> 全部合并，等待发布。
> 在完成此操作之前，我将通过解决方案强制使用新版本的app-builder-bin来解决此问题（仅适用于纱线）
> 
> ```
> "resolutions": {
> 	"electron-builder/**/app-builder-bin": "3.5.13",
> }
> ```

I tried, but it didn't work

**Comment by AlanSean** [comment]
> All merged, waiting for release.
> Until that is done I am working around the issue by forcing a newer version of app-builder-bin via resolutions (yarn only)
> 
> ```
> "resolutions": {
> 	"electron-builder/**/app-builder-bin": "3.5.13",
> }
> ```

I tried, but it didn't work

**Comment by dennisameling** [comment]
Versions 22.11.1 and higher of `electron-builder` [include the fix for this issue](https://github.com/electron-userland/electron-builder/commit/3dfb731433b4cc58897776fde4bbf35de344338a) (specifically it includes `app-builder-bin` 3.5.13 which has the fix).

Please report back here if that version works for you 👍🏼

**Comment by KillerCodeMonkey** [comment]
Same here like @AlanSean said. Seems like it is not working. Even with latest version electron-builder and sharp version.
Building the app is not the problem, but after starting it, it freezes and no gui appears (tested with deb and AppImage).
Any idea?

**Comment by rrgeorge** [comment]
> Same here like @AlanSean said. Seems like it is not working. Even with latest version electron-builder and sharp version.
> Building the app is not the problem, but after starting it, it freezes and no gui appears (tested with deb and AppImage).
> Any idea?
I think you're experiencing the same issue i just reported here: #6200 
If you try running your build application from the command-line, you should see the message: `libvips-cpp.so.42: cannot open shared object file: No such file or directory`
