### ISSUE TITLE
Building snap using electron-builder on a Raspberry Pi 4 running Ubuntu Desktop 20.10

### ISSUE THREAD

**Issue by aravind-sbox** [electron-userland/electron-builder#5452]
* **Version** : 22.9.1 

* **Electron Version**: 11.0.3
* **Electron Type**: current

* **Target**:  arm64

Building snap using electron-builder on a Raspberry Pi 4 running Ubuntu Desktop 20.10 creates a snap that can be installed. But cannot open the snap app after installation.
Opening the snap after installation causes the error :
`/snap/my-app/x1/app/my-app: /lib/aarch64-linux-gnu/libc.so.6: version 'GLIBC_2.30' not found (required by /snap/my-app/x1/usr/lib/aarch64-linux-gnu/libnspr4.so)` 

I've attached the warnings received during the snap build process [here](https://github.com/electron-userland/electron-builder/files/5631091/log.txt)

**ldd version** was 2.32 on Ubuntu Desktop 20.10

**Comment by aravindmeganathan** [comment]
I have core, core16, core18 and core20 installed. Still could'nt run the app. The base for snap is core 18.

**Comment by aravind-sbox** [comment]
I've core, core16, core18 & core20 installed. The base for snap is core18 by default. Still getting the same error.

**Comment by alariej** [comment]
Hi, running into the same problem using:

Raspberry Pi 4B
Ubuntu 21.04 arm64 Desktop
electron 13.3.0
electron-builder 22.11.7
Node 16.10.0 (snap install)
snapcraft 5.0
SNAPCRAFT_BUILD_ENVIRONMENT=host

Error when building snap for arm64 with base core18:

/bin/bash: /snap/core18/current/lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /lib/aarch64-linux-gnu/libtinfo.so.6)

ldd --version
2.33

Exact same app builds fine for amd64 (on amd64 host).

Any help appreciated!

**Comment by alariej** [comment]
For the record, I changed my setup from building the app using `SNAPCRAFT_BUILD_ENVIRONMENT=host` to using `SNAPCRAFT_BUILD_ENVIRONMENT=lxd`. I can now build arm64 electron apps without error.

The problem using 'host' is probably due to a library mismatch between the host OS (Ubuntu 21.04) and the base (core18). I can only guess that building with 'host' would work when running Ubuntu 18.04.

I ran these commands to install and initialize lxd on the Raspberry Pi:

```
sudo snap install lxd
lxd init --auto
```
Then tell snapcraft to use lxd:

`
export SNAPCRAFT_BUILD_ENVIRONMENT=lxd
`

Note: I also never succeeded building the app using multipass, although I could launch a multipass VM on the Pi without error.
