### ISSUE TITLE
Win64 system wide checkForUpdatesAndNotify() uninstalls but doesn't install

### ISSUE THREAD

**Issue by timvdalen** [electron-userland/electron-builder#5468]
* **Version**: 22.9.1

* **Electron Version**: 10.1.5
* **Electron Type (current, beta, nightly)**: current
* **electron-updater Version**: 4.3.5

* **Target**: win64

I'm running a generic server auto-update on Windows using NSIS.
Auto update works correctly if the application is installed per-user, but when the application is installed system wide:

1. The user launches an old version of the app
2. The user receives a notification that the app is ready to update on close
3. The user closes the app and received a UAC popup for `old-uninstaller.exe` (from a temporary folder)
4. The user gives permission
5. The old version of application is deleted
6. Nothing else happens

**Expected behaviour**
The new version of the application is installed

**Comment by timvdalen** [comment]
I unfortunately don't have any interesting logs for this behaviour, the app simply logs that it has fout an update and is going to execute it.

**Comment by timvdalen** [comment]
Still relevant. I've donated to the project to see if this can get priority.

**Comment by randomgithubuser1** [comment]
I'm also having this same issue.  It seems there is an issue with silent update and machine wide installation.

Another thread about it here: https://github.com/electron-userland/electron-builder/issues/4474

There is a solution in that thread that checks the registry and sets isSilent to false if the app is installed for all users.

I'm not sure how to set isSilent when using checkForUpdatesAndNotify() though since it doesn't look like it accepts any arguments.

**Comment by timvdalen** [comment]
@yorannn can you link to the workaround that ended up working for us?

**Comment by Yorannn** [comment]
> @Yorannn can you link to the workaround that ended up working for us?

This was the workaround I used 
https://github.com/electron-userland/electron-builder/issues/2363

**Comment by timvdalen** [comment]
Should be fixed by #6450
