### ISSUE TITLE
Failed to initialize sandbox for MAS

### ISSUE THREAD

**Issue by XRenSiu** [electron-userland/electron-builder#5506]
* **Version**: 
22.10.4

* **Electron Version**: 11.1.1
* **Electron Type (current, beta, nightly)**: current

* **Target**: mas

* **Last Known Working electron-builder version**:
22.9.1

Open app for mas dev:
`ERROR:bootstrap.cc(65) bootstrap_check_in org.chromium.crashpad.child_port_handshake..: Permission denied (1100)`
`Electron Helper[64045] <Error>: SeatbeltExecServer: Failed to initialize sandbox: -1 Operation not permitted`

**Comment by MrMYHuang** [comment]
First, I thank electron-builder team, because my PWA Electron MAS app built by electron-builder is approved for App Store!

I use the same versions of electron and electron-builder as XRenSiu. I also met a sandbox-related problem of mas-dev. The problem is related to these masDev settings:
```
      "entitlements": "build/entitlements.mas.plist",
      "entitlementsInherit": "build/entitlements.mas.inherit.plist",
      "provisioningProfile": "dev.provisionprofile"
```
Please provide your entitlements and entitlementsInherit files.

For dev.provisionprofile, you have to create a Provisioning Profile for macOS App Development on
https://developer.apple.com/account/resources/profiles/list
Then, link the profile to a Mac Development certificate and  your development devices.
(If you have no Mac Development certificate, you have to create one first.)
Then, download and use this profile for mas-dev.

**Comment by minhloi** [comment]
I also have the same issue. My app works fine if it is built using version 22.9.1. After upgrading to 22.10.4, the app crashes with ```Failed to initialize sandbox: -1 Operation not permitted```

**Comment by MrMYHuang** [comment]
Sorry, I was wrong. I find the correct version of electron-builder my app works well with is 22.9.1. After upgrading to 22.10.4, my app also crash.

**Comment by czzonet** [comment]
The mas-dev runs well after I install the correct provisionprofile. My crash info was 'EXC_CRASH (Code Signature Invalid)'.

"electron-builder": "22.10.5"
