### ISSUE TITLE
The packaged application does not overwrite the previous version when installed and does not automatically uninstall the old version of the application

### ISSUE THREAD

**Issue by Liting1** [electron-userland/electron-builder#5573]
* **Version**:  "electron-builder": "^22.9.1",

* **Electron Version**: "electron": "^11.1.1",
* **Electron Type (current, beta, nightly)**: current

"electron-updater": "^4.3.5",

* **Target**: 
"target": [
                {
                    "target": "nsis",
                    "arch": [
                        "x64"
                    ]
                }
            ],

I tried to package the new version of the application, tried to install the application that covered the old version of the original, but the installation failed, the new version was not installed successfully

**Comment by wbhAvivahc** [comment]
i have same problem

**Comment by LodeLesage** [comment]
Experiencing the same issue building & installing on Windows 10 Pro with NSIS: 
When trying to install a new version of the same app, the installation silently fails after getting to ~50% in the progress bar and just closes the installer. 
Normally it should show a final page with a checkbox to run the app.
The result is that the old version is still installed and the files are still the same.

electron: 11.2.0
electron-builder: 22.9.1 (also tried 22.8.1 & 22.7.0)

electron-builder.json:
```
{
    "productName": "X",
    "appId": "com.x.x",
    "artifactName": "${productName}.${ext}",
    "copyright": "Copyright text",
    "directories": {
        "output": "release/"
    },
    "files": [
        "**/*",
        "!**/*.ts",
        "!*.code-workspace",
        "!LICENSE.md",
        "!package.json",
        "!package-lock.json",
        "!src/",
        "!e2e/",
        "!hooks/",
        "!angular.json",
        "!_config.yml",
        "!karma.conf.js",
        "!tsconfig.json",
        "!tslint.json"
    ],
    "fileAssociations": [{
        "ext": "x",
        "name": "X File",
        "role": "Viewer",
        "isPackage": false
    }],
    "win": {
        "icon": "build/icons/icon.ico",
        "artifactName": "${productName}.${ext}",
        "target": [
            "nsis"
        ]
    },
    "nsis": {
        "oneClick": false,
        "perMachine": true,
        "allowToChangeInstallationDirectory": true,
        "createDesktopShortcut": false,
        "uninstallDisplayName": "${productName}"
    }
}
```

The issue is that the install works fine the first time, but installing subsequent versions fails silently.
Manually uninstalling through apps & features and then installing again works fine as well.
The same issue also occurs when changing perMachine to false and using a per-user install instead.
In that case the installer will even detect that there is a previous installation and mention that at the bottom of the page when choosing the installation directory, saying it will upgrade/overwrite the existing installation.
Unfortunately it silently fails in the same way as previously described and no upgrade actually happens.
I also made sure to update the version in package.json between builds but that doesn't change anything.

I read through numerous issues, but none were exactly the same and none provided a working fix.

Any help would be much appreciated.
Thanks for all the hard work and the awesome project!

**Comment by ejwilburn** [comment]
We're seeing the same issue and it only happens when doing the guided install (`"oneclick": false`)

**Comment by ttomaszewski** [comment]
Also seeing this issue.

**Comment by mmaietta** [comment]
@ejwilburn would you be willing to share your NSIS logs here? I'm not familiar with this topic but I'd like to take a gander.

**Comment by ejwilburn** [comment]
@mmaietta here's the relevant portion of the log:

```
IfFileExists: file "C:\Users\user\AppData\Local\Programs\Product Name\Product Name.exe" exists, jumping 0
Call: 1789
SetFlag: 13=6
File: overwriteflag=1, allowskipfilesflag=0, name="C:\Users\user\AppData\Local\Temp\nss14E9.tmp\StdUtils.dll"
File: skipped: "C:\Users\user\AppData\Local\Temp\nss14E9.tmp\StdUtils.dll" (overwriteflag=1)
Call: 1789
SetFlag: 13=6
File: overwriteflag=1, allowskipfilesflag=0, name="C:\Users\user\AppData\Local\Temp\nss14E9.tmp\StdUtils.dll"
File: skipped: "C:\Users\user\AppData\Local\Temp\nss14E9.tmp\StdUtils.dll" (overwriteflag=1)
CreateDirectory: "C:\Users\user\AppData\Local\Temp\nss14E9.tmp" (0)
SetFlag: 2=0
CopyFiles "C:\Users\user\AppData\Local\Programs\Product Name\Uninstall Product Name.exe"->"C:\Users\user\AppData\Local\Temp\nss14E9.tmp\old-uninstaller.exe"
Exec: command=""C:\Users\user\AppData\Local\Temp\nss14E9.tmp\old-uninstaller.exe" /S /KEEP_APP_DATA /currentuser --keep-shortcuts --updated _?=C:\Users\user\AppData\Local\Programs\Product Name"
Exec: success (""C:\Users\user\AppData\Local\Temp\nss14E9.tmp\old-uninstaller.exe" /S /KEEP_APP_DATA /currentuser --keep-shortcuts --updated _?=C:\Users\user\AppData\Local\Programs\Product Name")
```

As of 22.10.5 the uninstall does actually run (it didn't in 22.9) but after completion you hear a windows error tone and the installer closes.  Full log is attached.

[install.log](https://github.com/electron-userland/electron-builder/files/6131304/install.log)

**Comment by ravicious** [comment]
@ejwilburn How did you manage to get the NSIS logs? There's another issue asking how to do it with electron-builder (#5119), so I think this knowledge would be super helpful!

**Comment by sdelrue** [comment]
still seeing this issue, progress bar silently exits halfway. The uninstall ran, but the new version is not installed (empty folder)
"electron": "^19.0.1",
"electron-builder": "^23.0.3"
"electron-updater": "^5.0.1",

**Comment by mallamsripooja** [comment]
Facing the same issue, can someone please suggest a fix for this issue?

**Comment by adamcjm** [comment]
I find a way to solve this problem:

1. **You can try to add  a line code with the content `CRCCheck off` to bottom of the file `node_modules/app-builder-lib/templates/nsis/common.nsh`.**

2. And then rebuild and install the application to windows, and try to uninstall or update.

*these two step fixed my problem.*

**Comment by adamcjm** [comment]
> 这个问题还是没有解决。。。

 Pls see my comment.

**Comment by adamcjm** [comment]
> 面对同样的问题，有人可以建议解决这个问题吗？

Pls see my comment.

**Comment by adamcjm** [comment]
> 问题解决了吗？？？

My comment

**Comment by adamcjm** [comment]
> 这个问题还是没有解决。。。

My comment

**Comment by adamcjm** [comment]
> 你知道怎么办吗？

Bottom comment

**Comment by oxfordyang2016** [comment]
now i need to uninstall old installed software and reinstall the new version sotfware,it work,i wanna know why this happen
