### ISSUE TITLE
Get this error message when I build the app: Error: Exit code: EACCES. spawn filename.exe EACCES

### ISSUE THREAD

**Issue by janosvajda** [electron-userland/electron-builder#5575]
* **Version**: 22.2.0

* **Electron Version**: 10.3.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: windows

Hi,

I got this error message if I try to build the app:

```
Error: Exit code: EACCES. spawn filename.exe EACCES
    at ....\node_modules\builder-util\src\util.ts:129:16
    at exithandler (child_process.js:315:5)
    at ChildProcess.errorhandler (child_process.js:327:5)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:465:16)
```

 I use NSIS and this error occurs if I have this line in the NSIS file:
```

!macro customHeader
   RequestExecutionLevel admin
!macroend
```
My package.json contains these related values:

```
win: {
          icon: "public/icons/icon.ico",
          target: "nsis",
          requestedExecutionLevel: "requireAdministrator"
          ......
```
I tried this under Parallel Windows 10, Oracle VM Windows 10, and native Windows 10, and this issue exists under each of them.

Thanks for any assistance.

**Comment by janosvajda** [comment]
It solved. 

If Windows console is running in Administrator mode then no errors and it works fine.

**Comment by mook-as** [comment]
Hi! I've hit this too.  Writing my notes here because this was the best hit in the issues, and I'll probably hit this again later.

This appears to be because electron-builder will run the just-generated installer in order to get the uninstaller, so that it can be signed.  This behaviour was originally introduced in #526, following instructions from [the NSIS wiki](https://nsis.sourceforge.io/Signing_an_Uninstaller).

The better workaround is to set `__COMPAT_LAYER=RunAsInvoker` in the environment before running NSIS; this forces everything to run unelevated, which means that the installer can generate the uninstaller to be signed.
