### ISSUE TITLE
Application does not open after installed

### ISSUE THREAD

**Issue by XNexusPrimeX** [electron-userland/electron-builder#5600]
* **Version**:  22.9.1
* **Electron Version**: 11.2.1
* **Electron Type (current, beta, nightly)**: current
* **Target**: me

After starting the installer, the app icon appears on the windows start menu, but when I open the app, it doesn't open, and no error appears.
the funny thing is that if I type ```electron src/index.js``` the app works perfectly

index.js:
```js
const { app, BrowserWindow } = require('electron');
const preload = require('./preload')

app.setAppUserModelId('com.discord_contacts')

async function createWindow() {
    let mainWindow = new BrowserWindow({
        width: 800,
        height: 600,
        icon: './src/images/logo.png',
        webPreferences: { nodeIntegration: true },
    });

    mainWindow.loadFile(__dirname + '/views/html/load.html');
    await preload.load();
    mainWindow.loadFile(__dirname + '/views/html/home.html');

    mainWindow.on('closed', () => mainWindow = null);
    // mainWindow.setMenu(null);
}

app.on('ready', createWindow);
```

package.json:
```json
{
  "name": "private information",
  "version": "1.0.0",
  "description": "",
  "main": "src/index.js",
  "scripts": {
    "test": "electron .",
    "build": "electron-builder"
  },
  "author": "",
  "license": "private information",
  "dependencies": {
    "discord.js": "^12.5.1",
    "lowdb": "^1.0.0",
    "nativescript-toolbox-ssi": "^3.0.8"
  },
  "devDependencies": {
    "electron": "^11.2.1",
    "electron-builder": "^22.9.1",
  },
  "build": {
    "appId": "com.private_information",
    "productName": "private information",
    "directories": {
      "output": "dist"
    },
    "publish": null,
    "win": {
      "icon": "src/images/logo.png",
      "target": "nsis"
    }
  }
}
```

**Comment by laontme** [comment]
Try to remove `icon: './src/images/logo.png'`. Works for me

To set icon in build:
```json
"build": {
    "icon": "logo.ico"
}
```

**Comment by mmaietta** [comment]
Please double check that your icon is in the expected location (i.e. buildResources) and the correct size. It's possible you may need to resave the png file from another application (idk if there's any formatting/conversion issues for png->ico but that's a way to check)

>Windows (NSIS)
Optional icon.ico (Windows app icon) or icon.png. Icon size should be at least 256x256.
needs to be placed in the buildResources directory (defaults to build). It is important to provide icon.ico (or icon.png), as otherwise the default Electron icon will be used.
