### ISSUE TITLE
electron appx windows store rejected: “The available product tile icons include a default image”

### ISSUE THREAD

**Issue by MartinBarker** [electron-userland/electron-builder#5699]
* **Version**:  22.9.1

* **Electron Version**: 11.1.0
* **Electron Type (current, beta, nightly)**: current

* **Target**:  windows store

I am trying to submit my electron app to the windows store but whenever I do It gets rejected for this reason:
```
App Policies: 10.1.1 Inaccurate Representation - Icon

Notes To Developer

The available product tile icons include a default image. Tile icons must uniquely represent product so users associate icons with the appropriate products and do not confuse one product for another. For information about tiles see https://docs.microsoft.com/en-us/windows/uwp/controls-and-patterns/tiles-and-notifications-app-assets, or for 3D icons for Mixed Reality products, see https://docs.microsoft.com/en-us/windows/mixed-reality/3d-app-launcher-design-guidance. 
```

In order to build, sign, and submit my appx file, I run the following commands on then `appxBuild` branch of this nrepo: https://github.com/MartinBarker/RenderTune/tree/appxBuild

1. Run `electron-builder build --win` to build the dist/win-unpacked folder
2. Run the following powershell command to sign my appx file and export it to the folder `output-appx`:
```
electron-windows-store --input-directory C:\Users\marti\Documents\projects\RenderTune\dist\win-unpacked --output-directory C:\Users\marti\Documents\projects\output-appx --package-version 0.0.2.0 --package-name RenderTune --package-display-name 'RenderTune' --publisher-display-name `martinbarker' --identity-name ##########
```

The finished \output-appx\RenderTune.appx file can be uploaded and submitted to my windows store app page fine so I dont think the credentials signing are incorrect, but once it gets reviewed it always gets rejected with this tile rejection message.

I've tried following various different guides on how to submit an electron app to the windows store online:
https://www.electron.build/configuration/appx
https://www.electronjs.org/docs/tutorial/windows-store-guide
https://blog.mifi.no/2020/03/31/automated-electron-build-with-release-to-mac-app-store-microsoft-store-snapcraft/

And made sure I have the necessary icons in correct format and filenames (located in the build/appx folder: https://github.com/MartinBarker/RenderTune/tree/appxBuild/build/appx)

I've tried researching this tile error message online and found a stackoverflow question that didn't have a helpful answer:
https://stackoverflow.com/questions/57310667/how-to-fix-the-available-app-icons-include-a-default-icon-when-publishing-an-e

Can anyone help me figure out what microsoft is referring to when they say my product tile icons include a default image? Thanks

**Comment by mmaietta** [comment]
Can you please try reproducing with prerelease version 22.10.5? If it still fails, please post logs with env `DEBUG=electron-builder`

**Comment by MartinBarker** [comment]
I'm retrying with a tile image selected for the microsoft review process and it is still in review, will reopen this ticket if I think electron-builder could still be the problem

**Comment by MartinBarker** [comment]
fixed by adding the tile icon file to my resources folder

**Comment by mqtik** [comment]
You just added the file? Under what name?

Also, I've been looking at your StackOverflow post.
You really should clear your credentials from there..

**Comment by jklp** [comment]
Sorry to resurrect an old thread, but I've been struggling with the same problem for WEEKS and thought this might be helpful for someone.

I'm the same as OP, with the Microsoft Store sending me the same `App Policies: 10.1.1 Inaccurate Representation - Icon` rejection.  Turns out I need to define ALL the icons from the documentation here

https://www.electron.build/configuration/appx.html 

I've listed all the icons below in case the documentation changes:

- **Logo**: StoreLogo.png
- **Square150x150Logo**: Square150x150Logo.png
- **Square44x44Logo**: Square44x44Logo.png
- **Wide310x150Logo**: Wide310x150Logo.png
- _Optional_ **BadgeLogo**: BadgeLogo.png
- _Optional_ **Square310x310Logo**: LargeTile.png
- _Optional_ **Square71x71Logo**: SmallTile.png
- _Optional_ **SplashScreen**: SplashScreen.png

One thing which tripped me up (and the documentation wasn't 100% obvious on this)  is you can't put the files directly into `/build`, but need to go into `/build/appx`.

If you're after the icon sizes, there's a good Stackoverflow post here (and I also confirmed the sizes in Visual Studio):

https://stackoverflow.com/a/61805906/3847

It also pays to double check the `.appx` file is bundled correctly. You can do this by extracting it with any zip extraction utility (`.appx` files are just zip files), and make sure those icon files are in the `/assets` folder, and also double check they're all defined in the `AppxManifes.xml` file.

Hope this helps someone!

**Comment by jstn455** [comment]
@jklp Just to close all the unknowns, the stackoverflow comment doesn't have a size for BadgeLogo, do you happen to know that size?

**Comment by jklp** [comment]
@jstn455 Hi sorry for the super late response. I just loaded up Microsoft Visual Studio 2022 and for the Badge Logo it looks like at 100% scale, it's 24x24px

For the Splash Screen  it's 620x300px at 100% scale

Hope this helps!
