### ISSUE TITLE
When we should specify build.files in package.json and when not to create installer 

### ISSUE THREAD

**Issue by alokmahor** [electron-userland/electron-builder#5708]
electron-builder works with almost zero configuration to complex configuration.

I saw many project which are not specifying `build.files` field in `package.json` and installer get generated without any manual config.

I saw many other project which specify `build.files` like 
```
"build": {
    "appId": "com.example",
    "files": [
      "build/**/*",
      "node_modules/**/*",
      "package.json"
    ]
  }
```

When we should specify [`build.files`][2] and when not?

  [2]: https://www.electron.build/configuration/contents#files

**Comment by cawa-93** [comment]
I can explain on the example of my project:
My project uses a bundler. It takes the code from the `src`, optimize it and stores it in the `dist`.

In fact, everything you need to run the program is stored in the `dist`. But by default, the builder packs **all project files** (including the source code in the `src` folder). This is superfluous, so I indicated that he pack only the directory of `dist`. ([My config](https://github.com/cawa-93/vite-electron-builder/blob/cb616e18931cad1c3c0b06412f7683540b06ba32/config/electron-builder.js#L13-L15)).

Adding `node_modules/**` and a `package.json` to files is unnecessary, because according to the [documentation](https://www.electron.build/configuration/contents):

> `package.json` and `**/node_modules/**/*` (only production dependencies will be copied) is added to your custom in any case.
