### ISSUE TITLE
Unknown format in import during builder

### ISSUE THREAD

**Issue by brianmmorton** [electron-userland/electron-builder#588]
* **Version**: 5.12.1

* **Target**: mac

Thanks for the project guys. Working on signing an app build and getting this error: 

security: SecKeychainItemImport: Unknown format in import.

    at /Users/brianmorton/Sites/allocate/app/node_modules/electron-builder/src/util/util.ts:98:16
    at ChildProcess.exithandler (child_process.js:209:5)

Since im a noob to using electron and mac apps, I cant give you much more direction on the error. Could you all provide some direction on how to fix this? Thanks!

**Comment by develar** [comment]
Please attach build log. Do you use valid codesign cert?

**Comment by develar** [comment]
@brianmmorton I see `-P a4676bbb79cbffd6b8f174e3f4dd104f06e10c6b0c7dde47bd68004c028097d6 (sha256 hash) ` so password set correctly (no bash escaping issue).

Maybe solution:

> OK, I managed to solve it. It appears the .p12 file we were using before apparently wasn't complete, according to openssl pkcs12 -info it contained a single RSA private key. I replaced it with a freshly exported .p12 from Keychain Access, which contained 2 RSA keys and it's now working.

Does this solution helps you? See https://github.com/electron-userland/electron-builder/wiki/Code-Signing#how-to-export-certificate-on-macos

Please try to encode cert to base64 instead of link.
