### ISSUE TITLE
node addon is not getting linked in the final packaged app

### ISSUE THREAD

**Issue by robosushie** [electron-userland/electron-builder#5932]
Using electron-builder version ^22.10.5
 Using electron version ^13.0.1
 -NA-
 platform=win32 arch=x64

I have built an application using electron where I have added native Cpp functionality. The front end part is using react and I am using a webpack script that continuously watches for the changes in the react files

> "watch": "webpack --config webpack.renderer.js --watch",

and generate a compiled version of the react files into a compiled_renderer.js. I am then adding directly to the HTML file as a script.

> <script src="./compiled/compiled_renderer.js"></script>

My electron-builder script which I am using and the basic build configuration is

> "dist": "npm run clean && electron-builder && electron-builder install-app-deps",

> "build": {
>         "appId": "com.example.boxrf",
>         "nodeGypRebuild": true,
>         "asar": true  
>     },

I am adding the node addon to my project using the bindings library

> const addon = require('bindings')('libsdr');

On running the built app on the laptop where I have but the app, I am getting this error.

![image](https://user-images.githubusercontent.com/61646255/120135853-c071e900-c1ee-11eb-9183-e943593e66f7.png)

So I modified the code and added the addon .node file in a separate directory and hardcoded the file path in my js file instead of using bindings.

> "build": {
>         "appId": "com.example.boxrf",
>         "nodeGypRebuild": true,
>         "asar": true,
>         "extraFiles": [
>             {
>                 "from": "build/Release",
>                 "to": "resources/node.addon",
>                 "filter": "*.node"
>             }
>         ]
>     },

> const addon = require('../../node.addon/libsdr.node');

In this scenario I am able to run the built application on my personal laptop but when I take the entire folder on another computer and run the app or install the app using the setup and then try to run the application. It is giving the error that the .node file is not found, although the path which it is trying to reference is the correct path and it contains the node addon file.

![image](https://user-images.githubusercontent.com/61646255/120136486-dfbd4600-c1ef-11eb-8430-434472469dd7.png)

Whereas the file does exist in the given location

![image](https://user-images.githubusercontent.com/61646255/120136502-eea3f880-c1ef-11eb-8666-e8ed517520d0.png)

Any help would be appreciated. Thanks

**Comment by mmaietta** [comment]
Let's not go down the hardcoded path right now since that's a separate issue/error message.

`bindings` module should have just done the trick if you're packaging it correctly, and I see you're attempting to run it from the win-unpacked folder. Can you double check that your `.node` file is indeed at one of the file paths it specified?
I think I see an issue as your paths are within `app.asar` and I was under the impression that `.node` files all had to be unpacked, such as via:
```
    "asarUnpack": [
      "*.node"
    ]
```

**Comment by robosushie** [comment]
@mmaietta 
The file exist in the path. So if you see the path mentioned in the error \\?\C:\Users.....libsdr.node ( I am confused with the \\?\ portion is it causing any issue )

I tried asar unpack also, I have been keeping two different projects, with the exact same contents. One I have built using electron-builder, another using electron-forge. I tried unpacking the .node files in both my setups but it is not working. [Link](https://github.com/electron/electron-packager/issues/1245)

**Comment by robosushie** [comment]
@mmaietta 
I saw one of your comments in another similar issue. [(Link)](https://github.com/electron-userland/electron-builder/issues/5775#issuecomment-815029865)

I am not able to get the "awesome-node-loader" part and the "!packDistributable", is there any github repo which I can refer to?

**Comment by mmaietta** [comment]
`packDistributable` simply is a local var I use to discern whether we should be bundling for a distribution build (i.e. packed electron app) versus running locally via `electron .`

For the loader: https://github.com/gurisko/awesome-node-loader. This is the magic it's flipping between:
> This option chooses in between __dirname and path.dirname(process.execPath) 

Basically, I couldn't use `__dirname` in the prod distributable and I placed all `.node` addons at the app root (`/` for win/linux and `/Contents/MacOS` for mac)
I can't link the repo though because it's my company's internal project

**Comment by knaos** [comment]
I am having a common issue, though it seems electron related, because I am running the app in dev mode. When I am trying to load a NativeModule.node but the current working directory (cwd) **is different** than the one where the app is, the module is not loaded even though the path is absolute and correct. This happens when for example the application is run from windows startup.
