### ISSUE TITLE
Question: installation per machine within ProgramData without admin / UAC

### ISSUE THREAD

**Issue by capc0** [electron-userland/electron-builder#5986]
desired solution is to install the app for everyone using the machine, but without admin permission / windows UAC.

so I came up with the following config that seems to work

```json
"nsis": {
        "oneClick": true,
        "perMachine": false,
        "allowToChangeInstallationDirectory": false,
        "include": "build/installer.nsh"
    },
```

with the following preInit macro, as stated in the docs https://www.electron.build/configuration/nsis#common-questions

```nsh
!macro preInit
  SetRegView 64
  WriteRegExpandStr HKLM "${INSTALL_REGISTRY_KEY}" InstallLocation "C:\ProgramData\App"
  WriteRegExpandStr HKCU "${INSTALL_REGISTRY_KEY}" InstallLocation "C:\ProgramData\App"
  SetRegView 32
  WriteRegExpandStr HKLM "${INSTALL_REGISTRY_KEY}" InstallLocation "C:\ProgramData\App"
  WriteRegExpandStr HKCU "${INSTALL_REGISTRY_KEY}" InstallLocation "C:\ProgramData\App"
!macroend
```

everything seems to work, but since `perMachine` is set to  `false`, but the App is kind of installed per machine, I was wondering if this kind of setup can lead to any problems?

**Comment by DrewHagenAtInfiniteCampus** [comment]
I'm currently looking for the same solution as you described.

Have you been continuing to run with this the last few months and found any concerns?
Also, do you do any auto-update logic? We're getting burned by the UAC prompts on auto-update.

> I was wondering if this kind of setup can lead to any problems?

On the top of my head, I wonder what happens when multiple users are logged into Windows and have the software open, then one user gets an auto-update or manually tries to update the software. Have you tested that or had any production users encounter issue with that?

**Comment by capc0** [comment]
We are currently not using the described solution above. Instead we install per user. This leads to larger windows user profiles, but currently works best for us. Also using auto update which does not throw a UAC prompt (no admin permissions needed) if you install per user.
