### ISSUE TITLE
nsis: remove previous installation before install (all variants — per-user or per-machine)

### ISSUE THREAD

**Issue by atypicalprogrammer** [electron-userland/electron-builder#621]
Can I easily (with NSIS) move the user in an update of the app from a local to a machine-wide install (in c:/program files)? So that user is not left with multiple versions installed?

And why isn't machine-wide install recommended? 

Thanks!

**Comment by develar** [comment]
> Can I easily (with NSIS) move the user in an update of the app from a local to a machine-wide install (in c:/program files)? 

Yes, it seems you ask about feature (installer should check local and per-machine installations).

> And why isn't machine-wide install recommended?

Awkward UAC will be required to auto-update. Well, maybe it is ok. Well, maybe when auto-update will be implemented, installation will be per-machine by default.

**Comment by atypicalprogrammer** [comment]
What do you mean "it seems you ask about feature"? 

So if the user had previously installed locally, a new version which installs system-wide will automatically remove the local copy? This is what is needed, because I don't want two copies of the app on the user system.

**Comment by dharders** [comment]
Instead of 'remove' previous installation, I'd suggest '**move**' previous installation.

Care must be taken not to lose valuable data in `localStorage`, `indexDB` etc of the previous installation.

**Comment by develar** [comment]
@dharders Good point, auto uninstall must not remove local app-data.

**Comment by develar** [comment]
First part: per-machine installer automatically removes previous per-machine installation.

**Comment by mistersdevelopment** [comment]
I am experiencing an issue which I believe is related to this one. I am using electron-builder version 20.40.2.

I have two versions of my application (call them "Old" and "New").

"Old" has this configuration:
```
    "nsis": {
        "oneClick": false,
        "perMachine": false,
        "guid": "932e8623-b12b-496a-8de5-1ed94eea956b" // Not my actual GUID.
    }
```

"New" has this configuration:
```
    "nsis": {
        "oneClick": true,
        "perMachine": false,
        "guid": "932e8623-b12b-496a-8de5-1ed94eea956b" // Not my actual GUID.
    }
```

When "Old" is installed for "Anyone who uses this computer (all users)":
![image](https://user-images.githubusercontent.com/33233485/57883313-724a4280-77eb-11e9-94be-f968cc5378f4.png)

and "New" is installed (with one-click installer):
![image](https://user-images.githubusercontent.com/33233485/57883642-775bc180-77ec-11e9-9569-919c6a5106ed.png)

The "Old" application is not uninstalled from "C:\Program Files" after the "New" application is installed. This leaves the user with two versions of the application, one in "C:\Program Files" and one in "C:\Users\USER_NAME\AppData\Local\Programs".

This does not happen if the "Old" application is installed "Only for me":
![image](https://user-images.githubusercontent.com/33233485/57884130-927b0100-77ed-11e9-9941-11f5b76c2725.png)

The behavior I would expect is that regardless of how the "Old" application was installed the "New" application should uninstall the "Old" application correctly.

My guess is that this is related to a permissions issue since uninstalling the "Old" version when it was installed via the "Anyone who uses this computer (all users)" option would require UAC consent.
