### ISSUE TITLE
support native modules in  new electron version v15

### ISSUE THREAD

**Issue by kevinwang930** [electron-userland/electron-builder#6352]
* **Electron-Builder Version**:  22.14.5

* **Node Version**: v16.11

* **Electron Version**: v15.2.0
* **Electron Type (current, beta, nightly)**: current

* **Target**:  nsis

electron-builder command install-app-deps only works with electron version ^13 when building native modules,  can anyone kindly explain what is the situation now ?

**Comment by mmaietta** [comment]
>only works with electron version ^13 

That's bizarre, it's worked historically for many different versions of electron for me.
Are you saying that it no longer works specifically for electron 15?

**Comment by kevinwang930** [comment]
It's the node abi version problem I think 
```
> electron-builder install-app-deps

  • electron-builder  version=22.14.5
  • loaded configuration  file=E:\code\myApp\electron-builder.yml
  • rebuilding native dependencies  dependencies=better-sqlite3@7.4.3 platform=win32 arch=x64
  • install prebuilt binary  name=better-sqlite3 version=7.4.3 platform=win32 arch=x64 napi=
  • build native dependency from sources  name=better-sqlite3
                                          version=7.4.3
                                          platform=win32
                                          arch=x64
                                          napi=
                                          reason=prebuild-install failed with error (run with env DEBUG=electron-builder to 
get more information)
                                          error=E:\code\myApp\node_modules\node-abi\index.js:36
      throw new Error('Could not detect abi for version ' + target + ' and runtime ' + runtime + '.  Updating "node-abi" might help solve this issue if it is a new release of ' + runtime)
      ^

    Error: Could not detect abi for version 15.2.0 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron
        at getAbi (E:\code\myApp\node_modules\node-abi\index.js:36:9)
        at module.exports (E:\code\myApp\node_modules\prebuild-install\rc.js:52:57)
        at Object.<anonymous> (E:\code\myApp\node_modules\prebuild-install\bin.js:8:25)
        at Module._compile (node:internal/modules/cjs/loader:1101:14)
        at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
        at Module.load (node:internal/modules/cjs/loader:981:32)
        at Function.Module._load (node:internal/modules/cjs/loader:822:12)
        at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
        at node:internal/main/run_main_module:17:47


up to date, audited 1745 packages in 23s
```

**Comment by m4heshd** [comment]
@vladimiry There's no issue with the prebuilds. `prebuild` uses an up-to-date version of `node-abi` which does the job fine. I've carefully tracked the issue down to [`app-builder-bin`](https://github.com/develar/app-builder/blob/e229f413d635b78a59b0d4ef1a9aa0f3967c0fd4/pkg/node-modules/rebuild.go#L202) which seem to be using an old version of `prebuild-install` (not sure, probably). It simply fetches the incorrect prebuild asset. `prebuild-install` just updated `node-abi` only two days ago.

### Deps used in my test case:
- Electron - 15.3.1 _(ABI - 98)_
- electron-builder - 22.13.1
- better-sqlite3-multiple-ciphers - 7.4.4

In my test, `app-builder-bin` seems to be fetching `better-sqlite3-multiple-ciphers-v7.4.4-electron-v89-win32-x64.tar.gz` instead of [`better-sqlite3-multiple-ciphers-v7.4.4-electron-v98-win32-x64.tar.gz`](https://github.com/m4heshd/better-sqlite3-multiple-ciphers/releases/download/v7.4.4/better-sqlite3-multiple-ciphers-v7.4.4-electron-v98-win32-x64.tar.gz). Once I manually download the latter and set it up, everything works as expected. It leads to the conclusion that `prebuild` did the job correctly.

### Possible cause:

If you look at [`electron-releases`](https://www.npmjs.com/package/electron-releases) you'll see that Electron used ABI version `89` till the release of `v15.0.0-beta.7`.

![image](https://user-images.githubusercontent.com/6711514/141697124-3d05b5c8-5520-49e5-aed0-ce3e5082a16c.png)

I'm baffled by why that is because I usually see @codebytere snatching these ABI versions up during nightly releases but in the end this seem to have messed up a lot of native dependency related tools. 

We just need an update for `app-builder-bin`. I hope @develar can shed some light on this.

**Comment by vladimiry** [comment]
> @vladimiry There's no issue with the prebuilds.

I didn't say that there is an issue with prebuilds, it's your words, but that I don't use prebuilds at all. So I'm more interested in the native modules to be compilable at my side than being served with correct prebuilds.

**Comment by m4heshd** [comment]
Ok scratch my previous rant. I just realized while looking through the source of [`app-builder`](https://github.com/develar/app-builder), that it uses whatever version of `prebuild-install` installed in the root project or through a peer. So we just need to update `prebuild-install` to `7.0.0`. 

> I didn't say that there is an issue with prebuilds, it's your words

What I tried to respond to was you saying it's something wrong with `better-sqlite3`. Bad wording on my part.

> So I'm more interested in the native modules to be compilable at my side than being served with correct prebuilds.

Prebuilt assets makes large workflows run faster and makes the process of trying it out much easier for fairly new users. Otherwise the issue tracker gets polluted by users asking "How to compile?". Just my opinion.

For the moment, even installing the latest version of `prebuild-install` would do the trick.
