### ISSUE TITLE
Feature request: Allow files from outside current directory (monorepo)

### ISSUE THREAD

**Issue by florianbepunkt** [electron-userland/electron-builder#6558]
I have a monorepo structure with NPM workspaces. Everything works fine except that I need to manually add files from the root package, which electron builder does not allow

Structure

- root
-- package a (electron app)

So package a has the follwing files config

```json
files: [{
      from: '../../node_modules/.prisma/client/',
      to: '../../node_modules/.prisma/client/',
}]
```

This gives the following error:
```
  ⨯ Internal error: path must not start with "..": ../../node_modules/.prisma/client  failedTask=build stackTrace=Error: Internal error: path must not start with "..": ../../node_modules/.prisma/client
```

* **Electron-Builder Version**: 22.14.5
* **Node Version**:  v16.10.0
* **Electron Version**: 16.0.7
* **Electron Type (current, beta, nightly)**:
current

* **Target**:

**Comment by lukeshumard** [comment]
Have you tried using the `nohoist` option for `workspaces` in your `package.json` file? More info can be found [on Yarn's website](https://classic.yarnpkg.com/blog/2018/02/15/nohoist/). I have a feeling this is absent in npm workspaces at the moment from my initial reading.

I'm using a monorepo with [Turborepo](https://turborepo.org/) and using Yarn as the package manager. The monorepo has an Electron app and this worked for me when `electron-builder` could not find `electron` due to hoisting.
```package.json
{
  "workspaces": [
    "apps/*",
    "packages/*"
  ],
  "nohoist": ["**/electron"]
}
```

This is definitely a workaround and possibly related to #6448, but the above resolved my issue.

**Comment by florianbepunkt** [comment]
@lukeshumard Thank you. We are on NPM and there is no such option. As far as I know Yarn also changed this mechanism in Yarn2 so there is no "nohoist" option on Yarn berry
