### ISSUE TITLE
Rebuilding dependencies take forever

### ISSUE THREAD

**Issue by d3v0ps** [electron-userland/electron-builder#6596]
* **Electron-Builder Version**: 22.14.5

* **Node Version**: 16

* **Electron Version**: 16.0.8
* **Electron Type (current, beta, nightly)**:

* **Target**: Windows

Rebuilding dependencies never finishes. Got this error running the builder inside a [github action](https://github.com/samuelmeuli/action-electron-builder) with windows-latest, but I also got it running locally on Windows 11 WSL. Original issue [here](https://github.com/samuelmeuli/action-electron-builder/issues/72)

**Comment by mmaietta** [comment]
Out of curiosity, have you tried building with `electron-rebuild` to see if it's an env-related issue or not?

**Comment by d3v0ps** [comment]
HI @mmaietta no, I didn't know about that `electron-rebuild` command but as far as I know, the `electron-builder` package is the responsible to perform that operation (I guess through internally executing the `electron-rebuild` one). As it's an error happening in different environments and one of them being the Windows image from Github Actions I don't think it's an environment issue (or at least not something related with my code).

I just saw there's an `electron-forge` package, what's the difference with this one?

**Comment by mmaietta** [comment]
`electron-builder` uses a custom implementation written in Go (`app-builder-bin`). `electron-rebuild` is a package maintained by `electron` project themselves. I've contemplated migrating `electron-builder` to utilize `electron-rebuild`, but right now, the package significantly pollutes the console with verbose logs (due to bug in node-gyp ignoring --quiet flag).

`electron-forge` is another packager like `electron-builder` but the two are not associated with each other. I think `electron-builder` also provides additional functionality, such as auto-updates and publishing? I'm honestly not familiar with `electron-forge` to confirm differences though.

**Comment by notmedia** [comment]
Also get this problem when building on Windows in GitHub Actions.
I had `postinstall` script - `electron-builder install-app-deps`. Changed to electron-rebuild tool solved this issue. @mmaietta FYI

**Comment by notmedia** [comment]
@mmaietta I think it would be grate if you place it in docs.

**Comment by mmaietta** [comment]
@notmedia it already is :)
>If you want to use js file, do not name it electron-builder.js. It will [conflict](https://github.com/electron-userland/electron-builder/issues/6227) with electron-builder package name.

https://www.electron.build/configuration/configuration
