### ISSUE TITLE
msi Squirrel package does not run .exe after installation

### ISSUE THREAD

**Issue by DavidDurman** [electron-userland/electron-builder#660]
* **5.15.0**: 

* **squirrel**: 

Our build section of package.json looks like:

```
  "build": {
    "appId": "myapp",
    "win": {
      "target": ["squirrel"],
      "icon": "myapp/icon.ico",
      "msi": true
    }
   }
```

We run `build --win --ia32`. This generates a .msi file. When we run this .msi, the installation procedure creates a directory "my app Installer" in the Program Files directory. This directory contains .exe file which does the actual installation to (AppData/Local directory) where the actual electron application is put. However, we would like to associate our application with file extensions right during the installation phase. Is that possible?

**Comment by develar** [comment]
Duplicates #608

> we would like to associate our application with file extensions 
> right during the installation phase. Is that possible?

Consider to use NSIS target. file associations supported.

**Comment by DavidDurman** [comment]
Unfortunately, NSIS is not an alternative for Enterprise installations.

**Comment by develar** [comment]
I understand, that you want normal MSI installer. Unfortunately, Squirrel assume that you do all setup work on squirrel events. Can we build normal MSI installer? Yes — but I will not do it because no time.  Please don't expect that electron-builder will create proper MSI soon.  

> Unfortunately, NSIS is not an alternative for Enterprise installations.

Well.... no one forbid you to wrap nsis installer onto MSI as a quick workaround :)

**Comment by DavidDurman** [comment]
Right, thanks! We'll try http://www.exemsi.com/download. Thanks for the prompt responses!
