### ISSUE TITLE
`app-update.yml` not generated when building using the `--dir` flag

### ISSUE THREAD

**Issue by vraravam** [electron-userland/electron-builder#6876]
* **Electron-Builder Version**: 23.0.8

* **Node Version**: 16.15.0

* **Electron Version**: 18.2.4
* **Electron Type (current, beta, nightly)**: current

* **Target**: mac

I run `npm run build -- --x64 --mac --dir` to build the electron app since I'm targetting building the packaged app for local testing. But, when using the `--dir` flag, the `app-update.yml` file is not generated, and so I cannot test the autoupdater functionality.

**Comment by mmaietta** [comment]
mac auto-updates require a zip and as part of that pipeline, the app-update.yml is created. It will not be created for dir-only builds, so that is behaving as expected.

I believe you can set up a localhost server with electron-builder's generic publisher, from there you can test auto-updates. There's also this that might still be up to date for testing: https://www.electron.build/tutorials/test-update-on-s3-locally
