### ISSUE TITLE
windowsExecutableCodeSignatureVerifier fails in PowerShell Constrained Language Mode

### ISSUE THREAD

**Issue by jeremyspiegel** [electron-userland/electron-builder#6917]
* **Electron-Builder Version**: 23.0.3

* **Node Version**: 16.14.0

* **Electron Version**: 18.1.0
* **Electron Type (current, beta, nightly)**: current

* **electron-updater version**: 5.0.1

* **Target**: nsis

windowsExecutableCodeSignatureVerifier.ts is failing for some users with this error:

> Cannot execute Get-AuthenticodeSignature, stderr: Cannot invoke method. Method invocation is supported only on core types in this language mode. At line:1 char:175 + ... ch-Object { [Convert]::ToBase64String([System.Text.Encoding]::UTF8.Ge ... + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : InvalidOperation: (:) [], RuntimeException + FullyQualifiedErrorId : MethodInvocationNotSupportedInConstrainedLanguage . Failing signature validation due to unknown stderr.

I believe this is due to PowerShell Constrained Language Mode: https://devblogs.microsoft.com/powershell/powershell-constrained-language-mode/

**Comment by burgil** [comment]
Hey, How do I reproduce this error do you know maybe?

**Comment by jeremyspiegel** [comment]
Sorry I was wrong about it being the `Get-AuthenticodeSignature` part, it's actually the `[Convert]::ToBase64String` and `[System.Text.Encoding]::UTF8.GetBytes` that the result is piped into that's failing.

To reproduce, set a system environment variable __PSLockDownPolicy=4 (make sure to select OK in the Environment Variables window):
<img width="1234" alt="image" src="https://user-images.githubusercontent.com/776117/172072895-36f02dc0-393f-4e1e-97c5-60fddf373c23.png">

Then open a new PowerShell window and test `[System.Text.Encoding]::UTF8.GetBytes` or `[Convert]::ToBase64String`:
<img width="1127" alt="image" src="https://user-images.githubusercontent.com/776117/172072993-7f3462ba-518a-4eb3-acb9-3b0ded455226.png">

**Comment by burgil** [comment]
Not sure if that helps:
![image](https://user-images.githubusercontent.com/41600149/172073360-388fa0e7-22e1-4df5-a47f-8e83c3a1fc70.png)

And also did you know powershell is being maintained and updated by the minute? check it out:
https://github.com/PowerShell/PowerShell

You can also download the newest version there and it's supposed to be awesome, I was too afraid to get it to avoid compatibility issues..

I did not how ever set the env variables I was too lazy sorry let me know if you want me to lol

**Comment by burgil** [comment]
I just realized that the problem is coming from `electron-updater`, I think you are right yes it should work regardless of Powershell version, I just let you know you can update it, but yeah now I know that the problem is in other people computers, your users, I misread that part, perhaps one of the contributors here knows something, good luck with that

If you are looking for a quick hack, check if that environment variable is set, and delete it during the update process using some hook there, and as soon as it finished updating check if it was removed and restore it in that case..

Or you can like make a simply check that checks if that environement variable is there and if so it puts a message box saying `your pc configuration is preventing the updater from running, please remove this, or do this`
Could be a great start to debug it too, I will start from there and evolve to the first option..

But of course if anybody here can actually fix it yeah.. that will be the ultimate solution. I'm just a random guy here :)

**Comment by jeremyspiegel** [comment]
The environment variable is a way to set PowerShell in that mode for debugging purposes, but there are other ways to set it that can't be circumvented (like AppLocker or Group Policy Software Restriction settings).

**Comment by jeremyspiegel** [comment]
I've added a PR to address this: https://github.com/electron-userland/electron-builder/issues/6917
