### ISSUE TITLE
Not Publishing Artifacts to Github for Linux .rpm and .deb

### ISSUE THREAD

**Issue by jameskerr** [electron-userland/electron-builder#6942]
* **Electron-Builder Version**: 

Version 23.0.3

* **Node Version**: 

17.0.1

* **Electron Version**:
* **Electron Type (current, beta, nightly)**:

* **Target**: 
Linux rpm and deb

Linux is not publishing artifacts to Github while Mac and Windows do.

<img width="1212" alt="image" src="https://user-images.githubusercontent.com/3460638/173403257-0a064afc-281a-4e21-a87e-c8a4521e71d9.png">

<img width="679" alt="image" src="https://user-images.githubusercontent.com/3460638/173421890-c3bd548c-4e5a-489b-81b0-c4b72232689a.png">

**Comment by mmaietta** [comment]
This is not a bug because electron-builder doesn't support auto-update functionality for deb or rpm, so publishing only works for AppImages currently.

That being said, I've proposed a solution to support it in PR https://github.com/electron-userland/electron-builder/pull/7060
It's a Draft PR, and I could really use some feedback on the implementations of RpmUpdater and DebUpdater `/bin/bash` logic
