### ISSUE TITLE
Use dotenv or other way

### ISSUE THREAD

**Issue by StrangerGithuber** [electron-userland/electron-builder#7143]
Hello
When I am using the dotenv package then it works when I run the application in development mode however when I am using electron-builder and making executable my application then the dotenv doesn't work as should.
I tried to use process.env.TESTSOMETHING and I did put into .env file TESTSOMETHING = "Test message" but it gives undefined message instead so I suppose the dotenv package (https://www.npmjs.com/package/dotenv) not working properly after built the app.

I added this too:
require('dotenv').config()

Therefore in development mode my app works but not in built version.
What I am missing? Is there a method to fix it or there is other methods to able use .env file in development and in production?

Thank you in advance the answers.

**Comment by Woofer21** [comment]
Hello!

I also need help getting my ENVs in the final package, please advise on what to do.

**Comment by mmaietta** [comment]
ENVS don't load in the distributable, as electron-builder is a packager, not a bundler. ENVs only load for configuring the packaging step.
[comment](https://github.com/electron-userland/electron-builder/issues/6652#issuecomment-1042568422)

**Comment by gavan1** [comment]
@mmaietta Thanks for this clarification! 

I still have yet to to come across a thread or doc in one direct statement how to get it working. You're closing comment helped a lot to getting a better understanding of the issue.

Given I am working with NEXTjs and as @mmaietta pointed out, the issue is in the bundler you are using... in my [case](https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables).

adding "NEXT_PUBLIC_" next to the variable will tell the bundler to include it.

@N2D4 But some libraries will expect  ie "STACK_SECRET_SERVER_KEY" to not have "NEXT_PUBLIC_" in front of it.

Next docs mentions leveraging the `@next/env` lib and creating a  `envConfig.ts`as an example. 

```
import './envConfig.ts'
 
export default defineConfig({
  dbCredentials: {
    connectionString: process.env.DATABASE_URL!,
  },
})

```

@N2D4 can Stack Auth support an electron app?
