### ISSUE TITLE
Consider including notarization by default

### ISSUE THREAD

**Issue by ianstormtaylor** [electron-userland/electron-builder#7201]
It would be amazing if `electron-builder` could bundle and automate the `electron-notarize` process by default for mac apps. It would just involve taking in the extra Apple ID-specific credentials. 

And the experience could be greatly improved with `electron-builder`'s logging output. (Ideally even printing the notarization errors that come up by requesting the log URLs Apple provides and printing them. And then printing something helpful on status/success.)

**Comment by mmaietta** [comment]
@ianstormtaylor I can take a stab at doing this and implement it in the next release of electron-builder v24-alpha. Would you be willing to test it? I can add you as a PR reviewer
My Apple account is no longer valid, so notarization fails with a 403 😅

**Comment by ianstormtaylor** [comment]
@mmaietta that would be awesome! As soon as the holidays are over I'm happy to test it out.

**Comment by mmaietta** [comment]
@ianstormtaylor The notarization step automatically activates if you define `APPLE_ID` & `APPLE_APP_SPECIFIC_PASSWORD` env vars.

You can use this object to configure special behavior, otherwise, default tool is `legacy`
https://github.com/electron-userland/electron-builder/blob/a6d135ddacebeca54eb049f0b6430fa433d0cac5/packages/app-builder-lib/src/options/macOptions.ts#L217-L233

**Comment by popod** [comment]
Hi @mmaietta

What is the default notarization status ? Will my current generated app be notarized if I keep my actual electron-builder configuration ?

I notarize the build with the afterSign hook and do not want that the notarization process run before.

Thank you

**Comment by mmaietta** [comment]
Set 'notarize: false' in your config to explicitly deactivate
