### ISSUE TITLE
Signing AppX not working on Windows 11

### ISSUE THREAD

**Issue by michalzaq12** [electron-userland/electron-builder#7203]
* **Electron-Builder Version**:  23.6.0
* **Node Version**:  16.16.0
* **Electron Version**:  21.1.1
* **Windows**: 11

Signing AppX not working on Windows 11
Electron-builder output:

```
Exit code: 1. Command failed: C:\Users\Michal\AppData\Local\electron-builder\Cache\winCodeSign\winCodeSign-2.6.0\windows-10\x64\signtool.exe sign /tr http://timestamp.digicert.com /f C:\Users\Michal\Desktop\
cert.pfx /fd sha256 /td sha256 /p <...> /debug <..>\build\MyApp.appx

SignTool Error: Multiple signature support is not implemented for this filetype.
SignTool Error: An error occurred while attempting to sign: <..>\build\MyApp.appx

```

This is possibly a known bug in Windows 11 ? https://github.com/electron-userland/electron-builder/pull/6817

I used `signtool` from: `C:\Program Files*\Windows Kits\*\bin\*\x64\signtool.exe` instead of electron-builder cache and it works fine.

**Comment by rainbean** [comment]
@michalzaq12, the bundled sign-tool of electron-builder Windows build is outdated. You might overwrite the bundled sign-tool by specify the proper executive path, eg. `$env:SIGNTOOL_PATH = "C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x64\signtool.exe"`

**Comment by marf** [comment]
Hi, I tried to overwrite the `signtool.exe` the problem is that I receive this output:

` Command failed: C:\Users\fonta\AppData\Local\electron-builder\Cache\winCodeSign\winCodeSign-2.6.0\windows-10\x64\signtool.exe sign /t http://timestamp.digicert.com /sha1 CD54BFB9098EC5D036EF05D64D53488E3478B9C7 /s My /d eSound Music /du https://github.com/Spicy-Sparks/eSound-Desktop-Releases#readme /debug C:\Projects\eSound-Client\desktop\electron\dist\win-unpacked\eSound Music.exe`

`SignTool Error: No file digest algorithm specified. Please specify the digest algorithm with the /fd flag. Using /fd SHA256 is recommended and more secure than SHA1. Calling signtool with /fd sha1 is equivalent to the previous behavior. In order to select the hash algorithm used in the signing certificate's signature, use the /fd certHash option.`

because electron-builder uses `/sha1` command instead of `/fd` since it uses an old version of `signtool.exe` how can I fix this?

Thanks!

**Comment by rainbean** [comment]
@marf

Would you give it a try to specify hash algorithm in your build config file? Reference  https://www.electron.build/configuration/win
> signingHashAlgorithms = ['sha1', 'sha256'] Array<“sha256” | “sha1”> | “undefined” - Array of signing algorithms used. For AppX sha256 is always used.

**Comment by marf** [comment]
> @marf
> 
> Would you give it a try to specify hash algorithm in your build config file? Reference https://www.electron.build/configuration/win
> 
> > signingHashAlgorithms = ['sha1', 'sha256'] Array<“sha256” | “sha1”> | “undefined” - Array of signing algorithms used. For AppX sha256 is always used.

I removed the sha1 from the array and specified only the sha256 and that issue seems to be solved.

The problem is that by also substituting the original `signtool.exe` with the one in this path `"C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x64\signtool.exe"` it still give me the error:

`SignTool Error: Multiple signature support is not implemented for this filetype.`

**Comment by marf** [comment]
Any ideas on how to fix this issue?

Thanks!

**Comment by rainbean** [comment]
@marf, it is quite clear, in your attached screenshot and text logs, that correct `signtool` was not specified but electron-builder bundle one. It's suggested to specify compatible `signtool.exe` by environment variable `$env:SIGNTOOL_PATH` as previous comment.
