### ISSUE TITLE
A Issue I'm having when I export my gdevelop game manually.

### ISSUE THREAD

**Issue by MeanieSturgill** [electron-userland/electron-builder#7208]
When I export my game this manually, I get a warning about the osx sign. When I uninstall & reinstall node.js & yarn, I still get an warning about the osx sign. But I also got the warning about asar. And those are the things I'm pretty sure causes my game to crash before my even opened. What can I do?
![Screenshot (65)](https://user-images.githubusercontent.com/45501694/197318681-b2391f23-a223-4233-a0b6-06ec0dacf348.png)

**Comment by arthuro555** [comment]
> And those are the things I'm pretty sure causes my game to crash before my even opened.

I very much doubt it. As the warning itself says, this is just a new name for a dependency under which new updates to it will be published in the future. This is really not an issue that would impact your builds at all.

> I get a warning about the osx sign

The warning about OSX sign is most likely just because you are building on Windows and I am pretty sure that you cannot build for OSX on Windows.

---

What I did see impact builds in the past is putting special symbols in your game name, version, or app ID (package name in GDevelop), which can cause a segfault when launching the executable.

**Comment by MeanieSturgill** [comment]
> What I did see impact builds in the past is putting special symbols in your game name, version, or app ID (package name in GDevelop), which can cause a segfault when launching the executable.
I'll go fix that by removing the special symbols. Thank you for telling me that.

**Comment by MeanieSturgill** [comment]
It works! Thank you!
