### ISSUE TITLE
Environments variables from `electron-builder.env`

### ISSUE THREAD

**Issue by vitaliyzolotoy** [electron-userland/electron-builder#7249]
* **23.0.3**: 

* **14.18.1**: 

* **21.0.1**:
* **current**:

* **mac**: 

Hi, environments variables from `electron-builder.env` are ignored while building app

**Comment by briosheje** [comment]
Are you sure? I have no issues with version `^23.0.2`

**Comment by vitaliyzolotoy** [comment]
@briosheje For me it is not working, I placed file into root directory of angular project, maybe it should be placed in app/main.ts, where is main file of electron app

**Comment by mmaietta** [comment]
Hmmm Are you trying to use the env vars at runtime? If so, that's not how a packager works.

**Comment by vitaliyzolotoy** [comment]
@mmaietta I tried to use env vars in packager mode

**Comment by bblanke** [comment]
I have the same problem. I'm attempting to use the environment variables in `electron-builder.json` like so:
```
{
  "appId": "${env.APP_BUNDLE_ID}",
  "productName": "${env.APP_NAME}",
  "buildVersion": "${env.APP_VERSION}",
  ...
  }
  ```
  
  I've also tried using `dotenv-cli` to source my dotenv file before running electron-builder like so:
  ```
  dotenv electron-builder build
  ```
  
  It seems that the `env` file macro described [here](https://www.electron.build/file-patterns#file-macros) does not work.

**Comment by Slapbox** [comment]
It works for us on Windows with Electron Builder 23.x. Haven't tested newer.

**Comment by bblanke** [comment]
I ended up getting environment variable substitution into the electron-builder config by switching to a javascript config:

```javascript
// electron-builder-config.js

const dotenv = require("dotenv");
dotenv.config();

const config = {
  appId: `${process.env.APP_BUNDLE_ID}`,
  productName: `${process.env.APP_NAME}`,
  buildVersion: `${process.env.APP_VERSION}`,
  ...
}
 
module.exports = config;
```

```json
// package.json
{
  ...
  "scripts": {
    "package": "electron-builder build --config electron-builder-config.js",
      ...
    }
}
```

**Comment by qazhub** [comment]
Environment variable placeholders in `artifactname`s are working, but not placeholders in fields like `appId` or `productName`. As seen in the code [here](https://github.com/electron-userland/electron-builder/blob/80a3ae857b9305aff1774e1b2b932601af50231b/packages/app-builder-lib/src/appInfo.ts#L65) only `copyright` field expands macros inside it, other fields expect literal values.
So if you set `productName: "${env.APP_NAME}"` eletron-builder will pass the value literally to the bundler, e.g. NSIS, then certain bundlers (NSIS in my case) would throw error because they don't know a variable named `env.APP_NAME`.

Converting config to JS file seems to be the right way to go.
