### ISSUE TITLE
How can I customize package.json that app data will be removed for Linux && Mac?

### ISSUE THREAD

**Issue by apipaliya** [electron-userland/electron-builder#7265]
electron version: 17.4.3
electron-builder version: 23.3.3

I need to delete app user data for all supported platforms (Linux, Mac), when application uninstalled. 

How can I customise package.json that app data will be removed for Linux && Mac?

**Comment by FireMapleLeaves** [comment]
same question

**Comment by mmaietta** [comment]
linux deb config has a property for `afterRemove` for running a script, where you could remove user data. rpm config allows fpm args to be provided, you'd use `--after-remove FILE` (https://fpm.readthedocs.io/en/v1.14.0/cli-reference.html)

MacOS doesn't support any uninstall events since it's just a `.app` delete from the filesystem
