### ISSUE TITLE
Is it possible to check to see if the file is *already* downloaded?

### ISSUE THREAD

**Issue by jpheneger** [electron-userland/electron-builder#7272]
* **Electron-Builder Version**: 23.6.0
* **Node Version**: 16.7.1
* **Electron Version**: 19.1.4
* **Electron Type (current, beta, nightly)**: current
* **Electron Updater Version**: 5.3.0
* **Target**: win/mac

When our app starts we register for multiple events from autoUpdater.  We observe that when an update is available the 'update-available' event is triggered, and when the update has completed downloading the 'update-downloaded' event is triggered.

However, if the update was already downloaded, the 'update-available' event triggers before the 'update-downloaded' event triggers.  This means that we prompt the user to download the update, and then *IMMEDIATELY* tell the user that it is downloaded.

We would be able to work around this issue if the cacheDir was exposed so that we could check to see if the file exists before prompting our users to download the update.

**Comment by mmaietta** [comment]
Not currently AFAICT. Happy to review a PR adding that `update-*` functionality in if you're willing to contribute!

**Comment by jpheneger** [comment]
I am happy to contribute, there are a couple of different ways this could be addressed:
1. the most obvious way would be to expose the cacheDir variable so that I could check the directory myself.
    a. This requires that I add logic to check for the file *AND* account for all operating systems that I support (not ideal).
3. Export a new variable from the updater that indicates whether or not the update was already downloaded.
    a. This removes the need for users to add logic, but does require exposing the inner workings a bit.  Would require some documentation/education to be adopted widely.
4. Add the variable "downloaded" to the UpdateInfo interface.  When generating the "update-available" event, check to see if the file already exists in the cachDir.  If it does, set "downloaded" to true.
    a. This has the benefit of exposing the downloaded state with the least amount of impact while also not exposing the inner workings of the library.  It also means that any operating system specific logic is contained to the library.

Thoughts?

**Comment by mmaietta** [comment]
AFAICT, the logic flow doesn't allow any of those approaches.  `update-available` is purely checking server existence of an update. `update-downloaded` only occurs in the `done(() => {})` callback with `UpdateDownloadedEvent`, but that's after it checks for the cache during the download flow. We can easily add a `isCached` to the `update-downloaded` event, but then the `update-available` event still exists without solving for your request.

Are you willing to adjust your UX flow? Instead of having two prompts/notifications, use something "Download & Install" as the only notification prompt?

I'm still trying to brainstorm how we could achieve the `isCached` eval
