### ISSUE TITLE
if electron-updater didnt finish installation and user shutdown the pc how to revert to the previous version

### ISSUE THREAD

**Issue by Sajad321** [electron-userland/electron-builder#7321]
Hello,
I am asking about to revert the user to the previous version if the installation process didnt complete successfully or the user shutdown the pc

**Comment by mmaietta** [comment]
No it's not possible AFAIK.
Once an update installer process is executed, it is detached. electron-builder/updater can't receive events from it to know that a previous install didn't complete (if it did, then the app would already have to be running successfully in order for it to read any previously recorded "app/update state" and discern that an install didn't complete properly)

In order for it to work, the updater/installer would need to register a Start Up service or program to run separately and verify if the updater was successful. That being said, it'd still run into the same issue if the Start Up process was unable to be setup due to a user shutting down their PC.
