### ISSUE TITLE
NSIS Multi Language  License File support does not work

### ISSUE THREAD

**Issue by zanzara** [electron-userland/electron-builder#7334]
* **Electron-Builder Version**: 23.6.0 

* **Node Version**: 16.16.0 

* **Electron Version**: 21.1.0
* **Electron Type (current, beta, nightly)**: current

* **Target**:  Windows10 64bit

I have multiple license files as `license_en.html`  and `license_de.html`  i.e.
but it doesn't matter in which folder I put them, the installer `setup.exe` will never show them.

If i put the `license` prop directly to one license  file location as ie.
`license: license_en.html`
it works.

So I assume, that this feature does not work as described in the electron-builder docs under
[https://www.electron.build/configuration/nsis](https://www.electron.build/configuration/nsis)

**Comment by ielektronick** [comment]
I do understand that the issue is closed more than a year ago, but still.

According to `app-builder-lib` package source code, the license files could be placed in root on build resources (https://www.electron.build/nsis#license), meaning if you put the license files (`license_de.txt`, `license_en.txt` etc) to the root and run electron-builder to make nsis installer, the files should be handled accordingly. 

To check it, after the installer script review the `builder-debug.yml` file. There should be something like:

```
!macro licensePage
  LicenseLangString MUILicense 1033 "path\build\license_en.txt"
  LicenseLangString MUILicense 1031 "path\build\license_de.txt"
  !insertmacro MUI_PAGE_LICENSE "$(MUILicense)"
!macroend
```
