### ISSUE TITLE
Can't open the app after sign

### ISSUE THREAD

**Issue by CaptainRann** [electron-userland/electron-builder#7463]
* **Electron-Builder Version**: 23.6.0

* **Node Version**: 16.15.1

* **Electron Version**:20.3.1
* **MacOS Version**:13.2.1

![截屏2023-03-06 22 56 32](https://user-images.githubusercontent.com/112359898/223148579-dd27393a-c4c7-401d-ac0f-4fd2eb008838.png)

On Mac(m1) only build for arm64 have an issues , I found before signing the application can working.After singing can't.
But 'x64' can working.

p.s
dev can working
i try a new project arm64 can work.
i'm this project which one i writing is normality.because last moth it can work

**Comment by mmaietta** [comment]
If it's a new project that works, then it sounds like your other project either `entitlements` are incorrectly set (not the config path, but the actually key-values in the entitlements) or the app is not being notarized?
It's hard to say from the info provided, but considering 23.6.0 has been out for 5 months, I'm hesitant to say that this is an electron-builder bug.

**Comment by lurdbinanc** [comment]
Done Null On 6 Mar 2023, at 4:09 PM, CaptainRann ***@***.***> wrote:﻿




Electron-Builder Version: 23.6.0



Node Version: 16.15.1




Electron Version:20.3.1
MacOS Version:13.2.1



On Mac(m1) only build for arm64 have an issues , I found before signing the application can working.After singing can't.
But 'x64' can working.
p.s
i try a new project arm64 can work.
i'm this project which one i writing is normality.because last moth it can work
