### ISSUE TITLE
Unable to access a file inside asar pacakge

### ISSUE THREAD

**Issue by makeitcount** [electron-userland/electron-builder#751]
* **Version**: 6.7.3
* **Target**: Linux, Windows

I have some scripts in my app, which I need to execute when application starts. I am allowing asar packaging in the project. It throws following error at runtime
`Can't open /tmp/.mount_ryQosd/usr/bin/resources/app.asar/myfolder/subfolder/myscripts/myscript1.sh`

This does not happen during development so this seems to be error with asar packaging, not allowing to access the file.
Although it's not preferred but I tried unpacking myscripts folder by adding this in build options `"asar": {  "unpackDir": "myfolder/subfolder/myscripts"  }`, it did not work either. I get the same error.

Am I writing the right syntax for unpackDir?
Is there any alternative so that script file can be accessed during runtime?

Thanks

**Comment by develar** [comment]
> Am I writing the right syntax for unpackDir?

Path must be relative  to project base dir. Or, just `myscripts`.

**Comment by makeitcount** [comment]
@develar the path is relative to app directory. Script is at app/myfolder/subfolder/myscripts/myscript.sh
I am using two package json structure.

**Comment by develar** [comment]
> /tmp/.mount_ryQosd/usr/bin/resources/app.asar/myscripts/myscript1.sh

It seems app name is missed here. Please ensure that your path is correct (in your code where do you use it).

**Comment by develar** [comment]
> I am using two package json structure.

So, your error is that path is not relative to project base dir. BTW, please consider to use `extraResources` to copy such files, but not `asar.unpackDir`

**Comment by develar** [comment]
> Do you mean I need to write app/myfolder/subfolder/myscripts?

It is better to use [extraResources](https://github.com/electron-userland/electron-builder/wiki/Options#BuildMetadata-extraResources) and yes, `app/myfolder/subfolder/myscripts`

**Comment by makeitcount** [comment]
Just tried `app/myfolder/subfolder/myscripts`, did not work.
Let me try extraResources. Will update you. 
Thanks

**Comment by makeitcount** [comment]
Exhausted all my options to make it work. Please help.
Aim is to make scripts file readable anyhow, using asar packaging is mandatory.

**Comment by develar** [comment]
Please send me your project (of course, if it is private, you can remove all not required data and leave only bare minimum). develar@gmail.com

**Comment by makeitcount** [comment]
I used extraResources. I can see that the said folder app/myfolder/subfolder/myscripts is copied exactly similar way it was in the project. 
Now only thing left is to reference these files correctly, how can I reference these files in the project? Is there any api to get resources folder path?

**Comment by develar** [comment]
>  Is there any api to get resources folder path?

Hmm.... it should work without any modification, in the same way as without packaging. Maybe https://github.com/electron-userland/electron-builder/wiki/Options#source-and-destination-directories will be required for you.

Your task is very simple and I don't understand why it is so complex for you, if you can attach your project — please do and I will check what's wrong.

**Comment by makeitcount** [comment]
Thanks @develar, but it will take quite sometime to separate the needed code to share with you. 
For now I have added extraResources settings, it unpacks the required directory under resources folder. To access these files I have changed my path 
from `path.join(__dirname, "myscripts/myscript.sh")` 
to 
`path.join(process.resourcesPath, "app/myfolder/subfolder/myscripts/myscript1.sh")`
And as expected this works in final executable but not in development as the process.resourcesPath references the resources folder inside electron-prebuilt

**Comment by develar** [comment]
> And as expected this works in final executable but not in development as the process.resourcesPath references the resources folder inside electron-prebuilt

Please set [Destination Directory](https://github.com/electron-userland/electron-builder/wiki/Options#source-and-destination-directories).

```
 [
   {
     "from": "app/myfolder/subfolder/myscripts",
     "to": "myscripts",
   }
 ]
```

...and your script will be copied to `myscripts without `app/myfolder/subfolder`

**Comment by makeitcount** [comment]
I understand that it will directly copy the file inside myscripts folder instead of the complete hierarchy. That is as good as just declaring extraResources, I think. 
>it should work without any modification, in the same way as without packaging. 

No, it does not work without modification.
Because the required file is in different location after packaging so I think we would need to have two different references, one for after packaging and one for without packaging
To give you an overview:
I have a js file at `app/myfolder/mysubfolder/spawn_script.js` *which executes the bash scripts* in `app/myfolder/mysubfolder/myscripts`. spawn_script.js is the file where I reference these scripts, 

at `app/myfolder/mysubfolder/spawn_script.js`
1. If I reference the bash script file using `filepath = path.join(__dirname, "myscripts/myscript1.sh")` then *after packaging* _filepath==....resourcesDir/app.asar/myfolder/mysubfolder/myscripts/myscript.sh_
Works without packaging, *doesn't work after packaging*(as app.asar is not readable)

2. If I reference the file using `path.join(process.resourcesPath, "app/myfolder/subfolder/myscripts/myscript1.sh")` then *without packaging* i.e. in development _filepath==.....node_modules/electron-prebuilt/dist/resources/myfolder/mysubfolder/myscripts/myscript.sh_
*Doesn't work without packaging*(as file is not there in resources), works after packaging

**Comment by lucasbento** [comment]
@develar: I think I have the same problem.

I'm trying to use the library [spotify-node-applescript](https://github.com/andrehaveman/spotify-node-applescript) and the dev console returns `Error: osascript: node_modules/spotify-node-applescript/lib/scripts/get_track.applescript: No such file or directory` on packaged app.

I added `"extraResources": "node_modules/**/**/*.applescript"`, it does copy to the `Resources` folder but I'm not sure from where the `spotify-node-applescript` is being called to change the path in the library, it is using `__dirname` on the code which returns `node_modules/spotify-node-applescript/lib`.

I'm also using webpack to bundle everything but I'm not sure if it's related to that problem since it works on dev build.

**Comment by lucasbento** [comment]
Here's a github respository using [electron-webpack](https://github.com/electron-userland/electron-webpack) and hitting the same issue: https://github.com/lucasbento/electron-webpack-issue.

You can see that it works with `yarn dev` but not with `yarn dist`.

**Comment by develar** [comment]
@lucasbento please use asarUnpack and https://www.npmjs.com/package/hazardous

**Comment by lucasbento** [comment]
@develar: thank you for replying.

I added this:

```
// package.json
  "build": {
    "asarUnpack": "node_modules/spotify-node-applescript"
  },
```

and `hazardous` but didn't work, it throws the same error.

I'm using the same structure as in https://github.com/lucasbento/electron-webpack-issue.

**Comment by lucasbento** [comment]
@develar: anything else that I can try?

**Comment by develar** [comment]
I will check your case 22 September, I am on vacation.

**Comment by lucasbento** [comment]
@develar: omg, so sorry, don't worry about this, have fun on your vacation!

**Comment by aguynamedben** [comment]
FWIW I'm also having a painful 1+ day excursion on how to reference a simple file inside the ASAR in the production Node environment. I just wanted to offer some perspective on how I view the problem.

My project is based on https://github.com/chentsulin/electron-react-boilerplate. In my case, I've added EJS HTML templates inside my app and want to reference EJS files at runtime to render web pages.

It seems this problem is confusing because there are 3 options:
1. Use `extraResources`, keep the files outside the ASAR, and use [process.resourcesPath](https://github.com/electron/electron/blob/master/docs/api/process.md#processresourcespath) to get the path in production. You have to have an if statement do do different stuff between dev and production, just like @makeitcount [did above](https://github.com/electron-userland/electron-builder/issues/751#issuecomment-247590609). This is the easiest option, but it's kind of dirty if you have a lot of static files you're trying to reference. Plus splitting logic in code everywhere to differentiate between development and production is error prone.
1. Use `asarUnpack` + [`hazardous`](https://github.com/epsitec-sa/hazardous). This seems like the best solution if you need to execute a binary. All I'm trying to do is get a simple reference to a file.
1. Somehow the magic bullet. Keep the file in the ASAR, and have a sane way to access it during development and production.

NOTE: Debugging this is very time consuming and painful because everything works in fine, but breaks in production. This means you have to continue to rebuild using electron-builder, which takes 4-5 minutes on my project. Each time I want to tweak a simple path or logged path, I have to wait 5 minutes for electron-builder to run to see if it worked. That's why this is so painful and difficult to debug.

Maybe there is an opportunity for electron-builder or electron (not sure) to improve this API in the future. It seems like a great opportunity for a new API like `process.asarPath` (similar to `process.resourcesPath`), or `app.getAsarFile()` (similar to `app.getPath()`).

One more note: I think the core problem here is that `app.getAppPath()` returns very different answers between development and production. In development, it's just pointing to my local Electron version, when I want it to point inside my code. In production, it seems correct, but it's difficult to use to find an actual file inside the ASAR.

Thanks for the time you put into working on electron. I'm just trying to offer a perspective. I don't expect anything to be done specially for me here, just trying to give feedback. 🙏

**Comment by goldylucks** [comment]
@aguynamedben i'm using  https://github.com/chentsulin/electron-react-boilerplate as well, couldn't get `hazardous` to work. Can you share your code?

I have a call to a  node module inside `main.dev.js`, and that node module is using `__dirname`, which points to `app.asar` instead of `app.asar.unpacked`

**Comment by aguynamedben** [comment]
@goldylucks I gave up and just ended up using `extraResources` instead of trying to put my files inside the ASAR archive.

In main.dev.js I have:
```js
const somePath = isDev
  ? 'file.development'
  : path.join(process.resourcesPath, 'file.production');

foo.bar({ path: somePath });
```

This works, but it's undesirable because I have to continually switch between dev and packaged context anytime I want to grab a file.

**Comment by hatton** [comment]
Here's what I'm using:

```javascript
  // Get a path to prepend to any nodejs calls that are getting at files in the package,
  // so that it works both from source and in an asar-packaged mac app.
  // See https://github.com/electron-userland/electron-builder/issues/751
  private directoryAdjustment(): string {
    const appPath= app.getAppPath();
    // windows from source: "C:\myapp\node_modules\electron\dist\resources\default_app.asar"
    // mac from source: "/Users/me/dev/myapp/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar"
    // mac from a package: <somewhere>"/my.app/Contents/Resources/app.asar"
    if (appPath.indexOf("default_app.asar") < 0) {
      return Path.normalize(appPath+ "/../..");
    } else {
      // If we are run from outside of a packaged app, our working directory is the right place to be.
      // And no, we can't just set our working directory to somewhere inside the asar. The OS can't handle that.
      return "";
    }
  }
```

Then I use it like this:

```javascript
const foobDir= fs.realpathSync(
          Path.join(this.directoryAdjustment(), "sample data/foo")

**Comment by robot110011** [comment]
any update on this? still having issues between dev and prod envs

**Comment by niksmac** [comment]
@robot110011 don't worry on this. Check [ this](https://github.com/electron-userland/electron-builder/issues/751#issuecomment-247590609)

**Comment by pranavwani** [comment]
> I understand that it will directly copy the file inside myscripts folder instead of the complete hierarchy. That is as good as just declaring extraResources, I think.
> 
> > it should work without any modification, in the same way as without packaging.
> 
> No, it does not work without modification.
> Because the required file is in different location after packaging so I think we would need to have two different references, one for after packaging and one for without packaging
> To give you an overview:
> I have a js file at `app/myfolder/mysubfolder/spawn_script.js` _which executes the bash scripts_ in `app/myfolder/mysubfolder/myscripts`. spawn_script.js is the file where I reference these scripts,
> 
> at `app/myfolder/mysubfolder/spawn_script.js`
> 
> 1. If I reference the bash script file using `filepath = path.join(__dirname, "myscripts/myscript1.sh")` then _after packaging_ _filepath==....resourcesDir/app.asar/myfolder/mysubfolder/myscripts/myscript.sh_
>    Works without packaging, _doesn't work after packaging_(as app.asar is not readable)
> 2. If I reference the file using `path.join(process.resourcesPath, "app/myfolder/subfolder/myscripts/myscript1.sh")` then _without packaging_ i.e. in development _filepath==.....node_modules/electron-prebuilt/dist/resources/myfolder/mysubfolder/myscripts/myscript.sh_
>    _Doesn't work without packaging_(as file is not there in resources), works after packaging
> 
> **Edit**
> Basically final solution looks like this for me
> 
> ```js
> //package.json
> "extraResources": "app/myfolder/mysubfolder/mysripts"
> ```
> 
> ```js
> //app/myfolder/mysubfolder/spawn_script.js
> if(isDevelopment){
>      filepath = path.join(__dirname, "myscripts/myscript1.sh");
> } else {
>      filepath = path.join(process.resourcesPath, "app/myfolder/subfolder/myscripts/myscript1.sh");
> }
> ```

By providing extraResources in package.json and in path.join(process.resourcePath, 'path') it worked. Thanks @makeitcount .

**Comment by z1988hf** [comment]
> > Do you mean I need to write app/myfolder/subfolder/myscripts?
> 
> It is better to use [extraResources](https://github.com/electron-userland/electron-builder/wiki/Options#BuildMetadata-extraResources) and yes, `app/myfolder/subfolder/myscripts`

What is the difference between extraResources and asarUnpack? Their behaviour seems the same. I didn't find good documentation. They both copy files into another folder under resource, and keep another duplicate copy in app.asar. This duplicate copy seems unnecessary.

**Comment by charlesr1971** [comment]
> @goldylucks I gave up and just ended up using `extraResources` instead of trying to put my files inside the ASAR archive.
> 
> In main.dev.js I have:
> 
> ```js
> const somePath = isDev
>   ? 'file.development'
>   : path.join(process.resourcesPath, 'file.production');
> 
> foo.bar({ path: somePath });
> ```
> 
> This works, but it's undesirable because I have to continually switch between dev and packaged context anytime I want to grab a file.

I don’t 

> Here's what I'm using:
> 
> ```js
>   // Get a path to prepend to any nodejs calls that are getting at files in the package,
>   // so that it works both from source and in an asar-packaged mac app.
>   // See https://github.com/electron-userland/electron-builder/issues/751
>   private directoryAdjustment(): string {
>     const appPath= app.getAppPath();
>     // windows from source: "C:\myapp\node_modules\electron\dist\resources\default_app.asar"
>     // mac from source: "/Users/me/dev/myapp/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar"
>     // mac from a package: <somewhere>"/my.app/Contents/Resources/app.asar"
>     if (appPath.indexOf("default_app.asar") < 0) {
>       return Path.normalize(appPath+ "/../..");
>     } else {
>       // If we are run from outside of a packaged app, our working directory is the right place to be.
>       // And no, we can't just set our working directory to somewhere inside the asar. The OS can't handle that.
>       return "";
>     }
>   }
> ```
> 
> Then I use it like this:
> 
> ```js
> const foobDir= fs.realpathSync(
>           Path.join(this.directoryAdjustment(), "sample data/foo")
> ```

I don’t understand why you don’t just supply the appPath with two directory levels removed from the end?

Why bother with the function?

**Comment by mjmacleod** [comment]
> Somehow the magic bullet. Keep the file in the ASAR, and have a sane way to access it during development and production.

Has anyone managed to achieve this for ASAR?

For a normal android app with resource bundle (roughly equivalent to an ASAR) I can just get:
1. `applicationContext.packageResourcePath`
2. offset and length of the file inside the archive via `assets?.openFd`
3. Pass these to my backend/plugin/whatever, which can open the archive, jump to the offset and then treat it as it would a regular file.

It would be ideal if I could do the same for electron apps (on all platforms). Is there not some API via which I can retrieve this information?

**Comment by mjmacleod** [comment]
> > Somehow the magic bullet. Keep the file in the ASAR, and have a sane way to access it during development and production.
> 
> Has anyone managed to achieve this for ASAR?
> 
> For a normal android app with resource bundle (roughly equivalent to an ASAR) I can just get:
> 
>     1. `applicationContext.packageResourcePath`
> 
>     2. offset and length of the file inside the archive via `assets?.openFd`
> 
>     3. Pass these to my backend/plugin/whatever, which can open the archive, jump to the offset and then treat it as it would a regular file.
> 
> 
> It would be ideal if I could do the same for electron apps (on all platforms). Is there not some API via which I can retrieve this information?

For anyone who needs to do the same and stumbles upon this issue while looking for an answer, I ended up with the following:
```
import disk from "asar/lib/disk";
import path from "path";
const isDevelopment = process.env.NODE_ENV !== "production";
var myFilePath = "";
var myFileOffset = 0;
var myFileLength = 0;
if (isDevelopment) {
      myFilePath = path.join(
        app.getAppPath(),
        "../../../data/myfile"
      );
    } else {
      myFilePath = app.getAppPath();
      if (myFilePath.endsWith(".asar")) {
        const filesystem = disk.readFilesystemSync(myFilePath);
        const fileInfo = filesystem.getFile("myfile", true);
        myFileOffset =
          parseInt(fileInfo.offset) +
          parseInt(8) +
          parseInt(filesystem.headerSize);
        myFileLength = parseInt(fileInfo.size);
      } else {
        myFilePath = path.join(myFilePath, "myfile");
      }
    }
```

Far from ideal, it would be nice if there were an "official" way to do this, but it does the job for me.

**Comment by shto** [comment]
I had some applescript files I needed to keep out of the asar package.

What I ended up doing is using `asarUnpack` and then building a separate function to retrieve those files from the unpackaged folder in prod. In dev the contents are not packaged, so I can return the direct file path. I hope those `.unpack` files aren't localized...

package.json
```
mac: {
  ...
  "asarUnpack": [
    "applescripts/*"
  ]
}
```

In code:
```
function _getAsarNormalizedPathForAppleScriptNamed(name) {
    if (isDev) {
        return `./applescripts/${name}`
    }
    else {
        // Need to get the file in the .unpacked folder in prod
        let scriptFilePath = path.resolve(__dirname, `../../app.asar.unpacked/applescripts/${name}`);
        return scriptFilePath;
    }
}
```

I had no luck using `extraResources`.

Hope this helps someone.

**Comment by virendraQversity** [comment]
In my case I am able to read the asar data when its size is around 280 MB, but if its size is more than that it's unable to read the data and showing the attached image error.
![0SKcN](https://user-images.githubusercontent.com/77930347/119715771-fbd48680-be81-11eb-8a2c-4b26487130c0.jpg)

I am packing large course assets, so I can't put it as an extra resource.

**Comment by shenzhuxi** [comment]
@z1988hf was right. 

This issue should be considered as a bug and not closed just for the extraResources solution. 
All the developers will assume electron-builder behaves the same with asar on/off. 

Now all the shared object files must to dealt separately, because this error. 
```
/resources/app.asar/node_modules/*: cannot open shared object file: Not a directory
```
Think about how many different situations, prebuilt, must-rebuild, must download/install form somewhere, and etc., for shared objects in the node ecosystem, we probably just stop using asar.

**Comment by sebastianvitterso** [comment]
I'd like to add that I had this issue when using the Electron Vite quick start for Vue3 + Typescript, and when trying to use the spotify library that @lucasbento [mentioned](https://github.com/electron-userland/electron-builder/issues/751#issuecomment-329415534). I solved it by opening the `electron-builder.yml` file, removing the `asarUnpack` section and adding `asar: false` to the root of the document. Since my application is tiny, I didn't need the asar packing.
