### ISSUE TITLE
Error: Module version mismatch. Expected 48, got 50.

### ISSUE THREAD

**Issue by zaggino** [electron-userland/electron-builder#755]
* **Version**: 6.7.6

* **Target**: Mac, electron@1.4.0

Getting this error message: https://travis-ci.org/zaggino/brackets-electron/jobs/160330730

Can be fixed by having `electron-prebuilt` at `1.2.8` in the `package.json` during the `npm install` and then installing latest electron as `npm install electron-prebuilt@1.4.0`, see https://github.com/zaggino/brackets-electron/commit/18236408675769d1ff8a6d2a623331f587a200e3

After fix, it builds fine: https://travis-ci.org/zaggino/brackets-electron/jobs/160334464

Seems like `macos-alias` package which is pulled through `macos-alias -> ds-store -> appdmg` dependency is being built to the electron's module version and not module version of node.js installed on the machine (v6.5)

**Comment by develar** [comment]
I suggest you to use 2 package.json structure and forget about these problems :)

**Comment by zaggino** [comment]
The failing thing in this case is devDependency `electron-builder -> appdmg -> ds-store -> macos-alias` and not something for my application itself. I actually create `package.json` inside the `app` folder with a npm postinstall script (https://github.com/zaggino/brackets-electron/blob/516c0d34ff08a61d0790e4b71cd2bdca6d9785ce/tasks/npm-install.js#L50-L75)

**Comment by zaggino** [comment]
If the `electron-rebuild` is causing this, is there a flag for `electron-rebuild` to ignore `electron-builder` module?

**Comment by develar** [comment]
> If the electron-rebuild is causing this, is there a flag for electron-rebuild to ignore electron-builder module?

I strongly, strongly recommend you just use 2-package.json structure.

If you want to fight — `electron-rebuild` and `electron-builder` uses the same tool to rebuild your native modules — `npm rebuild` No magic. `electron-builder` DOES NOT REBUILD native deps if you   do no use 2-package.json stricture. Exactly because you must not rebuild you dev deps using electron headers and versions.

 If you still want to fight — `npm rebuild` uses node gyp.

No doubt — it will be great if you change `npm rebuild` to skip some modules. But keep in mind — some deps maybe required for both app and dev and, so, cannot be handled.

**Comment by develar** [comment]
Duplicate #699

**Comment by develar** [comment]
Yes, no doubt — electron-builder SHOULD not use native deps to simplify your life. I am going to investigate — is it possible to fix `appdmg` or not. But cannot promise when.

**Comment by zaggino** [comment]
Thanks for the explanations, it actually helped me a lot to fix my build.
