### ISSUE TITLE
Full Distinguished Name (DN) to publisherNames configuration ?

### ISSUE THREAD

**Issue by popod** [electron-userland/electron-builder#7583]
* **Electron-Builder Version**: 23.6.0

* **Node Version**: v16

* **Electron Version**: v19
* **Electron Type (current, beta, nightly)**: ...

* **Target**: win, nsis

Why is full certificat DN validation needed ?

I've had this warning `Signature validated using only CN <company name>. Please add your full Distinguished Name (DN) to publisherNames configuration` with this config `publisherName: ['<company name>']`.

Changing to `publisherName: ['CN=<company name>']` will not more display the warning... This is not very friendly to force adding this and this seems to not really improve security.. This new 'recommended' way is not documented anywhere..

**Comment by popod** [comment]
not stale :)

**Comment by mmaietta** [comment]
Full DN certification isn't needed but is highly advocated for per another engineer in the community. **I think** if one was able to man-in-the-middle the update server and then serve an exe update with a non-full DN `publisherName` that overlaps with your certificate CN, then it could still pass. Having it "full" means a security boost.

**Comment by mmaietta** [comment]
Mocking a full DN is really difficult to do AFAIK. It requires the signing certificate to have the same values, which is more difficult than just using a string value such as "Foo Bar". Just providing `CN=` will have limited effect, but providing [all values](https://learn.microsoft.com/en-us/previous-versions/windows/desktop/ldap/distinguished-names) is harder to mock (otherwise many websites would have the same security vulnerability)
I'm fairly cautious on adding new configuration options, especially since this one isn't enforcing full DN, just logging a warning that a more secure approach could be taken.

**Comment by mmaietta** [comment]
Mocking a full DN is really difficult to do AFAIK. It requires the signing certificate to have the same values, which is more difficult than just using a string value such as "Foo Bar". Just providing `CN=` will have limited effect, but providing [all values](https://learn.microsoft.com/en-us/previous-versions/windows/desktop/ldap/distinguished-names) is harder to mock (otherwise many websites would have the same security vulnerability)
I'm fairly cautious on adding new configuration options, especially since this one isn't enforcing full DN, just logging a warning that a more secure approach could be taken.

**Comment by popod** [comment]
Thanks for your reply.

I'm not an expert in certificates, but I don't think that creating a certificate with all the DN elements is any more complicated.

I think the security of a certificate depends on its issuer and the validation that has to be done of the company before it can get its certificate.

But I see your point. I'm just not sure it merits a warning in the logs every time a software is updated.

In any case, it might be interesting to add some information about this in the doc so that developers don't discover this recommendation in their software logs. Perhaps providing an example of `publisherName`with a complete DN would be useful?

**Comment by popod** [comment]
not stale :)

**Comment by mmaietta** [comment]
I'm not sure I understand what's the solution you're looking for here? We're not adding `checkFullDn` to the configuration options...
If all you want is to remove it from being a `warn`, that's another matter and seems entirely opinionated

**Comment by popod** [comment]
Hi,

I don't know exactly what is the better thing to do.. I only ask a question about this "new" option / warning (to correctly understand why is the full DN required) and the better way to handle that..

I don't really understand in which case a full DN is more secure than juste the DN. If you have concret exemple, it will be great.

For now, I use `publisherName: ['CN=<company name>']` as a workaround to not show the warning.

From my point of view:
- At least the documentation should be improved by adding an exemple of full DN for `publisherName`. This is not documented for now and the developer discover this "requirement" only by reading the application log..
- Adding a `checkFullDn` options will be a good compromise: let the developer choose and remove the warning from the application log

But what about auto-update on certificate renewal when a full DN is set ? Is the update broken ?
