### ISSUE TITLE
Code-Signing Windows on Mac, `osslsigncode` produces 'Unrecognized file type' error when signing .node modules 

### ISSUE THREAD

**Issue by romansp** [electron-userland/electron-builder#7652]
* **Electron-Builder Version**: 24.4.0

* **Node Version**: 18.16.1

* **Electron Version**: 25.2.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: x64

In our electron app we're using `websocket` package that includes native prebuilt .node modules. And we're signing both Mac and Windows x64 app versions on Mac. 

After upgrading to electron-builder v24 we can no longer sign Windows app on Mac. 

```
• signing         file=dist_electron/win-unpacked/redacted.exe certificateFile=/Users/runner/work/_temp/redacted-CodeSign-Exp-2023-10-06.pfx
  • signing         file=dist_electron/win-unpacked/resources/app.asar.unpacked/node_modules/utf-8-validate/prebuilds/win32-x64/node.napi.node certificateFile=/Users/runner/work/_temp/redacted-CodeSign-Exp-2023-10-06.pfx
  • signing         file=dist_electron/win-unpacked/resources/app.asar.unpacked/node_modules/utf-8-validate/prebuilds/win32-ia32/node.napi.node certificateFile=/Users/runner/work/_temp/redacted-CodeSign-Exp-2023-10-06.pfx
  • signing         file=dist_electron/win-unpacked/resources/app.asar.unpacked/node_modules/utf-8-validate/prebuilds/linux-x64/node.napi.node certificateFile=/Users/runner/work/_temp/redacted-CodeSign-Exp-2023-10-06.pfx
  • signing         file=dist_electron/win-unpacked/resources/app.asar.unpacked/node_modules/utf-8-validate/prebuilds/darwin-x64+arm64/node.napi.node certificateFile=/Users/runner/work/_temp/redacted-CodeSign-Exp-2023-10-06.pfx
  ⨯ Exit code: 255. Command failed: /Users/runner/Library/Caches/electron-builder/winCodeSign/winCodeSign-2.6.0/darwin/10.12/osslsigncode -in /Users/runner/work/1/s/redacted/dist_electron/win-unpacked/resources/app.asar.unpacked/node_modules/utf-8-validate/prebuilds/linux-x64/node.napi.node -out /Users/runner/work/1/s/redacted/dist_electron/win-unpacked/resources/app.asar.unpacked/node_modules/utf-8-validate/prebuilds/linux-x64/node.napi-signed-sha1.node -t http://timestamp.digicert.com -pkcs12 /Users/runner/work/_temp/redacted-CodeSign-Exp-2023-10-06.pfx -h sha1 -n redacted -i https://redacted.example.com/ -pass xxxxxxxxxxxxxxxxx (sha256 hash) file type: /Users/runner/work/1/s/redacted/dist_electron/win-unpacked/resources/app.asar.unpacked/node_modules/utf-8-validate/prebuilds/linux-x64/node.napi.node

Failed

Unrecognized file type: /Users/runner/work/1/s/redacted/dist_electron/win-unpacked/resources/app.asar.unpacked/node_modules/utf-8-validate/prebuilds/linux-x64/node.napi.node

Failed
  failedTask=build stackTrace=Error: Exit code: 255. Command failed: /Users/runner/Library/Caches/electron-builder/winCodeSign/winCodeSign-2.6.0/darwin/10.12/osslsigncode -in /Users/runner/work/1/s/redacted/dist_electron/win-unpacked/resources/app.asar.unpacked/node_modules/utf-8-validate/prebuilds/linux-x64/node.napi.node -out /Users/runner/work/1/s/redacted/dist_electron/win-unpacked/resources/app.asar.unpacked/node_modules/utf-8-validate/prebuilds/linux-x64/node.napi-signed-sha1.node -t http://timestamp.digicert.com -pkcs12 /Users/runner/work/_temp/redacted-CodeSign-Exp-2023-10-06.pfx -h sha1 -n redacted -i https://redacted.example.com/ -pass xxxxxxxxxxxxxxxxx (sha256 hash) file type: /Users/runner/work/1/s/redacted/dist_electron/win-unpacked/resources/app.asar.unpacked/node_modules/utf-8-validate/prebuilds/linux-x64/node.napi.node
  Failed
    Unrecognized file type: /Users/runner/work/1/s/redacted/dist_electron/win-unpacked/resources/app.asar.unpacked/node_modules/utf-8-validate/prebuilds/linux-x64/node.napi.node
  Failed
    at /Users/runner/work/1/s/redacted/node_modules/builder-util/src/util.ts:133:18
    at ChildProcess.exithandler (node:child_process:427:5)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:322:12)
From previous event:
    at processImmediate (node:internal/timers:476:21)
From previous event:
    at WinPackager.signApp (/Users/runner/work/1/s/redacted/node_modules/app-builder-lib/src/winPackager.ts:407:27)
    at WinPackager.doSignAfterPack (/Users/runner/work/1/s/redacted/node_modules/app-builder-lib/src/platformPackager.ts:332:21)
    at WinPackager.doPack (/Users/runner/work/1/s/redacted/node_modules/app-builder-lib/src/platformPackager.ts:317:7)
    at WinPackager.pack (/Users/runner/work/1/s/redacted/node_modules/app-builder-lib/src/platformPackager.ts:136:5)
    at Packager.doBuild (/Users/runner/work/1/s/redacted/node_modules/app-builder-lib/src/packager.ts:442:9)
    at executeFinally (/Users/runner/work/1/s/redacted/node_modules/builder-util/src/promise.ts:12:14)
    at Packager._build (/Users/runner/work/1/s/redacted/node_modules/app-builder-lib/src/packager.ts:376:31)
    at Packager.build (/Users/runner/work/1/s/redacted/node_modules/app-builder-lib/src/packager.ts:337:12)
    at executeFinally (/Users/runner/work/1/s/redacted/node_modules/builder-util/src/promise.ts:12:14)
  • building block map  blockMapFile=dist_electron/redacted-0.9.4846-develop.dmg.blockmap
```

It seems that https://github.com/electron-userland/electron-builder/pull/7421 introduced automatic code-signing for such modules, but it looks like `osslsigncode` doesn't support .node files and will produce `Unrecognized file type` error when trying to sign.

Is code-signing Windows app on Mac still supported or we should consider splitting our build steps into dedicated pipelines for Mac and Windows?

**Comment by willemdjong** [comment]
I ran into the same issue. I've this issue since I upgrade from electron-builder 23.6.0 to 24.4.0. It seems that prebuilt binaries are not correctly installed. In the signing process electron builder tries to sign a .node file for mac with a windows certificate.

**Comment by willemdjong** [comment]
@mmaietta can you have a look at this. It's the same I mentioned before https://github.com/electron-userland/electron-builder/pull/7465

**Comment by davej** [comment]
We are also seeing this issue in `24.x` of Electron Builder.
The issue seems to be that Electron Builder now leaves all `*.node` prebuilds for every platform in the distribution package. The prebuilds should be filtered so that only prebuilds that match the target platform/architecture are in the distribution package.

**Comment by mmaietta** [comment]
Hey guys, I'm traveling. 
Can you try this patch-package?
`patches/app-builder-lib+24.5.2.patch`
```
diff --git a/node_modules/app-builder-lib/out/macPackager.js b/node_modules/app-builder-lib/out/macPackager.js
index 1193574..beffd7c 100644
--- a/node_modules/app-builder-lib/out/macPackager.js
+++ b/node_modules/app-builder-lib/out/macPackager.js
@@ -257,6 +257,7 @@ class MacPackager extends platformPackager_1.PlatformPackager {
             strictVerify: options.strictVerify,
             optionsForFile: await this.getOptionsForFile(appPath, isMas, customSignOptions),
             provisioningProfile: customSignOptions.provisioningProfile || undefined,
+            preAutoEntitlements: false,
         };
         builder_util_1.log.info({
             file: builder_util_1.log.filePath(appPath),

```
`preAutoEntitlements` was added without any documentation in the Migration Guide for electron/osx-sign's package upgrade, so I'm curious if that's related. (Might also be related to https://github.com/electron-userland/electron-builder/pull/7642)
Note: `TEAM_ID` needs to be provided in entitlements manually then per https://www.electronjs.org/docs/latest/tutorial/mac-app-store-submission-guide#extra-steps-without-electron-osx-sign

**Comment by mmaietta** [comment]
Okay, so I genuinely don't know how prebuilds work tbh. I was under the impression electron/rebuild would automatically handle that.
Can someone please post a screenshot of the folder structure where the .node prebuilds are all being included?

**Comment by davej** [comment]
Hey @mmaietta, thanks for the communication. Here is a clean project with just `ffi-napi` installed using `24.4.0`.

<img width="644" alt="CleanShot 2023-07-09 at 12 46 58@2x" src="https://github.com/electron-userland/electron-builder/assets/26971/2641dd4d-af30-4735-91bc-2ad49dc9c016">

```
.
├── darwin-x64
│   └── node.napi.uv1.node
├── linux-arm64
│   └── node.napi.uv1.armv8.node
├── linux-x64
│   └── node.napi.uv1.node
├── win32-ia32
│   └── node.napi.uv1.node
└── win32-x64
    └── node.napi.uv1.node
```

**Comment by mmaietta** [comment]
So im trying to replicate what I believe would be the correct behavior on 23.6.0 (i.e. only the prebuilt library for the respective OS+arch) and I'm seeing that the `app.asar.unpacked` contains all the prebuilds for every OS+arch still. Tested this building Windows app on arm64 mac. Could anyone confirm that observation?

v24 didn't change anything about the asar packaging approach or logic, so I'm really confused how this issue just appeared from the migration to electron/rebuild.

Wondering if the most efficient approach is to just not unpack prebuilds that aren't for the app's OS+arch, then they wouldn't attempt to be signed?

**Comment by willemdjong** [comment]
> 

I cannot confirm this information definitively because the specific package I am currently using may overwrite the .node file based on the architecture. However, I can verify that it is still functioning as expected on version 23.6.0. The only discrepancy in the build logs is the inclusion of the following line:

`install prebuilt binary name=better-sqlite3-multiple-ciphers version=8.3.0 platform=win32 arch=x64`

This line appears after the process of 

`rebuilding native dependencies, including better-sqlite3-multiple-ciphers@8.3.0 `
 
Due to this difference, I am uncertain whether the electron-builder still installs the prebuilt binaries at all.

**Comment by mmaietta** [comment]
@willemdjong thank you for that info, that was immensely helpful.  It appears that the previous Go binary was executing both prebuild-install cli manually and then compiling locally if something failed. Right now, electron-builder v24 is only set up with electron/rebuild (an oversight on my side, my sincere apologies. I really do wish I had the previous domain knowledge of the original maintainer of this project). I'm working to resolve this asap

Additional context, electron/rebuild was needed for the latest electron versions that required new C++ compiler flags IIRC, which AFAICT I can't configure via the Go binary.

What version of electron are you using?

**Comment by mmaietta** [comment]
Okay, I'm going to attempt reverting the electron/rebuild migration in a new PR. I'm struggling to find a way to create a native module dependency mapping that I can execute the prebuild-install cli on for each native module. From another github comment, the need for electron/rebuild due to Cxx flags may no longer be needed? It appears that may be the case since you're using electron 24 with electron-builder v23.

Just to continue checking all my bases, what changes in v24 do you need that aren't in v23? (i.e. is it requiring electron/rebuild integration?)

**Comment by willemdjong** [comment]
I will provide you with more information about the issue later on, but for now, reverting this migration would be beneficial for us.

The sole reason for considering the upgrade to v24 is due to Electron, as v23 is functioning perfectly fine.

**Comment by leolabs** [comment]
I'm experiencing the same issue with the `fsevents` package. Downgrading back to electron-builder ^23 helped, but I'd love to use ^24 for some other fixes you've implemented. Let me know if there's anything I can do to help resolve this.

**Comment by mmaietta** [comment]
Trying to revert but running into a test failing that I can't identify why for windows builds on linux.
https://github.com/electron-userland/electron-builder/pull/7668
Back to work now though and running low on free time

**Comment by mmaietta** [comment]
Alriiiiight, electron/rebuild migration has been reverted. Please try [v24.6.1](https://github.com/electron-userland/electron-builder/releases/tag/v24.6.1) 🤞

**Comment by willemdjong** [comment]
@mmaietta thanks, this works for me!

**Comment by davej** [comment]
Thank you @mmaietta! 🙏

**Comment by mmaietta** [comment]
Wonderful!

**Comment by romansp** [comment]
Tried upgrading to `24.6.2` but still experiencing the same issue. Maybe it's something else on my side. 

Can anyone confirm if their builds are working after the upgrade?

**Comment by jgresham** [comment]
> Tried upgrading to `24.6.2` but still experiencing the same issue. Maybe it's something else on my side.
> 
> Can anyone confirm if their builds are working after the upgrade?

Having this issue too on `26.4.2`

**Comment by johnpyp** [comment]
Thanks, this has fixed all of our builds. It also fixed a couple of other incidental issues, namely:
- properly building Windows from Linux
- building a universal x64/arm w/ native binaries (e.g leveldown, sqlite) on macos
- properly identifying the matching prebuild target from github releases
- faster install times in general!

**Comment by tobiasmuecksch** [comment]
Yup. I've still got the issue on `26.4.2` too. In my opinion we should re-open this issue.

**Comment by tobiasmuecksch** [comment]
I just tried `26.4.1` and the error disappears. So something went wrong during the upgrade to 26.4.1. Could you please reopen this issue?

**Comment by johnpyp** [comment]
@tobiasmuecksch what native module working for you? And what kind of binary is the .node file?

Could you try to reproduce in a minimum example repo?

Also, try making sure npmRebuild: true is on

**Comment by tobiasmuecksch** [comment]
The Module is sqlite3. I'll provide you with more Information and a demo repo tomorrow 👍

**Comment by willemdjong** [comment]
We have encountered the same issue during our testing. However, the building and installation of the prebuilt binary with the name 'better-sqlite3-multiple-ciphers' and version 8.3.0 on the 'win32' platform and 'x64' architecture are now functioning properly again.

Unfortunately, the build is currently crashing with the error message: 'Error: Could not detect abi for version 25.2.0 and runtime electron. Updating 'node-abi' might help solve this issue if it is a new release of Electron.' We have already opened an issue (https://github.com/m4heshd/better-sqlite3-multiple-ciphers/issues/52) for this particular problem in the 'better-sqlite3-multiple-ciphers' repository. However, we are uncertain whether the responsibility lies with this package or electron-builder to address and resolve this issue.

**Comment by johnpyp** [comment]
@willemdjong So, better-sqlite3 and better-sqlite3-multiple-ciphers, with their latest 8.5.0 release 5 days ago (looks like you're using 8.3.0) support electron v25 prebuilds, so if you update to that that should now work and get the right version.

As far as node-abi, the reason is because one of your downstream dependencies hasn't updated node-abi to the latest version which has the mapping information that says "electron v25 means use node abi version 116". To fix that, I'd recommend using override capabilities in whatever package manager you use to pin the version of node abi, then upgrade it when needed (or use a permissive version range).

Node abi is backwards compatible each release, and just adds new supported versions, so there isn't harm to this.

For example, with pnpm, I add
```json
  "resolutions": {
    "node-abi": "^3.45.0"
  },
```
to my root package.json

**Comment by tobiasmuecksch** [comment]
@johnpyp 
1. According to the docs `npmRebduild`'s default is true. I haven't disabled it so I assume, that it already was true. Just to be extra sure, I've added it to my configuration.
2. Since `sqlite3` wasn't updated in 4 months, I don't think that there are the needed prebuilds. The idea to create your own fork and providing the prebuilds is genius. I need to find out how to do that.

This is my error stack:

<img width="1314" alt="image" src="https://github.com/electron-userland/electron-builder/assets/1294854/a2165342-5fc3-4c40-91a0-5d3749ed6ded">

But still, I'm confused by this strange error message `Unrecognized file type:`

**Comment by tobiasmuecksch** [comment]
regarding `better-sqlite3-multiple-ciphers` I've been advised to stop cross building [in this issue](https://github.com/m4heshd/better-sqlite3-multiple-ciphers/issues/51#issuecomment-1615085114)

**Comment by johnpyp** [comment]
@tobiasmuecksch Got it. Yeah so a couple things going on here:

#### Why do you get an `Unrecognized file type` error?

The `Unrecognized file type` error is caused because electron-builder is attempting to sign a binary that isn't platform-compatible. So in this case, it's trying to sign a windows arm64 `.node` binary, instead of x64 like it's expecting.

#### Why did this break now but not on 23.6.0?

In 24.x, electron-builder started signing `.node` binaries when it didn't before (for unrelated reasons), so it's just scanning for any file ending in `.node`, which happens to be those. Those binaries it's referencing in `sqlite3` wouldn't actually be used as far as I know, but since they're in the folder, they're getting picked up. Then electron-builder is failing to sign them. I think @mmaietta could better comment on if a long term solution could be provided for this issue.

#### What should you do?

You have a couple options:
- Use something like better-sqlite3 which doesn't have the same packaging quirks as far as I can tell. Regarding the guidance from the post 3 weeks ago, that was under the `@electron/rebuild` mode, which had a myriad of issues. I'd retry it. Note that **better-sqlite3 (and the multiple-ciphers variant) has now pushed out 8.5.0 that has support for electron v25 prebuilds, which should fix other issues for you, and others**. 
- You can try to ignore `*.node` files, for example you can make a `beforeSign` hook that ignores those files:
```js
// This code was sourced from
// https://github.com/electron-userland/electron-builder/issues/6304#issuecomment-1057739612
const path = require("path");
const { doSign } = require("app-builder-lib/out/codeSign/windowsCodeSign");

/**
 * @type {import("electron-builder").CustomWindowsSign} sign
 */
module.exports = async function sign(config, packager) {
  // Do not sign if no certificate is provided.
  if (!config.cscInfo) {
    return;
  }

  const targetPath = config.path;

  const ext = path.extname(targetPath);

  // Don't sign .node files, since the logic doesn't quite understand different binary types yet that may be left over.
  // Could be improved through better introspection of the files.
  // PR that introduced signing .node files: https://github.com/electron-userland/electron-builder/pull/7421
  if (ext === ".node") {
    return;
  }

  await doSign(config, packager);
};
```

#### Can you cross compile at all...?

You still should be able to, but these issues are something that you're going to run into regularly (which is the only reason I know my way around it decently). I stuck it out for a long time, but now just have dedicated build VMs for each os that I publish from with a standardized script. It simplifies the headache to have dedicated build machines, but obviously has that downside. It is possible cross-compile if you really want to, there isn't actually anything technically untenable here, it's just about getting the tooling hooked up right and interop-ing with the ecosystem. For me, it was worth the effort until recently.

**Comment by tobiasmuecksch** [comment]
@johnpyp Thank you so much, for this in-depth answer. Now I fully understand the issue at hand. Sadly, I'm also having issues with `better-sqlite3-multiple-ciphers` even on a real windows machine which is why I decided to stick with `sqlite3`. 

Anyways; now having this information I can continue my work and find a new way to solve my build issues. I guess, this issue can be closed again.

**Comment by johnpyp** [comment]
@tobiasmuecksch I’m curious what issues you have now building with it even on a windows machine, as I have a very similar setup and it’s working fine for me.

As far as this issue goes, I think there’s still some clear work in the area of documentation, error message clarity and ironing out prebuild issues… I’d be interested if others can post about their issues too if they still have some on 24.6.2, especially non-cross-compile issues which seem strange.

**Comment by tobiasmuecksch** [comment]
@johnpyp I'm still investigating whether my issues really are `electron-builder` issues. For now, I found out that the build process starts working again, as soon as I remove the `--arm64` flag. So I guess there are two underlying problems. 

1. There are no prebuilds for windows arm64 
2. I'm missing some build tools, which would allow me to build for arm64 (since I've never worked with VS and its build tools, it takes some time for me to understand how to do things right in that domain)

Removing the flag, also re-enables me to cross-build 😃

**Comment by willemdjong** [comment]
Thank you, @johnpyp, for your suggestions. I have encountered another issue now, which is related to https://github.com/electron-userland/electron-builder/issues/7683. It appears that everything is working correctly, except for the signing process, which is causing a problem. Based on other issues in electron-notarize, it seems that the issue should be related to electron-builder, as suggested in this particular issue."

**Comment by mmaietta** [comment]
>Why did this break now but not on 23.6.0?
In 24.x, electron-builder started signing .node binaries when it didn't before (for unrelated reasons), so it's just scanning for any file ending in .node, which happens to be those. Those binaries it's referencing in sqlite3 wouldn't actually be used as far as I know, but since they're in the folder, they're getting picked up. Then electron-builder is failing to sign them for the reason mentioned above, but if they were skipped I think the app would work. I think @mmaietta could better comment on if a long term solution could be provided for this issue.

`.node` files started being signed due to https://github.com/electron-userland/electron-builder/pull/7421

So it seems, all node files need to be signed for WDAC, but not all node files are able to be signed? Perhaps we need an additional `signDlls` var for Windows config but now also `signNode`, default false? I'm always hesitant in adding a new config var, but I don't see another way to about this then.

What are your thoughts?

**Comment by johnpyp** [comment]
Maybe the configuration could take the opposite approach of defaulting to
maybe “skipping” signing .node files that don’t match the target arch (to
catch most cases, and with a special case for macOS unified or other
unified builds), and have a way to opt in to signing all .node files if
needed.

The other thing I’m curious about is whether just straight up deleting
those files might be a solution. Obviously if dependencies are doing weird
things with them it’ll break… but for most of them, the path just won’t be
triggered in the first place since the arches don’t match.

**Comment by mmaietta** [comment]
AFAICT, the packager class doesn't have access to what architecture or target it is packaging for during the signing stage, it just runs blindly the same flow.

I'm okay with default skip `.node` files to return back to previously working functionality. The WDAC sign-all requirement can be considered supplemental and require the user/developer adding `.node` to the `signExts` array.

**Comment by johnpyp** [comment]
One side effect of the .node signing is that it "catches" these issues ahead of time (either cross-compilation issues or prebuild nonsense), maybe it's worth some "best-effort" heuristics warnings that will help people go in the right direction?

I don't know much about how native modules get resolved or what matters/doesn't matter, but it seems like the `build/Release/examplefile.node` is what's usually relevant... maybe we can pre-scan that arch (similar to what `file` does) and verify it matches?

**Comment by mmaietta** [comment]
AFAICT, `build/Release` is only present when node-gyp is actually run. prebuilds are in a different directory. The asar packager doesn't know anything about arch or target, just `process.platform` which doesn't apply to cross-platform builds.

Opened https://github.com/electron-userland/electron-builder/pull/7685 for `signExts` option with default empty array. `.node` and `.dll` can be provided there if needed. `signDll` option will be deprecated

**Comment by mmaietta** [comment]
Please try 24.6.3

**Comment by jgresham** [comment]
> 

`24.6.3` fixed the issue for me. Thanks! @mmaietta

**Comment by johnpyp** [comment]
@willemdjong Yeah, that's expected behavior. The only way to cross compile properly is to have prebuilts ready for the different platforms, so compiling source means you won't be able to compile from source.

I'd recommend turning it off, and make sure that whatever native dependencies you have have prebuilts available for the version of electron you're using.

**Comment by willemdjong** [comment]
@johnpyp I find this behavior unexpected since the previous version (electron-builder v23) worked perfectly. The package better-sqlite3-multiple-ciphers includes prebuilt files, which are installed correctly. However, the build process still attempts to build the native dependency from sources for the name=better-sqlite3-multiple-ciphers version=8.5.0. This results in an error on Windows, stating "cannot build native dependency" with the reason being "prebuild-install failed with error," and building from sources is not possible because the platform or architecture is not compatible, causing an exit status 1.

**Comment by mmaietta** [comment]
@willemdjong can you create a minimum reproducible repo for this and I can take a look

Sounds like it may be worth opening a new issue/ticket for this though? Doesn't seem related to `osslsigncode 'Unrecognized file type'` OP

**Comment by willemdjong** [comment]
@mmaietta Managed to successfully upgrade to Electron v25 using the latest Electron Builder. Thanks once again for your help.

**Comment by JaviOverflow** [comment]
I'm experiencing this bug again in `24.12.0`, downgrading to `24.6.3` solves this. Can you undo the change that causes this in a later version?

**Comment by mmaietta** [comment]
What's the error? Can you post with `DEBUG=electron-builder` env var?
Wondering if it's related to this change: https://github.com/electron-userland/electron-builder/pull/7998
