### ISSUE TITLE
Broken asset files after build. Dev is working

### ISSUE THREAD

**Issue by MarcelFinkbeiner** [electron-userland/electron-builder#7703]
* **Electron-Builder Version**: 
24.6.3

* **Node Version**: 
v16.17.0

* **Electron Version**:
* **Electron Type (current, beta, nightly)**:

25.3.1

* **Target**: 
prod

How can I make sure that asset files are accessible in build?
Test: npm run dev <- is working
npm run build <- file links are broken
(https://github.com/MarcelFinkbeiner/vite-vue3-build-testing)

**Comment by mmaietta** [comment]
Thank you for the reproducible repo.

Your `electron-builder.json5` is being ignored because you have `build: {}` specified in the `package.json`

Removing `build` from `package.json` resolves the issue and your app works just fine.
(Note the "loaded configuration  file=/Development/vite-vue3-build-testing/electron-builder.json5" in the logs)

**Comment by MarcelFinkbeiner** [comment]
@mmaietta Okay thank you for your help my minimal version is now working but if i move the `NestedView` page into a pages subfolder (like it is in our huge project) like `test` and also update the dynamic imports in the `NestedView` page to `../../` instead of just `../` the links are broken again.
