### ISSUE TITLE
The X-USER-STAGING-ID header electron-builder sends is a privacy violation

### ISSUE THREAD

**Issue by fortuna** [electron-userland/electron-builder#7728]
Whenever electron-builder fetches the update file, it sends a `X-USER-STAGING-ID` header that uniquely identifies the user. That is a privacy violation that affects any Electron app using electron-builder. See code at https://github.com/electron-userland/electron-builder/blob/66bef0f7f1a0371ff924d29ed5453f9b3222c1ab/packages/electron-updater/src/AppUpdater.ts#L406

It looks like [it was added back in 2017](https://github.com/electron-userland/electron-builder/issues/1639#issuecomment-307692082) to support some advanced version of staged rollouts.

Please disable the `X-USER-STAGING-ID` by default and don't enable it without explicit developer action. You don't need that for staged rollouts.

**Comment by mmaietta** [comment]
Can you elaborate on how that is a privacy violation?

Unfortunately, disabling it by default is a breaking change, so that doesn't feel like we can easily take that approach. The final headers still will allow overrides via `this.requestHeaders` being set, so if you were to provide `x-user-staging-id: ""`, that seems like you'd resolve your privacy issue?
