### ISSUE TITLE
How does this thing work?

### ISSUE THREAD

**Issue by ir-fuel** [electron-userland/electron-builder#779]
Sorry for the newbie question, but the docs aren't helping me out at all here.
In short:
I have an Electron app that uses webpack. Webpack outputs all files in a `dist` folder. How does electron-builder know which files it has to pack and which one it should ignore? In theory it should use all the files from my `dist` folder and the `node_modules` generated in my `app` folder.

I tried following the docs and checked several sites explaining how electron-build works, but I only seem to end up with an empty `resources/app` folder and an error:

`Error: Application entry file "main.js" does not exist. Seems like a wrong configuration.`

Where in the package.json files can I specify what files it has to copy? The documentation doesn't mention anything about this. It's as if everything just is supposed to happen by magic.

Also it seems the docs are quite inconsistent when it comes to what attribute should be put where. For instance concerning the windows icons. On one page it's just mentions a local file, on another it only mentions linking to the ico file online.

A very confused user ....

**Comment by develar** [comment]
>  How does electron-builder know which files it has to pack and which one it should ignore?

If directory `app` or `www` exists — [two package.json structure](https://github.com/electron-userland/electron-builder#two-packagejson-structure) is automatically used.

[App](https://github.com/electron-userland/electron-builder/wiki/Options#MetadataDirectories-app) folder (root if two package.json structure is not used) is packed completely.

> Webpack outputs all files in a dist folder.

In this case you must or change Webpack output folder, or change electron-builder [output](https://github.com/electron-userland/electron-builder/wiki/Options#MetadataDirectories-output) (because also defaults to `dist`). I think, it is your problem.

> on another it only mentions linking to the ico file online.

Squirrel.Windows issue. NSIS doesn't require it.

**Comment by ir-fuel** [comment]
I managed to solve the "what files" by using this in package.json:

```
  "files": [
      "**/*",
      "dist/*"
    ],
  ```

and have webpack production output everything in `app/dist`

**Comment by develar** [comment]
` "**/*",` automatically includes `"dist/*"` and in any case `"**/*",` is the default pattern (not exactly, but details is not important in this case). So, I don't understand. Ah — maybe you have `app` folder but don't use two package.json structure? And `app` folder in your case is not the `app` folder (as electron-builder detects two-package.json structure and copies only `app`)?
