### ISSUE TITLE
Code Signing For Windows On My Mac

### ISSUE THREAD

**Issue by YourAverageTechBro** [electron-userland/electron-builder#7802]
Hi all,

I'm trying to configure autoupdating for my electron app and I'm specifically trying to generate the CSC_LINK and CSC_KEY_PASSWORD values.

I'm following the instructions [here](https://www.electron.build/tutorials/code-signing-windows-apps-on-unix) and I'm particularly confused at the following step:

```
Check the library link to make sure you have the correct PKCS module. This link might be different per token. On Linux you will find it in /lib, while on Mac you can find it in /Library/Frameworks or /usr/local/lib.
```

Does anyone have a step-by-step guide on how to do this? Also, am I supposed to buy a certificate or something too? Would appreciate any help and guidance on how to do this right to support auto update for my app on windows.

**Comment by pitw** [comment]
Does this help ? [Code Siging OS X](https://www.jviotti.com/2016/03/16/how-to-code-sign-os-x-electron-apps-in-travis-ci.html)
CSC_LINK is the base64 encoded Code Signing Cert (you have to buy it)
CSC_KEY_PASSWORD is the password for the Signing Cert

**Comment by YourAverageTechBro** [comment]
Seems to point me in the right direction. I was able to get the signing working for Mac, but if I wanted to support auto update on windows would I need a separate certificate? Or could I use my mac developer certificate to code sign for windows to auto update?

**Comment by pitw** [comment]
You can't use your mac developer cert. For windows you need a "Code Signing Cert" - you have to buy it.
I'm not sure if you need code signing cert for auto update - we use it mainly because there are less warnings for user with proper code signing on windows.

Also check if you have set an update provider in electron-builder config:

` publish: [{
    provider: 'generic',
    url: 'http://update.*********.ch',
    channel: 'latest',
    publishAutoUpdate: true,
  }],`

In example above we use generic: After building app with CI we send the complete "dist" folder to FTP. Electron app then can check the yaml on update server. If it's newer -> autoupdate.

**Comment by YourAverageTechBro** [comment]
Thanks for clarifying! Interesting point re: not needing a code signing cert for auto updates on windows — I thought that I would need to code sign it to allow that but I guess not.

Thank you for the instructions.
