### ISSUE TITLE
libz.so: cannot open shared object file with Ubuntu arm64

### ISSUE THREAD

**Issue by yanguoyu** [electron-userland/electron-builder#7835]
* **Electron-Builder Version**: ^24.6.4

* **Node Version**: >=18

* **Electron Version**: ^26.2.1
* **Electron Type (current, beta, nightly)**:

* **Target**: Ubuntu arm64

I can not open the AppImage on Ubuntu arm64, and when I execute with the terminal it throws en error, here is the log: "Error while loading shared libraries: libz.so: cannot open shared object file: No such file or directory."

[Here](https://github.com/yanguoyu/electron-react-boilerplate) is the repo that I package for Ubuntu arm64, I fork from [electron-react-boilerplate](https://github.com/electron-react-boilerplate/electron-react-boilerplate), and [here](https://github.com/yanguoyu/electron-react-boilerplate/actions/runs/6582728304) is the package result.
The x64 result runs successfully on the x64 Ubuntu.

**Comment by yanguoyu** [comment]
https://github.com/yanguoyu/electron-quick-start is a smaller repo for reproducing this problem.

https://github.com/yanguoyu/electron-quick-start/actions/runs/6586287443 is the electron-builder build result. It runs failed on Ubuntu arm64.

https://github.com/yanguoyu/electron-quick-start/actions/runs/6586287445 is the electron-forge build result. It runs successfully on Ubuntu arm64.

**Comment by toastmanAu** [comment]
> Hmm... I also found this: [AppImage/AppImageKit#1092 (comment)](https://github.com/AppImage/AppImageKit/issues/1092#issuecomment-1346367364) Does that work?

Not sure if related but seems the team who referenced the same issue elsewhere found a solution.

**Comment by Keith-CY** [comment]
> > Hmm... I also found this: [AppImage/AppImageKit#1092 (comment)](https://github.com/AppImage/AppImageKit/issues/1092#issuecomment-1346367364) Does that work?
> 
> Not sure if related but seems the team who referenced the same issue elsewhere found a solution.

Hi @toastmanAu 
Sorry for replying late. @yanguoyu had tried this solution and found it requires users to install/link a dependency locally, as stated at https://github.com/ChurchApps/FreeShow/issues/352#issuecomment-1877903913

IMO, it cannot be considered a solution because unnecessary complexity was introduced that users should be told about the problem and how to fix it before they download the application. The better one is to fix the dependency problem before the application is delivered to users.
