### ISSUE TITLE
Electron-updater version mismatch

### ISSUE THREAD

**Issue by mtdvlpr** [electron-userland/electron-builder#7839]
Electron-updater@6.1.6 is marked latest on GitHub, but npm marks v6.1.4 as latest and 6.1.6 as next (see https://www.npmjs.com/package/electron-updater?activeTab=versions). Is this intentional?

**Comment by mmaietta** [comment]
More of a side effect than intentional. The release automation always sets the auto-created versions as `latest` on Github, but `pnpm publish` always sets the newest as `next` on npm. We use https://github.com/changesets/action under the hood for the CI/CD

I usually let `next` on npm bake for a bit before tagging it as `latest`. Please defer to npm versions to determine `latest` vs `next`
