### ISSUE TITLE
Mac archive tar.* doesn't run after extraction

### ISSUE THREAD

**Issue by jackric** [electron-userland/electron-builder#784]
* **Version**: 6.7.7

* **Target**: Mac

Archives created this way don't run after extraction:
`node_modules/.bin/build --mac tar.gz`
You get:
```
dyld: Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /private/tmp/MyAppName/Contents/MacOS/Gridmarkets Envoy
  Reason: image not found
```

However if I go into the `dist` directory and manually create the `tar.gz` myself from the unpacked mac directory, that `tar.gz` unpacks and runs fine. I can't spot anything obvious that explains it from looking at `targets/archive.js`

**Comment by yuya-oc** [comment]
I have same problem, too.

* **Version**: 7.10.2
* **Target**: mac:tar.gz

I feel `--transform` is not good for this case. I tried `gtar` manually like the way `electron-builder` spawn `gtar`:

```
cd <RELEASE>/mac/<APPNAME>.app
gtar --gz --transform s,^.,<APPNAME>-<VERSION>-mac, -cf <RELEASE>/mac/<APPNAME>-<VERSION>-mac.tar.gz .
```

The extracted `<APPNAME>-<VERSION>-mac.app` doesn't start due to the dyld error. Then I manually executed `gtar` like below:

```
cd <RELEASE>/mac
gtar --gz -cf <RELEASE>/mac/<APPNAME>-<VERSION>.tar.gz <APPNAME>.app
```

The extracted `<APPNAME>.app` can successfully start.
