### ISSUE TITLE
Any easier way to keep folder even after uninstalling?

### ISSUE THREAD

**Issue by rustleliu** [electron-userland/electron-builder#7880]
* **Electron-Builder Version**: 24.6.4

* **Node Version**: node/20.9.0/x64

* **Electron Version**: 27.0.2
* **Electron Type (current, beta, nightly)**: current

* **Target**: NSIS for Windows x64 & arm64

My app stores data in a directory named `Data` under the installation directory, fox example:
> Installation Directory: `C:\Program Files\MyApp\`
> Executable Path: `C:\Program Files\MyApp\MyApp.exe`
> Data folder: `C:\Program Files\MyApp\Data\` 

When I uninstall MyApp, the `Data` folder is automatically deleted, how can I keep the folder even after uninstalling the program.

Perhaps I can change this behavior by using a customized `script` option, but I believe that would be too complicate for this purpose.

Do you know of any easier way to achieve this?

**Comment by mmaietta** [comment]
Persistent data that is meant to be retained should not be in the application install directory, there's dedicated directories on Windows for that purpose. There's no way for electron-builder to know what files would/should be retained in the app's installation directory, it will always overwrite it (intentionally by design)
