### ISSUE TITLE
Windows App Doesn't Start / Shortcut Links Broken (after successful installation)

### ISSUE THREAD

**Issue by dharders** [electron-userland/electron-builder#800]
* **Version**: 7.11.2

* **Target**: NSIS Windows

Just updated to latest electron-builder 7.11.2 and successfully built a Win64 NSIS target on Windows 7 (no errors/warnings given).

After running the setup.exe, I noticed the app did not auto-launch after installation. So I went to manually open the link on the desktop (and menu) and found they were broken links.

I managed to trace it back to **something was released** in version 7.11.1, as 7.11.0 does work (if I simply change my package.json version and npm install then build).

Looking at your release notes (and commits) it's not too obvious to me what in fact is the cause.

I've attached some relevant details below.

```javascript
"electron-builder": "7.11.2",
"electron-prebuilt": "1.4.3",
```

```javascript
"build": {
    ...
    "asar": true,
    "compression": "store",
    "npmRebuild": false,
    "win": {
      "target": "nsis",
      "certificateSubjectName": "My Cert",
      "iconUrl": "https://www.example.com.au/app.ico",
      "legalTrademarks": "Example™"
    },
    "mac": {
      "target": "dmg"
    },
    "nsis": {
      "perMachine": false,
      "allowElevation": true,
      "oneClick": true,
      "language": "3081"
    }
  }
```

**Comment by popod** [comment]
Same thing for me using NSIS installer on windows 32 bits OS. All shortcut are without app icon and broken.

**Comment by lbssousa** [comment]
I've noticed the problem here. The issue is that generated NSIS package are installing files at `App\Version\win-*-unpacked` rather than `App\Version` as before, but generated shortcut tries to launch `App\Version\App.exe`.

I suppose the original intention of the project is to install files at `App\Version`, thus the behaviour observed at version 7.11.2, I mean, installing files at `App\Version\win-*-unpacked`, should be a regression.

**Comment by develar** [comment]
@lbssousa Thanks. And sorry for regression. Missed tests will be added later (it was not tested :(), for now I have fixed error.
