### ISSUE TITLE
is support asar integrity feature?

### ISSUE THREAD

**Issue by qyh214** [electron-userland/electron-builder#8181]
According https://www.electronjs.org/docs/latest/tutorial/asar-integrity and https://github.com/electron-userland/electron-builder/issues/6365

I add Afterpack function in electron-builder.json but how to do like:
![QQ截图20240420225022](https://github.com/electron-userland/electron-builder/assets/3896160/11d01a09-d670-4a02-bf65-35f262926f65)

If only add afterpack function can build but can not open app.

**Comment by mmaietta** [comment]
I think that will now be covered by https://github.com/electron-userland/electron-builder/pull/8245
@indutny-signal can you confirm?

**Comment by ssh-peppe** [comment]
Using electron-builder 25.1.8 I can flip the fuse for asar integrity checking in afterPack, and I can see that the integrity check is enabled by running npx @electron/fuses read --app xxx.exe, but with Windows on startup I'm getting an error "Failed to find file integrity info for resources\app.asar". The build log also has "updating asar integrity executable resource  executablePath=dist/win-unpacked/xxx.exe".

When using 26.0.12 and the new electronFuses configuration in the builder config instead of using afterPack, it works perfectly. 

I'm using Electron 36.2.1.

Is this a known issue, or perhaps an incompatibility between the Electron version (36.2.1) and electron-builder (25.1.8), or is there some other configuration or build step I might be missing?

I'd switch to electron-builder 26.x.x but can't do so right now due to Linux .rpm builds being broken in macOS, and because I cannot install 26 for production due to there being a GitHub dependency in @electron/rebuild to @electron/node-gyp and this violates the strict network access policies we have in place.

**Comment by ssh-peppe** [comment]
Ah, just found this: https://github.com/electron-userland/electron-builder/issues/8690 and it sounds like what I'm seeing, as I'm building on a Mac for Windows.

**Comment by mmaietta** [comment]
Due to the way the CI/CD works in the monorepo, I can't patch previous versions of electron-builder (25.1.8 in this case).

> I'd switch to electron-builder 26.x.x but can't do so right now due to Linux .rpm builds being broken in macOS

I reported this in https://github.com/electron-userland/electron-builder/issues/9057
Workaround:
```
gem install fpm
USE_SYSTEM_FPM=true npm run your:build:command
```
PR to upgrade portable ruby and fpm in https://github.com/electron-userland/electron-builder/pull/9100
Currently need to rebuild the portable ruby bundle so that it works with older version of GNU/Linux since it currently works fine on ubuntu 22.04 images (base electron-builder image), but I also need it to work in `debian:latest` for black-box updater e2e tests to continue to be functional.

> GitHub dependency in @electron/rebuild to @electron/node-gyp and this violates the strict network access policies we have in place.

This will be resolved once I can upgrade the project to ESM + node 22.12 engine
PRs https://github.com/electron-userland/electron-builder/pull/9086 https://github.com/electron-userland/electron-builder/pull/9085
The downside is both PRs are not backward compatible and are essentially also not going to be reverted once merged, so it'll be a major semver bump. Working on mac-rpm issue currently, a few other issues, then plan to revisit the ESM migration

**Comment by ssh-peppe** [comment]
Thanks for your comment, and for an excellent tool! I believe I can fix the @electron/node-gyp issue for now with an "overrides" definition for it in my package.json.
