### ISSUE TITLE
app-update.yml Not Generated When Using –prepackaged with .json Config in electron-builder

### ISSUE THREAD

**Issue by maoryadin** [electron-userland/electron-builder#8266]
Issue Details:

When using electron-builder with the --prepackaged option for a .json configuration file, the app-update.yml file is not generated. This issue occurs despite following the standard procedure for building and packaging the Electron application.

Steps to Reproduce:

	1.	Create a .json configuration file for electron-builder.
	2.	Run electron-builder with the --prepackaged option.(make sure app-update.yml is not exist in the .app)
	3.	Observe that the app-update.yml file is not generated in the output directory.

Expected Behavior:

The app-update.yml file should be generated in the output directory when using the --prepackaged option with a .json configuration file.

Actual Behavior:

The app-update.yml file is not generated.

Additional Context:

the .app is generated with electron-forge and also do not include (make sense) an app-update.yml. it is look like it is just ignoring adding/modifying the Resource folder before packaging it to a .dmg file

Thank you for looking into this issue.

**Comment by mmaietta** [comment]
IIRC, the intent of `--prepackaged` is to take an already-bundled/packaged app and simply produce a distributable. Since `app-update.yml` changes the bundle/prepackaged app directory, it's not a valid operation to perform on the app as part of `prepackaged` assumptions.

What functionality is missing from electron-builder that you need to leverage electron-forge for? The two tools aren't designed to work together.
