### ISSUE TITLE
Windows NSIS Installer license is cut off at 126 Byte

### ISSUE THREAD

**Issue by philkrpp** [electron-userland/electron-builder#8294]
* **Electron-Builder Version**: 24.13.3 but also tested with latest alpha and also older versions

* **Node Version**: tested in 20.9.0/20.11.1/16

* **Electron Version**: 31.1.0 and also tried other electron versions
* **Electron Type (current, beta, nightly)**: current

* **Target**: Windows NSIS

Hello all,

in our latest Windows NSIS installer I recognized that the license page does not contain whole content. It is always cut off when I am building on macOS at 126 Bytes. When I am building on Windows it seems to be fine with length but special characters (like in German äöü) are only displayed in cryptic characters.

macOS Sonoma 14.5 (MacMini i7 and also Mac Studio M2 Pro Max tested)
Windows 11 Pro 23H2 22631.3810 x86

Does anyone faces same issue?

Here is simple code for reproduction:
[electron-builder-test.zip](https://github.com/user-attachments/files/16094099/electron-builder-test.zip)

macOS Build:
![CleanShot 2024-07-04 at 08 05 59](https://github.com/electron-userland/electron-builder/assets/64036976/42ee3266-1897-48b4-8b20-13cf3d8d1687)

Windows Build:
![CleanShot 2024-07-04 at 08 10 05](https://github.com/electron-userland/electron-builder/assets/64036976/5943cf36-ca3c-4e17-a0f6-1c452864a477)

**Comment by orlv** [comment]
Hello,
have you found a solution?

**Comment by philkrpp** [comment]
Unfortunately not yet. My workaround is to build macOS on macOS and Windows on Windows. I replaced all special characters like "Ä" to "Ae" and build the new version...

**Comment by beyondkmp** [comment]
@philkrpp For Windows Build, If we change license file's encode to utf-8 with bom, it works well.
![image](https://github.com/electron-userland/electron-builder/assets/5462444/bbf00e59-893e-4616-a204-e12628093578)
![image](https://github.com/electron-userland/electron-builder/assets/5462444/1fa9b417-af3d-4511-91da-1a12cc25bae0)

**Comment by arslc** [comment]
Hello, I encountered the same problem. I don't quite understand why the ticket was closed if the issue isn't resolved. I have the exact same behavior: when building from MacOS to Windows, the license is truncated at 126 characters.

The author solved the problem by building from Windows to Windows, but that's not a solution for me.

---

@mmaietta if no one can find the reason for this, I think it's worth mentioning this problem in the documentation and suggesting people to use this solution.

@philkrpp if it's still relevant, then try this option; it's much better than switching between systems to make a new build just because of the license.

---

### **SOLUTION:**

I've already tried different files (rtf, txt) and different encodings (utf-8, utf-8 with BOM), but nothing worked except for one solution: **use HTML (utf-8 with BOM) as the license file.**

Especially for those who will ever come back here with this question. 

Create `license.html` file something like this:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <style>
      body {
        font-family: sans-serif;
        font-size: 12px;
        line-height: 1.4;
        color: #000000;
        background-color: #ffffff;
      }
    </style>
  </head>
  <body>
  
    <h3>END USER LICENSE AGREEMENT (EULA)</h3>
    
    <p>
      <b>Software:</b> Software name<br>
      <b>Copmany:</b> Company Name
    </p>
  
    <p>
      <b>ATTENTION! PLEASE READ THIS AGREEMENT CAREFULLY BEFORE INSTALLING OR USING THE SOFTWARE.</b>
    </p>
  
  	<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
  
  	<h4>Where does it come from?</h4>
  
  	<p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32..</p>
  
  </body>
</html>
```

Append license like this (in your config):

```json
"license": "windows/license_en.html"
```

And got it:

<img width="600" height="436" alt="Image" src="https://github.com/user-attachments/assets/a2d05347-e83e-41b2-bb38-055e9f3a3a40" />


p.s. 
```json
"electron-builder": "^26.0.12"
```
