### ISSUE TITLE
Adding PackageDependency to generated AppManifest.xml

### ISSUE THREAD

**Issue by simonbrunou** [electron-userland/electron-builder#8434]
Which version of electron-builder are you using?
Please always try to use latest version before reporting any issue.
* **Electron-Builder Version**: 25.0.5

Which version of node are you using?
* **Node Version**: 22.7.0

Which version of electron are you using?
Please verify if the error is electron related before reporting any issues.
* **Electron Version**: 31.4.0
* **Electron Type**: current

Which version of electron-updater are you using (if applicable)?
6.3.4

For which target are you building for?
* **Target**: AppX

Enter your issue details below this comment.

I would like to know if there is any way to specify custom fields on the generated AppManifest.xml. I have to add a dependency to VCRedist, so basically I need to insert this block

```xml
<Dependencies>
    <PackageDependency Name="Microsoft.VCLibs.140.00.UWPDesktop" MinVersion="14.0.24217.0" Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US" />
</Dependencies>
```

to the generated AppManifest.xml.

I tried adding it using extensions, but package dependencies are not extensions.

I could not find an example online, or documentation on the website mentioning how to add this block.

**Comment by mmaietta** [comment]
First off, thank you for reporting this with the `next` version of electron-builder, it really helps me 🙂 

I took a quick look at the code and it looks like the generated app manifest file is accessible via the electron-builder hook `appxManifestCreated(manifestFilePath: string)`. (side note, one of my projects is to improve electron-builder's documentation site, since it seems this hook isn't documented like `afterSign` and `afterPack`)

Would you be willing to try manipulating the file to insert your block directly into the file generated by electron-builder?

**Comment by simonbrunou** [comment]
Hi, thank you for your answer.

I can try manipulating the file using the provided hook to see if it solves my issue.

I'll keep you updated!

**Comment by simonbrunou** [comment]
Hi again.

Using the hook seemed to be working, it allows me to update the file as I would like.

Thank you very much for your time and efforts.
