### ISSUE TITLE
"!node_modules/?angular${/*}" in files doesn't exclude node_modules/@angular folder

### ISSUE THREAD

**Issue by tim-wilkins** [electron-userland/electron-builder#8460]
25.0.5

* **Electron-Builder Version**: 

v20.12.0
* **Node Version**: 

32.0.2

* **Electron Version**:
* **Electron Type (current, beta, nightly)**:
n/a

 Windows, msi
* **Target**: 

 This worked with 24.13.3 and electron 32.0.1, but I noticed that the asar file had grown a lot and extracting it find the angular folder with contents.  All versions are updated using "ng update electron" etc. when "npm outdated" shows an outdated version.  I do also have  electron-reload@1.5.0 (not updated since only alpha).

**Comment by mmaietta** [comment]
The only change I was able to find in [the diff](https://github.com/electron-userland/electron-builder/compare/v24.13.3...v25.0.6) that might be related is an upgrade from `"minimatch": "^5.1.1"`, to `"^10.0.0"`

Can you try force-resolving/overwriting the version of minimatch in your package.json to 5.1.1 and see if that resolves the issue? If so, I can open a PR asap and get it into the next release

**Comment by absidue** [comment]
@mmaietta I tried overriding the minimatch version with yarn but it complained about the versions being to far apart and ignored the override. In our case we tell electron-builder to ignore the node_modules folder entirely because we use webpack to bundle the files first, but going from 24.13.3 to 25.0.5, resulted in electron-builder pulling in packages in the node_modules folder that start with `@`, even things like babel which are listed in the development dependencies which electron-builder is supposed to ignore by default. For the moment we have reverted back to the previous electron-builder version that we were using.

On an unrelated note the newer version of electron-builder logs that it is adding asar integrity data, even though we don't even use that and the docs don't list any obvious way to stop electron-builder doing that unnecessary work (bit like how there doesn't seem to be a way to turn off code signing completely).

**Comment by absidue** [comment]
With that version `electron-builder install-app-deps` takes forever. According to task manager `app-builder.exe` is using a bunch of CPU and has very slowly increasing RAM usage (been running for over 10 minutes and currently sitting at 230MB of RAM usage), so it is going to be a while before I can report back on whether that upgraded version fixes the original problem or not.

As for why we don't use code signing, it comes with various downsides that make it unsuitable for an open source project maintained by various unrelated individuals, such as costing lots of money (especially when you consider that creating a signing certificate for a macos requires buying a mac first), requires tying your legal details to the app and requires tying it to someones personal Microsoft account and Apple ID or setting up a company to tie it to a company account.

If you know any way of signing apps that doesn't come with those downsides I would love to hear it.

**Comment by mmaietta** [comment]
Ahhh, my apologies. I mean [25.1.6](https://github.com/electron-userland/electron-builder/releases/tag/v25.1.6), that version has the fix for the app-builder-bin bug that causes that memory loop.

**Comment by absidue** [comment]
A lot faster with that version but unfortunately the `@` package problem still exists:
![extracted-app-asar-with-node-modules](https://github.com/user-attachments/assets/e16e6ca6-38de-4d50-b331-e8711d0d04ae)

This is what we pass to the `files` option in the electron-builder config object:
```js
[
  '_icons/iconColor.*',
  'icon.svg',
  './dist/**/*',
  '!dist/web/*',
  '!node_modules/**/*',
]
```

**Comment by mmaietta** [comment]
Could you share a minimum repro repo/gist/zip that I could test locally with?
