### ISSUE TITLE
Unable to copy file for caching: ENOENT

### ISSUE THREAD

**Issue by theboolean** [electron-userland/electron-builder#8507]
* **Electron-Builder Version**: 24.13.3

* **Node Version**: 18.x

* **Electron Version**: 31
* **Electron Type (current, beta, nightly)**: current
Which version of electron-updater are you using (if applicable)? 6.3.4

* **Target**:  macOS

After updating electron-updater from 6.2.0 to 6.3.4 we are getting errors like:
`Unable to copy file for caching: ENOENT: no such file or directory, copyfile '/Users/{USER_NAME_REDACTED}/Library/Caches/{APP_NAME_REDACTED}-updater/pending/{APP_NAME_AND_VERSION_REDACTED}-arm64-mac.zip' -> ''`
every time users check for updates. this line seems to be the problem: https://github.com/electron-userland/electron-builder/blob/3b03f27245458a0b595b7a65c8634f184d32f2fa/packages/electron-updater/src/MacUpdater.ts#L123

**Comment by mmaietta** [comment]
Great find in identifying the root cause. Looks like it's non-blocking of the update due to the try-catch, but definitely something that warrants further investigation.
https://github.com/electron-userland/electron-builder/blob/3b03f27245458a0b595b7a65c8634f184d32f2fa/packages/electron-updater/src/MacUpdater.ts#L122-L127
The var is set on this line.
https://github.com/electron-userland/electron-builder/blob/3b03f27245458a0b595b7a65c8634f184d32f2fa/packages/electron-updater/src/MacUpdater.ts#L104

I'll continue diving into this, but curious on @beyondkmp's thoughts here? Why would this not be getting executed?
https://github.com/electron-userland/electron-builder/blob/3b03f27245458a0b595b7a65c8634f184d32f2fa/packages/electron-updater/src/MacUpdater.ts#L104

**Comment by MelonCode** [comment]
hey, any updates on this?

**Comment by beyondkmp** [comment]
@mmaietta 
https://github.com/electron-userland/electron-builder/blob/3b03f27245458a0b595b7a65c8634f184d32f2fa/packages/electron-updater/src/AppUpdater.ts#L698-L702
The problem likely lies here. If it already exists, the task function won't run; instead, the done function will be executed directly.

**Comment by mmaietta** [comment]
Released in 25.1.7, please feel free to give it a shot!
