### ISSUE TITLE
Github as NSIS update server

### ISSUE THREAD

**Issue by zh99998** [electron-userland/electron-builder#868]
currently NSIS updater can't use github as update server.

as https://github.com/electron-userland/electron-builder/issues/529#issuecomment-257807535

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder/wiki/Auto-Update

**Comment by integrable** [comment]
@develar Hi, I use github as a provier and latest.yml is not generated, only .exe file is generated and uploaded, so I there is an error "Error: Cannot find latest.yml in the latest release artifacts: Error: 404 Not Found" while app checks for updates.

**Comment by develar** [comment]
@integrable Thanks, fixed,

**Comment by integrable** [comment]
@develar  Thank you for the quick fix! Works for me on Windows 10. 
So far I have also found few issues:

1) ReleaseNotes variable in update-downloaded handler is Null
2) latest.yml is not automatically uploaded to GitHub (I do it manually)
2) The name of a file uploaded to GitHub is based on "name" setting from app/package.json, while the .exe name is actually "productName"+ "-Setup-<version>", also "path" in latest.yml would be  <productName>-Setup-<version>.exe, so it has to be corrected manually, otherwise the file will not be found during update download .

**Comment by develar** [comment]
> ReleaseNotes variable in update-downloaded handler is Null

Please file issue. Why do you need release notes?

**Comment by integrable** [comment]
@develar In fact, the issue is not critical for me. In my case, the app just shows release notes when the new version of app is downloaded: 

```
 autoUpdater.addListener("update-downloaded", function (event, releaseNotes, releaseName, releaseDate, updateURL) {
      log("A new update downloaded");
      const cancelIndex = 1; 
      const index = dialog.showMessageBox(windows[0], {
        type: 'info',
        buttons: ['Restart', 'Later'],
        title: "Update available",
        message: 'The new version has been downloaded.',
        detail: releaseName + (releaseNotes ? "\n\n" + releaseNotes : '')
      });

      if (index === cancelIndex) {
        return;
      }
      autoUpdater.quitAndInstall();
    });
```
