### ISSUE TITLE
Rebuild with --no-bin-links option

### ISSUE THREAD

**Issue by MTRNord** [electron-userland/electron-builder#869]
* **Version**: 7.18.0

* **Target**: Linux

I want to build in Jenkins (which runs inside docker on windows) therefor I need the --no-bin-links option in node. But when it does the `npm rebuild` part it fails because it is missing the --no-bin-links. Is there a way to add this option at build to fix this issue?

**Comment by MTRNord** [comment]
Thanks :)

**Comment by lgeiger** [comment]
@develar Thanks for maintaining this awesome package. Keep up the great work 👍 

After upgrading to `7.19.1` we run into https://github.com/npm/npm/issues/9953 on windows because the `--no-bin-links` flag doesn't work correctly.
Could we make it optional?

Here is the full error: https://ci.appveyor.com/project/nteract/nteract/build/1.0.652/job/0ij1f4vrs2aaeg8o#L77

**Comment by develar** [comment]
npm must die, yarn FTW :( https://github.com/npm/npm/issues/10776 ok, will be investigated.

**Comment by develar** [comment]
Env `NPM_NO_BIN_LINKS` is added. Set it to true — `NPM_NO_BIN_LINKS=true` to force usage of `--no-bin-links` I hope yarn will be replace npm soon.

**Comment by lgeiger** [comment]
@develar Thank you a lot for the quick fix!

**Comment by Strangerxxx** [comment]
it was fixed in newer npm version, tested with npm 6.13.4 and 6.14.4 and reverted in #4915
