### ISSUE TITLE
How can i replace automatically LICENSE file in electron app folder?

### ISSUE THREAD

**Issue by artpol** [electron-userland/electron-builder#916]
After installation, in folder with my application a see 2 license files:

- LICENSES.chromium.html - nesessary electron license, I do not touch it
- LICENSE - if I understand correctly, it should be license for my application

How to say electron builder replace LICENSE file with my cutom file when packaging?

**Comment by develar** [comment]
Please specify target platform — windows/linux? Hmm... I guess we can just remove it because in any case LICENSE file is not included into the mac app.

Could you please ask about it in the electron issue tracker (https://github.com/electron/electron/issues) —  Is it legal to remove  LICENSES.chromium.html and LICENSE.

**Comment by develar** [comment]
In any case you can try to use `extraFiles` to copy any file to root of the packed app directory.

**Comment by artpol** [comment]
Thanks. i will try to use extraFiles, if it would be legal. Target platform - Windows.  
Ok, i asked https://github.com/electron/electron/issues/7988

**Comment by develar** [comment]
`LICENSE` will be removed by electorn-builder.
`LICENSES.chromium.html` will be not touched.
