### ISSUE TITLE
app-update.yml missing

### ISSUE THREAD

**Issue by beljand** [electron-userland/electron-builder#950]
* **Version**: 
Latest

* **Target**:
Windows 

When using installer (.exe) **app-update.yml** is not installed, although it is included in the _.zip_ package. Therefore an error is thrown on app startup:

`ENOENT: no such file or directory, ... .../app-update.yml`

**Comment by develar** [comment]
Could you please provide installer to test?

**Comment by dustintownsend** [comment]
@develar I get this message as well. But not sure if it happens with the installer since I can't see the console. But when I do a production build and run it from the command line I see the same error.

In my case it is trying to find that file inside the electron prebuilt node module folder (\node_modules\electron\dist\resources\app-update.yml).

I'm using the Electron React Boilerplate.

**Comment by develar** [comment]
@dustintownsend Yes, auto updater is not supposed to be running by electron — only from  installed app.
